### ISSUE TITLE
500 error editing fields

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1011]
Customer says:

*Happily cramming in all sorts of lines and fields for a naturalization records collection I'm playing with, and around line 26 I got a 500 error when trying to save my latest additions.

Might could that be just too dang many? That's the only page throwing me that error. Or should I be more patient? That is frequently my problem.*

And the logs show:

```
ActionView::Template::Error (undefined method `map' for nil:NilClass):
    13:             =text_field_tag "fields[#{field.id}][#{field.label}]", content, class: 'field-input'
    14:           -elsif field.input_type == "select"
    15:             -options = field.options.split(";") unless field.options.nil?
    16:             =select_tag("fields[#{field.id}][#{field.label}]", options_for_select(options, content), class: 'field-input')
    17:           -else
    18:             =text_area_tag "fields[#{field.id}][#{field.label}]", content, class: 'field-input'
  app/views/transcription_field/_field_layout.html.slim:16:in `block (2 levels) in _app_views_transcription_field__field_layout_html_slim__4077767118976575395_50177460'
  app/views/transcription_field/_field_layout.html.slim:6:in `each'
  app/views/transcription_field/_field_layout.html.slim:6:in `block in _app_views_transcription_field__field_layout_html_slim__4077767118976575395_50177460'
  app/views/transcription_field/_field_layout.html.slim:3:in `each'
  app/views/transcription_field/_field_layout.html.slim:3:in `_app_views_transcription_field__field_layout_html_slim__4077767118976575395_50177460'
  app/views/transcription_field/edit_fields.html.slim:28:in `_app_views_transcription_field_edit_fields_html_slim___1374757601646387445_35063360'
```

When we try to "edit fields" for her project.

**Comment by saracarl** [comment]
Failing line:

https://github.com/benwbrum/fromthepage/blob/master/app/views/transcription_field/_field_layout.html.slim#L16

**Comment by saracarl** [comment]
Reproduced it by adding a field that's a "select" type but no values entered for the select field.  Hit the 500 as soon as I saved.

**Comment by saracarl** [comment]
https://gist.github.com/benwbrum/fff406b623af944146755a259c7c624e  has the json of the customer's fields.

I see a number of selects with "null" options:
  {
      "id":170,
      "label":"C5 birth day",
      "collection_id":217,
      "input_type":"select",
      "options":null,
      "line_number":33,
      "position":105,
      "percentage":null
   },
   {
      "id":171,
      "label":"C5 birth month",
      "collection_id":217,
      "input_type":"select",
      "options":null,
      "line_number":33,
      "position":106,
      "percentage":null
   },
   {
      "id":172,
      "label":"C5 birth year",
      "collection_id":217,
      "input_type":"select",
      "options":null,
      "line_number":33,
      "position":107,
      "percentage":null
},

(and more)

**Comment by saracarl** [comment]
Remediated in production.  Need to fix the underlying issue.

**Comment by benwbrum** [comment]
Remediated in production by setting `select` inputs with `nil` for `options` to be `text` input types:

```
2.2.0 :003 > f = TranscriptionField.where(:input_type => 'select', :options => nil).first
 => #<TranscriptionField id: 180, label: "x", collection_id: 199, input_type: "select", options: nil, line_number: 1, position: 4, percentage: nil> 
2.2.0 :004 > f.input_type='text'
 => "text" 
2.2.0 :005 > f.save!
 => true 
```
