### ISSUE TITLE
add tzinfo-data to gem file

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1024]
To allow FromThePage to work with MySQL 5.7, the mysql2 gem is updated. The tzinfo-data gem was recommended on https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors and helped resolve the error described on that page that I got when building FromThePage in Docker.

**Comment by bencomp** [comment]
This is related to #349, isn't it?

**Comment by bencomp** [comment]
I'm not seeing the error anymore on a RHEL6 machine. I used a customised Gemfile before *with* the tzinfo-data gem included, but now that it's not in the Gemfile, it still works.
