### ISSUE TITLE
Add TEI schema to TEI export

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#103]
Comment from Gavin Robinson:

First, could you put the schema in a publicly accessible place on the
web? That way oXygen can access it from anywhere. Currently it's giving
me an error because it can't find the schema.

**Comment by bencomp** [comment]
It looks like this has been solved in recent versions of FromThePage:

```
<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 http://www.tei-c.org/release/xml/tei/custom/schema/xsd/tei_all.xsd" xml:lang="EN" xml:id="export">
```

oXygen has no issues loading this file.
