### ISSUE TITLE
spam transcription

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1050]
We recently experienced some spam transcriptions.

This one has a user that wasn't deleted:
https://fromthepage.com/digitalindy/may-wright-sewall-papers/katherine-gould-to-may-wright-sewall/versions/172548
(I've since deleted the user, but this is their ID and visit:  user_id=54960&visit_id=469142  )

This one transcribed and then deleted the user:
https://fromthepage.com/page_version/show?page_version_id=363355

The URL in the spam transcription is not a live link (on purpose), so this may discourage spammers.

It's been 10 days and we haven't seen any additional spam.  I think we should wait and see if they come back before we take action.

We think the right first step is to add recaptcha to the user registration -- both guest and signed in users.

**Comment by benwbrum** [comment]
Let's add ReCAPTCHA to guest transcriber's first transcription and a new user login.  

Ideally users would only see ReCAPTCHA once during their entire career with us.

Because ReCAPTCHA requires a site (fordham, UT, us) to register and get an API key -- their own key -- we need to be fault-tolerant for sites that have not (or will not) gotten their API key.

**Comment by benwbrum** [comment]
documentation written on how to deploy this (on the wiki here:  https://github.com/benwbrum/fromthepage/wiki/Configuring-FromThePage-For-Your-Environment )

put the key in config/initializer/01fromthepage.rb

We need to make sure that this works for 
1) our site, with our API key
2) another site with its own API key
3) sites that do not have API keys and have not updated their configuration after deploying.

**Comment by benwbrum** [comment]
Two places (so far) to implement ReCAPTCHA:
* Guest users' first transcription/translation
* New user account creation
