### ISSUE TITLE
contributors tab performance updates

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1052]
retain date range

retain list of collaborators

change "recent transcriptions"  to a summary -- copy "last 7 days" table from the statistics tab.  Change the date to reflect the drop range.

"Details" link that takes you to the deed list for that collection, i.e.:  https://www.fromthepage.com/deed/list?collection_id=58

**Comment by saracarl** [comment]
"Recent pages needing review" should be removed as part of this.

**Comment by saracarl** [comment]
test this with a new dump file that includes AL.

**Comment by benwbrum** [comment]
A new dump file has been added to the google drive folder

**Comment by jackweinbender** [comment]
I may just be unfamiliar with the architecture here, but it seems like this isn't going to be quite as straightforward as just moving that code from the statistics view. The statistics partial is reliant on the statistics functions on the collection model---these run SQL queries that wouldn't be affected by the date-range scoping and instead use `last_days_clause()` which takes an `int`.

**Comment by benwbrum** [comment]
No, you're right -- that's very different than how I expected that code to work.

Looking at https://github.com/benwbrum/fromthepage/blob/master/app/models/collection_statistic.rb I'm tempted to rewrite the lot to execute a single `SELECT COUNT(*), deed_type FROM deeds WHERE collection_id = ? AND created_at BETWEEN ? AND ? GROUP BY deed_type`, cache that in a hash and have the getters pull from the hash for everything except `contributor_count`.  

That's a lot of refactoring, and [functions like this](https://github.com/benwbrum/fromthepage/blob/master/app/models/collection_statistic.rb#L46-L54) make me suspect that there's more going on than the initial read leads me to understand.  For now, how about adding a new method that takes a date range as parameters, returns a hash of `deed_type=>count` created by the single group by query, then just list those values in the view?  It's kind of a temporary solution, but at least it would get us past the performance problem and make the screen usable for large customers.  We can open a new issue to refactor `collection_statistic` for performance later.
