### ISSUE TITLE
Warn users if another user is editing this page.

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1063]
We're running into problems at Transcribe-a-thons and other high-volume projects in which transcribers have their page save fail because of stale database records.  We should track down what's going on and come up with a strategy for dealing with this.  (I'd thought that we implemented optimistic locking 11-13 years ago -- is that not working?  Is that the problem?)

Possible reproduction scenario:
- User A starts to edit a page.
- User B starts to edit the same page.
- User A saves the page.
- User B attempts to save the page and sees an error.

Once we come up with a reproduction scenario, we'll need to formulate how to present the error to the end user.  If the scenario I suggested is correct, should we attempt to merge B's changes into A's transcript?

Example error email:
====Page Save Failed on FromThePage====

=====Failure message=====
```
TRANSCRIPTION 2018-05-09 16:15:37 +0000 TRANSCRIPTION User ID: 49611 Email: staff02.archives@archives.alabama.gov	Display Name: ADAH student TRANSCRIPTION Collection ID: 69 Title:WWI service records for Jefferson County, Alabama Owner Email: digital.adah@gmail.com TRANSCRIPTION Work ID: 3974 Title: World War I military service cards for Jefferson County, Alabama (Scaife through Seymore). TRANSCRIPTION Page ID: 115435 Position: 135 Title:Marion Seals TRANSCRIPTION Source Text: BEGIN_SOURCE_TEXT END_SOURCE_TEXT
```

=====Error/Exception message=====
`Attempted to update a stale object: Page`

**Comment by benwbrum** [comment]
Make sure works with field based projects like Alabama's.

**Comment by benwbrum** [comment]
Maybe the right thing to do here is go ahead and over-write the previous version, and send a warning letter to the project owner with a direct link to the version comparison view.

**Comment by benwbrum** [comment]
Looks like this can turn off optimistic locking:  ActiveRecord::Base.lock_optimistically = false 

However, we only want to disable it on pages.  However, if we disable optimistic locking we'll lose the exception that we could use to send error messages.

Please duplicate and make sure our theory is correct & we can reproduce.  Can we create a spec test???

Let's think through this some more.  Docs to review:

http://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html
https://stackoverflow.com/questions/26443338/receiving-attempted-to-update-a-stale-object-user-exception-when-updating-cur?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by benwbrum** [comment]
After talking with some of our users, people would really prefer to be warned so that they don't edit each others pages.

We have two goals:
1) Warn the user if someone else is already editing a page when they try to transcribe it
2) Handle the StaleObjectError gracefully somehow.

For 1, I think we will need a small new feature.
I'd add a new timestamp on the `pages` table and update it with `Time.now` whenever a user hits the Transcribe or Translate tab.
Whenever another user hits the Transcribe or Translate tab for that page, check the time on that record and if it's `> Time.now - 15.minutes`, flash a Warning on the screen.

Let's go into that in more detail, since that description has a lot of assumptions.  ("another user", "whenever", ...)

We'll need to add a migration for
```
page.edit_started_at, :timestamp
page.edit_started_by_user_id, :reference
```

On the `transcribe_controller#display` (and the similar action for translating a page), first check:
```ruby
if @page.edit_started_by_user != current_user && @page.edit_started_at > Time.now + 15.minutes 
  flash[:warning] = "This page is being edited by another user!"
else
  @page.edit_started_at = Timestamp.now
  @page.edit_started_by_user = current_user
  @page.save!
end
```

Of course 15.minutes will need to be a constant we can edit.
That will address #1

On #2, we could do what Wikipedia does.
In Wikipedia, if 
* user A edits version 1, 
* user B edits version 1, 
* user B saves version 2 (from version 1), and 
* user A saves (attempting to create version 3 from version 1, overwriting version 2)
then the page will reload with an error message explaining that someone else edited that page.  
It suggests that user A fix their edits (essentially through a merge) and shows them  the text of version 2 with their own text appended below it.  
If the user hits "save", version 3 will be created from whatever they merged.

**Comment by jackweinbender** [comment]
Would it be incredibly bad practice for us to use a much shorter constant (say, 1-2 minutes?), then ping a server endpoint (updating to add another 1-2 minutes) at that interval from the client side? Basically it'd be like a kind of long "debounce" to record the presence of another editor. I wouldn't think that'd be too much server overhead, and it would be negligible for the client, even on a poor connection.

**Comment by benwbrum** [comment]
I like this idea.  If we ping a server endpoint while the transcribe (or translate) tab is open, that lets the server know the page is being edited..

**Comment by benwbrum** [comment]
Further research from reading the code and attempting to reproduce locally:

I've figured out why we aren't able to reproduce the stale page object exception: the transcription form does not have a hidden lock_version field, so the version the current user is editing does not get tracked: each time the user saves a transcript, we fetch a page from the database with the current lock_version, do all our XML and link parsing, update the page with the new trancript, and save it.
The only way we can get a stale page object error in that case is if two different users press save simultaneously, and there is a race.

Looking in the production logs, I see the error occurring when two different processes are running `save_transcription` on the same page:

## Process 15002
```
I, [2019-07-04T17:17:23.587507 #15002]  INFO -- : Processing by TranscribeController#save_transcription as HTML
I, [2019-07-04T17:17:23.587632 #15002]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"wVNFsGtSO/oMkgbfCJS
Y5nFbd3elEKycfEZyb04R5Fc=", "page_id"=>"346694", "page"=>{"mark_blank"=>"0", "needs_review"=>"1", "source_text"=>"Califo
rnia M42\r\nJ.Y. McDuffie\r\n[illegible] Ind. Agency\r\nAugust 9, '59\r\n\r\nReports having visited\r\nthe different Ind
ian Agencies\r\nand farms in the [illegible]\r\nfor [illegible] of his [Sphere?]\r\nand return that he intends\r\nto [il
legible] [illegible] in his return\r\nto San Francisco - [Maintained?]\r\ninventories of [illegible] property\r\non hand
 the 30th June last\r\n[illegible] finding\r\non his arrival at San Francisco\r\nfor his [extermination?] and \r\n[illeg
ible] [illegible] full [regions?] of the \r\n[indebtedness?] of the [illegible] for\r\nthe past [illegible] years\r\n"},
 "save"=>""}
W, [2019-07-04T17:17:23.597996 #15002]  WARN -- : WARNING: Can't mass-assign protected attributes for Page: mark_blank, 
needs_review
        app/controllers/transcribe_controller.rb:93:in `save_transcription'
I, [2019-07-04T17:17:23.611888 #15002]  INFO -- :   Rendered deed/_deed.html.slim (8.5ms)
I, [2019-07-04T17:17:23.620983 #15002]  INFO -- :   Rendered deed/_deed.html.slim (6.6ms)
I, [2019-07-04T17:17:23.626364 #15002]  INFO -- : TRANSCRIPTION 2019-07-04 17:17:23 +0000

```


## Process 14982
```
TRANSCRIPTION   User    ID: 214612      Email: pirategal03@gmail.com    Display Name: Pirate
TRANSCRIPTION   Collection      ID: 55  Title:Letters of the Office of Indian Affairs, 1849-1880, California Superintend
ency    Owner Email: digitalprojects@library.lacounty.gov
TRANSCRIPTION   Work    ID: 13203       Title: MF1323.1197 Reel 37_0440
TRANSCRIPTION   Page    ID: 346694      Position: 1     Title:page_0001
TRANSCRIPTION   Source Text:
BEGIN_SOURCE_TEXT
California M42
J.Y. McDuffie
[illegible] Ind. Agency
August 9, '59

Reports having visited
the different Indian Agencies
and farms in the [illegible]
for [illegible] of his [Sphere?]
and return that he intends
to [illegible] [illegible] in his return
to San Francisco - [Maintained?]
inventories of [illegible] property
on hand the 30th June last
[illegible] finding
on his arrival at San Francisco
for his [extermination?] and 
[illegible] [illegible] full [regions?] of the 
[indebtedness?] of the [illegible] for
the past [illegible] years

END_SOURCE_TEXT


I, [2019-07-04T17:17:23.704980 #14982]  INFO -- : TRANSCRIPTION 2019-07-04 17:17:23 +0000       SUCCESS 
I, [2019-07-04T17:17:23.713204 #14982]  INFO -- :   Rendered deed/_deed.html.slim (1.8ms)
I, [2019-07-04T17:17:23.714891 #14982]  INFO -- :   Rendered deed/_deed.html.slim (1.3ms)
```

## Process 15002
```
E, [2019-07-04T17:17:23.754683 #15002] ERROR -- : TRANSCRIPTION 2019-07-04 17:17:23 +0000       ERROR   EXCEPTION       Attempted to update a stale object: Page
E, [2019-07-04T17:17:23.754891 #15002] ERROR -- : /home/fromthepage/deployment/shared/bundle/ruby/2.3.0/gems/activerecord-4.1.2/lib/active_record/locking/optimistic.rb:95:in `_update_record'
```

**Comment by benwbrum** [comment]
Okay, here is the feature we want developed:

# Warn users if another user is editing the same page

If user A is editing page 1, and user B clicks the _Transcribe_ or _Translate_ tab, they should see a red warning saying "Someone else is editing this page right now.  Please choose a different page to transcribe."

If the user decides to edit the page anyway, we should go ahead and let each user over-write each other's work.

## Implementation

On the Transcribe / Translate screen, add a JS timer that pings the server 

(to be continued)
