### ISSUE TITLE
assign_categories view needs more context

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1073]
Whenever a user marks up a new subject, we present them with a screen to assign categories to the subjects on the next page.  For subject-heavy texts like Alcedo, it can be bewildering to see the subjects outside of their context within the transcripts.  Presenting the following words for their occurrence in the transcribed page would help immensely, and possibly the preceding words as well.

Example:
![uncategorized](https://user-images.githubusercontent.com/199961/40213253-20808dc8-5a1a-11e8-9288-4e418ed0dd86.png)

Compare with (hypothetical):

*Abary* ABARY, a small river of Guayana, between

*Abbeville* ABBEVILLE County, in Ninety-six district, S. Carolina

*South Carolina* S. Carolina, bounded on the n.e. by the Saluda

*Abbots* ABBOTS, a small river of N. Carolina

**Comment by jackweinbender** [comment]
#1076

**Comment by benwbrum** [comment]
We've had a request that the number of characters providing the context be at least doubled.
