### ISSUE TITLE
Develop strategy for Ahoy

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1074]
We installed the ahoy gem to track down all the guest user accounts we have registering.  This has (so far) failed to accomplish its goal, and the audit data being created is filling up our database:

```

mysql> SELECT table_name AS "Table", round(((data_length + index_length) / 1024 / 1024), 2) as size FROM information_schema.TABLES WHERE table_schema = "diary_development" ORDER BY size DESC
    -> ;
+----------------------------+--------+
| Table                      | size   |
+----------------------------+--------+
| ahoy_events                | 324.75 |
| page_versions              | 228.72 |
| visits                     | 136.80 |
| pages                      | 132.38 |
| table_cells                |  73.11 |
| sc_canvases                |  51.61 |
| deeds                      |  27.13 |
```

In addition, it's likely that ahoy presents problems for GDPR.

**Comment by bencomp** [comment]
If the personally identifiable information in the database is not used for any legitimate reasons, it should not be collected. And if the information is used, it should be deleted when it's no longer needed.

Also looking at #791, is Ahoy still used for anything?

**Comment by saracarl** [comment]
1)  Don't track every single click.
2)  one possibility: nightly rake task that deletes everything that isn't used for the volunteer time on site statistics.   (we abandoned this idea for the following one)
3)  alternatively:  nightly job that creates roll up totals for each person for each project in a new "data warehouse" table.  Modify contributors report to read from this new table.  Then delete all the ahoy entries for that day.
4)  If I delete my personal account, what happens?  Like deeds, we should "move" their ahoy deeds/the data warehouse stuff to a guest user.  (See user deletion code and what we do with deeds.)
5)  Data warehouse table fields should include:  userID, collectionID, Day, Total Time.

Also fix #791 as part of this work.

**Comment by benwbrum** [comment]
A quick note on Ahoy: we used the detailed click tracking today to troubleshoot a problem we couldn't reproduce, looking back at clicks as old as two weeks ago.  I suggest that we retain such clicks for 2-4 weeks before deleting them.  That would modify step 3 above to delete the ahoy entries outside the retention window.

**Comment by benwbrum** [comment]
A strategy has been developed in #1589 which will delete Ahoy data older than two weeks while preserving time entries.
