### ISSUE TITLE
nybg: Coordinators want weekly/etc roll-up of contributor contributions 

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1077]
Coordinators want to know how many contributions each contributor made during a period of time.  It makes sense to add this as new columns to the contributor tab spreadsheet download.

**Comment by jackweinbender** [comment]
How do we define a "contribution"? Is it any deed? or is there a subset of deeds that we should count?

**Comment by benwbrum** [comment]
The spreadsheet has a row per contributor with statistics (currently minutes worked) for their activity on that collection during that time window.  We'd like to add columns for pages transcribed, page edits, notes, etc. -- essentially the same stats we show on the statistics screen for a collection, but on a per-user basis.
