### ISSUE TITLE
contributors in IIIF export

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1081]
The IIIF export needs to include the contributors for a page or a work. 

@benwbrum please define what this should look like and then assign to @jackweinbender.

This is a requirement for the Stanford Libraries/Parker Library project.  We'll need it before they import back into the Parker on the Web site.

**Comment by saracarl** [comment]
Depends on #1082

**Comment by benwbrum** [comment]
We should expose an array of the users who edited a page as an element on the transcript annotation.  @saracarl and I have examples on how this works in other systems.

**Comment by benwbrum** [comment]
Hey @diegoviola, I'm pretty sure you did this back in July. Can I close this?
