### ISSUE TITLE
Include ORCIDs for contributors

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1082]
Contributors should be able include their ORCIDs, likely as a field in their profile.

Example ID:
https://orcid.org/0000-0001-8774-7964

We need to figure out how we include those IDs (URIs, basically) in our exports.

**Comment by saracarl** [comment]
Related to #1081

**Comment by bencomp** [comment]
It would be great if people can log in using their ORCID too, but that's another issue (I know OAuth is available, so I should try to configure it for ORCID).
