### ISSUE TITLE
When uploading images that don't need resizing image permissions aren't correct

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1093]
When you upload images in a zip files with a metadata.yml file, they are processed and put on the filesystem correctly, but do not have the right permissions:

-rwx------ 1 fromthepage fromthepage 251632 Jun 14 21:08 young-740_031614_cca659.jpg
-rwx------ 1 fromthepage fromthepage 139465 Jun 14 21:08 young-740_031614_cca660.jpg

Need to be world readable.

**Comment by saracarl** [comment]
After reviewing the code, don't think the metadata.yml processing would affect this.  It's happened twice now, but I'm not sure of the pattern.  This upload was a zip file with jpg in it.  Maybe it's the jpgs?  If so, it would be this line:
https://github.com/benwbrum/fromthepage/blob/fd801d2d275b170816e8a91870199655e50b6871/lib/tasks/ingestor.rake#L152
destination = ImageHelper.compress_image(path)

I'm about 80% sure what's happening is that these images are small enough not to need compression (supported by the rareness of the "Compressed file is now..." messages in the upload log) Without compression, the files aren't rewritten, which means they don't inherit the appropriate permissions.

https://github.com/benwbrum/fromthepage/blob/1ebf1cd5d227d3cb92de95ade2b9bccfcd17b250/lib/image_helper.rb#L64

I'm not sure how to fix it, because that resize code is called recursively, and it seem not-performant to rewrite every time an image doesn't need compressing.  

@benwbrum ?

**Comment by benwbrum** [comment]
When I download the zip file and unzip it, the images are 700:
```
gomer-740_031614_cca393.jpg  gomer-740_031614_cca394.jpg  metadata.yml
benwbrum@mariecurie:~/dev/products/fromthepage/scratch/lva_zip/upload/740-stonewallcamp-111$ ls -l
total 424
-rwx------ 1 benwbrum benwbrum 267199 Jun 14 15:22 gomer-740_031614_cca393.jpg
-rwx------ 1 benwbrum benwbrum 159511 Jun 14 15:22 gomer-740_031614_cca394.jpg
-rwx------ 1 benwbrum benwbrum    419 Jun 14 15:22 metadata.yml
```

**Comment by benwbrum** [comment]
We can `chmod` each file at the beginning of the compression routine, or `chmod -R` the directory immediately after `unzip_tree`.

**Comment by benwbrum** [comment]
Better, at the end of the unzip command.

**Comment by saracarl** [comment]
I like that.

**Comment by saracarl** [comment]
Right before this line? 
https://github.com/benwbrum/fromthepage/blob/fd801d2d275b170816e8a91870199655e50b6871/lib/tasks/ingestor.rake#L102

**Comment by benwbrum** [comment]
That looks like the best spot.

**Comment by saracarl** [comment]
Dupe of #1170
