### ISSUE TITLE
Requests for TEI document get HTTP 302 redirect to dashboard page

### ISSUE THREAD

**Issue by jbhoward-dublin** [benwbrum/fromthepage#1094]
Requesting a TEI document returns a 302 redirect rather than the TEI document. See example below.

curl -i  https://fromthepage.com/export/tei?work_id=5367

`HTTP/1.1 302 Found

Date: Sat, 26 May 2018 08:31:36 GMT

Server: Apache/2.4.18 (Ubuntu)

Cache-Control: no-cache

Access-Control-Allow-Origin: *

Strict-Transport-Security: max-age=31536000

X-Request-Id: 2267dfd0-4e22-4bf7-a947-3a10749a0473

X-Runtime: 0.010423

Access-Control-Request-Method: GET

X-Powered-By: Phusion Passenger 5.1.8

Set-Cookie: ahoy_visitor=318594ae-f568-41f3-a1da-f09d7f60fbdd; path=/; expires=Tue, 26 May 2020 08:31:36 -0000; secure

Set-Cookie: ahoy_visit=81367357-31ba-4cbb-8228-0bb51e5577b0; path=/; expires=Sat, 26 May 2018 12:31:36 -0000; secure

Set-Cookie: _fromthepage_session=azNlK0IwRzFXazlyNWxGNCtKazNxQUZsSFdFb09ONlBxWFdybXVhWnVOZjZQTGhXa3dDY2pqOTBubU45NUJ5MjV4STRnZU5vME1MeVNPZFNHbElFRS9neld3aUZYcy9NK1loVGZ1NE8vODdGeXhzbzd2YVE4enNIWWd3djZzcUUtLVRGOHVUZ0N5YmMzYkx1cE00YTZHeVE9PQ%3D%3D--0a578ee5e7118a1042154b956be3b855895d028e; path=/; secure; HttpOnly

Location: https://fromthepage.com/dashboard

Status: 302 Found

Transfer-Encoding: chunked

Content-Type: text/html; charset=utf-8`

**Comment by benwbrum** [comment]
Works now.  Possibly this is related to private collections.
