### ISSUE TITLE
Pagination on the "read work" pages

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#110]
From @saracarl - Can you review how pagination looks for screens like http://beta.fromthepage.com/display/read_work?ol=c_work_list_work&work_id=3 and recommend a course of action?

**Comment by kolking** [comment]
Explain please. What do you feel is wrong with the current pagination? Why do you think it's require an improvement and what would you like to achieve in terms of user experience?

**Comment by benwbrum** [comment]
Thanks.  We will double-check the pagination under the new UI and see if we
have more concrete suggestions.

**Comment by benwbrum** [comment]
I double-checked this, and am pleased with the results -- looks like you got to this earlier and I missed it.
