### ISSUE TITLE
get rid of emails when someone else edits a page you edited.

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1101]

**Comment by saracarl** [comment]
We've received another email from a transcriber complaining that someone WRONGLY made changes to their transcription.  Sigh.

Removing "page_edit" from the deed_type on line 25 of user_helper would probably fix this.  

```
   user_page_ids = user.deeds.where(deeds: {deed_type: ['page_trans', 'page_edit', 'review', 'note_add', 'ocr_corr']}).pluck(:page_id).uniq
      #find pages that have been newly edited by someone other than the user (the user is not the last editor)
      pages = active_pages.where(id: user_page_ids).select {|page| page if page.deeds.where(deed_type: ['page_trans', 'page_edit', 'review', 'ocr_corr']).last.user_id != user.id}
```

Would it make the owner emails not include edits?  Need to see where else the user helper is used.

user_helper doesn't exist anymore, think it got moved into contributor helper.  Review this to figure out what is the right thing to do:
https://github.com/benwbrum/fromthepage/blob/master/app/helpers/contributor_helper.rb

I think we want to make sure the emails go out when "someone worked on a collection you were working on", but not "someone edited a page you edited" -- we don't want to discourage transcribers, but we do want to keep folks coming back to work on collections they worked on in the past.

**Comment by benwbrum** [comment]
Liz at Maryland State Archives has requested this be fixed:

_ It would be great if the owner could shut off the "You have been edited" email feature (maybe I just haven't found it).  Some of our transcribers were hurt and huffy when they started getting these emails during our review process.  Some of the reviewers automatically clicked on <Save Changes> on EVERY page just to be sure, sending hundreds of "You have been edited" emails to our most dedicated volunteers, who took it as a negative judgement on their work. _

**Comment by jackweinbender** [comment]
From Ben: "Turning off emails transcribers get whenever someone edits a page they've worked on.
At this point they should only get emails when people (who are not them!) add notes to those pages."
