### ISSUE TITLE
Transcription Field configuration does not allow multiple lines

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#1107]
When I configure a collection for field-based transcription and start configuring the fields, I cannot add lines to the form.

![screen shot 2018-07-05 at 14 35 41](https://user-images.githubusercontent.com/1303898/42323563-ea83ed7e-8060-11e8-81cf-4e19e1d75197.png)

In this form, the "Add additional line" button doesn't do anything, whereas I expect to see a form below showing "Line 2" etc.

**Comment by benwbrum** [comment]
This works now.  (Please reopen if you can reproduce on the current code base.)
