### ISSUE TITLE
Clarify that 'Omeka connection' refers to Omeka Classic

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#1113]
Minor issue, 'follow-up' to #384.

Omeka has two branches of development: Omeka Classic and Omeka S. Both provide a APIs, but they use different types of authentication.

Only when one tries and fails to connect to the API of an Omeka S site, FromThePage says you can only connect to Omeka 2.1 or higher. It would be great if the interface says more clearly and before trying that Omeka (Classic) 2.1 or higher, but not Omeka S, is required.

(There is a [IIIF Server module for Omeka S](https://github.com/Daniel-KM/Omeka-S-module-IiifServer), which should allow users to import collections/manifests from Omeka S via IIIF. I haven't tried this yet.)

**Comment by saracarl** [comment]
relabelled in the UI; better Omeka S integration is on the roadmap.
