### ISSUE TITLE
Transcription screen (research only)

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#112]
From @saracarl - Users trying out the new translate feature have asked if, once they have zoomed in on a part of an image for a page they're reading, when they click a tab for the same page, if they can keep the image zoomed in at the same level.  Do we have any way to record the zoom level zoomer.js is at, then (when the user loads the same document page from a different tab [i.e. 'transcribe' from 'display']) bring zoomer.js back to that same part of the image?  (We need to load an example of this into your development database for you to see this)

**Comment by kolking** [comment]
Well, after checking the zoomer plugin I've realized the following:

* it does not have a method to get the current zoom level and pan position
* it does not have a method to set a zoom level in a runtime
* it has a method to pan, but it useless in our case

Don't get me wrong, I don't want to say it's impossible and I'm going to find a solution. I have a couple of works with images so I can test the zoomer functionality. Also, please clarify the phrase "when the user loads the same document page from a different tab" - have you mentioned a different tab of the **browser**?

**Comment by benwbrum** [comment]
Thanks Nick -- this is exactly what I needed to know.  

No need to work more on this.

**Comment by kolking** [comment]
Good news! I've found a way to get the current zoom level and pan position from the zoomer. Now I can utilize localStorage to save these values and recover zoomer's state. Please give me some time to finish with it, I think this feature will be very useful for transcribers.

**Comment by benwbrum** [comment]
Hi, Nick -- let's go ahead and tackle this, if you think you have a handle
on it.

The specific project that's asked for this is using a new feature of
FromThePage that allows documents to be translated after they're
transcribed.  If you login as a work owner for a work that has images, edit
the settings for the work and check "Supports Translation", you'll see a
new set of tabs when users are viewing or editing a page.

In addition to the "transcribe" tab, there will also be a "translate" tab
when `supports translation` is set on a work.  We anticipate users reading
texts, spotting problems in the transcript, zooming in on the relevant part
of the image, then hitting the "transcribe" tab to correct the transcript.
Ideally, this wouldn't lose the place where they are zoomed in.

Ben

**Comment by kolking** [comment]
I've finished, here is how it works now:

1. When a user leave a page with zoomer plugin instance loaded before, my handler stores the last used zoom level and pan position into the browser's local storage. It also stores the image file name to associate zoom & pan values with this particular image.
2. Once a user open the same page later, my function is checking a zoom and pan values in the local storage for the image and apply them if found.

As a result, for every image user request with the zoomer plugin the zoom and pan will be stored and restored once that image will be requested again. I think you better try this to see. Open a work page with the zoomer, scale imapge up and pan, click "Next Page", do the same (zoom&pan) on the next page, once again click "Next Page", do the same, and so on. Now, go back. You can move with "Prev Page", or using "Back" browser button, or, you can even close the browser window and re-open it. When you request any of the images you've zoomed before, the last state will be restored.

**Comment by benwbrum** [comment]
Fantastic!  It'll be about 5 hours before I can look at it, but I'm looking
forward to it.

Ben

**Comment by kolking** [comment]
Yes, please, some user testing would be great :)

**Comment by kolking** [comment]
Btw, my solution is quite isolated, so I can prepare it for including into the currently running beta version.

**Comment by benwbrum** [comment]
Excellent.  We only need it in your branch and in master at the moment, so
no need to put it in beta.

If you've made changes to zoomer.js you'd like to submit as a pull request
to that project, feel free to take a couple of hours to do that.

**Comment by kolking** [comment]
I didn't make any changes to zoomer.js, but updated it's version to the latest available just in case to keep it up-to-date. My function will work with the old zoomer's version as well. I can also push this feature into master if you wish.

**Comment by benwbrum** [comment]
Please do push the feature into master.

**Comment by benwbrum** [comment]
I just looked at this.  Very, very impressive.

**Comment by kolking** [comment]
@benwbrum thanks Ben!
