### ISSUE TITLE
white spaces in table headers break export

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1135]

**Comment by benwbrum** [comment]
We think this happens when a field configuration has a label with a trailing space.

**Comment by benwbrum** [comment]
An alternate explanation:
1) create a field to be transcribed with a trailing whitespace
2) transcribe a page of the text
3) rename the field to remove the trailing whitespace
4) export.

**Comment by benwbrum** [comment]
We really need to try to duplicate this in isolation to make sure we understand the underlying issue.  It may not be possible to do that before we push out th efix for LVA's issue.
