### ISSUE TITLE
transcription fields: add styling to distinguish labels from field values on transcription

### ISSUE THREAD

**Issue by AustinCarr** [benwbrum/fromthepage#1151]
For transcription fields, most users don't care about the labels on the full page transcription, what they actually care about is the data that has been input into the fields.

It would be nice to have some styling so that the labels to help distinguish labels from field values

<img width="689" alt="styling" src="https://user-images.githubusercontent.com/1855345/43525491-ecee144e-956f-11e8-9c71-2a3905e9553f.png">

**Comment by benwbrum** [comment]
I really like how this looks -- it's much more readable.

At the moment, the new styles appear on the single-page view (the "Overview" tab for a single page) but not on the read-work view (the "Read" tab for the work).  I wonder if the stylesheet isn't being included in the display controller, or if it needs to be added to `app/views/display/read_work`?

Read page view:
![lva_page_view](https://user-images.githubusercontent.com/199961/43771622-72075c00-9a05-11e8-8b97-684bdec24535.png)

Read work view (without styles):
![lva_read_work_view](https://user-images.githubusercontent.com/199961/43771621-71e73f92-9a05-11e8-8ce9-e7e6c513d408.png)
