### ISSUE TITLE
transcription fields: add "instruction" type for transcription fields

### ISSUE THREAD

**Issue by AustinCarr** [benwbrum/fromthepage#1153]
The "instruction" field type would be instructions from the collection creator to the transcribers themselves to help with certain fields that may be confusing.

![instructions](https://user-images.githubusercontent.com/1855345/43531759-7ea71b2a-957e-11e8-8f3b-6978643c08f7.png)

**Comment by benwbrum** [comment]
If I understand correctly, this is text meant to be shown by the application to the transcribers as in-line help, but not to be recorded on the transcript.

**Comment by AustinCarr** [comment]
Correct.
