### ISSUE TITLE
Owner's section - Modal dialog for "Import from Omeka.org" form

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#116]

**Comment by kolking** [comment]
@benwbrum could you please provide me with some omeka.org book urls, so I can test the import process and also add a validation similar to archive.org import form.

**Comment by benwbrum** [comment]
Wait a bit on this, please. The omeka integration is still in early development.

**Comment by kolking** [comment]
ok, no problem

**Comment by kolking** [comment]
Duplicate of #136, resolved by f208593
