### ISSUE TITLE
trial owners tab in admin view

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1177]
We need a way to review all the trial owners, when their account was created (or turned into a trial), how many pages they have, last login.  Basically, replicate the owner tab, but just for trial users.

**Comment by saracarl** [comment]
@benwbrum do you think we can close this?  Most of it is in the owner tab...

**Comment by benwbrum** [comment]
Happy closing this.  Current functionality seems to address this pretty well.
