### ISSUE TITLE
add html annotation to pages in iiif api

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1189]

**Comment by jbhoward-dublin** [comment]
I wonder what the rationale is for the change. Currently the plain text annotation is convenient for indexing; if does not matter really whether it is quoted as character data in the anno or referenced from a link. I think if FtP page were to carry over formatting information from the TEI into the annotation  we'd just strip the tagging info before indexing it. I assume that the same might be true for other third parties that might be passing the data into an annotation store or database for IIIF search.

So, if you make the change we'd adapt.

**Comment by benwbrum** [comment]
@jackweinbender How about a URI for HTML annotations on a particular canvas that roughly matches the `service` URIs:
from `http://localhost:3000/jbhoward/ucd-letters-71/note-from-john-henry-newman-to-an-unnamed-recipient-apologising-for-his-inability-to-answer-letters-due-to-old-age-355/export/18252/plaintext/searchable`
to `http://localhost:3000/jbhoward/ucd-letters-71/note-from-john-henry-newman-to-an-unnamed-recipient-apologising-for-his-inability-to-answer-letters-due-to-old-age-355/annotation/18252/html/transcript`
similarly `to `http://localhost:3000/jbhoward/ucd-letters-71/note-from-john-henry-newman-to-an-unnamed-recipient-apologising-for-his-inability-to-answer-letters-due-to-old-age-355/annotation/18252/html/translation`

**Comment by jackweinbender** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HTML Annotations](https://trello.com/c/j9flG4Kg/12-html-annotations)

**Comment by benwbrum** [comment]
@jbhoward-dublin For harvesting the page-level annotations for indexing, can you use the [`service` block for each canvas](https://github.com/benwbrum/fromthepage/wiki/FromThePage-Support-for-the-IIIF-Presentation-API-and-Web-Annotations#seealso-1) instead?  Since Mirador is aware of annotations (but not `service` or `seeAlso`) at the canvas level, we'd like to optimize the annotations for display/reader experience.

**Comment by jbhoward-dublin** [comment]
@benwbrum I've looked at the documentation linked in your comment for service blocks; it looks like this provides status informaiton but not links to annotations representing plain text transcriptions. Am I missing something?

I wonder, too, regarding the plain text versus html question, why both cannot be present?

**Comment by benwbrum** [comment]
@jbhoward-dublin My apologies; I'm afraid that I mistyped earlier. I meant the `seeAlso` block for each canvas, which includes links to plaintext exports for each canvas.

We'll explore retaining both, but are optimizing for the default Mirador experience, and will need to test how those work.

**Comment by jbhoward-dublin** [comment]
@benwbrum Thanks Ben, I did see the example under seeAlso and thought that the links there were appropriate, but wasn't sure that they'd be expressed at canvas level. As long as they are, then we're good to go!

**Comment by benwbrum** [comment]
Once we get the page-level HTML endpoint working and exposed as an annotation, we should also add that endpoint to the `seeAlso` block for better HTML harvesting.
