### ISSUE TITLE
Improve maxZoomPixelRatio setting on OpenSeaDragon

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1193]
If users are on very high-resolution monitors, or are looking at low-resolution scans, they may want to zoom in beyond the one-to-one pixel ratio.  This is an option configurable on OpenSeaDragon.

https://openseadragon.github.io/docs/OpenSeadragon.html#.Options

**Comment by jackweinbender** [comment]
Closed by #1198
