### ISSUE TITLE
subject categorizing context is wrong sometimes

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1194]
If you have the same verbatim text on the page in two or more places, but the text is only linked in one place, the context for categorizing that link will likely be wrong.  So if you have the word "Agua" linked and the word "Aguacaliente" elsewhere in the page (I'm guessing higher, but I didn't test that), then FtP will show "Aquacaliente" as the context even thought it wasn't the linked text.

**Comment by jackweinbender** [comment]
This was fixed by #1076. 

For example:
![image](https://user-images.githubusercontent.com/1544859/62807895-3fe37500-babc-11e9-883f-506a64bb0068.png)
