### ISSUE TITLE
Show subject URI (if present) as hotlink on subject overview page?

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#1195]
I just added a subject that is an Ottoman administrative title for which there is a Wikipedia page I'd like to use as a URI. If someone is browsing subjects, the URI and link won't appear on the overview page. I can get around this by repeating the URI in the description, but it would be simpler to just have the URI appear on the overview page -- and if it's a valid URL, even better if it appeared as a clickable link. This would foster exploration for visitors who are unlikely (or who will be unable?) to open the "Settings" tab for a subject.

**Comment by lortza** [comment]
I'm not sure where on the page this link should be put or what its text should look like. For example, do we A) make this article title a link? or B) add "Also see:" and the url? Are URIs always complete, linkable paths?

![Screenshot 2018-09-27 15.11.38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ba00ccd9e0f8c0011902af3/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc64167e3e7b53e37a25cbb279f1112343434d0eee1e020a17b8eb8339a3b23a76db5b5ee9d8655921946f11aeb8821bbb54b376df5d99a4fedb1294b7607caddecd5d340c071983fe5836a8994cc15bf343e44555b65e.png)

**Comment by benwbrum** [comment]
Definitely B, probably as "See also" and hot-linked to the URL with the URL itself as the anchor text contents.
