### ISSUE TITLE
Owner homepage does not show user sets they can collaborate on

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1196]
If a student account has access to a document set (that is otherwise private) and visits @atomrab's homepage, they do not see the document set.  We need to double-check the display logic to make sure it matches the collection screen's listing.

**Comment by jackweinbender** [comment]
I've reproduced this locally and I'll add some observations:
  1. This bug shows up for both collaborators AND "owners" (not the creating organization, but the list of "owners")
  2. This bug shows up for both `collections` and `document_sets`
  3. The activity bar on the right does not appear to be affected by either of these, i.e., private activity is likely being exposed.

**Comment by benwbrum** [comment]
On 3, the activity stream does not appear to show any activity on the use profile, even on collections that `current_user` is authorized to see.  So it doesn't look like we're leaking private data.

I think that we should test from the perspective of a transcriber who has a close institutional connection with an owner organization, has been granted access to their collections or document sets, and wants to work on their project.  They'd probably like to use a project homepage (like `localhost:3000/adah`) to see the projects they'd like to choose from and to see activity happening within projects they're on for that organization.  They'd also like to use that homepage to choose a document set to transcribe on.

**Comment by jackweinbender** [comment]
Closed by #1146
