### ISSUE TITLE
Add database ERD to the new dev resources

### ISSUE THREAD

**Issue by lortza** [benwbrum/fromthepage#1203]
An ERD of the database may be helpful to new devs who are learning the relationships between the many tables in this app. Either the new dev resources google drive or to the [wiki](https://github.com/benwbrum/fromthepage/wiki) seems like a good spot for one. As I understand it, the schema is not changing very frequently, so this would not be a liability for misinformation.

### Current ERD 
<img width="950" alt="screen shot 2018-09-18 at 11 13 06 am" src="https://user-images.githubusercontent.com/8680712/45701076-dec55280-bb33-11e8-8229-dc79c6e9609a.png">

Download the pdf: [erd.pdf](https://github.com/benwbrum/fromthepage/files/2393533/erd.pdf)

### Generating the ERD
There is a [gem called `rails-erd`](https://github.com/voormedia/rails-erd) that uses Graphvis to read your schema and generate a pdf. This is how I generated the linked file above. The gem can be installed for the generation and then uninstalled, or we can leave it in there for future convenience.

**Comment by benwbrum** [comment]
Done.
