### ISSUE TITLE
"Mark page blank" should log a deed

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1214]
We do not currently log deeds whenever a page is marked blank.  This may seem trivial, but turns out to be important for the contributions API.

**Comment by lortza** [comment]
Views where activity stream happen
- [ ] Edits section: collections and recent ac
- [ ] Projects Tab: activities
- [ ] Show more tab: long form activity stream
- [ ] app/views/deeds/list
- [ ] deeds helper
- [ ] collection show line 96
