### ISSUE TITLE
DeedType string page_pg_xlat bug

### ISSUE THREAD

**Issue by lortza** [benwbrum/fromthepage#1223]
## Bug Fixed
While working on #1221 (replacing `DeedType` strings with constants), I noticed what looks like a broken query for for the translation count in the owner and document set statistics. I’m guessing that these `page_pg_xlat` strings in the links below are supposed to be `pg_xlat`.

- https://github.com/benwbrum/fromthepage/blob/master/app/models/document_set_statistic.rb#L47
- https://github.com/benwbrum/fromthepage/blob/master/app/models/owner_statistic.rb#L49

I have made those replacements in this branch. 

### Due Diligence 
I am _fairly_ certain that no deeds in the production db could have a `deed_type` of `'page_pg_xlat'` because 1) it would not have been assigned originally and 2) the character count exceeds the db limit. However, it is possible that they could exist as relics from previous versions. I would recommend checking the production database to see if it exists.
```
Deed.all.pluck(:deed_type).uniq
```
If so, we can write a small script to replace those instances and recommend to our customers that they do the same.

I am also making the assumption that correcting this bug will not cause other bugs. I've run the test suite with the corrections, and it is passing.

**Comment by benwbrum** [comment]
Here is the distribution of deed types in production:
```
mysql> select deed_type, count(*) from deeds group by deed_type;
+------------+----------+
| deed_type  | count(*) |
+------------+----------+
| art_edit   |     1976 |
| note_add   |     7307 |
| ocr_corr   |      107 |
| page_edit  |   144047 |
| page_index |     2605 |
| page_trans |    88038 |
| pg_xlat    |       63 |
| pg_xlat_ed |       73 |
| review     |    18290 |
| work_add   |     9534 |
| xlat_index |        3 |
| xlat_rev   |       10 |
+------------+----------+
12 rows in set (0.41 sec)
```
