### ISSUE TITLE
Clean up `Page` status strings

### ISSUE THREAD

**Issue by lortza** [benwbrum/fromthepage#1225]
The `Page` class has a few constants for indicating a page's status:
```
class Page < ActiveRecord::Base
...
  STATUS_TRANSCRIBED = 'transcribed'
  STATUS_BLANK = 'blank'
  STATUS_NEEDS_REVIEW = 'review'
  STATUS_INDEXED = 'indexed'
  STATUS_TRANSLATED = 'translated'
```
_See [page.rb](https://github.com/benwbrum/fromthepage/blob/development/app/models/page.rb#L57-L61)_

They appear as namespaced constants like `Page::STATUS_NEEDS_REVIEW` in many parts of the codebase:
```
service["pageStatus"] << "needsReview" if page.status == Page::STATUS_NEEDS_REVIEW
```
_See [iiif_controller.rb](https://github.com/benwbrum/fromthepage/blob/development/app/controllers/iiif_controller.rb#L728)_

However, there are some places where their string values are being used instead of the constant:
```
# Current Use:
-if page.status == 'blank'

# Preferred Use:
-if page.status == Page::STATUS_BLANK
```
_See [display/_pages_view.html.slim](https://github.com/benwbrum/fromthepage/blob/development/app/views/display/_pages_view.html.slim#L35)_ 
and this leaves room for error. We'd like those strings to be replaced with constants. 

## Similar Existing Code
Similar work was done with the `DeedType` class.

**Comment by pratik0809** [comment]
I'll take this one!

**Comment by diegoviola** [comment]
@benwbrum done.

Just some observations:
- I did some additional "cleanup" and removed some trailing whitespace.
- The nested conditionals in `display_helper.rb` (`page_action` method) could IMHO see some refactoring (make it more object-oriented).
