### ISSUE TITLE
Improve time_ago function

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#123]
Show "MM month(s) ago" and "YY year(s) ago"

**Comment by diegoviola** [comment]
Rails has a `time_ago_in_words` for this purpose.

http://api.rubyonrails.org/classes/ActionView/Helpers/DateHelper.html#method-i-time_ago_in_words

Why not use it?

**Comment by kolking** [comment]
@diegoviola I might be wrong, this function was initially added before I came to the project, but I assume that the reason of not using the `time_ago_in_words` is because it may produce a longer strings, for example:

* less than a minute ago
* about 3 months ago
* over 2 years ago

The custom function keeps the strings short and more consistent.

Maybe the better idea would be to override the default messages in `en.yml` but if we just omit all these "less than", "about", "over", and "almost" the result will be not quite accurate because "almost 1 year ago" is not the same as "1 year ago"

@benwbrum what do you think of it?

**Comment by benwbrum** [comment]
The custom function was created several years ago, back in the days of
Rails 1.2 or earlier.  I'd be happy to switch to the standard Rails form
from the custom function.

Thanks for the suggestion, @diegoviola!

**Comment by kolking** [comment]
@saracarl I've replaced the old custom function with the Rails standard one

**Comment by saracarl** [comment]
Looks great!
