### ISSUE TITLE
Hierarchical project list for org homepage

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1232]
Organizations like the Library of Virginia may have several projects (WW1 questionnaires, pension applications, photograph collections) uploaded as individual collections, with document sets under each collection used to organize material by county.  They'd like to be able to present these on their organization landing page as a tree:
```
WW1 Questionnaires
  County A
  County B
  County C
1812 Pension Applications
  County A
  County B
  County C
```

Since we treat document sets as if they were top-level collections (which is valid for other use cases) they are instead organized in a flat, alphabetical format:

```
1812 Pension Applications
County A
County A
County B
County B
County C
County C
WW1 Questionnaires
```

This layout is confusing for volunteers on each project.

We'd like to re-model the organization home page to present a new hierarchical display *if a project has public collections with document sets*.  So the logic should be something along the lines of:

```
for each collection-or-set
  if collection-or-set.is_a Collection && collection.public?
    print collection title/description/link (as top level)
    for each collection.document_set
      print document set title/link (as member)
  if collection-or-set.is_a DocumentSet && set.collection.private?
  print document set title/link (as top-level)
```

**Comment by saracarl** [comment]
only caveat:  don't show private document sets of a public collection
