### ISSUE TITLE
Some collection links not working in Collections index

### ISSUE THREAD

**Issue by lortza** [benwbrum/fromthepage#1237]
## Expected Behavior:
- branch: `development`
- on the `http://localhost:3000/collections` page
- as a signed out user
- click on a collection title
- go to that collection's show page

## Actual Behavior 
- branch: `development`
- on the `http://localhost:3000/collections` page
- as a signed out user
- click on a collection title "1902 Minute Logic" 
- be redirected back to `http://localhost:3000/collections` 

## Theory
I located the record in the database and discovered:
- it is a `DocumentSet`
- it is not public
<img width="611" alt="screenshot 2018-11-05 19 23 13" src="https://user-images.githubusercontent.com/8680712/48037113-b2d84d80-e130-11e8-8d9e-675413056106.png">

My theory is that while `DocumentSets` are supposed to be displayed on the public Collections page, _private_ ones are not.

**Comment by saracarl** [comment]
We believe this is fixed.
