### ISSUE TITLE
provide volunteer transcribers with their time on their dashboard

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1240]
On the right side of the contributor dashboard (https://fromthepage.com/dashboard/watchlist) under "Your activity" create a "Your time" section that shows 

Need to discuss this to find the right time for volunteers.  2 possibilities:

week to date
month to date
year to date
all time

This week
1/1/2018-1/8/2018
1/24/2017-1/31/2017
(going back this week + 4 previous weeks, to cover an entire month)

Student service hour reporting and LVA has people transcribing for court mandated service hours.

**Comment by saracarl** [comment]
How SI is doing this:
https://twitter.com/TranscribeSI/status/1389569247857188870

**Comment by saracarl** [comment]
request for this from a transcriber today.

**Comment by benwbrum** [comment]
To address (if possible) in #2822

**Comment by saracarl** [comment]
Closed -- volunteer service hour letter & dashboard is now available.
