### ISSUE TITLE
show the IIIF manifest URI in the "export" tab of a collection by work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1263]
show the IIIF manifest URI in the "export" tab of a collection by work

**Comment by saracarl** [comment]
maybe include the iiif URL?

**Comment by benwbrum** [comment]
On the export tab, in addition to HTML, TEI, Plaintext export formats, we'd also like a link to the IIIF manifest (e.g. `https://fromthepage.com/iiif/9/manifest`).  For now, just use the text `IIIF` for the anchor element.

**Comment by benwbrum** [comment]
In addition to the link to the API for each work, we should add a link to the IIIF collection manifest (e.g. `https://fromthepage.com/iiif/collection/1` ) displayed at the bottom of the Export screen.

This link should appear under the text "We also have an API for programmatically exporting transcripts for your collections." next to the text
Collection API Endpoint: `link`
