### ISSUE TITLE
More usable "page has been changed" email contents

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1264]
Transcriber sent the following in response to one of the emails that start like this:

"We just wanted to let you know that there's been activity in a collection that you worked on."

Her response:
Thanks for the info.  Of course I am unable to see where the corrections were needed or made.

Which is totally valid.  The answer is "go look at the versions tab".  We need to enhance that email text to direct people to the versions tab of the page.

Click here  to view page WWIM0009530-A in Indiana World War I Service Record Cards: Indiana WWI Service Record Cards, Army and Marine Last Names "MOO - MOP", which has been edited since you worked on it.

Should become:
Click here  to view changes to page WWIM0009530-A in Indiana World War I Service Record Cards: Indiana WWI Service Record Cards, Army and Marine Last Names "MOO - MOP", which has been edited since you worked on it.

and the link should be to the versions tab, i.e.:
https://fromthepage.com/indianaarchives/indiana-wwi-service-record-cards/in-wwi-service-record-cards--army-and-marine-moo-mop/versions/357527
Instead of the page:
https://fromthepage.com/indianaarchives/indiana-wwi-service-record-cards/in-wwi-service-record-cards--army-and-marine-moo-mop/transcribe/357527

**Comment by benwbrum** [comment]
We took out the "page has been edited" email, so this may be moot.
