### ISSUE TITLE
double brackets not exporting (no subject linking)

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1277]
We decided to use double brackets to mark non-textual elements on a page, for example [[official seal]] or [[postcard]].  We have disabled  "subject indexing" but have found that the double brackets aren't exporting with the text. We simply get postcard and not [[postcard]].

We would like to be able to use double brackets in this way if possible. Is this something that can be addressed?

**Comment by benwbrum** [comment]
Scenario 1:  [[James Smith | Jim]] in the transcription, but "subject indexing" is disabled
In this case, the export should show James Smith  
This is what the code already does.

Scenario 2:  [[James Smith]] in the transcription, but "subject indexing" is disabled
In this case, the export should show [[James Smith]]
This *could* be a subject link (from before subject indexing was disabled), but this case seems less likely than the needs of our plaintext transcribers.

@benwbrum please review before @jackweinbender works on this.  We are concerned that  exports with subjects in 2 different link formats will insert brackets in the second scenario but not the first, which is weird.

**Comment by benwbrum** [comment]
Another thought:  We could also take the approach that if subject linking is turned off, there is no such thing as a subject link in the text.  Therefore, any brackets in the text are treated as plaintext markup, even if they happen to look like [[James Smith|Jim]].  Don't like it, go fix it.  :)  
In other words:  Subject indexing being enabled or disabled changes the semantics of what double brackets are or do.

This is what @jackweinbender and @saracarl think we should do.

**Comment by benwbrum** [comment]
That last approach is what the client actually wants -- "no such thing as a subject link" is precisely what they're after.

**Comment by benwbrum** [comment]
Ben's "simple" solution to disable the wiki-mark-up is more difficult and requires:
* Refactoring the `wiki_to_xml` method into two methods
  * Wikilinks-to-xml just handles links
  * Whitespace-to-xml just deals with line breaks and non-link stuff like that
* Conditionally calling wikilinks-to-xml based on the collection setting.
