### ISSUE TITLE
add support@fromthepage.com to the list of transcribers for a collection

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1278]
We'd like to be "in the loop" for project owners when they send transcription newsletters.  Easiest way is to just add support@fromthepage.com to their list of transcribers.  (Just the copy and paste list.)

**Comment by JosieBrum** [comment]
Collaborator tab for a collection, at the bottom, list of email addresses

**Comment by JosieBrum** [comment]
https://github.com/benwbrum/fromthepage/blob/fe44c777adb0b164dc02e0eb43548d74f8f25723/app/models/owner_statistic.rb#L73

Could maybe add line that just adds support@fromthepage.com.

**Comment by JosieBrum** [comment]
https://github.com/benwbrum/fromthepage/blob/bcdc11bcc5f408a8ba3c1d4e11ebb0febce8f6ca/spec/features/owner_view_spec.rb#L97
Better option.

**Comment by saracarl** [comment]
I don't think we want to add it to the all_collaborators because that will be used elsewhere (and not having a deed for a collection would probably break things).  Can you find the view where it is displayed and just add it "on the fly" there?

The owner_view_spec.rb is actually a test, not part of the product.  (It tests the product.)  So that's not a good place to change it.

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/51502e74ddcf93cb132b2e4f1f4f49606989ce82/app/views/statistics/collection.html.slim#L12

https://github.com/benwbrum/fromthepage/blob/51502e74ddcf93cb132b2e4f1f4f49606989ce82/app/views/collection/_contributors_body.html.slim#L34
