### ISSUE TITLE
improve time tracking

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1285]
So if you use the activity time reporting as a project owner, it can be way off.  This happens when a transcriber has the transcription screen open and walks away -- for lunch, for the day, for the week....  

Two thoughts on how to improve this:
-- if it's been more than an hour between deeds, take that time out.
-- find a javascript library that basically sees if the tab is active, etc.  similar to what Pandora does "are you still here?"  Maybe we log them out if they aren't active or don't respond to a popup? (hmm -- risky if there is a transcription in progress) 

The first might be easier to implement.

**Comment by saracarl** [comment]
It takes more than an hour to transcribe a medieval document.

**Comment by benwbrum** [comment]
We addressed this in #3502
