### ISSUE TITLE
Translation screen offers image or transcription

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1294]
When on the translate tab, it would be nice to have the option of displaying the original page or the transcribed text.

Implementation idea:  Include both divs and have a javascript that sets display=none on one or the other

**Comment by saracarl** [comment]
If not transcription, show the image by default

**Comment by benwbrum** [comment]
This has been requested by KamranOnBike and SDSUDigital.

**Comment by benwbrum** [comment]
On the translation tab, I would go ahead and render two `div` elements, one containing the zoomable facsimile, and the other containing the transcript text.  Then add a button that uses javascript to toggle visibility of each div.

Open question: if there is no transcript, should we even show the toggle?

Open question: which div should we show initially?

Side discussion: how does support for translation-first projects impact project status, the read-work view, etc.?  (Tabled)
