### ISSUE TITLE
bug: "all works are fully transcribed" when not

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1299]
![screenshot from 2019-02-27 08 04 39](https://user-images.githubusercontent.com/708566/53496010-be94aa80-3a66-11e9-94f2-c4cb62fcb690.png)

I'm not sure what is causing this.

**Comment by saracarl** [comment]
https://fromthepage.com/saracarl/iiif-showcase-2018?works=hide <-- this is the collection that has it wrong.

**Comment by saracarl** [comment]
This might be related to #1351 -- we should check and see if it is fixed once that issue is fixed.

**Comment by benwbrum** [comment]
Can't reproduce; probably a dupe of #1351 (and fixed manually).
