### ISSUE TITLE
add collection view to admin dashboard

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1304]
I need a way to see the most recent collections across FromThePage.com.  I think we do this as the last 100 (50?  20?) collections created with the following fields:
Collection owner
Collection name
public?  y/n
last activity 
number of deeds (?)

please link the collection owner and name to the appropriate places.

**Comment by isabelabarton** [comment]
![Screen Shot 2020-08-03 at 2 07 07 PM](https://user-images.githubusercontent.com/66695287/89217929-b06b8780-d592-11ea-8f55-5f9ac6a5713b.png)

Would this be a tab in here? @saracarl

**Comment by benwbrum** [comment]
We already have a collection listing which was designed to accomplish part of this, accessed by clicking on the number of collections.  It's not very usable at all however; we should totally refactor it to display all collections in datatables.

**Comment by benwbrum** [comment]
This is completed.
