### ISSUE TITLE
Contributor activity email includes too much

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1307]
I added to notes to a work I didn't own and edited a page on the evening of March 13.  The next morning, I got an activity report saying that something had happened on each of the three pages.

I clicked through and discovered that no actual changes had been made since my edits; rather the three pages had all been edited earlier in the day on March 13.

We should modify the contributor activity email to only report on activity that happens after the user's's activity, to minimize surprise.

**Comment by benwbrum** [comment]
To reproduce:
* User A adds note to page 1.
* Contributor activity email runs
  * User A should not get email about activity on page 1
* Later, User B adds a note to page 1
* Contributor email runs
  * User A should get email about activity on page 1
  * User B should not get email about activity on page 1

Note that we do not need to filter out a user's own contributions from the email contents itself.  It's fine to list the User A's activity in the email to User A.  What we want to avoid is a situation when a user gets email, is happy because someone has worked on their project, then is disappointed when they open an email and see it was only themselves.

**Comment by diegoviola** [comment]
@benwbrum I cannot reproduce this.

The current implemented behavior works exactly as you describe.
