### ISSUE TITLE
Disable Guest Registration

### ISSUE THREAD

**Issue by JustAShoeMaker** [benwbrum/fromthepage#1308]
Or more appropriately "transcribe as guest"

Helping a prof out. Is there a way to disable guest registration entirely? (I understand there is a captcha setting and a way to set the number of saves required, so 0 would require immediate registration or infinite?) But trying to limit the number of pharmacies and other sales organizations around the world we support.

(enhancement perhaps, still learning the vocabulary of the application, but the code is helpful, so rather than restrict work to a set of scribes, what might also be helpful, in addition, is to restrict work to all registered scribes for when guests are allowed?)

Thanks

**Comment by benwbrum** [comment]
We'd like to add a configuration parameter to disable guest registration/transcription on a site-wide basis.

**Comment by saracarl** [comment]
You can also set:
GUEST_DEED_COUNT = 0
config/initializers/01fromthepage.rb
which still displays the guest option, but won't let the guest save any pages.

Also consider the recaptcha option to reduce any robot-y stuff:
https://github.com/benwbrum/fromthepage/wiki/Configuring-FromThePage-For-Your-Environment#recaptcha
