### ISSUE TITLE
Add community guidelines to the bottom of user activity emails

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1309]
FromThePage is a collaborative transcription platform.  That means we collaborate -- work together -- to transcribe interesting historical documents.  If someone makes a change to a page you transcribed, please consider it well-intentioned.  It's easy to take corrections as criticism, but they probably aren't.  Even professional writers have editors that correct their work.

Things to consider:
-- Did I make a mistake?  If I did, that's OK -- mistakes are human.
-- Were the changes to my transcription a mistake?  If so, the right course of action is to fix the transcription, but not to get upset.
-- In doubt?  Review the transcription conventions on the bottom of the page, the help tab, and the example documents.  Have a civil conversation in the "notes" on the page.  You can also contact the project owner, usually listed on the footer of every page.

**Comment by saracarl** [comment]
Inspired by https://mastersofscale.com/caterina-fake-build-a-more-human-internet/  
Do a blog post about this change once we get it rolled out.

**Comment by benwbrum** [comment]
We removed the "you've been edited" emails instead.
