### ISSUE TITLE
Images distorted in banner

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1313]
So the Stanford AI Lab is a good example of this.

https://fromthepage.com/stanforduniversityarchives
![Screenshot from 2019-03-28 12:42:10](https://user-images.githubusercontent.com/708566/55180215-21a55a00-5157-11e9-83d5-09fa50f7a4b6.png)

Because it's more horizontal than vertical.  It looks OK if you click through to the collection.

**Comment by saracarl** [comment]
@anabeabas Would you test this and see if it is still happening?  If not, close it.

**Comment by anabeabas** [comment]
@saracarl It looks okay to me!

![image](https://user-images.githubusercontent.com/98731543/227980121-b7e17132-2775-4385-a1d0-7c8842fe1c6f.png)

**Comment by benwbrum** [comment]
I think that this was fixed by the replacement of the carousel.
