### ISSUE TITLE
missing collaborators when adding to restricted works

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1315]
USHMM says that when you are trying to add a user as a collaborator in a work, sometimes they can't find that user (but sometimes they can).  

My best guess is that the full list hadn't loaded yet.  (If you were working quickly to keep trying it, I could see that might have happened.) We haven't thought of that piece of FromThePage as needing performance tuning, but it seems like it might.  I

@benwbrum  do you agree with my assessment here or do you think it's something else?
Can we look into making that list load faster or search better?

**Comment by benwbrum** [comment]
Issue #1317 fixed this problem.
