### ISSUE TITLE
IIIF manifests give 500 errors

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1326]
Several of the Julia Brumfield Diaries manifests are giving errors, including returning the wrong item and producing 500 errors.

The following manifests yield 500 errors:
* https://fromthepage.com/iiif/17/manifest
* https://fromthepage.com/iiif/6/manifest

**Comment by benwbrum** [comment]
An example of what should be returned instead of the `500` errors: https://fromthepage.com/iiif/9/manifest

**Comment by benwbrum** [comment]
We did not explaine what should happen in cases of source_text being nil. If that happens, we should still create a canvas with an image-resource annotation. This code may suppress the error, but it will also hide a lot of legitimate pages that have images but don't have transcriptions.

If there is no image information, however -- if the width/height attributes are nil for a `page` object, we should not generate the canvas.

I'm not sure why we're getting the 500 error -- what's the exception?

**Comment by saracarl** [comment]
Diego, do you know why this change would have resulted in a 25% increase in page load times?

So the working example:  http://localhost:3000/iiif/9/manifest
takes 28.18 seconds to load. 

```Oink statistics:

Completed 200 OK in 26360ms (Views: 21.0ms | ActiveRecord: 4748.4ms)
Oink Action: iiif#manifest
Memory usage: 591608 | PID: 3171
Instantiation Breakdown: Total: 2050 | User: 746 | Work: 374 | Collection: 374 | Page: 372 | ActiveRecord::SchemaMigration: 175 | Note: 5 | Visit: 2 | WorkStatistic: 1 | Ahoy::Event: 1
Oink Log Entry Complete
```

In the development branch, the same request takes
20.44 seconds to load
```Completed 200 OK in 18322ms (Views: 10.9ms | ActiveRecord: 4430.2ms)
Oink Action: iiif#manifest
Memory usage: 591708 | PID: 3319
Instantiation Breakdown: Total: 2050 | User: 746 | Work: 374 | Collection: 374 | Page: 372 | ActiveRecord::SchemaMigration: 175 | Note: 5 | Visit: 2 | WorkStatistic: 1 | Ahoy::Event: 1
Oink Log Entry Complete```

The same number of objects are being instantiated.
