### ISSUE TITLE
Restyle collection pages - Categories tab

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#133]

**Comment by kolking** [comment]
I've moved category management to the Subjects tab:

![image](https://cloud.githubusercontent.com/assets/4656448/7673080/c09334b2-fd13-11e4-913f-2d7a787747dd.png)

For sure, the actions menu is visible only to the collection owners. I've also added the ability to edit an existing category title.

**Comment by benwbrum** [comment]
I suspect that this will be OK, but setting up categories is usually
something that only happens once or twice for a project.
