### ISSUE TITLE
 Adding document set context for individual works. 

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1330]
LVA asked:

Also, as far as improvements/ requests, if each document could show the doc set it belongs to in the title area (below), that would be great. I get that we may have more levels than some other places, but that would be a nice option for us (WWI Questionniares - Accomack County - Powell, Cecil Cleveland, for example). Users are often able to work through a document, but get stuck at the last page going "now what?" I think the breadcrumb navigation may help (?).

![image(1)](https://user-images.githubusercontent.com/708566/56140563-bfbf5f80-5f60-11e9-8239-a975d23815e8.png)

I responded:

Adding document set context for individual works.  I like this idea.  The challenge is that a single work can belong to more than one document set, and we don't know how the transcriber got to this particular work.  What if we added a list of document sets the work belongs to?  I think a line directly under the "World War I Questionnaires --> Powell, Cecil Cleveland" line, a list of all the document sets this work is part of:  "belongs to Accomack County, Northern Virginia Counties, Last Names starting with Po"  I think that gives transcribers more context to find additional works, would only list your county document set, and wouldn't matter how they had found this particular work.  Do you think that would work?

**Comment by benwbrum** [comment]
If we just add the first document set, that might be enough.

**Comment by benwbrum** [comment]
We discussed this again this week, and came up with this solution:

On the About tab, list the document sets a work is part of (which the current user can see).

**Comment by saracarl** [comment]
Sherilyn at WWP asked for this as well.
