### ISSUE TITLE
searching collections should search owner names 

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1334]
So it's getting hard to find particular collections, because we remember the owner, i.e. Chicago Botanic, but not the name of the collection "The Scientific Notebooks of German Orchidologist Friedrich Wilhelm Ludwig Kränzlin".  We should search owner names as well as collection names when you search from the "Find a Project" page.

**Comment by benwbrum** [comment]
So ideally a search for "Virginia" would find the Library of Virginia, the University of Virginia, and the University of Virginia Law Library.  This may require changes to whatever view we are using to display search results.

**Comment by benwbrum** [comment]
Concrete reproduction scenario using recent production data:

* Search for "vertebrate" on the Find A Project screen.
* Expected result: Find projects by the Museum of Vertebrate Zoology
* Actual result: Find no results
