### ISSUE TITLE
ReCAPTCHA blocked in China

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1348]
Chinese transcribers are unable to sign up because the ReCAPTCHA will not display for them.  Apparently we can address this by changing the recaptcha URLs: https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally

**Comment by saracarl** [comment]
solution-ish:  https://github.com/ambethia/recaptcha/pull/306/files

**Comment by jackweinbender** [comment]
I went ahead and made a [PR in the ReCAPTCHA repo](https://github.com/ambethia/recaptcha/pull/320) and it looks like they've already merged it. I don't know what their release cycle is like, but once it lands it should be as simple as updating that Gem.
