### ISSUE TITLE
Review Work-completeness statistics

### ISSUE THREAD

**Issue by jackweinbender** [benwbrum/fromthepage#1349]
Perhaps related to  #471

I'm noticing certain percentages and statistics for works that are either wrong or unintuitive. For example, the statistics given below says that this is 0% transcribed:
![image](https://user-images.githubusercontent.com/1544859/58120006-ead54880-7bc9-11e9-8c96-566345ec0199.png)

But, upon inspecting the pages, we see that the whole thing is transcribed, but marked as "Needs Review".
![image](https://user-images.githubusercontent.com/1544859/58120225-646d3680-7bca-11e9-985f-5f97fb0dd952.png)

I assume this has something to do with how we deal with page `status`: pages are only `transcribed` if they aren't also `needs review`. Maybe this makes sense and I'm just not understanding the system. 

If nothing else, it may be worth looking at how we label these statistics (e.g., whats the difference between the yellow and green bars?)

**Comment by saracarl** [comment]
cf. #1351

**Comment by saracarl** [comment]
Let's make the "% transcribed" display the percentages of pages that are transcribed OR needs review.

**Comment by benwbrum** [comment]
Tracked in #2451
