### ISSUE TITLE
easier to find untranscribed works

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1359]
We decided in issue #1324 to drop a transcriber straight into an untranscribed or least-recently-transcribed work using the "start transcribing" button.  We tried naming it "find untranscribed works", but that didn't make a lot of sense because we didn't show you the untranscribed material.

What we think we should do instead is order the works on the collection landing page with the untranscribed/least transcribed listed first.  We're *assuming* that returning transcribers use their dashboard or activity streams to find where they were.

**Comment by jackweinbender** [comment]
I think that makes sense for transcribers, but do we need to take into account people who are just there to read? Like, if I wanted to read the Stanford letters, I would be pushed toward letters that hadn't been transcribed yet. Is this a user story we need to address?

**Comment by jackweinbender** [comment]
the works list pages already have filtering capabilities to show/hide complete/incomplete works; so maybe extending that would be one way to address this.

**Comment by benwbrum** [comment]
Handled in #3689
