### ISSUE TITLE
Polish Omeka integration

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#136]
I've just finished up the back-end functionality for the integration with Omeka sites, and would like @kolking to give it the same kind of polish the Internet Archive integration has.

## Background
Omeka is an open-source digital exhibit platform, that is used both in hosted form (on Omeka.net) and is installed on-site by libraries, archives, museums, and classrooms.  The Omeka->FromThePage integration allows Omeka users to use FromThePage to transcribe material they've added to their Omeka site.

The FromThePage/Omeka integration requires the Omeka API developed with Omeka 2.1.  Currently Omeka.net only runs Omeka 1.5.  As a result, we need to be careful to use the phrase "Omeka", "your Omeka site", or "Omeka site" instead of "Omeka.net"

## Process
When a project manager wants to import from Omeka, they will click the "Import from Omeka" action from the owner dashboard.

They will see the Omeka sites which FromThePage already knows about, and have the option to specify a new one.  If they specify a new one, they will need to enter an API url and (optionally) an API key.

One real-world Omeka site (already used for a transcription project on a different platform) has opened up their API for us to test with.  Connecting to http://urcrowdsource.org/omeka/api will query this site.

## Omeka Collections
FromThePage will query Omeka collections for a site and list the items to import into the system.  This currently takes a long time and needs a spinner.

The user can choose an item to import, then publish it to FromThePage.

## Work needed
Please review this flow and make any improvements you think are worth doing.  This will be seen mainly by project owners sophisticated enough to have installed Omeka on their own servers, so we do not need to spend a lot of time on user-friendliness, but it will be the first experience of the site many of them will have.

**Comment by kolking** [comment]
@benwbrum thanks for the explanation! I've tested the Omeka integrations and it would be nice if you could find some time to answer the questions I have.

After submitting the form for a new Omeka import, I get the following page with the list of items:
![image](https://cloud.githubusercontent.com/assets/4656448/7213377/59371ba4-e584-11e4-912d-1c8db68d3967.png)

1) The waiting time is quite long, that's probably ok for the initial import, but if I refresh this page, or go to the list of Omeka sites and click show, I have to wait again. It seems that the import process performed every time the page requested. Is it possible to cache the response after the very first import?

2) What is items? I assume it's the collection pages (scans), right? Is it possible to show a preview if these images in the list?

3) Don't you think it would be better to show checkboxes instead of "Import Item" buttons and "Import Selected" button somewhere?

4) Is it possible to have a button that will allow to import all items in a collection (entire collection) at once?

5) Is there an addition information for the items we can show in the list?

**Comment by benwbrum** [comment]
In this case we're really trying to support a basic Omeka integration functionality -- we'll invest more into this when a FromThePage/Omeka site is running and we have real user needs to prioritize.

That said, 
1. Because the contents of the Omeka site can change as new collections are added or new items are added to an existing collection, it's better to wait for the page to load than to have a stale cache.  Worth revisiting once we get an Omeka deployment.

2. Sadly, `items` are not files, but arrays of things which may have files.  For our purposes they correspond to documents.  A thumbnail would rock, but would require yet another API call per item, which would slow the page load down even more.

3. I suspect that the solution you propose in point 4 is better.

4. Yes.  It's very worth doing, just needs to be implemented.  *Logged in #161* and postponed for later.

5. While the Omeka site display made sense for a test environment, touching the UrCrowdsource example's API shows that there is probably a lot more descriptive information which they've put in fields different from those I was expecting.  See http://urcrowdsource.org/omeka/api/collections or an item-level description (including a transcript inserted by a different tool) at http://urcrowdsource.org/omeka/api/items/7 *recorded in #159*

**Comment by kolking** [comment]
@benwbrum the cache can be made very simple for now, we'll just save the response file (a json?) somewhere (`omeka_cache` directory for example) and will set the expire time to 12 or 24 hours. So, until expire we'll get the response from the saved file and then request Omeka server to get a fresh copy.

**Comment by benwbrum** [comment]
You're welcome to try it, but don't spend more than 2 hours, please.

Ben

**Comment by kolking** [comment]
There is now "Omeka Import" section in the owner's dashboard. This is where users manage Omeka connections and see the list of Omeka items they have imported.

![image](https://cloud.githubusercontent.com/assets/4656448/9778423/b5330696-5778-11e5-860c-9be4db853705.png)


To import an item they should start from exploring Omeka source by clicking it at the right. To speed up the process only collections (and items without a collection) are initially loaded:

![image](https://cloud.githubusercontent.com/assets/4656448/9778497/c789790a-5779-11e5-9c9c-c74dd7a27a81.png)


When they click the load button, the collection items are loaded via ajax:

![image](https://cloud.githubusercontent.com/assets/4656448/9778574/e605853a-577a-11e5-9d1e-a709834d3f58.png)

To import a single items they click "Import" in the list, or they can import all items in the collection by clicking the button at the top. Import process is also performed via ajax request, so users will stay on this page as long as they need.
