### ISSUE TITLE
order collections by most recent activity

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#137]

**Comment by saracarl** [comment]
on the dashboard.

For a unlogged in user, order collections by most recent activities/edits.
For a logged in user, order "interested in" collections by most recent activities/edits (??)

**Comment by kolking** [comment]
@saracarl could you please specify which dashboard? You know, we now have collections listed in the "public" dashboard (the "Collections" link in the top menu) and also we have collections listed in the new Editor's Dashboard section.

**Comment by saracarl** [comment]
I was looking at the public dashboard.

I'll start adding URLs.  http://localhost/app/dashboard

@benwbrum doesn't know what the Editor's dashboard should be ordered by -- we'll do a new issue for that.  (Related -- issue #118 )

**Comment by kolking** [comment]
@saracarl btw, maybe we should switch these dashboards? I mean, when a user is not logged, he see the public dashboard (like now), but once he log in, we show the editor's dashboard instead?

**Comment by benwbrum** [comment]
I agree with Nick completely.  When people are not logged in, "Home" takes
them to a global listing of collections -- the public dashboard.

Once they are logged in, they should see the editor's dashboard.  (In fact,
even if they are an owner, we should send them to the editor's dashboard
first.)

Ben
