### ISSUE TITLE
opt-out users & collaborator lists

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1371]
In the collaborator list, we should either leave out or list separately any users who opted-out when they signed up for a FtP account.

**Comment by benwbrum** [comment]
We do not currently suppress users who have opted out of receiving emails: [this code](
https://github.com/benwbrum/fromthepage/blob/6d6d5a4afb9bf0971fe210a8db523463191480c2/app/controllers/collection_controller.rb) should respect the `activity_email` flag on the user model and should not add those users to `@all_contributors`.

**Comment by symmetrically** [comment]
@benwbrum shouldn't we exclude these users from `new_collaborators` too, as we are listing user's email there too.

**Comment by benwbrum** [comment]
That is a very good catch.  Yes, please!
