### ISSUE TITLE
Setting for optional "you've been edited" emails.

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1377]
So we've already gotten feedback on #1101 and at least one set of project collaborators will miss the email informing folks of page edits.

Collaborators on the Parker Manuscripts actually look forward to emails telling them they've been edited by a particular celebrity professor -- "Look, I'm collaborating with Professor Celebrity!" 

We should add a "Inform collaborators of page edits" collection setting that turns them back on if checked.  (And we should turn it on for the Parker.)

**Comment by benwbrum** [comment]
This is the contributor email.

**Comment by benwbrum** [comment]
The Parker is no longer running active projects.
