### ISSUE TITLE
Make IIIF images rotatable

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1378]
This is a page that has been imported via IIIF.  I saw a comment on it on where to find the rotatable image, and was like "the owner can rotate the image in the page settings!"  Except -- they can't.  Not if it was imported via IIIF.  They can if it is an uploaded image.  

https://fromthepage.com/theparkerlibrary/anglo-saxon-kingdoms/cambridge-corpus-christi-college-ms-100-transcripts-16th-century-simeon-of-durham-osb-geoffrey-of-coldingham-osb-tito-livio-frulovisi-walter-of-guisborough-osa-asser/display/304808

Perhaps solved by (closed) issue #569 (does OSD have rotation as a built in control?).

We definitely don't want fewer features in IIIF than in uploaded images.

**Comment by saracarl** [comment]
See also #505 and #273

**Comment by benwbrum** [comment]
This might be done by turning on an option in OpenSeadragon.
