### ISSUE TITLE
Handle text markup in sidebar

### ISSUE THREAD

**Issue by jackweinbender** [benwbrum/fromthepage#1385]
We currently allow `<b> <strong> <em>, etc.` tags in notes (this isn't advertised in the note field). but we don't handle rendering those in the activity sidebar:
![image](https://user-images.githubusercontent.com/1544859/60727064-a1835300-9f02-11e9-9748-783062941962.png)

We should probably just strip those tags out or, if needed, handle them properly.

**Comment by benwbrum** [comment]
Similar problems happen with quotes and ampersands left in notes, which are displayed escaped as `&quot;` within the side-bar.
