### ISSUE TITLE
back out gravatar

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#139]
FromThePage transcribers are typically middle aged history buffs.  As such, they do not usually have gravatars.  

We can revisit this at a much later date, but for now we don't want default avatars showing up and we would like to remove that from the code base.

**Comment by saracarl** [comment]
rethinking.    Gravatars do look good in the activity stream.

Here's the problem -- many users will be "insitutional" users (in other words, use university email addresses) which won't be tied to something like gmail which has gravatars.

If we assume 80% of users don't have gravatars, would we still want them?

Let's discuss more.

**Comment by kolking** [comment]
@saracarl gravatar can be associated with any email address, not only a gmail one, so even a users with university email could have it. I'm agree with you that if 80% users will have a default "no picture" then it's better to remove it. So I think we should at least check out the coverage.

**Comment by benwbrum** [comment]
We could test this by adding the gravatar display to the admin's list of
users.  Since that covers all users in the system, it would give us some
idea of the coverage.

**Comment by kolking** [comment]
@benwbrum great idea, I'll do it today.

**Comment by kolking** [comment]
In my local database the total number of users is 490, and 97 of them have gravatar image, so the coverage is about 20%. Sara's estimate was quite precise :)
