### ISSUE TITLE
transcriber default page

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#140]
If you log in as a transcriber, you are directed to the work owner page (http://localhost/app/dashboard/owner) even if you don't own any collections or works.  

Instead, you should be directed to your watchlist (http://localhost/app/dashboard/watchlist ) 

At least for now.

**Comment by saracarl** [comment]
(the editor dashboard will eventually change, but needs to be hashed out by us before we do anything more there.  see #118 )

**Comment by kolking** [comment]
A quick question - if a uses is not an owner and not admin, then he is a transcriber (aka editor), am I right? Just to make sure I'll add the right condition for the redirect.

**Comment by benwbrum** [comment]
Yes--exactly

**Comment by kolking** [comment]
Now, like Ben have mentioned in #137, transcribers and owners are redirected to the watchlist after log in.
