### ISSUE TITLE
bad record id

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1423]
If you hit a not-valid URL (which the script kiddies do all the time, looking for vulnerabilities), you are directed to the collections_list, which is a very expensive page to load:

https://github.com/benwbrum/fromthepage/blob/master/app/controllers/application_controller.rb#L146 

We'd prefer that bad record ids are sent to a (static) 404 page.

**Comment by benwbrum** [comment]
I'm not sure whether this is helpful for fixing the issue, but wanted to add this to this issue:

Here is a list of the bad record exceptions we're getting.  As you can see, some of them are from browsers trying to access recrods that have been deleted, like `fromthepage.com/indypl/sewell-letters/record-that-no-longer-exists`, while others are from bots looking for vulnerabilities hitting `fromthepage.com/wp/admin.php` or something similar.

[bad_record_exception.txt](https://github.com/benwbrum/fromthepage/files/3478190/bad_record_exception.txt)

**Comment by saracarl** [comment]
And the 404 page we already have and aren't using:
https://fromthepage.com/404.html
