### ISSUE TITLE
trial signup failure reloads "normal" signup.

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1424]
So if you go to the new trial link:
https://fromthepage.com/users/new_trial
and create a new account, some portion of the time you *will* become a project owner and some portion of the time you won't.  In our workshop today, there were 5-6 people who did not succeed in creating a trial owner.

These are examples of folks who didn't get a trial account created (need admin access to production):
https://fromthepage.com/admin/visit_actions?user_id=215192&visit_id=6174738

https://fromthepage.com/admin/visit_actions?user_id=215189&visit_id=6174750

https://fromthepage.com/admin/visit_actions?user_id=215188&visit_id=6174742

https://fromthepage.com/admin/visit_actions?user_id=215194&visit_id=6174462

This seems to be the pattern:
15:08:49	registrations#new_trial				
15:08:52	registrations#create				
15:08:20	registrations#create

Here's an example that worked just fine:
https://fromthepage.com/admin/visit_actions?user_id=215190&visit_id=6174788

And the activity for that user does *not* show the double "registrations#create" action:

15:08:50 | registrations#new_trial 
15:08:31 | registrations#create   
15:08:31 | dashboard#owner

That registrations code is getting a create action perhaps because it is failing validation -- if you don't check the recaptcha or if you use an email or account that is already in the system.
After the failure it renders the standard, non-trial template.

**Comment by jackweinbender** [comment]
I have been able to reproduce this and I think I have a solution
