### ISSUE TITLE
document set edit screen visible without being logged in

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1425]
If you go to a document set listing for a collection, without being logged in, you can see the "edit and delete" screen for the document sets, which is a problem.  (I haven't tried to see if you can actually do the edit, but you can see the view for sure):

https://fromthepage.com/document_sets?collection_id= (shortname)

A customer reported this -- we need to fix it soon.

**Comment by benwbrum** [comment]
Closed by #1429.
