### ISSUE TITLE
opt-out for "new work added to collection"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1443]
We need an "opt-out" option for the "new work has been added to the collection" part of the nightly emails.  

I just had a user unsubscribe -- which is a manual email to us -- and when I looked at her email settings she had all of them unchecked.  The collection she has worked on was one that just had a lot of things uploaded, so I'm pretty sure that's why she unsubscribed.

**Comment by benwbrum** [comment]
Other email notifications may have an "opt out" link.  This is also in the user profile.
