### ISSUE TITLE
better usability for "Start a Project"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1447]
On the "start a new project page" we have a lot of options for getting material into FromThePage.  I'd like to improve the usability of that page.
http://localhost:3000/dashboard/startproject?collection_id=431

1)  reorder the list of options:
upload pdf or zip
import from a iiif repository
import from ContentDM
import from internet archive
import from Omeka
create an empty work

2)  If we could collapse each section with a pointed triangle widget to open it, then all of the options would be visible initially.  

3)  Change the word "Omeka" to "Omeka Classic"

4)  Get rid of "Search for IIIF Content" and "Explore IIIF Collections"

**Comment by diegoviola** [comment]
@saracarl do we want to change to "Omeka Classic" just in the title or everywhere that Omeka is mentioned?
