### ISSUE TITLE
Bulk export collections as a background task with API access

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1449]
Some of our largest clients are using the Export All tools and are running into difficulties because the exports run during the browser request lifecycle and time out before they are finished.

For large collections (with > 1000 pages, perhaps?) we should have this controller action fire off a rake task that runs the export, then emails the user (and CCs administrators) with a link to download the file.

Note that this will necessitate putting a large zip file in a directory where it can be downloaded, which will also require a new rake task (with cron job) to clean up files that are older than e.g. 7 days.  

The `document_upload` processor may be a good model to follow here.

**Comment by benwbrum** [comment]
With the Rails6 additions to the export granularity and formats, exporting all works takes even longer.  In addition, some institutions would like to use this feature for off-site back-ups of their data, based on cron jobs.


## Implementation

### Data model
Moving the export UI to the background will require persistence for per-export configuration options as well as the collection being exported and the status of the export.

We should create a new model as follows
```ruby
Model BulkExport
  belongs_to :collection
  belongs_to :user
  status [:queued, :running, :finished, :deleted, :errored]
  current_phase_started (date)
  selection [:all, :completed]
  per_page [true,false]
  full_document [true,false]
  plaintext [true,false]
  html [true,false]
  tei [true,false]
```
### Controller
A new BulkExport controller will control the user experience with the following actions
* `new` Present the export screen described in UI (see below)
* `create` Launch a new export from the UI
* `download` Fetch the zip file from the filesystem and return it to the user, or display an appropriate error message if the file is not present, the export has not completed, or the user is not authorized to see thsi export

### Project Owner UI
The current "export all" button should take the user to a new screen, presenting them with these options:
* Selection (radio button)
  * All works (including uncompleted works)
  * Completed works (excludes uncompleted works)
* Granularity (check boxes)
  * Per-page exports
  * Full document exports
* Format
  * Plaintext
  * HTML
  * TEI-XML

A Start Export button will create a new `bulk_export` record from the parameters and launch a `rake fromthepage:bulk_export` task (see below).

### Admin UI
A new Exports tab in the Admin dashboard will display a list of `bulk_export` records similar to the `document_upload` UI.

### Bulk Export rake tasks
New `exporter.rake` rake file containing two export tasks
  * `export` task
    * Takes `full_export_id` as a parameter
    * Exports to `/tmp/fromthepage_export/`*bulk_export_id* according to the parameters defined in the `bulk_export` attributes.
    * Emails the project owner a "Your export is ready" message with a link to download the exprot.
  * `clean` task
    * Taks `days` as a parameter
    * Deletes all export files older than `days` from `/tmp/fromthepage_exports`

### Bulk Export API
We should create a new API with the following actions
* `create` launches a bulk export with parameters about selection, granularity, and formats, creates a `bulk_export` record, executes the bulk export rake task, and returns a JSON object with URI for the `status` API call for this export and the `download` API call for this export
* `status` takes parameters used to locate the `bulk_export` record and returns the `to_json` values of the `bulk_export` record, from which the client should be able to read the status, date started, etc.  (These attributes may need to be scrubbed.)  Included with these is a link to the URI for the `download` API call for this export.
* `download` returns the appropriate HTTP status code for a download that has not been started or is still running.  If the `bulk_export` shows that it has completed, it checks the filesystem for the export file, and either returns an appropriate HTTP status code (if it has been cleaned) or streams the zip file to the client.

### Configuration
We will need to add a new cron job to the server to run the `clean` task nightly.

**Comment by saracarl** [comment]
An API key reference:  
Search page https://sourcey.com/articles/building-the-perfect-rails-api for Authenticating Your API  
and maybe this:
https://rails.devcamp.com/trails/rest-microservices/campsites/outside-api-access/guides/how-to-create-api-key-generator-rails
