### ISSUE TITLE
Create New Page:  New Project

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#145]
We need to create a new page for starting a new project.

Start a New Project
Project Name
(help text underneath "e.g. Julia Brumfield Diaries")

Image File
(help text underneath: "a zip file of images")
OR
dropbox or google drive shared URL
(help text underneath: "directory should be public or shared to benwbrum@gmail.com"

note -- not sure how to make it clear they only choose 1 -- either the zip file or the shared drive.  How would you suggest, Nick?

Button:  Start Project

notes:  we'll link to this page off of the collection owner dashboard and also lead to for a new user who has a entered their billing information.

**Comment by kolking** [comment]
@saracarl could you please explain the difference between a Collection and a Project?

**Comment by saracarl** [comment]
So the code has logic for a "work" -- a collection of related images (all the pages of a diary, for instance), and a "collection"  -- a group of related works owned by the same person.

In this case, it's a new "work", but since "work" is not a user-friendly word and this is the first screen a user will see after signing up to host transcriptions, we've chosen to call the screen "start a new project".  I don't expect the user to understand our data model of works & collections, so we should make our UIs easy enough to use you don't have to.

**Comment by kolking** [comment]
@saracarl okay, so maybe we should rename "works" into "projects" everywhere (in the ui at least) otherwise it could be confusing for users when they create a "project" but then see a titles like "list of your works" and so on. And the application structure (from the point of a user) will be:
**Collection** > **Projects** > **Pages**
What do you think?

**Comment by benwbrum** [comment]
Whoa!

Okay, here's the data model: Collections have Works, Works have Pages.  This makes sense to librarians and people who are running ongoing digitization projects. 

The challenge, however, is that novice users don't know much about this -- they have one book they've scanned into a directory of images, or they have 20 letters they've scanned into 20 directories, which they've zipped up.  They want to start a *transcription project* with their *images*, but we don't want them to have to learn the jargon before they start.

So New Project should 
* Create a user account
* Create a collection associated with that user account (with a name like "Grandpa's Letters" )
* Receive a zip file
* Create 1 or more works within that collection from the zip file

The user will end up with a collection of works, each with pages, and that will comprise their *transcription project* in their view.

**Comment by saracarl** [comment]
Agreed.  A new user doesn't need to understand the data model to start a project.  Once they have works in a collection, they will understand it without having to think about it up front.

**Comment by benwbrum** [comment]
The bulk uploader has obviated this.
