### ISSUE TITLE
create new page:  New Project Submission

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#146]
After the "new project" page (issue #145), the user should see this page.  It is nothing but some text:

Thank you for starting your project.  Next we'll perfect your images for transcription in FromThePage (resizing, splitting recto/verso pages, ordering the pages correctly).  This may take up to 24 hours -- we'll email you once your project is ready.  If you have any questions, or don't hear from us, please send us email at support@fromthepage.com.

**Comment by benwbrum** [comment]
This has been obviated by the bulk uploader.
