### ISSUE TITLE
broken links on collection/edit set page

### ISSUE THREAD

**Issue by jackweinbender** [benwbrum/fromthepage#1461]
ActionController::UrlGenerationError in DocumentSets#index

Showing /fromthepage/app/views/document_sets/index.html.slim where line #24 raised:

No route matches {:action=>"show", :controller=>"collection", :format=>nil, :id=>#<DocumentSet id: 657, is_public: true, owner_user_id: nil, collection_id: 246, title: "asdf", description: "", picture: nil, created_at: "2019-08-10 00:38:52", updated_at: "2019-08-10 00:38:52", slug: "asdf", pct_completed: nil, default_orientation: nil>, :user_slug=>nil} missing required keys: [:user_slug]

```
         -@collection.document_sets.each do |document_set|
           tr
             td
               =link_to document_set.title, collection_path(document_set.owner, document_set)
             td
               =document_set.is_public ? 'Public' : 'Private'  
             td
```

`document_set.owner` seems to be the problem. should be `@collection.owner`

**Comment by jackweinbender** [comment]
We need to double-check the links to the docset pages, too. I'm getting some bad ones there. (on the "sets" tab, where the sets are listed---I'm getting errors when I click on one of the sets)

**Comment by benwbrum** [comment]
Not reported by extensive DS users.
