### ISSUE TITLE
Duplicate resolution needs more context

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1464]
Our subject duplicate resolution does not provide any context for a user actually trying to resolve duplicates.  We list the potential duplicate subjects, but don't let them see the pages or the context each potential duplicate appears within.

Reproduction:
* Transcribe a page that contains a reference to `William Smith` as `[[William Smith|Wm Smith]]`
* Transcribe a second page that contains a reference to `William Smith` as `[[William Smith|William Smith]]` 
* After a long delay, transcribe a third page that has a reference to `William F. Smith` as `[[William F. Smith]]`
* Explore the subject for `William F. Smith`
* Click on Resolve Duplicates
* Observe that a possible duplicate `William Smith` is mentioned on two pages
* How can you read those pages?

Proposal: Hyperlink the _2 pages_ to open a new window with a search for the pages the potential duplicate is mentioned within.

**Comment by lenathelibrarian** [comment]
I also have this problem and support this proposed solution!

**Comment by benwbrum** [comment]
In addition, if a user is looking at a possible duplicate and figures out which record should be the main one, they have no way to get to that record.

See, for example, [the edit page for Doct. "R White" in the Jeremiah White Graves diaries](https://fromthepage.com/benwbrum/jeremiah-white-graves-diaries/article/58856/edit).  "R White" is clearly Doctor Rawleigh White, but there is no way to get to the entry for that page to make it the main record.

![Screenshot from 2020-07-21 13-36-14](https://user-images.githubusercontent.com/199961/88094289-f2d7a200-cb58-11ea-8816-27b26b83f594.png)

Proposal: Hyperlink each name in the listing of potential duplicates to the edit action for that subject.

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/a58096fd0c15a64169340288df327962a0978d9c/app/views/article/edit.html.slim#L63

https://github.com/benwbrum/fromthepage/blob/51502e74ddcf93cb132b2e4f1f4f49606989ce82/app/views/article/show.html.slim#L49

places? @benwbrum

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/a58096fd0c15a64169340288df327962a0978d9c/app/views/article/edit.html.slim#L71

this is mostly a guess, but would I make the 'from_article_ids[]' or maybe the "dup.title" the link

**Comment by benwbrum** [comment]
Okay, that's the right file, but what we'll need is to do two things:

1. Make the title of the article link to the article body.  That's a little after the check_box_tag line you mentioned (which only renders the check box), in the span that renders the title in https://github.com/benwbrum/fromthepage/blob/a58096fd0c15a64169340288df327962a0978d9c/app/views/article/edit.html.slim#L73
You'll want to make that a `span =link_to(dup.title, path_to_the_article)` -- @JosieBrum has done `link_to` before, but you may need help finding the proper path (it'll be something like `article_path(dup)`, I suspect).

2. Make the "N pages" link to the pages mentioning that article.  That link should go in https://github.com/benwbrum/fromthepage/blob/a58096fd0c15a64169340288df327962a0978d9c/app/views/article/edit.html.slim#L75 and should be a `link_to` identical to the one in https://github.com/benwbrum/fromthepage/blob/a58096fd0c15a64169340288df327962a0978d9c/app/views/article/_article_links.html.slim#L3 (though the anchor text should be the "... pages", of course)

**Comment by isabelabarton** [comment]
@benwbrum I was able to turn both the name and the "... pages" button into links 
![Screen Shot 2020-07-27 at 2 04 11 PM](https://user-images.githubusercontent.com/66695287/88580985-1a73b200-d012-11ea-80c9-ca58457294d3.png)

but no matter which link you click on, i can't get any other screen than the one below to come up
![Screen Shot 2020-07-27 at 2 04 21 PM](https://user-images.githubusercontent.com/66695287/88581083-3e36f800-d012-11ea-8d50-69276979fe1b.png)

I believe it has something to do with the areas that the arrows are pointing to, but everything that I've tried in those places has resolved in an error on the server
![Screen Shot 2020-07-27 at 2 06 39 PM](https://user-images.githubusercontent.com/66695287/88581352-a38ae900-d012-11ea-95e5-190964e8a08b.png)
