### ISSUE TITLE
Highlight search/subject in search/index results.

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1465]
Currently the multi-page view is used to render pages matching search results and index term results: when a user clicks on a subject, then clicks any of the "View all pages ..." links or "Search all pages...", they see all pages mentioning the subject they're searching for, but have no easy visual way of finding that subject within each page.  

We should make the matching search term bolded or highlit to make it easier to see the term within the search context.

**Comment by benwbrum** [comment]
I'm looking for a javascript function we could add to the rendering screen in the [multi-page view](https://github.com/benwbrum/fromthepage/blob/main/app/views/display/_multi_page.html.slim#L8); if a `@search_string` is present, we'd call the function, passing in the class of the div containing the text (so the function knows where to highlight) and the list of terms to be highlighted (so the function knows where to highlight).

**Comment by saracarl** [comment]
Mount Auburn would like this as well.

**Comment by symmetrically** [comment]
@benwbrum @saracarl 
So what I understood from the description is that when user select any subject and then click on the link `Show pages that mention <Selected Subject> in all works`  than if i enter a text in the `search in collection... ` search box and click `Search` button than the resulted pages should highlight the entered text?

**Comment by benwbrum** [comment]
That is one of the two use cases:
* Clicking 'Show pages that mention Miss E McCulloch' in [the `article#show` view](https://fromthepage.com/benwbrum/jeremiah-white-graves-diaries/article/70244) should show [the `display#read_all_work` view](https://fromthepage.com/display/read_all_works?article_id=70244) with bold text or colored text around all the parts of text which link to her.  (Note that these will already be rendered as HTML anchor tags with attributes referring to the subject (`<a href="[/article/show?article_id=70244](https://fromthepage.com/article/show?article_id=70244)" title="Miss E McCullock">Mrs M<sup>c</sup>Cullock</a>` in the current example's first page).  The text contents itself may be different from search term to search term, so we may need to modify the [xml_to_html](https://github.com/benwbrum/fromthepage/blob/development/app/helpers/abstract_xml_helper.rb#L27-L49) method to add a class attribute to the link with the ID of the subject, then use CSS to color the currently-searched-for subject with some kind of highlight.
* The other use case in when people are performing full-text searches in text that may not have been linked at all:  [searching for court in the Jeremiah White Graves Diaries](https://fromthepage.com/paged_search?action=search&authenticity_token=07qBU8px5XtsXUlwrWvbeIRUA%2Fl7euUYh7gvLXmPxOOFZuoI%2Bm7xczLGgTq%2F7xZ2XIlDsf5NSGd1W3awwAclTQ%3D%3D&button=&collection_id=jeremiah-white-graves-diaries&controller=display&search_string=court) should highlight the same terms you would see if you pressed `CTRL-F` in your browser.
