### ISSUE TITLE
Add work image

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#147]
There should be a work image -- similar to the mock ups -- to be used to make the UI more appealing.

Collections should also have an image.

These images should be optional.

If a collection image, but not work image, inherit from the collection.

If a work image but no collection image, inherit from the most recent work image.

Create a "upload work image" field on the work owner dashboard.

Create a "upload collection image" field on the collection owner dashboard.  

Show the inherited images on the dashboard, with a "change image" option. (that lets you upload or choose from other images)

If no uploaded images, choose from one of the scanned images.  (or use the first one?)

**Comment by kolking** [comment]
> choose from one of the scanned images

this is not a good idea I think... all such images will look like a "blurred something" in sepia tones.

**Comment by saracarl** [comment]
Agreed -- scanned images are not a good idea for the work image.

**Comment by tbl73** [comment]
This is duplicated in #737, so I'm closing.
