### ISSUE TITLE
IIIF collection export link is wrong

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1470]
In the export for a collection, we display the IIIF collection link (correctly) but what it links to is the export page for the collection (the same page you are already on).

**Comment by diegoviola** [comment]
I can't reproduce this.

@saracarl can you say which collection is the one that has this problem please?

**Comment by benwbrum** [comment]
Here's an example from the East Civil War letters collection (owned by `benwbrum`):

`<p>IIIF Collection API Endpoint: <a href="/benwbrum/east-civil-war-letters/export">https://fromthepage.com/iiif/collection/4</a> </p>`

The text of the anchor tag is the correct endpoint, but the `href` value is just the current URL.  We need to change the `href` value to the same as the text.
