### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1471]

**Comment by saracarl** [comment]
Code flow
Close all open pull requests
Fix and Close the Sass issue
Create a “rails5” branch from development
Create new branches off of rails5 for incremental fixes/upgrades; create pull requests against rails5 branch

Deployment
We’ll deploy the rails5 branch on the staging server that is at Ubuntu 16 (just like production).  That deployment will be done with a screenshare and Sara, Diego and Ben working together to get it deployed.  Start with a snapshot of the production database.  We’ll document the 

Open Source Installations
After we are satisified with the rails5 branch, we should engage with our open source customers (maybe a Zoom call or two) and discuss the upgrade process.
