### ISSUE TITLE
Restyle the  page view

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#148]
Use page 5/42 of the UI mockups to improve the page view.  

http://localhost/app/display/display_page?page_id=471

**Comment by saracarl** [comment]
Wrong page:  4/23 -- google drive is horrible at numbering pdf pages.  Download the pdf instead so you can find it easily.

**Comment by saracarl** [comment]
We realize the mock-ups are not a perfect design, so this will require some judgement.  What we like:

1)  The collection/work header (same page, labelled) 
2)  arrows instead of words for back/forward navigation
3)  page title/navigation/actions all on the same line
4)  move "add comment" to the same line as the "Notes" header.
5) change "add comment" to "add note"

**Comment by kolking** [comment]
I'm going to work on this page a bit more later.
