### ISSUE TITLE
Upgrade to Rails 6 (2020 P1)

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1481]
This depends on #1471.

**Comment by saracarl** [comment]
1)  In development environment, pull down a recent DB dump, run with (master?  development?  ftp.com?) branch.  Run tests.
2)  In development environment, upgrade to the rails 6 branch (what exactly does this require?)
3)  Run tests.  Manually run through functionality: upload, transcribe, export.  Hit the low use features like OCR correction and translation and the IIIF API.

After comfortable with that, then deploy to a staging server.  Get Jennifer H to do some testing there, in addition to us.

**Comment by benwbrum** [comment]
Based on conversation with @ackrmann, we will be running an upgrade on a staging server, then upgrading fromthepage.com, then delivering upgrade documentation by August 3, 2020.

**Comment by benwbrum** [comment]
Done!
