### ISSUE TITLE
Restyle the Transcribe Page View

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#149]
restyle the transcription page based on what's on page 5/23 in the UI design PDF.

This is the page that people will spend the most time on.  We want the experience to be great.

**Comment by saracarl** [comment]
http://localhost/app/transcribe/display_page?page_id=471

**Comment by saracarl** [comment]
The mock up has a search screen "Joanna Brumfield" with a magnify glass -- we are not using that.

**Comment by saracarl** [comment]
1)  We like the buttons at the top (preview/save/status)
2)  like the "page 5 of 25" 
3)  Any styling should support the ability for editors to edit titles ("scribes can edit titles" on the work settings.)

**Comment by kolking** [comment]
Now we have the option to re-arrange panes in the transcribe view. Last selected layout mode is stored for the user, so it won't reset after page reload. Moreover, when user set the preferable mode, it will be applied to other pages as well.

![image](https://cloud.githubusercontent.com/assets/4656448/7693672/9cd40c20-fddd-11e4-8a3e-c3bfe2912111.png)

**Comment by saracarl** [comment]
Ooh, looks cool.  Can't wait to pull it and take a look.
