### ISSUE TITLE
Restyle the subject pages

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#152]
http://localhost/app/article/show?article_id=4&title=Benjamin+Franklin+Brumfield%2C+Sr.

See page 11/23 in the UI mockups

**Comment by kolking** [comment]
@benwbrum the "Graph" does not work for me:

![image](https://cloud.githubusercontent.com/assets/4656448/7242800/a7468194-e7ce-11e4-8851-7d128a6104eb.png)

**Comment by benwbrum** [comment]
To get the graph working, you'll have to install graphviz and neato:

http://graphviz.org/

You can use a placeholder client-side imagemap if you'd like.

Ben

**Comment by kolking** [comment]
@benwbrum I've fixed that already, anyway thanks!

**Comment by kolking** [comment]
I've combined subject edit form and possible duplicates list into one page, rather then having them in a separate modal windows. The "Edit Subject" tab is more consistent with other sections, more noticeable and keeps everything that can be edited in one place.
