### ISSUE TITLE
Fix race condition on automated tests

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1521]
Currently we have tests failing intermittently.  Our theory is that we're running into a race condition -- our test suite uploads a document, the upload processor fires off a rake task in the background, other tests run, then tests run using the uploaded material.  If the uploaded material isn't ready yet, we fail.  

In the short term, we may need to use `sleep` to handle this.  In the long term, we may need to use the Rails 5 mechanism for testing whether a task is done.

**Comment by jackweinbender** [comment]
I'm less convinced this is actually what's going on here, now. The image that can't be found, as far as I can tell, is not one that we actually import. It is a path that is hard-coded into some of our fixtures.
