### ISSUE TITLE
Popup for "potential duplicates"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#153]
Move the "potential duplicates" out of the subject page into a pop up.

See pages 11 & 12 / 23 in the UI MockUps

**Comment by kolking** [comment]
Use the link to open duplicates modal dialog:

![image](https://cloud.githubusercontent.com/assets/4656448/7310505/fce31f40-ea35-11e4-92a0-dd876ed3580d.png)

**Comment by benwbrum** [comment]
Nice!

**Comment by saracarl** [comment]
Looks really slick!  Much better than before.
