### ISSUE TITLE
Remove Omeka support

### ISSUE THREAD

**Issue by diegoviola** [benwbrum/fromthepage#1539]
## Description:

As the title says, we are removing Omeka support because nobody appears to be using the feature.

Also, I ended up hitting a codepath that touches Omeka code while working on #1531.

It seems to be easier to just wipe that code rather than work around it.

**Comment by bencomp** [comment]
We are experimenting with Omeka S. We don't necessarily need a connection between FromThePage and Omeka S, although there may be a wish for this in the future. On the other hand, it's likely that import from Omeka (S) is supported through exposing Omeka (S) object through IIIF.

**Comment by benwbrum** [comment]
This feature describes dropping our custom support for Omeka Classic, which is currently broken.

We have successfully imported from Omeka-S with the IIIF-Server module.  

We're very interested in a full round-trip integration with Omeka-S, which would push transcripts (and other contributions) back into Omeka-S.  Designs for this have been written into two proposals, so we are pursuing funding for the feature.
