### ISSUE TITLE
Popup for subject categores

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#155]
See page 15 & 16 of the UI MockUps

**Comment by kolking** [comment]
I've decided to include categories edit into the subject edit modal window:

![image](https://cloud.githubusercontent.com/assets/4656448/7335456/6200b550-ebca-11e4-95f5-bc45b7ea5081.png)

In the categories field you see the selected categories, the context search makes easy to search / select a category from the list.

**Comment by benwbrum** [comment]
It looks pretty good, but we need to be sure to include parent categories
in the display, since projects are very interested in their ontology.

If you modify the display text to include the parents (e.g "People ->
Julia's Children -> Jim Brumfield Family") then I think we're doing well.
