### ISSUE TITLE
Limit individual researcher collection count

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1560]
Individual researcher accounts can only have 1 collection.  We need to enforce this in the UI, and keep a 2nd collection from being created if they are an individual researcher.

**Comment by benwbrum** [comment]
When we display the "create a collection" user interface, we should check `user.account_type == 'Individual Researcher'`.  If the user already has a collection, they should get this message:

`Individual Researcher Accounts are limited to a single collection.  To upgrade your account, contact support@fromthepage.com`.

The collection creation interface is available in these places:
* Owner Home Page -> Actions -> New Collection
* Start a Project -> [Collection list] -> New Collection

This code should be branched from `fromthepage.com` and PRed back into that branch.
