### ISSUE TITLE
IIIF Collection Import support for pagination

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1561]
The IIIF specification includes support for pagination in the API.  This is not a feature we've ever written for, but is implemented by NCSU, the Internet Archive, and (in very large collections) CONTENTdm.

In particular, it is visible in https://cdm17010.contentdm.oclc.org/iiif/info/81443/manifest.json

We should support this in imports.

**Comment by saracarl** [comment]
This was just requested by Carleton.  When we add the support, we should also change the import screen to indicate it can be a collection URL as well.
