### ISSUE TITLE
Extract existing text from PDFs for OCR correction

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#1576]
I would like to try correct the OCR text that is embedded in PDF files.Is there a way that FromThePage automatically extracts the text for each page on (or after) import?

It looks like the only way to start a OCR correction project currently is from importing from the Internet Archive or ContentDM, isn't it?

**Comment by bencomp** [comment]
Alternatively, I could create OCR plain text files and images for each page and upload them in a zip file, but that doesn't seem to be currently supported either.

**Comment by benwbrum** [comment]
That's an accurate description of the current functionality, however we received word on Monday that a new client will fund development of a feature to extract the text layer from uploaded PDFs and use it as raw OCR to be corrected.  Would you be willing to contribute example PDFs (to use as development/test data) and possibly do some early testing on the feature?  I suspect we will be building it in the next month.
