### ISSUE TITLE
Add all export formats to _Export All Works_

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1578]
Currently, the _Export All Works_ feature produces a zip file containing an XHTML file for each work.  We've had some requests to expose additional export formats (plaintext, translation, etc.) in the UI, and it seems like exposing them in a zip file is the appropriate thing to do.  We do not need to create new export formats for this, but just expose the ones that already are exposed in the IIIF API's `seeAlso` elements.

I'd suggest we do this:

* Add a new "zip" export for each work.  This will create a new one-file-per-work export download constructed as follows
  * `README.txt` file that described the contents of the export.  (You can start with this issue description: we'll edit it later.)
  * `plaintext/verbatim_transcript.txt` file containing the per-document verbatim plaintext export of the transcript.
  * `plaintext/searchable_transcript.txt` file containing the per-document searchable plaintext export of the transcript.
  * `plaintext/emended_transcript.txt` file containing the per-document emended plaintext export of the transcript.
  * `plaintext/verbatim_translation.txt` file containing the per-document verbatim plaintext export of the translation if it is present.
  * `plaintext/searchable_translation.txt` file containing the per-document searchable plaintext export of the translation if it is present.
  * `plaintext/emended_translation.txt` file containing the per-document emended plaintext export of the translation if it is present.
  * `plaintext/verbatim_transcript_pages/#{page.title}.txt` files containing per-page verbatim plaintext export.
  * `plaintext/searchable_transcript_pages/#{page.title}.txt` as above.
  * `plaintext/emended_transcript_pages/#{page.title}.txt` as above.
  * `plaintext/verbatim_translation_pages/#{page.title}.txt` as above.
  * `plaintext/searchable_translation_pages/#{page.title}.txt` as above.
  * `plaintext/emended_translation_pages/#{page.title}.txt` as above.
* Modify the Export All Works feature to contain the above for each work in the collection.

**Comment by saracarl** [comment]
So the challenge we've encountered with the html export is that folks would like to leave out the version history and contributors.  How does that fit into this?  Separate issue or should we consider it here?

**Comment by benwbrum** [comment]
I think that's a separate issue.  It does remind me that I forgot the HTML export:
* `html/full.html` with current document-level HTML contents
* `html/full_pages`#{page.title}.html` with page-level HTML contents.

For the other issue,
* `html/text.html` could have an HTML export that omits the edit history but contains transcripts, subjects, and translations
* `html/transcript.html` could have an HTML export that omits the edit history, subjects, and translations
* `html/translation.html` could have an HTML export that omits the transcript, edit history, and subjects

**Comment by diegoviola** [comment]
#1579
