### ISSUE TITLE
Downgrade owner account functionality

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1582]
When a trial user account expires, we need to revert the user back to a regular transcriber.

We need a `downgrade` method on the `User` model that
* Removes the `owner` bit.
* Loops through any collections they created, and for each collection 
  * Makes the collection inactive
  * Makes the collection private

The adminstator's Edit User functionality should include a Downgrade button for owners that will call this functionality.

**Comment by saracarl** [comment]
This will need a decent amount of UI testing (and probably discussion) -- I have no idea what will happen if we have owned collections but not a owner bit.  Will they show up in that user's dashboard?  I doubt it.  That's probably OK.  (This does imply there's no way but exiting links to get to those collections, which means they are effectively orphaned.)  What if we flip the owner bit back?  I assume they'll show up.  This is probably the only way to unorphan the collections.  I'm curious how often we'll do that.
