### ISSUE TITLE
Differentiate organization or researcher owner accounts from staff-member owner accounts

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1585]
Currently, our `users` table has a single `owner` boolean, a single `account_type` field, and no way to associate users with each other.  An owner can also add another user as an owner on a collection, which makes the new user an `owner` and adds them to the collection via the mapping table `collections_owners`.

We need to support the following scenarios:
* An individual researcher, Josephine, may create a collection and upload documents to that collection.  They may not create additional collections.  (This is already supported.)
* Giuseppina, a staff member at the Wakanda National Archives (WNA) logs into the WNA account and creates collections A, B, and C and uploads documents to the collections.  (This is already supported)
* Josefina, another staff member at WNA, has been added as an owner to A, but not B or C.  
  * Josefina can upload documents to A (already supported).
  * Josefina cannot upload documents to B or C.  (Already supported.)
  * Josefina can also create a collection D.  Currently D will be associated with Josefina's account instead of the WNA account.  D (and any other collections created by Josefina) _should_ be associated with WNA's account instead.

Implementation suggestion:
* Create a new owner account type of "Staff".  
* When an owner adds a non-owner to a collection, in addition to marking the non-owner as an owner, set their account type to "Staff".
* When an owner creates a collection, check their account type.
  * If account type is not "Staff", operate normally and associate any created collection with the user.
  * If account type is "Staff", look at the owned collections association for the user.   Find a collection with an owner whose account type is not "Staff".  Associate the created collection with that owner.  Add the current user to the collection_owners mapping table for the created collection.

**Comment by saracarl** [comment]
All collections will have an owner whose account type is not "Staff" (right?)  

What happens if you are staff on multiple projects?  For now, let's use the *last* (most recent) collection that the staff member is associated with.

**Comment by saracarl** [comment]
I think we *might* be able to migrate previous users who should have been staff but aren't (from before we had this feature) using the same logic I propose in #1581 :

_Should that person be an owner at all, or were they made an owner before we had collaborators on private projects?_ with a DB query, as collaborating owners aren't marked as owners in the UI (I think -- if not this, there is some differentiater, but we may need to research what it is.)

**Comment by saracarl** [comment]
Additional scenarios that we've discussed:
* _A trial owner is added as a staff owner on an organizational account._  In all the cases we've encountered, the trial owner should be downgraded to a transcriber, then made into an owner.
* _A staff owner is removed from a project._   If there are no other projects that include this user as an owner, downgrade them to a transcriber.  If they are an owner on other projects, leave them as a staff owner.

(Note that "downgrade them" should _not_ make their owned collections private/inactive if they are removed from a project as an owner:  Imagine that organization account A has staff owner B.  Staff owner B leaves the organization, and is replaced by C.  User A should be able to remove B as an owner and add C without any change to the collections owned by A.)

We do not anticipate managing `Staff` status in the user interface, so we do not need to add that account type to the edit user list.

**Comment by saracarl** [comment]
@benwbrum and @saracarl to find specific records in the production data and suggest how this feature should apply to them.

The main thing we want to focus on is collection creation.  Some of the edge cases (like downgrades) may not be worth the effort.
1)  a staff member creating a collection needs to create it for the organization
2)  a staff member should not be able to create a collection for themselves

**Comment by saracarl** [comment]
Here's how I'm going to test this:

1. create an owner. "Wakanda"
2. owner creates a collection "Letters from America"
3.  create a non-owner user "Shuri"
4.  Wakanda adds Shuri as a collection owner.
5.  Confirm Shuri can see the "Letters from America" collection settings.
6.  Create a collection, "Science Archives" as Shuri (menu -> "create new collection" or upload and create one there)
7.  "Science Archives" should be listed under the Wakanda account as a collection.  (It should look the same as "Letters from America")
8.  Regression test -- make sure Shuri can upload/add material to Wakanda collection.

**Comment by saracarl** [comment]
Add "organization?" to User model
Add organization_user table (mapping organization_user_id, staff_user_id)
Add to User model
```
belongs_to :organization, :through => :organization_user
has_many :staff_users, :through => :organization_user

def organization
  if account_type = "Staff"
    parent_organization
  else
    self
  end
end
```

**Comment by saracarl** [comment]
Probably we don't need a separate mapping table, but can just add :organization_user_id foreign key to the User model with a `belongs_to parent_organization, :foreign_key => organization_user_id`
