### ISSUE TITLE
User export for mailing lists (2020 P4)

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1588]
Clients have requested the ability to download email addresses for all users who have worked on their projects, along with opt-out information and activity summaries, so that they can add them to monthly newsletters or other communications.

We've manually created a sample export like this for USHMM, who has approved it.  Now we should add it to the product.  The Owner Dashboard should have a new action, "Mailing List Export" which sends a spreadsheet to the user containing columns for User Login, User Name, Email, Opt-in, and columns for each of the owner's collections.  Each user should appear as a data row, with deed totals as the cell for each collection.

This is an edited listing of the code used to generate the sample spreadsheet, which may be useful:
```
header = ['User Login', 'User Name', 'Email', 'Opt-In']
owner = User.find 'ushmmarchives'
collection_ids = owner.collections.map { |c| c.id }.sort
deed_map = Deed.where(:collection_id => collection_ids).group(:user_id, :collection_id).count
user_ids = deed_map.keys.map {|e| e[0]}.uniq
Collection.where(:id => collection_ids).order(:id).each { |c| header << c.title }
csv << header
User.find(user_ids).each do |user|
  row = []
  row<<user.login
  row<<user.display_name
  row<<user.email
  row<<user.activity_email
  collection_ids.each do |collection_id|
    row << deed_map[[user.id,collection_id]] || 0
  end
print csv_out
File.write('/tmp/ushmm_users.csv', csv_out)
```

(This should be branched off of `development` and migrated to `rails6` if necessary.)

**Comment by saracarl** [comment]
I'd like to add this to the "summary" tab of the owner dashboard, under "collaborators" but before the leader boards.

We should also add a link to the "collaborators" tab for a collection that says:
"A detailed spreadsheet export of all collaborators is available on your owner dashboard."
