### ISSUE TITLE
Dictation microphone obscures text

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1598]
A new user has complained because they mis-typed a word which was covered up by the dictation microphone on this page: https://fromthepage.com/sma-archives/city-of-seattle-records/9106-03-001-032/transcribe/699174

We should consider moving this microphone to the upper-right corner of the textarea, or somewhere else less obtrusive.

**Comment by benwbrum** [comment]
Customers are also reporting that the dictation microphone obscures the image.  (I'm not sure if this is still a problem or not.)

![image002](https://user-images.githubusercontent.com/199961/113181991-01ae4280-9218-11eb-86a5-6673c06bf09e.png)

**Comment by saracarl** [comment]
Fixed in the UI (but broken? -- opening a new issue for that.)
