### ISSUE TITLE
Collection Page:  add work descriptions & stats

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#160]
On the collections page 
( http://localhost/app/JuliaBrumfield )
in the works section

Add for each work: the work description and the work statistics 

See page 1/23 of the UI Mockups -- we want a combination of the descriptions and the last item in the last (stats) for each of the works in a collection.

**Comment by kolking** [comment]
@saracarl so, the statistics block (for all works in the collection) show come very last, below the list of works with descriptions, did I understand right? Alternatively, we can show the statistics for each work in the list under its title / description.

**Comment by benwbrum** [comment]
We want each work to be more interesting, so we want the statistics for each to appear with it.

**Comment by saracarl** [comment]
Ben is correct -- next to or right below the title/description.
