### ISSUE TITLE
Support characters beyond Unicode Basic Multilingual Plane

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1603]
A user added Greek characters to the text she was transcribing by copying them from the MacOS 10 Character Viewer tool.  This truncated the text when the text was saved, also truncating the `xml_text` derived from it.  Repeating the work by pasting in text from Greek Wikipedia showed that the application can handle Greek text, just not _this_ Greek text.

Some possible clues:
My Linux terminal shows the problematic characters in italics, but the good characters in a normal font.
`od -c` shows different characters for the first letter (Greek kappa) in files containing good and bad characters.

See attached files with bad characters vs. good characters.
[bad_greek.txt](https://github.com/benwbrum/fromthepage/files/4054817/bad_greek.txt)
[good_greek.txt](https://github.com/benwbrum/fromthepage/files/4054818/good_greek.txt)

**Comment by bencomp** [comment]
Interesting! We're not currently using much 'esoteric' parts of Unicode, but I would hope that in principal all (visible) characters are supported. 

After some searching, and eventually learning about `uniutils` (on [superuser.com](https://superuser.com/a/777560/200568)), and `brew install uniutils`, I found the characters in `bad_greek.txt`:

```
$ uniname -g bad_greek.txt 
No LINES variable in environment so unable to determine lines per page.
Using default of 24.
character  byte       UTF-32   encoded as     name
        0          0  01D705   F0 9D 9C 85    MATHEMATICAL ITALIC SMALL KAPPA
        1          4  01D70A   F0 9D 9C 8A    MATHEMATICAL ITALIC SMALL OMICRON
        2          8  01D704   F0 9D 9C 84    MATHEMATICAL ITALIC SMALL IOTA
        3         12  01D708   F0 9D 9C 88    MATHEMATICAL ITALIC SMALL NU
        4         16  01D70A   F0 9D 9C 8A    MATHEMATICAL ITALIC SMALL OMICRON
        5         20  01D70E   F0 9D 9C 8E    MATHEMATICAL ITALIC SMALL SIGMA
        6         24  01D705   F0 9D 9C 85    MATHEMATICAL ITALIC SMALL KAPPA
        7         28  0003CC   CF 8C          GREEK SMALL LETTER OMICRON WITH TONOS
        8         30  01D70B   F0 9D 9C 8B    MATHEMATICAL ITALIC SMALL PI
        9         34  01D704   F0 9D 9C 84    MATHEMATICAL ITALIC SMALL IOTA
       10         38  01D6FC   F0 9D 9B BC    MATHEMATICAL ITALIC SMALL ALPHA
       11         42  00000A   0A             LINE FEED (LF)
```
Mathematical symbols! Maybe in a weird non-UTF-8 encoding?
```
$ chardetect bad_greek.txt 
bad_greek.txt: no result
```
Compare this to good greek:
```
$ uniname -g good_greek.txt 
No LINES variable in environment so unable to determine lines per page.
Using default of 24.
character  byte       UTF-32   encoded as     name
        0          0  0003BA   CE BA          GREEK SMALL LETTER KAPPA
        1          2  0003B1   CE B1          GREEK SMALL LETTER ALPHA
        2          4  0003B9   CE B9          GREEK SMALL LETTER IOTA
        3          6  000020   20             SPACE
        4          7  0003C0   CF 80          GREEK SMALL LETTER PI
        5          9  0003CC   CF 8C          GREEK SMALL LETTER OMICRON WITH TONOS
        6         11  0003BD   CE BD          GREEK SMALL LETTER NU
        7         13  0003BF   CE BF          GREEK SMALL LETTER OMICRON
        8         15  0003C5   CF 85          GREEK SMALL LETTER UPSILON
        9         17  00000A   0A             LINE FEED (LF)
```

**Comment by bencomp** [comment]
While looking at other issues around line breaks, I stumbled upon
https://github.com/benwbrum/fromthepage/blob/35caa2a2eb82bbe4f4aff0d92c3290ea8246b42f/app/helpers/abstract_xml_helper.rb#L12

Could it be that the character encoding is different than lines like these assume? Or that the MySQL schema or connection use an incompatible encoding?

**Comment by benwbrum** [comment]
We're also running into this problem with Alchemical symbols in Unicode, which should also be supported.  

The problem text:
```


Gold or Silver in Shells-4
Green Paint for Wood. 103
Glass Vessels to purify-122
Gold to deforme     147
Greek. [🜂] [fire]. 150
[☉] [Gold] Experiment 181
[🜘][Bismuth?] 187
🜘.[bismuth?] Magic188
Glass artificial 193
[☉}[Gold] from [h with cross on it] [♄} 202

🜘[Bismuth?]-----203
```

(Also attached as a file.)
[bad_alchemy.txt](https://github.com/benwbrum/fromthepage/files/4753690/bad_alchemy.txt)

**Comment by benwbrum** [comment]
Alchemy symbols, Mathematical alphanumerics, and *Deseret script* reside in a higher (`> 65535`) block of Unicode code-points, the [Supplemental Multilingual Plane](https://en.wikipedia.org/wiki/Plane_(Unicode)#Supplementary_Multilingual_Plane).

Apparently we will need to update our MySQL character encodings to support these, as they require [UTF-8 4-byte encoding](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb4.html).  This may require downtime.

**Comment by benwbrum** [comment]
A nice guideline on how to convert character set encodings is [excerpted here](https://dba.stackexchange.com/questions/8239/how-to-easily-convert-utf8-tables-to-utf8mb4-in-mysql-5-5)
