### ISSUE TITLE
Upload processing log does not capture STDERR

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1611]
When an owner uploads a document, we fire off a rake task and direct `STDOUT` to a `processing.log` file which can be viewed to diagnose any problems.  Unfortunately, we do not also redirect `STDERR` to this file, so many errors which cause upload processing to fail are invisible.

**Comment by saracarl** [comment]
Fixed. https://github.com/benwbrum/fromthepage/pull/1984
