### ISSUE TITLE
Subject export hardcodes 'http://' in links

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#1627]
The subject export controller hardcodes 'http://' links, instead of using URL helper functions that should automatically use the configured scheme.

**Comment by diegoviola** [comment]
@bencomp @saracarl can you please provide some steps to reproduce for this issue? I looked at this tonight and couldn't reproduce it. Thanks in advance.

**Comment by bencomp** [comment]
Sure, @diegoviola. On the export page of a collection, near the bottom, there is a button to export the Subjects as CSV. When you use that to download a CSV file, I notice that all the URLs in the file start with `http://`, even though our FromThePage is configured to only use HTTPS.

The issue is in https://github.com/benwbrum/fromthepage/blob/35caa2a2eb82bbe4f4aff0d92c3290ea8246b42f/lib/subject_exporter.rb#L21 and https://github.com/benwbrum/fromthepage/blob/35caa2a2eb82bbe4f4aff0d92c3290ea8246b42f/lib/subject_exporter.rb#L30 – though the latter may be a Rails configuration issue. I think Rails 4 needs extra configuration to tell it that we are using HTTPS (which is handled by a proxy server).

It's not the biggest issue, of course, but hopefully it's easy to fix.

**Comment by diegoviola** [comment]
@bencomp can you please try https://github.com/benwbrum/fromthepage/pull/1719?

**Comment by bencomp** [comment]
I'm afraid I can't easily test any fixes, as we don't have a test environment 👼 
I did comment on your PR. Thanks for your work!
