### ISSUE TITLE
Collection Page: restyle subjects and fix broken functionality

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#163]

**Comment by kolking** [comment]
@saracarl @benwbrum I have a question regarding the subject list in the collection section. Right now we have two places where the subjects displayed - on the Overview page and on the separate Subjects page. Expand/collapse functionality makes the Overview page very long and I want to avoid that. My idea is to show the complete subject tree on the Subjects page but limit the subjects listed on the Overview page. We can show only the root-level ones or maybe even not show subjects here and instead of them show stats - top transcribers, top editors, top indexers?

**Comment by saracarl** [comment]
Yes, just delete the subject links.  (We may get it it before you -- please prioritize other work.)

**Comment by saracarl** [comment]
or, delete the subject section on the overview page (to be clearer).

**Comment by saracarl** [comment]
Ok, so now we have top level categories on the collection page, which is nice.  However, if I click on the top level category I'd expect it to take me to the subject tab (which it does) with the category expanded and loaded (which it doesn't).  We should either fix this or get rid of subjects on the overview  tab completely.

**Comment by kolking** [comment]
Yes, there was a bug. Now if you click on a top level category in the collection overview page, you should be redirected to the subjects tab with the appropriate category selected (and expanded if it contains any subcategories) and subjects loaded (if any).
