### ISSUE TITLE
If all works transcribed, don't "hide completed works"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1634]
We have a "hide completed works" feature that hides finished works so unfinished works can be transcribed.  That's fine, unless all works are fully transcribed.  If all works are fully transcribed, then you get an empty list of works (and a "show all" link) which is confusing to the user.

We should show all the works if they are all transcribed.

**Comment by diegoviola** [comment]
@saracarl I'd really appreciate some steps to reproduce for this issue.

**Comment by benwbrum** [comment]
* Create a new collection
* Verify that Settings-> Hide Completed Works is checked
* Import or upload or create 2 works ("A" and "B")
* Transcribe all pages in work A
* Visit the collection home page
* Verify that work A is not visible but work B is visible.
* Transcribe all pages in work B

Current behavior has the collection `show` listing no works, or saying "All works are completed"
We'd like this to show all works.

So, if the collection is set to "Hide completed works"=`true`, only show works that are not completed _unless_ the resulting list would be empty; then show all works.

**Comment by diegoviola** [comment]
@benwbrum @saracarl do we still want to show the "All works are fully transcribed." message after displaying the completed works?

**Comment by saracarl** [comment]
Yes.
