### ISSUE TITLE
"New FromThePage Activity" emails -- first link broken

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1636]
_Every time I receive an email with the subject "New FromThePage Activity" the first link always throws a 404 error.  The others seem to work.  I'm just worried that if someone gets this message and the first thing they get is a 404 they won't click on any others._

This is when new works are uploaded (although we should test it with new notes and no uploads as well) in the following tasks:
https://github.com/benwbrum/fromthepage/blob/0d740cd7f9c1ec95964fd081e5ef1fca2e420503/lib/tasks/nightly_user_activity.rake

While we're fixing this let's also fix #1358 in the same email.

**Comment by diegoviola** [comment]
I can't reproduce this, all the links I get in the emails work fine.

**Comment by benwbrum** [comment]
This appears to work for me.
