### ISSUE TITLE
document set thumbnail images not displayed on document set page

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1637]
Here you see a document set with a thumbnail
![Screenshot from 2020-02-25 13-56-57](https://user-images.githubusercontent.com/708566/75282490-c7819e80-57d6-11ea-8cd4-94a9913f4de4.png)

So this document set page:
https://fromthepage.com/lva/accomack-county-va
Should look similar to to collection page:
https://fromthepage.com/lva/wwi-va-questionnaires  
but with different images.

**Comment by saracarl** [comment]
To test / reproduce this:
1)  create a collection with 2 works in it.
2)  upload a thumbnail image in the collection settings page.
3)  view the collection page transcribers see; the thumbnail image should show up.
4)  create a document set based on the collection (in the settings on the right hand side)
5)  add a work to the document set
6)  add a thumbnail image to the document set settings.
7)  verify that the thumbnail image shows up on the document set page transcribers see.

**Comment by diegoviola** [comment]
@saracarl I followed your steps to reproduce and I can see the thumbnails for the collection and document set after uploading them.

I noticed that the thumbnail uploading is broken on the rails6 branch, I'll open a separate PR for that.

**Comment by diegoviola** [comment]
Fixed the thumbnail issue (rails6 branch) with this commit: https://github.com/benwbrum/fromthepage/commit/593ae423cf5280777efb26a385debb8b7106a0ff
