### ISSUE TITLE
Page version comparison: make a better style for the view mode switcher

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#164]
@benwbrum am I right that you want to see the diff mode on by default for the version comparison?

**Comment by benwbrum** [comment]
I'd prefer the diff mode to default, but think you're right about the
checkbox.

Ben

**Comment by kolking** [comment]
okay, thanks!

**Comment by benwbrum** [comment]
We really like the revision list on the left side.  Having the diff view suggests a new need, however:

Previously we compared the selected version with the current version.  Now that we have a diff view, and a much easier navigation, we should reconsider this.  Users viewing revision history will be interested in what that revision changed from the previous state of the page.

Can we replace parts of this as follows?

* Left pane: revision list as you've implemented
* Middle pane: selected version displayed as implemented
* Right pane: diff view of selected version and the previous version (selected version - 1) -- blank if there is none

In addition, we need to be able to highlight/diff changes to the page title.
Also, if we absolutely can't hide the ability to turn the diff mode off, then relabel "Original" to "Text".  But I'd really like the diff mode to be the only mode, even if we lose the link information.

I'll be happy to send the rails code for getting the previous version if you need it.

**Comment by benwbrum** [comment]
Moving comments on this and #150 to a new issue and moving these to "done"
