### ISSUE TITLE
When editing an owner in the admin dashboard, redirected to the user tab instead.

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1645]
When you edit an owner in the admin dashboard, after saving you are redirected back to the user tab instead of the owner tab.  You should go back to the owner tab instead.

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/5d26334da0470eaf3fe4ebeba66eecc9a8782093/spec/features/admin_view_spec.rb 

I think the issue could be in here but I'm not super sure about that

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/51502e74ddcf93cb132b2e4f1f4f49606989ce82/app/controllers/application_controller.rb#L237

actually it might be here

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/fe44c777adb0b164dc02e0eb43548d74f8f25723/app/views/admin/owner_list.html.slim#L43

**Comment by JosieBrum** [comment]
We can't find where the thing is supposed to be. Help Please

**Comment by JosieBrum** [comment]
LINE TO FIX
https://github.com/benwbrum/fromthepage/blob/4eaa82581f5be7030cd165e24de0734bd20c26d8/app/controllers/admin_controller.rb#L81
