### ISSUE TITLE
Wiki markup should be documented

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#1650]
Some of our users were surprised by how lines of `=======` were interpreted, namely with errors. Because the default transcription conventions don't mention wiki markup (anymore?), I realised this line of equals signs was interpreted as a bunch of misformed headings only after diving into the source code.

Would it be possible to point to documentation on the built-in parsing of wiki and (pseudo) HTML markup?

**Comment by bencomp** [comment]
@benwbrum provided the answer in https://github.com/benwbrum/fromthepage/issues/1090#issuecomment-597408109 by referring to <https://content.fromthepage.com/project-owner-documentation/advanced-mark-up/>.

I'm not closing this yet, as I think it should be part of the system itself, or at least be linked from some location within FromThePage. Maybe the default transcription rules/guidelines?

**Comment by saracarl** [comment]
Will be addressed by #1832

**Comment by benwbrum** [comment]
In-app links to documentation have been added.
