### ISSUE TITLE
incorrectly reporting 100% transcribed when should be 0%

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1654]
The following work shows at 100% transcribed in the collection view: 
https://fromthepage.com/dclep/council-project?works=show
![image](https://user-images.githubusercontent.com/708566/76986200-52097980-690f-11ea-953b-e1da24d77b22.png)

But 0% transcribed once you look at the pages:
https://fromthepage.com/dclep/council-project/minutes---august-15--1902
![image](https://user-images.githubusercontent.com/708566/76986131-3c944f80-690f-11ea-909c-a3a6769daf6f.png)

Also note that it says "20% needs review" -- none of the pages are marked "needs review" and there are 6 of them (which wouldn't lead to a 20% number).

A theory is that we are mixing up works for this status -- A 5 page with 1 in needs review would be reporting like this.  (And there are a number of other works in this collection with 5 pages.  Some with 1 page in needs review.  

Other similar problems:
- August 16 https://fromthepage.com/dclep/council-project/minutes---august-16--1901 is *correct* with 5 pages/20% needs review.  Perhaps this is the source of the other status?

- https://fromthepage.com/dclep/council-project/minutes--april-20--1900 is 4 pages but shows 5 pages/20% needs review

- https://fromthepage.com/dclep/council-project/minutes---august-15--1902 is 6 untranscribed pages but shows 5 pages/20% needs review

- https://fromthepage.com/dclep/council-project/minutes---august-17--1900/display/747390  is 3 pages but shows at 5 pages/20% needs review in the collection.

- https://fromthepage.com/dclep/council-project/minutes---august-18-26--1899 is 6 pages, but shows 5 pages/20% needs review in the collection.

EVERY OTHER work from there to the end reports 5 pages/20% needs review in the collection.  I'm sure some of them are wrong.

I'd also point out that the green status bar on the 5 pages/20% needs review just shows solid green, which is also wrong.  It should show 20% light green.

**Comment by benwbrum** [comment]
I've fixed the data problem in production.  The snapshot file `2020_03_13_08_00_01.dmp` still contains the incorrect `work_statistics` value.

Remediation can be done by finding a problematic work `w` and recalculating all statistics for the collection:
`w.collection.works.each { |work| work.work_statistic.recalculate }`
