### ISSUE TITLE
Page Version should compare version N with N-1, not current

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#166]
Moving from #150 and #164

We really like the revision list on the left side.  Having the diff view suggests a new need, however:

Previously we compared the selected version with the current version.  Now that we have a diff view, and a much easier navigation, we should reconsider this.  Users viewing revision history will be interested in what that revision changed from the previous state of the page.

Can we replace parts of this as follows?

* Left pane: revision list as you've implemented
* Middle pane: selected version displayed as implemented
* Right pane: diff view of selected version and the previous version (selected version - 1) -- blank if there is none

In addition, we need to be able to highlight/diff changes to the page title.
Also, if we absolutely can't hide the ability to turn the diff mode off, then relabel "Original" to "Text".  But I'd really like the diff mode to be the only mode, even if we lose the link information.

I'll be happy to send the rails code for getting the previous version if you need it.

**Comment by kolking** [comment]
@benwbrum totally agree. Could you please clarify one thing for me - is the most recent page_version always equal to current page version?

**Comment by kolking** [comment]
I've implemented the new logic with only one exception - when the very first revision selected (no previous version) it compared with an empty text and shows everything as "added", I think this is the right behavior. Also, I've made the unchanged text highlighted with white background.

![image](https://cloud.githubusercontent.com/assets/4656448/7403503/01242b64-eedf-11e4-8a7a-6e3039cf354f.png)
