### ISSUE TITLE
expand subjects when clicked

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#167]
When you click on 

People --> Ben Brumfield Family

in subjects on this page:
http://96.126.116.203/app/JuliaBrumfield

You should get an expanded list of people who are in that subject category.  (sub-categories)

(Ben says this may or may not work in the deployed app right now -- it's an Ajax call of some sort that is supposed to happen.)

**Comment by saracarl** [comment]
Even when the subject isn't expandable, the link doesn't work -- it doesn't take you to the subject page like it ought to.

**Comment by kolking** [comment]
I've already added issue #163 to fix that, don't worry I'll take care of it.

**Comment by saracarl** [comment]
Close in favor of 163.
