### ISSUE TITLE
S3 Storage configuration

### ISSUE THREAD

**Issue by pointoneseven** [benwbrum/fromthepage#1670]
Trying to get storage to go to an already configured S3 bucket, but files keep uploading locally. 

Is there another place to set the storage preference for the environment other than in?: 

 config.active_storage.service = :amazon

**Comment by benwbrum** [comment]
We've never tried storage outside of local storage, so you're breaking new ground here.  Let us know what you find!

**Comment by pointoneseven** [comment]
So the storage.yml in ../config is a boilerplate and not a current feature?

**Comment by diegoviola** [comment]
@pointoneseven `config/storage.yml` is the Active Storage configuration, FromThePage currently does not use this, if you want to use it, the [documentation](https://edgeguides.rubyonrails.org/active_storage_overview.html) may be a good place to start.

Please let us know if you have more questions.

**Comment by pointoneseven** [comment]
Thanks much!
