### ISSUE TITLE
Rows of equals signs interpreted as section headers

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1685]
If documents have long rows of equals signs in them, transcribers type those verbatim.  Unfortunately we interpret them as `==header markup==` and convert them into invalid XML.

We need to intercept these and avoiding interpreting them as entry headers.

Example text:
```
ACCREDITED HIGH SCHOOLS FOR NEGROES IN NORTH CAROLINA
WITH THEIR CLASSIFICATION ON THE BASIS OF ANNUAL HIGH
SCHOOL REPORTS FOR THE SCHOOL YEAR ENDING JUNE, 1942

There are five classes of accredited schools as 
follows:  I-AA, 12; I-A, 20; I-B, 9; II-A, 124; II-B,
15.  Total ----- 180

=====================================================================
POST OFFICE     NAME OF SCHOOL      PRINCIPAL            CLASS   DATE *ASA
---------------------------------------------------------------------------------------------------------------------
                                                                       PRIVATE SCHOOLS
                                                                       ------------------------------

```
![image001](https://user-images.githubusercontent.com/199961/78277261-d47e6580-74d9-11ea-93a0-6c40a0519843.png)

**Comment by bencomp** [comment]
I think #1650 is related, which was answered in https://github.com/benwbrum/fromthepage/issues/1090#issuecomment-597408109 by referring to <https://content.fromthepage.com/project-owner-documentation/advanced-mark-up/>.

**Comment by benwbrum** [comment]
We still need to modify [the code that looks for `==section headers==`](https://github.com/benwbrum/fromthepage/blob/development/app/models/xml_source_processor.rb#L274) to only match sections with textual contents between equals signs.

To reproduce:
* Transcribe a page
* Create a valid section header `==header==` up to `======header======`
* Create a line of equals signs (and no other characters) `=====================`
Desired behavior:
The headings should be created correctly, the line of equals signs should remain as equals signs.

**Comment by benwbrum** [comment]
This has been fixed.  It will be deployed on FromThePage.com this week, and will be part of the next release.
