### ISSUE TITLE
carousel image stretched

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1689]
![image](https://user-images.githubusercontent.com/708566/78671683-3a396b80-78a5-11ea-9145-92bbf6305fbe.png)

https://fromthepage.com/whslamc

The image in the carousel here is stretched.  I'm not sure why, because on my browser it looks fine.

**Comment by saracarl** [comment]
Looked fine on a reload.  Closing.

**Comment by saracarl** [comment]
From the customer:
The odd stretch appeared again today and I discovered the reason. It looks fine at 1920x1080 resolution, but one of my monitors is 2560x1440. When the browser is full screen the carousel stretches taller. This happens in Chrome and Edge and is repeatable. An edge case, but thought you should know.

**Comment by benwbrum** [comment]
Fixed when @kolking replaced the carousel.
