### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by srl295** [benwbrum/fromthepage#17]
in general, it would be nice to not have to modify files under change control to do configuration. Not sure how to do that.

Anyways, here's a .gitignore that reduces the noise a little.

```
public/images/simple_captcha
public/images/working/dot/*
public/images/working/upload/*
public/.htaccess
log
```

**Comment by saracarl** [comment]
+ assets

.gitignore should be checked in...

**Comment by tbl73** [comment]
Added /public/assets/
