### ISSUE TITLE
subject pop ups on transcribed pages  broken when not logged in

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#170]
If you are on a page like:  http://localhost:3000/display/display_page?page_id=378 and click on a linked subject within the page, you should get a pop up with information about that subject (and a link to the subject page).

Just tried this with the most recent code and the pop up happens, but the URL for the popup does't work so you get some other page in the app.

This only happens if you are not logged in.  If you are logged in, it works.

**Comment by kolking** [comment]
yes, I see the same bug... will take a look into it.

**Comment by saracarl** [comment]
got it working for now by taking the image out of the pipeline

**Comment by kolking** [comment]
great!
