### ISSUE TITLE
Preview lightbox and new feature view

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#171]
For the purposes of the preview, I'd like to modify the splash screen as folllows:

# Splash Screen Lightbox

As/after the screen loads (ideally for the first time per session, though that's not essential), pop up a lightbox with this text:

Welcome to the preview of FromThePage 2.  This site offers a sneak preview of the new verision of FromThePage.  Lorem ipsum text
 * Learn more about FromThePage 2 (big link button to static#about_fromthepage2.html.slim
 * Standard X for closing the lightbox

# About FromThePage2 Screen
This should just be a new view under the static controller, set up similarly to the current splash screen.  We will fill it with some text descriptions, thumbnail links to screen shots, and demo instructions.

**Comment by kolking** [comment]
I've added the lightbox on the home page, it should show only once per session. Btw, what are the settings for session to expire? I assume it should expire when a user close browser window, but it seems that the session variable I set to not show the lightbox with every refresh is still exist when I close and reopen website. For sure, you can clear cookies to see the lightbox again.
I've also created the empty "About" page here `views/static/about`. You're welcome to send me the text and screenshots for this page.
