### ISSUE TITLE
Internet Archive imports failing

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1717]
These items:
https://archive.org/details/sc62samuelwilmotfonds/mode/2up

https://archive.org/details/sc39kerrfondsv1/mode/2up

Failing on this line:
https://github.com/benwbrum/fromthepage/blob/master/app/models/ia_work.rb#L296

With a:
`undefined method 'parent' for nil:NilClass`

The problem is a usability problem.  If you paste in https://archive.org/details/sc39kerrfondsv1 it works.  We need to parse the end of the URL out so this works.

**Comment by benwbrum** [comment]
As of today, even "normal" imports from the Internet Archive details page URL were failing:

URL: https://archive.org/details/Jeremiah_White_Graves_Diary_Volume_3_Book_01

Log messages:
```

I, [2020-07-11T19:56:12.735581 #11948]  INFO -- : Processing by IaController#import_work as HTML
I, [2020-07-11T19:56:12.735969 #11948]  INFO -- :   Parameters: {"detail_url"=>"https://archive.org/details/Jeremiah_White_Graves_Diary_Volume_3_Book_01"}
I, [2020-07-11T19:56:13.329647 #11948]  INFO -- : Completed 500 Internal Server Error in 593ms
F, [2020-07-11T19:56:13.343737 #11948] FATAL -- : 
NoMethodError (undefined method `parent' for nil:NilClass
Did you mean?  present?):
  app/models/ia_work.rb:302:in `files_from_loc'
  app/models/ia_work.rb:134:in `ingest_work'
  app/controllers/ia_controller.rb:127:in `import_work'

```
