### ISSUE TITLE
Canonical Metadata for Works in a Collection

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1725]
As users upload metadata spreadsheets or ingest IIIF manifests we need to store configuration information about what metadata fields are present on works in that collection.  (This will be used to configure and populate faceted browsing later.)  To that end, we should create a new hash called `canonical_metadata` column on the Collection model (this could be JSON, but doesn't have to be.  It could be done natively in ruby.).  This value should be populated when `work.original_metadata` is updated probably on an `after_save` callback.  

When a work's metadata is updating, we should look at all of the labels for the metadata, then look in the Collection's `canonical_metadata` field for an element with each label.  If none is found, then that label should be added with a value of 1.  If the element is present, increment the value.  The result will be a hash with counts of works that have each metadata field.

**Comment by diegoviola** [comment]
@saracarl https://github.com/benwbrum/fromthepage/blob/1640-import-metadata-iiif-manifest/app/models/metadata.rb#L69-L91
