### ISSUE TITLE
Private document set in private collection lists unrelated people as collaborators

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#1734]
We have a private collection for a master's programme course. Only six people have access to this collection; five as owner and one as collaborator.
Document sets have been enabled for this collection and all four created sets are private. Only in one of the four sets, say set A, one person has been added as collaborator; the other sets have accessibility inherited from the collection.

The issue is this: in document set C, a whole bunch of people are listed under "All Collaborator Emails" who have nothing to do with the collection. Most of these have no access to the collection or document set. Redacted screenshot of the document set collaborators showing one active user over the last year (i.e. since the start of this set) and a long list of 'all collaborators':

![docset-collaborators](https://user-images.githubusercontent.com/1303898/81204081-05febb00-8fc9-11ea-88fa-e7a62bbb6df4.png)

The Collaborators tab for set A lists different people under "All Collaborator Emails" that again should not have access to the document set. Even to me, the administrator, there is no connection between the names on the list and the collection or document set.

These lists of names and emails are longer than the list for the whole collection, as this redacted screenshot of the collection collaborators shows:

![collection-collaborators](https://user-images.githubusercontent.com/1303898/81204062-ff704380-8fc8-11ea-8de8-c8283d7e683a.png)

I'm not sure if/how this relates to existing issues. Maybe #1435?

(Note: the collection owners are thinking that using document sets is not really needed, as the collection won't be very large and they don't really need strict separation of access to the document sets. Hence this is not a huge issue for us, but it is still confusing and just weird.)

**Comment by saracarl** [comment]
This may be fixed by a lot of work we did on document sets a while back.  @bencomp any chance you've upgraded in the last 3 months and could check?

**Comment by bencomp** [comment]
The collection no longer has document sets. I will close this for now.
