### ISSUE TITLE
Metadata facet configuration

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1746]
The third stage of the metadata facet work is to create an interface that will allow project owners to configure how original metadata will be transformed into searchable facets, and how those searchable facets will appear to end users.

We will be using the [Forty Facets Gem](https://github.com/FortySource/forty_facets) to display and search facets, which allows searching text, numeric values, and dates.  I don't think any library metadata includes numbers, but we will need to search text vs. dates.  We will also need to attach a label to the facet and a display order.

On the Facets configuration tab of the Collection,
* for each row, add
  * a text input for Label
  * a select listing "text" or "date" called Type
  * a short text input for Order
* when the form is saved, persist the new values in a `facet_config` Hash column on `collections`
  * the keys should be the name of the field in the original metadata
  * the values should be a hash with keys `:label`, `:type` and `:order`, filled in with values from the form.
  * Any row on the form which does not contain a `:label` value should not create an entry in `facet_config` -- these fields will be ignored when we transform data for faceting.

**Comment by diegoviola** [comment]
> Any row on the form which does not contain a :label value should not create an entry in facet_config -- these fields will be ignored when we transform data for faceting.

@benwbrum is this still needed after the rework/refactor we did? (MetadataCoverage, FacetConfig).

The reason I ask is because we now create a `facet_config` while creating `metadata_coverages`, see:

https://github.com/benwbrum/fromthepage/blob/1640-import-metadata-iiif-manifest/app/models/metadata.rb#L79
