### ISSUE TITLE
change "notes" to "ask a question"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1748]
Change the “notes” field label to be “ask a question”

**Comment by saracarl** [comment]
in the input field, have "Ask a question or leave a note."

**Comment by benwbrum** [comment]
I vote we change this to "Notes and Questions"

**Comment by JosieBrum** [comment]
https://github.com/benwbrum/fromthepage/blob/4eaa82581f5be7030cd165e24de0734bd20c26d8/app/views/display/display_page.html.slim#L69 and https://github.com/benwbrum/fromthepage/blob/4eaa82581f5be7030cd165e24de0734bd20c26d8/app/views/notes/_notes.html.slim#L17
