### ISSUE TITLE
Clicking work thumbnail should take user to the work

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1754]
Currently, if a user is looking at a list of pages, they see a thumbnail image for each page and also a title for each page.  Both the title and the thumbnail image are links to the page.

If the user sees a list of works, they see a thumbnail image and a work title, but only the work title is a hyperlink.  We should make the thumbnail be a link to the work just as the work title is.

**Comment by JosieBrum** [comment]
https://github.com/benwbrum/fromthepage/blob/4eaa82581f5be7030cd165e24de0734bd20c26d8/app/views/collection/show.html.slim#L33

This line's link, but for the image thumbnail (thumbnail name one line above)

**Comment by benwbrum** [comment]
Right.  So adding `link_to` in the previous line is what we're after here.  Since `link_to`'s first argument is the thing being displayed (technically the contents of the anchor tag), you could take the `link_to` call in line 33, replace `work.title` with the `image_tag` call (and its arguments) in line 32, and that should work.  

Note that the person who wrote this loved to skip the optional parentheses in method calls, so you might want to add them to the arguments to `link_to` in 33 and to `image_tag` in 32 first and see if everything still works before you start moving code around.
