### ISSUE TITLE
Missing space between lines in read-work view

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1767]
In the "read work" view, where we display texts without the transcription line breaks, we are "smooshing" lines together without a space between the last word of one line and the first word of the 2nd line.

https://fromthepage.com/yale/susan-shelby-magoffin-journal/needs_review?page=7  (private collection)

See "tojust" and "myhands" in the screenshot below:
![image](https://user-images.githubusercontent.com/708566/84425518-57612200-abe7-11ea-9cda-02c6360797d0.png)

**Comment by benwbrum** [comment]
This is an screenshot of the same page, taken today.  No edits have been made to the text during that time.
![Screenshot from 2020-06-12 16-03-41](https://user-images.githubusercontent.com/199961/84546596-4b4c9180-acc7-11ea-9a43-97c9500c15b1.png)

**Comment by saracarl** [comment]
This is only happening in the needs review listing of pages.
