### ISSUE TITLE
add footer to collection and work views

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1768]
So we display footers on transcription pages and collection views, but we don't show them on work views:

Working:
https://fromthepage.com/lacountylibrary/letters-of-the-office-of-indian-affairs-1849-1880-california-superintendency

Not working:
https://fromthepage.com/lacountylibrary/letters-of-the-office-of-indian-affairs-1849-1880-california-superintendency/mf1323-1197-reel-37-0806

I'd like to add the owner footer to those pages.

Here's how to display the footer:

https://github.com/benwbrum/fromthepage/blob/master/app/views/article/list.html.slim#L68

**Comment by JosieBrum** [comment]
Successfully added the footer to 'About' and 'Versions' tabs, but I need help finding the folder that has the 'Read' tab. I checked all the pages in the 'works' folder, and could not seem to find it there.

**Comment by benwbrum** [comment]
Check the display views.  There should be a `display/read_work` view that might be it.

**Comment by JosieBrum** [comment]
Finish the other tabs in the work views

**Comment by JosieBrum** [comment]
I need help with finding the code where the "Contents" and "Help" tabs are
