### ISSUE TITLE
preview/autolink buttons cover text of transcription

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1786]
It's annoying to transcribers.  Can we move them higher or outside of the transcription box?

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/views/transcribe/display_page.html.slim#L81 

I feel like it's probably in here because it's where the displaying of both buttons are as well as the "Mark as blank" button, etc above.

**Comment by saracarl** [comment]
I think "Save Changes" needs to be the rightmost button, but otherwise, I like this.  I think the order should be:
mark blank/needs review/preview/autolink/save changes.

We may want to think about adding autolink and preview to the bottom of the screen, near the other save changes button.
