### ISSUE TITLE
add iiif manifest to "about" page for a work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1796]
If a work has been imported via IIIF, let's add a "IIIF Manifest:" field at the bottom of the "About" tab for the work and show the IIIF manifest for the work.

**Comment by benwbrum** [comment]
This can be retrieved by conditionalizing on something like `@work.sc_manifest.present?` and displayed by `@work.sc_manifest.at_id`.

**Comment by isabelabarton** [comment]
could this be done here?
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/views/collection/show.html.slim#L5

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/spec/features/editor_actions_spec.rb#L133

In these lines of codes theres a section that says "expect(page).to have_content("Description")" which I believe is the area that this issue wants the IIIF Manifest to go. Would it make sense to put a line under this one thats says something like "expect(page).to have_content("IIIF Manifest")

**Comment by benwbrum** [comment]
Hm.  These (and anything else in the `spec` directory) are part of a test which looks at a screen for a test `@work` and checks to see if it's there.  It would make sense to add a test here, however I don't think that the test work loaded into `@work` is imported from IIIF, so it should be blank.

It would make sense for the IIIF manifest loading test to check this (in https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/spec/features/zz_iiif_collection_spec.rb#L18-L30 though you'd have to navigate to the correct screen).

Regardless, all of that is just test code.  To make the thing show up, you'll need to look in `app/views` for something that renders the work -- I suspect it'll be `works/show`.
