### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#18]
Dominik Wujastyk has been interested in using FromThePage for Sanskrit manuscripts [(see his blog entry on crowdsourced transcription)](http://cikitsa.blogspot.com/2012/06/crowdsourcing-manuscript-transcription.html).  Quick tests reveal that the current production server running Ruby 1.8 and Rails 2 does not support unicode in any form.  Migrating to Ruby 1.9 is required for this to work, as well as possibly migrating and/or changing the encoding of the backing MySQL database.  srl295 might be interested in following this issue.

**Comment by srl295** [comment]
@srl295 definitely is.

**Comment by saracarl** [comment]
done.
