### ISSUE TITLE
Revise notes to use AJAX

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#180]
Currently it's impossible to leave a comment on a page while you're editing the transcript or translation. This is something that users have requested, as they would like to use the comments to ask questions about the text they're working with.

**Comment by kolking** [comment]
Yes, this will be definitely good. I will do that.

**Comment by saracarl** [comment]
So the transcribe tab and the translate tab  don't have notes sections.  On the display page page it is styled but doesn't look Ajax-ified.   Maybe this change wasn't checked in or we are missing it in the UI?

**Comment by kolking** [comment]
I've added page notes section into transcribe and translate tabs. It works using AJAX, means that adding a note, edit and delete made with AJAX requests without reloading the whole page. I think this is the behavior @benwbrum mentioned in the initial comment.
