### ISSUE TITLE
Do not flag content for abuse if it was created by a (non-Trial) project owner

### ISSUE THREAD

**Issue by isabelabarton** [benwbrum/fromthepage#1803]
In the abuse tab, content created by (non-Trial) project owners is being flagged. Owners like Iowa State and UNC is being flagged.

**Comment by saracarl** [comment]
This may take care of all (most?) of the OCR text that's being flagged, as it's introduced by project owners uploading material.

**Comment by saracarl** [comment]
There is probably two steps to this:
- keep newly uploaded works that are "bad" but owned by a project owner from showing up in the abuse tab
- clean up old abuse entries that are already there (that are owned by a project owner)

**Comment by isabelabarton** [comment]
This is the most promising place I found to start to fix the problem

https://github.com/benwbrum/fromthepage/blob/5d26334da0470eaf3fe4ebeba66eecc9a8782093/app/models/article_version.rb#L8

**Comment by isabelabarton** [comment]
This one looks good too.

https://github.com/benwbrum/fromthepage/blob/5d26334da0470eaf3fe4ebeba66eecc9a8782093/app/models/flag.rb#L1

**Comment by benwbrum** [comment]
It looks like `check_content` defers to `Flag`, so that's the most logical place.

I think that adding a check for the content's user's `owner` flag and `account_type` in `Flagger.check_page` and `Flagger.check_article` makes the most sense.

**Comment by isabelabarton** [comment]
Would this make sense for a check in
https://github.com/benwbrum/fromthepage/blob/5d26334da0470eaf3fe4ebeba66eecc9a8782093/app/models/flag.rb#L36

if account_type.owner?
      FALSE_POSITIVE
    end

**Comment by benwbrum** [comment]
Yes, I think so.

**Comment by isabelabarton** [comment]
I'm not really sure how to check if this one works on the server.

**Comment by benwbrum** [comment]
Before you add your code (note that you can just comment it out if the code's already there), I'd 
* log on as a regular user, edit a page, and leave a URL in the transcription.  
* Then log in as an owner and leave a URL in a *transcription.  
* Then log on as an administrator (your owner account may already be one) and verify that both of the transcripts you left show up in the Abuse tab.  That verifies the problem.

Then you can add your code and try the same thing again:
* Leave a link in a transcript as a regular user
* Leave a link in a transcript as a project owner
* Check the abuse tab and verify that only the regular user's content was flagged.
