### ISSUE TITLE
warning about others transcribing this page should stick around 

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1804]
From a transcriber:

```
my one issue with our transcribing projects is that occasionally a page will be transcribed twice by 2 people. If a page is
 already in use by someone, there is a warning message at the top of the page in red.  However, I wish the message was
 bigger, and I really want that message to stay there. Now its only there briefly, and then it disappears.  It is possible to
 miss it entirely because it goes away pretty fast.
```

I'd like an investigation into keeping this around for as long as you're on this page or just making it last longer.  I'd like the first, but the second may be substantially easier.

**Comment by JosieBrum** [comment]
https://github.com/benwbrum/fromthepage/blob/0d740cd7f9c1ec95964fd081e5ef1fca2e420503/app/controllers/transcribe_controller.rb#L36

**Comment by saracarl** [comment]
Looks like the right place.  Now please go find where the "this page has been marked needs review" (not the exact message) message is displayed so you can see the difference in the two types of messages.  @benwbrum suggests we change this one to that kind of message.

**Comment by JosieBrum** [comment]
Possible? https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/views/transcribe/translate.html.slim#L18

**Comment by benwbrum** [comment]
That's the label for the checkbox, but a few lines down are just the ticket:

https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/views/transcribe/translate.html.slim#L26

There should be a similar block in the transcribe view as well as the translate view which you've identified.

**Comment by JosieBrum** [comment]
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/views/transcribe/display_page.html.slim#L38

**Comment by JosieBrum** [comment]
Where in that line is the thing that says show this message? Is it included?

**Comment by benwbrum** [comment]
Sorry, my pasted URL was totally random.  This is the bit I meant:
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/views/transcribe/translate.html.slim#L26-L28

**Comment by benwbrum** [comment]
The indented `.page-review` is slim's way of saying "apply the `page-review` CSS class to the bit that comes next".

**Comment by JosieBrum** [comment]
How would I test this in the AWS server? Does the server even have other people on it, so will it even show the message?

I think Bela would show up, though.

**Comment by benwbrum** [comment]
The server doesn't have any other people on it.  What you could do, however, is to pretend to be two different users.  Your browser will remember your login information (stored in a cookie), but you can get around that by opening a new incognito window and logging on as Josie2, while your regular window is logged on as Josie1.
