### ISSUE TITLE
turn off "new document upload"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1828]
We get admin emails every time a new document is uploaded, and another one when it is successful.  Let's turn both of these off, and remove the code.

**Comment by JosieBrum** [comment]
These are IIIF import success/failure messages. Are these the ones you mean or are there other ones?
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/mailers/admin_mailer.rb#L34
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/mailers/admin_mailer.rb#L41

**Comment by JosieBrum** [comment]
Never mind those, I found the ones you were talking about.
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/mailers/system_mailer.rb#L19
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/mailers/system_mailer.rb#L36

**Comment by JosieBrum** [comment]
Remove the files that say new upload or upload success in system mailer and track down and delete places that call new upload and upload success:
https://github.com/benwbrum/fromthepage/blob/bcdc11bcc5f408a8ba3c1d4e11ebb0febce8f6ca/app/helpers/add_work_helper.rb#L33
