### ISSUE TITLE
IIIF service 'work status' calls non-existent function

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#1846]
When I look at the IIIF manifest <https://transcription.digitalscholarship.nl/iiif/349/manifest> (generated by FromThePage), there is a link to the service <https://transcription.digitalscholarship.nl/iiif/349/status> that should present the completion status – the same information that is also included in the service block.

The URI of the service <https://transcription.digitalscholarship.nl/iiif/349/status> throws an error. From our logs:

```
I, [2020-07-16T14:22:45.345413 #21710]  INFO -- : Started GET "/iiif/349/status" for [IP] at 2020-07-16 14:22:45 +0000
I, [2020-07-16T14:22:45.347396 #21710]  INFO -- : Processing by IiifController#manifest_status as HTML
I, [2020-07-16T14:22:45.347591 #21710]  INFO -- :   Parameters: {"work_id"=>"349"}
I, [2020-07-16T14:22:45.397916 #21710]  INFO -- : Completed 500 Internal Server Error in 50ms
F, [2020-07-16T14:22:45.427102 #21710] FATAL -- : 
NoMethodError (undefined method `status_service_for_work' for #<IiifController:0x00007f3e36f03b80>
Did you mean?  status_service_for_page):
  app/controllers/iiif_controller.rb:333:in `manifest_status'
```

This is not the newest version of FromThePage yet, but I could confirm the error is still in the version running at fromthepage.com: e.g. <https://fromthepage.com/iiif/918/status>.

It looks like the function call to `status_service_for_work` should be going to `status_service_for_manifest`.

**Comment by benwbrum** [comment]
This has been fixed as a by-product of the structured data API development last year.  Apologies for not letting you know at the time, @bencomp !
