### ISSUE TITLE
Inclusive language 

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1854]
Please read:  https://www.zdnet.com/article/linux-team-approves-new-terminology-bans-terms-like-blacklist-and-slave/

And then review this document from the Internet Engineering Task Force:
https://tools.ietf.org/id/draft-knodel-terminology-02.html

Then please search through the code base for any instances where we use inappropriate terms.  Document those instances in this issue, with suggestions on alternatives.  Then we can review, discuss, make updates, and then implement the changes.

**Comment by isabelabarton** [comment]
@saracarl I looked for the words mentioned in the two article in the fromthepage repository. From what I could tell none of the words were displayed on the actual website but there are 7 instances of "master," 0 of "slave," 6 of "blacklist," and 1 of "whitelist" present in the code. If I were to change those to one of the possible alternatives would that mess up the code?

**Comment by isabelabarton** [comment]
I believe this is all of the places that inclusive language could be implemented. 

"Whitelist" -
ALTERNATIVE: allowlist or passlist
3 instances 
https://github.com/benwbrum/fromthepage/blob/61a86f048ca35d24d1c954c662ccd4ffe48ba44a/lib/tasks/ingestor.rake#L191


"Blacklist" -
ALTERNATIVE: blocklist or denylist
8 instances
https://github.com/benwbrum/fromthepage/blob/5d26334da0470eaf3fe4ebeba66eecc9a8782093/lib/flagger.rb#L2
5 instances
https://github.com/benwbrum/fromthepage/blob/5d26334da0470eaf3fe4ebeba66eecc9a8782093/db/migrate/20190713144825_blacklist_pageblock.rb#L1
3 instances
https://github.com/benwbrum/fromthepage/blob/5d26334da0470eaf3fe4ebeba66eecc9a8782093/app/views/admin/settings.html.slim#L14
2 instances
https://github.com/benwbrum/fromthepage/blob/fe44c777adb0b164dc02e0eb43548d74f8f25723/lib/tasks/send_owner_emails.rake#L5
5 instances
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/app/controllers/admin_controller.rb#L195
2 instances
https://github.com/benwbrum/fromthepage/blob/1ae2aea58ffae54e3707a8ca5c1868f961654a58/lib/contentdm_translator.rb#L52

"Master" -
ALTERNATIVE : Primary
2 instances https://github.com/benwbrum/fromthepage/blob/a58096fd0c15a64169340288df327962a0978d9c/index.html#L25
1 instance
https://github.com/benwbrum/fromthepage/blob/51502e74ddcf93cb132b2e4f1f4f49606989ce82/.travis.yml#L47
1 instance
https://github.com/benwbrum/fromthepage/blob/ba398863cc5721a6794df1d21e41d28574627ce4/config/deploy/production.rb#L49
1 instance
https://github.com/benwbrum/fromthepage/blob/a8061f81a7dbff61ea79257419e8cde88f61a8ba/config/deploy/nybg.rb#L51
1 instance
https://github.com/benwbrum/fromthepage/blob/ba398863cc5721a6794df1d21e41d28574627ce4/config/deploy.rb#L7
1 instance
https://github.com/benwbrum/fromthepage/blob/a58096fd0c15a64169340288df327962a0978d9c/app/assets/javascripts/plugins/jquery.jcarousellite.js#L5
1 instance
https://github.com/benwbrum/fromthepage/blob/a58096fd0c15a64169340288df327962a0978d9c/app/assets/javascripts/plugins/select2.js#L6

"Slave" -
ALTERNATIVE : Secondary
0 instances but I thought I'd include an alternative if it ever came up
