### ISSUE TITLE
If collection is private, limit restricted work collaborators to collection collaborators

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1856]
We ran into an issue today where a customer had restricted a work and assigned a collaborator, and then later made the collection private.  The collaborator was not able to see her restricted work because she couldn't see the collection.

We should have a second fix here that is you have restricted works and you click "make collection private" (and the restricted collaborators on a work aren't collaborators on the collection, which they won't be because you can't add collection collaborators until after the collection is private) we should show a warning (and perhaps list the work collaborators)  Or we can automatically add the users that need to be added?

**Comment by isabelabarton** [comment]
I went through the steps that we went over yesterday but I'm still having trouble finding/exactly understanding what needs to be fixed. I added a collaborator to my project on the environment after I made it private and then I could transcribe it logged in as the collaborator. Am I supposed to make that possible? @saracarl

**Comment by benwbrum** [comment]
Covered in #2315
