### ISSUE TITLE
Restyle Work section: Contents tab

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#186]

**Comment by benwbrum** [comment]
Let's remove the revision count and lst reision section here, as you suggest in #188.  The contents page is meant to be a navigation aid, with a (minor) invitation to improve pages that need transcription/annotation.

Eventually this page will get more complex, but that complexity will come from representing chapters and sections, not more attributes of each page.

**Comment by kolking** [comment]
@benwbrum sorry for bothering you, but I'm still confused. What do you mean:
> lst reision section here

List revision section? If so, then how should I list revisions here? In #188 I've proposed to show here (Contents tab) only the number of revisions for each page in the list instead of all revision links.
For example, instead of this (like it shows in Versions tab):
```
Page 1 .... view revision 5
Page 1 .... view revision 4
Page 1 .... view revision 3
Page 1 .... view revision 2
Page 1 .... view revision 1
Page 2 .... view revision 3
Page 2 .... view revision 2
Page 2 .... view revision 1
```
I suggest to show:
```
Page 1 ... 5 revisions
Page 2 ... 3 revisions
```
Where `5 revisions` and `3 revisions` are links to Page Versions where all these revisions are listed.

**Comment by benwbrum** [comment]
I disagree.  The Table of Contents page is meant to show the overall structure of a document to a reader, with only the small side-effect of inviting them to transcribe or index if the page needs it.  It's not intended to be a detailed exploration of the status of each page, nor a roll-up of an activity stream.

The goal is something closer to
```
Page 1
Page 2
Page 3
```

For works that have meaningful titles--ones edited by transcribers or filled in via OCR, the listings may look like

```
Dedication
January 1-3
January 4-6
January 7-9
```

Eventually we will add chapters and sections, so that the contents page will look more like a treeview:

```
Introduction
January
February
   January 31-February 2
   February 3-5
   February 6-8
    ...
March
```

If you'd like, I can find some good examples of contents pages for more complex digital editions.

**Comment by kolking** [comment]
Ok, no problem. Let's summarize then:

**1) Contents Tab**
Remove revision count from the grid. Later we'll implement here grouping by chapters and sections.


**2) Versions Tab**
This is for #188. The grid should be restyled, pagination should be added. There is still a question for me - how would you like to display revision info in the Versions tab:

a) List all page revisions for every page:
```
Page 1 .... view revision 5
Page 1 .... view revision 4
Page 1 .... view revision 3
Page 1 .... view revision 2
Page 1 .... view revision 1
Page 2 .... view revision 3
Page 2 .... view revision 2
Page 2 .... view revision 1
```

b) Show number of revisions (like in the Contents tab now):
```
Page 1 ... 5 revisions
Page 2 ... 3 revisions
```

**Comment by kolking** [comment]
The revision information has been removed. I've decided to show here the number of page notes, I think this information could be useful to see "most commented" pages in the list. Also I've added small icon in front of page title, this will help to visually distinguish pages from chapters and sections later.

**Comment by benwbrum** [comment]
Thanks.  That gets to the goal of the story, and I look forward to
reviewing it.

**Comment by benwbrum** [comment]
Reviewed -- it looks really good
