### ISSUE TITLE
Restyle Work section: Versions tab

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#188]

**Comment by kolking** [comment]
This page could be (and will be) very long and very slow. Even on a local machine the loading time is about 20 seconds. Do we really need to display here direct links to **all versions** for **every page** in a work? I think these links are redundant and because of the page size it makes even harder to find a certain page in this huge list.
I suggest the following: let's show just one link for every page with the number of page revisions and this link will open the version compare for the selected page. This will work much faster, we can include the versions link in the list of pages (Contents tab) like this:

![image](https://cloud.githubusercontent.com/assets/4656448/8865933/0c89fae2-31bf-11e5-921e-51f210e04cec.png)

If you agree then we don't need a separate Versions tab and it can be removed. Please let me know your thoughts.

**Comment by benwbrum** [comment]
You're quite right here, and while I do think it important to allow access to all changes to a work, the list should be paginated instead of displayed on a single page..

If you've worked with a pagination libarary here (like in the read_work tab for a work), and can do the work, please do.  Otherwise I can look at it.

**Comment by kolking** [comment]
Ben, sorry, I didn't quite understand. Are you agree to show page revisions count (link to versions compare) like on the screenshot above? And remove Versions tab in that case?

**Comment by benwbrum** [comment]
Okay, I now understand the confusion.  This issue tracks the "work versions" tab restyling, not the "work contents" tab.  The work versions tab needs to be styled, and needs pagination.  (See screenshot)
![work_versions_screenshot](https://cloud.githubusercontent.com/assets/199961/9065145/95b8a2c6-3a95-11e5-8edd-be3365457657.jpg)

By contrast, the page you're talking about is the work contents page, which is tracked in issue #186.  I agree with you, and will add my comments there.

**Comment by kolking** [comment]
With pagination the page loads fast now. Also I've combined both of my previous ideas - by default we show the number of revisions for every page and date of the current page version in the grid. User can click on the number and see drop down with the list of all revisions, so it's possible to go straight to a selected revision compare from this page.

![image](https://cloud.githubusercontent.com/assets/4656448/9187466/97d5b096-3fd9-11e5-8d96-7172210212ce.png)

**Comment by benwbrum** [comment]
One revision -- the versions tab should be organized by most recent
edit--indeed most recent page version--not rolled up by page.  The goal of
the versions tab is much more like that of an activity stream -- show all
changes made to pages within a document, with the expectation that users
will want to see the changes edit-by-edit, rather than aggregated by some
other unit.

**Comment by kolking** [comment]
Pages in the list are now sorted by the most recent version date.

**Comment by benwbrum** [comment]
We're still off from what I'm looking for.  I want this to be a list of each edit made to pages within the work, not collapsed by page. 

For example, take a work that has pages A, B, and C.

* User Foo edits A, then B
* User Bar edits C
* User Foo edits C
* User Quux edits B

In that case, we'd want every edit displayed, about like so:

* B (edited by Quux on [date])
* C (edited by Foo on [date])
* C (edited by Bar on [date])
* B (edited by Foo on [date])
* A (edited by Foo on [date])

Note that the two edits for B and C are repeated, not rolled up to the most recent version.

Does that make sense?   The goal is to present every single thing that happened within a document and allow people to navigate directly to those changes; not to present each page -- in this way the work version screen is more akin to a log than to a watchlist.

**Comment by kolking** [comment]
@benwbrum please check it now, sorry that I have misunderstood you previously.
