### ISSUE TITLE
Uploaded page images do not appear [regression]

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1886]
Some images that have been manually uploaded do not appear to transcribers, as in https://fromthepage.com/phillipsacademyarchives/head-of-school-stearns-correspondence-chinese-students/folder-5037-alfred-and-helen-tsai/display/1385997

Looking in the database, the `base_image` attribute that is supposed to store the path to the image on the filesystem instead has some Ruby object:
```
2.7.1 :011 > page = Page.find 1385997 # broken image
2.7.1 :012 > page.base_image
 => "#<ActionDispatch::Http::UploadedFile:0x00000000092c9ff8>" 
2.7.1 :013 > page = Page.find 1383997 # working image
2.7.1 :014 > page.base_image
 => "/home/fromthepage/deployment/releases/20200727195214/public/images/uploaded/41437/page_0608.jpg" 
```

We'd like to attempt to reproduce this by creating an empty work, clicking the "Pages" tab, then uploading individual pages.

**Comment by saracarl** [comment]
3 customers have reported this.

**Comment by benwbrum** [comment]
To reproduce, navigate to a work you own, then click the "Pages" tab and add a page.  The file you upload should appear but doesn't.

**Comment by benwbrum** [comment]
After this code is deployed to production, we should clean up old DB records via this:
`Page.where("base_image != '' AND base_image NOT LIKE '/%'").update_
all(:base_image => '')`

(I don't think this is big enough to warrant a migration.)
