### ISSUE TITLE
work_count not interpolated in "restrict completed works" setting [regression]

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1927]
```
This button will restrict the #{work_count} works that are completed but not currently resticted to project owners or designated collaborators. You may change this setting and add collaborators in each work's settings page.
```

Restricted is also misspelled!

**Comment by saracarl** [comment]
You'll need to find the string in the messages files.  It's probably missing the work count in the string.  Make sure to change it in all 3 language dictionaries  -- english, portuguese and spanish.

**Comment by isabelabarton** [comment]
https://github.com/benwbrum/fromthepage/blob/6c770fdb98d05b695f3275e7edf084877a51b90d/config/locales/collection/collection-en.yml#L90

https://github.com/benwbrum/fromthepage/blob/6c770fdb98d05b695f3275e7edf084877a51b90d/app/views/collection/edit.html.slim#L184

would it be a change in one of these files?

**Comment by isabelabarton** [comment]
@saracarl I've found all of the messages files for english, portuguese, and spanish and in those files the only one that has a line similar to the one you listed above is the english one. 
https://github.com/benwbrum/fromthepage/blob/6c770fdb98d05b695f3275e7edf084877a51b90d/config/locales/collection/collection-en.yml#L90

**Comment by benwbrum** [comment]
Fixed.
