### ISSUE TITLE
Versions tab causes exception if no subject description

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#196]
See Mabel Brumfield for example

**Comment by kolking** [comment]
Yes, I can reproduce that bug. Unfortunately, description absence is not a reason for the error, for example this article has no description but the versions tab is ok - http://beta.fromthepage.com/article_version/list?article_id=8
The error occurs for subjects that does not have a corresponding entries in the `article_versions` database table. I believe it's wrong. I mean that every subject must have at least one version.

Also I've noted the following. When I create a new subject (by adding [[something]] in a page transcription), new entry will be added into `article` but no `article_version` created. Now, if I go to this newly created subject's Edit page and simply click Save Changes (without writing a description) - then `article_version` will be created.

@benwbrum I've checked the article model and there is `after_save :create_version` callback:
```
def create_version
  if !@text_dirty or !@title_dirty
    return
  end
  ...
  create version, etc
```
I believe that something wrong with this condition, so it returns without creating a version for a new subject. Could you please take a look and fix that?

**Comment by benwbrum** [comment]
I'll take it.

**Comment by saracarl** [comment]
Is this the same as this exception?:

D, [2016-11-30T00:44:07.157947 #16869] DEBUG -- :   ESC[1mESC[36mPageBlock Load 
(0.6ms)ESC[0m  ESC[1mSELECT `page_blocks`.* FROM `page_blocks`  WHERE `page_bloc
ks`.`controller` = 'article_version' AND `page_blocks`.`view` = 'list'ESC[0m
I, [2016-11-30T00:44:07.158809 #16869]  INFO -- : Completed 500 Internal Server Error in 253ms
F, [2016-11-30T00:44:07.161038 #16869] FATAL -- : 
NoMethodError (undefined method `article_versions' for nil:NilClass):
  app/controllers/article_version_controller.rb:6:in `set_versions'

I suspect so.  @tbl73 would you investigate, please?

**Comment by saracarl** [comment]
change line 140
https://github.com/benwbrum/fromthepage/blob/master/app/models/article.rb#L140
to use the rails way (dirty?  attributes_changed?  dirty_attributes -- something like that.  Ask the model what attributes changed, then check and see if text or title changed....)

Also get rid of all the title_dirty manual references from article.rb.

**Comment by tbl73** [comment]
The if statement in that blob was causing the function to return if either the title or text had not changed.  Since when the article is created via brackets in the text, there is no text, that was always evaluating to true and returning without creating the version.  I rewrote the if statement as an unless, and it looks like it's working now.  I'm also switching it to the rails .changed? method so that we aren't doing it manually, but that doesn't seem to be the reason it wasn't creating that initial version.

**Comment by saracarl** [comment]
verified.
