### ISSUE TITLE
Navigate from Document Set to Collection

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#1983]
If a user is working on a document within a document set, and if they have access to the document set's parent collection, they still have no way to navigate to that collection without starting at FindAProject page.

Implementation:
Analyze possible locations for a link to the parent collection.  (I'd favor the line above the current Document Set - Work - Page header which serves as a breadcrumb, but in a smaller font.)  Add the parent collection link, provided that the current user can see the collection.

Testing:
Test on projects that have a private collections and public document sets (like LVA's WWI questionnaires), as well as projects that have public collections and sets, and projects that have no sets.

**Comment by ThomBurns** [comment]
This would be wonderful! Love this idea.
