### ISSUE TITLE
Transcribe page: add ability to edit titles

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#199]

**Comment by kolking** [comment]
@saracarl it's possible to edit titles on the transcribe page, but this option could be restricted in the work settings:

![image](https://cloud.githubusercontent.com/assets/4656448/9265033/0be38f04-4236-11e5-923e-aca16f32baf6.png)

When the option is allowed, the transcribe editor will show the title edit field:

![image](https://cloud.githubusercontent.com/assets/4656448/9265058/93213016-4236-11e5-8c82-d523f97c5b46.png)

**Comment by saracarl** [comment]
What is the right thing to do here?  @benwbrum

**Comment by benwbrum** [comment]
Looks like this works fine.  Closing.

**Comment by saracarl** [comment]
I think this only works if you are the owner of the work -- I can't do it, even if I'm logged in.  Suspect that's how we want it to work, though.
