### ISSUE TITLE
dashboard links shows up even if not logged in [regression]

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1998]
The "dashboard" link in the navigation at the top of the application shows up even if you are not logged in.  It shouldn't, and didn't before rails6 (I think).

**Comment by saracarl** [comment]
@benwbrum and I are arguing over whether it was visible in rails4 before the upgrade, but either way we agree that it shouldn't be.

**Comment by benwbrum** [comment]
Closed by #2022
