### ISSUE TITLE
Pages without images handled gracelessly

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#20]
Currently the system allows users to create works and associate images for only a few of their pages.  This can lead to exceptions being thrown, for example 
    ActionView::TemplateError (private method `sub' called for nil:NilClass) on line #23 of app/views/shared/_zoom_div.rhtml
or
    ActionView::TemplateError (private method`sub' called for nil:NilClass) on line #34 of app/views/display/_multi_page.rhtml

We should do something other than barf if we're missing images for a page.

**Comment by tbl73** [comment]
It appears that this has been fixed - an error is generated in the logfile if the page doesn't have an image, but the user just sees a missing thumbnail and no exception is thrown.
