### ISSUE TITLE
user alert email issues  [regression]

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2002]
```
We just wanted to let you know that there's been activity in a collection that you worked on.

New Notes
Click here  to view the note on page #{page} in #{collection}: #{work}, which has been added since you worked on it.
```

The "Click here" doesn't work and the pages, collections, and work are not interpolated correctly.

I think we need to go through all the mail templates and check both links and interpolations.  Are they all broken?

**Comment by benwbrum** [comment]
This has been deployed.
