### ISSUE TITLE
Revise page selection icons

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#203]
Based on user testing last week, users had no idea what the icons to select over/under - side-by-side transcription views meant.

We need to reconsider this UI.  At minimum we need onhover text.

**Comment by kolking** [comment]
Not sure I can find a more clear icons here. I though that adding text labels to the options when open will be enough:

![image](https://cloud.githubusercontent.com/assets/4656448/9067109/3d300d84-3ae4-11e5-9f14-2404b507ffaa.png)

Maybe I include the text label for the currently selected state? Will that make it more clear?

**Comment by benwbrum** [comment]
That sounds perfect -- they trouble was that they didn't know to click on
the striped-square icon in the first place.
