### ISSUE TITLE
Too many possible subject duplicates in list.

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2030]
The list of duplicates is so long that it's nearly useless, and is causing performance problems for some sites.

See, for example, https://fromthepage.com/sma-archives/city-of-seattle-records/article/54057 which lists nearly 10K duplicates and performs a SQL query for each of them.

**Comment by saracarl** [comment]
We ran into this again watching CWRGM work with their subjects.  They have a very large corpus with lots of subjects, and it causes the subject pages to load *very* slowly.
