### ISSUE TITLE
After note is saved, transcription save says it isn't

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2043]
> I have noticed that if I put a Note in while I am transcribing – I have a tendency to have to edit it with additional info. 
> 
> When I edit it and save it and then try to move on – the program gives me the message that I have not “saved” the note – although I did.
> 
> So what I have to do is copy the note, delete it and then add it back in as if it was a new note -- and then it allows me to save it properly.

**Comment by benwbrum** [comment]
To reproduce
* Click on the Transcribe tab
* Add a note to the page
* Save the note
* Edit the same note
* hit Update to save the note
* Edit the text of the transcript
* hit Save
