### ISSUE TITLE
Hide defunct collections

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#205]
Some collections were created as test collections -- these should be hidden from the main listing.

**Comment by saracarl** [comment]
or maybe just delete them?

**Comment by saracarl** [comment]
I think we should filter out any collection that hasn't been worked on in X time frame (1 year, for example) in the collection list and the dashboard.

**Comment by saracarl** [comment]
if not worked in a year, don't show it in the dashboard.
