### ISSUE TITLE
new collaborators/joined wrong on private collection

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2078]
This email showed a "join" and recent activity by the same person on the wrong collection.  

> Recent activity on your Fromthepage project
> You have new collaborators!
> crobson@oeb.harvard.edu
> You may consider sending them a How to write a welcome email a short note welcoming them to your project.
> 
> Other Recent Activity in Your Collections:
> Samuel Latham Mitchill Papers, 1801-1809
> crobson JoinedSamuel Latham Mitchill Papers, 1801-1809

https://fromthepage.com/harvardlibrary/stephen-elliott-1771-1830-papers  <-- this is a public document set
https://fromthepage.com/wlcl/mitchill <-- this is a collection with the same ID

**Comment by benwbrum** [comment]
This is a document set/collection confusion issue:
2.7.1 :006 > DocumentSet.find 'stephen-elliott-1771-1830-papers'
 => #<DocumentSet id: 781, is_public: true, owner_user_id: 217372, collection_id: 739, title: "Stephen Elliott papers", description: "<p>The Stephen Elliott papers consist of manuscrip...", picture: nil, created_at: "2020-06-07 23:01:06", updated_at: "2020-09-21 13:29:17", slug: "stephen-elliott-1771-1830-papers", pct_completed: 48, default_orientation: nil, works_count: 68, next_untranscribed_page_id: nil> 
2.7.1 :007 > Collection.find(781)
 => #<Collection id: 781, title: "Samuel Latham Mitchill Papers, 1801-1829", owner_user_id: 216190, created_on: "2020-04-24 15:35:45", intro_block: "The Samuel Latham Mitchill Papers consist of 522 l...", footer_block: "<h2>William L. Clements Library Transcription Proj...", restricted: true, picture: "Screen_Shot_2020-04-24_at_4.08.24_PM.png", supports_document_sets: false, subjects_disabled: true, transcription_conventions: "<p><b>Transcription Conventions</b>\r\n<ul>\r\n<li><i>...", slug: "mitchill", review_workflow: true, hide_completed: true, help: "<p>The <a href=\"https://quod.lib.umich.edu/m/mitch...", link_help: "<h2>Linking Subjects</h2>\r\n<p> To create a link wi...", field_based: false, voice_recognition: false, language: nil, text_language: "eng", license_key: nil, pct_completed: 16, default_orientation: "ltr", is_active: true, works_count: 521, next_untranscribed_page_id: 1152445, api_access: false>

**Comment by saracarl** [comment]
How we determine collection joined:
 https://github.com/benwbrum/fromthepage/blob/6c770fdb98d05b695f3275e7edf084877a51b90d/app/controllers/registrations_controller.rb#L101

**Comment by saracarl** [comment]
Resolved.  PR #2140
