### ISSUE TITLE
"new collaborators" in nightly emails missing contributors

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2088]
From a customer:

> I think I'm not being notified of new collaborators for our three new transcription projects:
> 
>  
> 
> ·       Colorado Agricultural Experiment Station Director’s Correspondence, 1896 to 1912 
> 
> ·       Select journals dated 1918 to 1922 of Llewellyn A. Moorhouse, an agricultural economist and professor 
> 
> ·       State Board of Agriculture Letters, 1883 to 1905
> 
>  
> 
> I definitely don't remember sending our welcome email to all of the people who signed up. Is there any way you can check to see if the daily notification emails are working correctly?

This may be a document set vs collection issue.  The collection IDs are 991, 1015, and 1011

**Comment by benwbrum** [comment]
Related to #2078 ?

**Comment by saracarl** [comment]
might be fixed.  to be tested after we deploy on Monday.

**Comment by saracarl** [comment]
We did test this, it can be closed.
