### ISSUE TITLE
Pages needing indexing shows pages with linked subjects

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2097]
> Hi, I noticed that there are a few pages that show up in the Pages that need to be indexed view. Even though they are indexed.
> https://www.fromthepage.com/mountauburncemetery/mount-auburn-cemetery-letterpress-copying-books/33519?needs_review=index

In the above example CB01_0136_1 and CB01_0137_1 both shouldn't be showing up.

Theory:  Could it be subjects that are indexed for the second time on a different page rather than the first?

**Comment by benwbrum** [comment]
I can't duplicate this.
