### ISSUE TITLE
unflag potential abuse/spam in db if owned by the collection owner.

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2108]
@diegoviola would you write a migration to "unflag" potential spam that was added by the collection owner.

This is remediation to fix existing identified spam; new spam is checked in
https://github.com/benwbrum/fromthepage/pull/1841

**Comment by benwbrum** [comment]
This does not seem to be an issue, as the flagger code checks for content created by project owners and does not flag it.
