### ISSUE TITLE
Add more metadata fields to work settings

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2118]
We need to make a number of changes to the work settings tab.  (See https://fromthepage.com/benwbrum/ben-s-test-collection/bungalow-magazine-v-2-no-6-jun-1913/edit for an example)

1)  Move "Transcription Conventions" and "Translation Instructions" to right below "Description"

2)  Please add the following fields below "Translation Instructions" and above "Physical Description"
https://fromthepage.com/benwbrum/ben-s-test-collection/bungalow-magazine-v-2-no-6-jun-1913/edit  
Genre
Date
Place of Creation
Source Location
Source Collection Name
Source Box/Folder
In/Out of Scope
Editorial Notes
The first 7 should be text fields (single lines) the last (Editorial Notes) should be a text box (multi-line)

**Comment by benwbrum** [comment]
This is completed.
