### ISSUE TITLE
I18N Fixes

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2123]
Attached is a PDF with screenshots showing missed internationalized messages and their accompanying translation into Portuguese.  

Please copy and paste the Portuguese into message files.  For the equivalent Spanish messages please mark them with a "#needs translation" comment in the message files and our collaborators at UT will translate them.
[Traduções de FromThePage.pdf](https://github.com/benwbrum/fromthepage/files/5424902/Traducoes.de.FromThePage.pdf)

**Comment by saracarl** [comment]
Model content in DB:  https://guides.rubyonrails.org/i18n.html#translating-model-content
https://github.com/barsoom/traco
https://github.com/globalize/globalize
https://dejimata.com/2017/3/3/translating-with-mobility

**Comment by benwbrum** [comment]
This has been close by MT work associated with #3165
