### ISSUE TITLE
Quality Control

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2129]
This feature requires the “reviewer role” feature in #2128 , as it will extend the user interface developed for that feature.
Review of transcriptions for quality can be a time-consuming process.  Maryland State Archives, for instance, asked a group of staff members to commit 2 hours a day to reviewing volunteer transcriptions.  Some other state archives, like Alabama, use an informal sampling approach to identify transcribers that produce dependable transcriptions and need less review and transcribers who might make more mistakes or produce a pattern of mistakes.This feature will add a sampling-based review process to the software to focus staff effort on material or users that need the closest scrutiny.
In the first phase of the review process, the application will take a random sampling of pages representing a small but meaningful percentage (e.g. 3%) of the collection and a broad range of transcribers. These pages would be enqueued for a special review process. A set of reviewers would review and correct or approve those pages. The outputs of this phase will be a handful of corrected or approved pages and a more thorough understanding of patterns within the contributions, since the pages which required correction indicate areas for closer review.
In the second phase of the new process, the reviewer dashboard will display “stacks” representing contributions to a work by a particular user, along with statistics representing the percentage of pages reviewed and the accuracy rate of the pages reviewed so far.  For each stack, a reviewer can approve all pages, review all pages, or review a larger random sampling of pages from the stack.  Approving or correcting pages within a stack will update the statistics for the stack, providing further insight into the accuracy of those contributions.   
This review process will be tracked in batches so that once a batch has been through the process the review will not need to be repeated.

**Comment by saracarl** [comment]
https://docs.google.com/presentation/d/1ezWUS1ejXyNuz13CV0Yfa5nz6wr7X5e9UFrw21ZDypA/edit?usp=sharing

**Comment by saracarl** [comment]
look at #1749

**Comment by benwbrum** [comment]
We have done some substantial statistical analysis and found that for both users and works, a sampling of `5` pages provides the best indicator of the average quality of the contributions.
