### ISSUE TITLE
TEI Export for CWG-K Workflow

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2130]
Prerequisites:
* When a user reviews a page (unchecks the 'needs review' box), we should log a new `reviewed` deed.
* New metadata fields per work for CWG-K should be added

# TEI Export Review Results

* The `corresp` attribute in the `p` element should not appear if translation is not enabled for the work.  _Priority:_ *low*
* Paragraphs include `lb` elements because users have pressed carriage return between lines.  KY to change the transcription conventions to make the desired behavior explicit.
* `respStmt` is within `titleStmt` in CWG-K, nested within `editionStmt` in FromThePage.  This is not consumed down-stream, so let's leave it there.
* `respStmt` contents: add `n="transcriber"` or `n="reviewer` for person reviewing.  Add something similar for Double Proofed for the person exporting the document, at the time of export.  _Priority:_ *high*
* `profileDesc` is populated by the new metadata fields we are building -- look at CWG-K for an example of how the export should look _Priority:_ *high*
* `msIdentifier` may be populated by the new metadata fields we are building -- look at theirs for how the export should look _Priority:_ *high*
* revisionDesc is irrelevant to CWGK; ignore it for now, if tests break remove it.  (Most other projects hate this element) _Priority:_ *low*
* `pb` is used by other projects and somewhat used by CWGK.  To test and see how it looks in the Omeka site
* `fw` is not used by CWK.  Stylesheet should be modified to suppress display in Omeka if needed.

**Comment by benwbrum** [comment]
This depends on #2120

**Comment by saracarl** [comment]
What's left:

- Reviewer deeds
- reviewer resp in TEI
- exporter as double-proofer in TEI
