### ISSUE TITLE
Subject Search results order not consistent

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2188]
If you click on the "search unlinked pages" in the subject view, the pages that are returned, even within one work, are not in a logical order.  For instance, searching "Abram Crews" in Jeremiah White Graves, here: http://localhost:3000/benwbrum/jeremiah-white-graves-diaries/article/70066 I get a May page, a December page, and then another May page.

**Comment by benwbrum** [comment]
Folded into #2533
