### ISSUE TITLE
codemirror popup

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2197]
This page:
https://www.mediawiki.org/wiki/Extension:CodeMirror

Implies that wikipedia uses CodeMirror for editing (see the screenshots in particular). 

If it is, then an edit page, like this one:
https://en.wikipedia.org/w/index.php?title=Pride_and_Prejudice&action=edit

which has popups for links and files, might be a good place to start for popups in our TEI XML editor.

**Comment by benwbrum** [comment]
This is an implementation suggestion, not a feature description.
