### ISSUE TITLE
Leaderboard for last 7 days

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#220]
This should be prominent, while the over-all leaderboard should be harder to get to.

**Comment by saracarl** [comment]
If we can define what this looks like and where it goes, Nick can implement.

**Comment by tbl73** [comment]
@saracarl - is this taken care of with the leaderboard on the statistics page?

**Comment by saracarl** [comment]
that's a "overall" leaderboard.  This idea was a "week" leaderboard.  call it a feature.

**Comment by benwbrum** [comment]
We are philosophically opposed to increasing competition between transcribers, so this isn't a direction we'd like to go in.
