### ISSUE TITLE
On-site SEO: All pages should contain relevant to content meta tags

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#224]

**Comment by saracarl** [comment]
So individual transcription pages have the same meta description tags as higher level pages in from the page.  We're thinking we should pull (a subset of?) the collection title + work title + work description into an individual page's meta description tag. 

In other words, we want to highlight the *work* rather than from the page in that tag.

Make sense?

**Comment by kolking** [comment]
@saracarl right now individual pages meta information consists of the following:
```
TITLE: <page_title> (<collection_title>, <work_title>) | FromThePage
DESCRIPTION: <page_title> (<collection_title>, <work_title>) - page <active_tab>. <page_content_snippet>
```
For example, this page http://localhost:3000/display/display_page?page_id=378 will have:
```
<title>Wednesday, January 2, 1918 (Julia Brumfield Diaries, 1918) | FromThePage</title>
<meta name="description" content="Wednesday, January 2, 1918 (Julia Brumfield Diaries, 1918) - page overview. A colde snowy day. Has snowed nearly all day. We all set around the fire most of the day. I milked and churned and fed the chickens. Josie...">
```
Is it okay?

**Comment by saracarl** [comment]
Which branch?  It's not what I saw last night, but I may have been looking
at the wrong thing.

Sara

**Comment by kolking** [comment]
@saracarl you had probably viewed 'ui-design' branch, but these changes were initially implemented in the 'uploader' branch. Anyway, I've already merged 'uploader' into the 'ui-design', so you should re-check it in the 'ui-design' now.

**Comment by benwbrum** [comment]
ui-design was exactly the branch we were looking at.

**Comment by kolking** [comment]
@benwbrum most likely it wasn't merged yet when you were checking it. Right now it should contain all the latest changes.
