### ISSUE TITLE
Riiif image service broken if filenames contain a space

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2271]
A customer (William Woodruff project) reports:

> Hi there, I am working with your IIIF API and I've noticed that several of the URLS for images in the project I'm working on are returning a 500 error.
> Here is one example: https://fromthepage.com/image-service/1580519/full/full/0/default.jpg
> and it's coming from this manifest: https://fromthepage.com/iiif/48048/manifest
> Thanks in advance for your help!

**Comment by saracarl** [comment]
Error from logs:

```
I, [2021-01-14T14:35:41.392110 #19988]  INFO -- : Completed 500  in 39ms (ActiveRecord: 3.5ms | Allocations: 6311)
F, [2021-01-14T14:35:41.402293 #19988] FATAL -- :   
Riiif::ConversionError (Unable to execute command "identify -format '%h %w %m %[channels]' /home/fromthepage/deployment/releases/20210112155212/public//images/uploaded/48048/Letter-1879-10-16-D-p4-WW to N
ellie.jpg[0]"
identify: unable to open image `/home/fromthepage/deployment/releases/20210112155212/public//images/uploaded/48048/Letter-1879-10-16-D-p4-WW': No such file or directory @ error/blob.c/OpenBlob/2712.
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
identify: unable to open image `to': No such file or directory @ error/blob.c/OpenBlob/2712.
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
identify: unable to open image `Nellie.jpg': No such file or directory @ error/blob.c/OpenBlob/2712.
):
```

**Comment by saracarl** [comment]
This seems to be a problem with spaces in the filenames.  The full filename is:
`Letter-1879-10-16-D-p4-WW to Nellie.jpg `
which is passed to the command, but the error says:
`unable to open image ``/home/fromthepage/deployment/releases/20210112155212/public//images/uploaded/48048/Letter-1879-10-16-D-p4-WW': No such file or directory`

**Comment by saracarl** [comment]
Fix this somewhere around here:  https://github.com/benwbrum/fromthepage/blob/main/lib/iiif/from_the_page_file_resolver.rb#L17

**Comment by benwbrum** [comment]
A second problem here is that--while Riiif is using `FromThePageFileResolver` under Apache/Passenger--our development environments do not use that resolver, instead using the default resolver.  As a result, we can't fix this in development until our Riiif initializer works again.

**Comment by benwbrum** [comment]
See https://github.com/curationexperts/riiif/issues/119 on the second issue.
