### ISSUE TITLE
UI for "Export All Works" screen

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2288]
In the 1449-bulk-export branch, please style (restyle?)
app/views/bulk_export/new

It's in progress code, so it's pretty rough!

https://github.com/benwbrum/fromthepage/tree/1449-bulk-export

**Comment by kolking** [comment]
@saracarl wrote:

> Ignore the first/old button -- or remove it!

![image](https://user-images.githubusercontent.com/4656448/105410705-cefe3180-5c4b-11eb-8206-0e0650c00ccc.png)
