### ISSUE TITLE
work and collection slug validation -- require a string

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2328]
Folks are using numbers for slugs (i.e. 1895) and this will or does cause problems.  Let's add a validation that requires slugs to include at least one letter.

**Comment by sylvieed** [comment]
Is the input for the slug the "URL" input on the [collection settings page](https://fromthepage.com/benwbrum/ben-s-test-collection/edit)?

![slug input](https://user-images.githubusercontent.com/35716893/150711213-5d36f872-0f11-468c-a0a5-1f14046c7ab7.jpg)

**Comment by benwbrum** [comment]
Yes, that's the slug input.  (We don't expect our users to know what a slug is ... or at least we didn't when we wrote this.)

**Comment by sylvieed** [comment]
The slug/URL input's value is stored as `@collection.slug` in [the page's view](https://github.com/benwbrum/fromthepage/blob/main/app/views/collection/edit.html.slim#L12). 

To add validation for this value, we can add the following to [line 33 of the collection model](https://github.com/benwbrum/fromthepage/blob/main/app/models/collection.rb#L33).

```
validates :slug, format: { with: [/a-zA-Z/] , message: "#{t('.slug_include_letter')}" }
```

The `@collection.title` validation also needs to be updated with an error message. We'd change [line 32 of the collection model](https://github.com/benwbrum/fromthepage/blob/main/app/models/collection.rb#L32) to:

```
validates :title, presence: true, length: { minimum: 3, maximum: 255, too_short: "#{t('.title_too_short')}", too_long: "#{t('.title_too_long')}" }
```

Wording would be need to be added to the [collection translation files](https://github.com/benwbrum/fromthepage/tree/main/config/locales/collection); in the [English one](https://github.com/benwbrum/fromthepage/blob/main/config/locales/collection/collection.en.yml#L69) after line 69 we can add:

```
title_too_short: "The title must be at least 3 characters long."
title_too_long: "The title cannot be more than 255 characters long."
slug_include_letter: "Please include at least one letter in the URL."
```

To let the user know what's wrong with their input, an error message should be shown below the URL input. Something like the following lines can be added to the [view](https://github.com/benwbrum/fromthepage/blob/main/app/views/collection/edit.html.slim#L16) after line 16.

```
@collection.errors.full_messages.each do |msg|
  tr
    th.hidden URL
  td
    p.nomargin.error =msg
```

This accounts for the case where there is an error in both the Title and URL fields.

Finally, styling should be added for error messages. After [line 403 of the collection stylesheet](https://github.com/benwbrum/fromthepage/blob/main/app/assets/stylesheets/sections/collection.scss#L403), add:

```
.error {
  color: $fgRed;
}
```

**Comment by benwbrum** [comment]
Do we really never display validation errors on the collection settings screen?  I'm kind of astonished (though I confess I don't remember the last time I saw one).

Does this line handle at least some of the validation display for us?
https://github.com/benwbrum/fromthepage/blob/main/app/views/collection/edit.html.slim#L5

**Comment by sylvieed** [comment]
We should use `[:alpha:]` instead of `[/a-zA-Z/]` for the regex expression validating the presence of a character.

[POSIX ](https://en.wikibooks.org/wiki/Regular_Expressions/POSIX-Extended_Regular_Expressions)

**Comment by saracarl** [comment]
This wasn't actually implemented (and we just ran into a customer problem with a numeric slug) -- just Ben's fix for the error.  @sylvieed please put it back on your list.  Also make sure to test with *work* slugs as well as *collection* slugs -- I suspect we'll need to do the validation in two places.
