### ISSUE TITLE
Ledger style transcription

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2343]
> In addition to the current full-text transcription/OCR correction mode, the one-record-per-page code funded by CoSA, and the many-pages-per-record enhancements contributed by LVA, we propose to add support for multiple records per page.  Since many of the tabular documents you shared with us include additional, non-ledger fields at the top or bottom of the page--e.g. county/registrar for a voter list or regiment/unit/commander for a muster roll-- we are integrating the spreadsheet data entry into the field-based transcription system.

> The field configuration screen will allow project owners to add a spreadsheet control for a project, and to configure the columns of the spreadsheet for data type, controlled vocabulary, and width.  Configuring a spreadsheet column will be almost identical to configuring a field in the current system -- "line" and "page" will not apply, but the other options are likely to be the same.  Projects will be able to mix one (and only one) spreadsheet control with regular fields above or below the spreadsheet in order to support fixed header or footer fields. 
> 
> Transcribers will see a web control similar to a spreadsheet on their transcription screen.  Any non-spreadsheet fields will appear above (or below) the spreadsheet.  Drop-downs will appear for controlled vocabularies.  (See attached mock-up.)
> 
> Transcripts will be displayed as HTML tables, which will also be embedded in the full-text export formats.  The table export will export one row per spreadsheet entry (with existing links to the page URL, page and work titles, and imported metadata), and any header or footer fields will be added as additional columns onto the rows from the page they were transcribed from.
> 
> 
> Mock-up of spreadsheet control below header fields for 19th-c Welsh census forms
> 
> Image-Spreadsheet Linking
> It is very easy for the human eye to skip from the first half of one line to the second half of another--or to miss lines entirely--while transcribing, and it requires extra effort to avoid this problem, which can slow down or frustrate volunteers.  We think that highlighting the line a volunteer is transcribing will improve transcriber productivity and enjoyment while reducing transcription errors.  For documents that are consistently formatted and which have been consistently imaged, we have designed a system for automatically highlighting (and panning to) the portion of the page image that corresponds to the row a user is transcribing in the spreadsheet control.  (See image above.)  To enable this, the project owner configuring the system will need to specify the location on a representative page at which the first row begins, the location at which the last row ends, and the number of rows on the table.

**Comment by saracarl** [comment]
Release of HandsOnTable that is available under the MIT license:
https://github.com/handsontable/handsontable/releases/tag/6.2.2

**Comment by saracarl** [comment]
Design notes:

> How to store it? can we convert it to a markdown table and put in in text db field?
> I feel like there are really three questions here:  1) How do we store it, 2) how do we display it, and 3) how do we load it for editing again?
> 
> A) text-first persistence: On 1, reading JSON from HoT, converting to markdown, then writing that to the transcription text should mean we don't have to write any special code for saving the data.  For 2, no work would be needed for display, since we already convert from markdown to an internal XML, then to HTML for display.  On 3, it's a bit harder to convert from markdown to JSON to pass to HoT, but we could ignore the markedown in the transcription text and just read the cell data directly from the table_cells table.
> 
> B) cell-first persistence: On 1, reading JSON from HoT, writing data to table cells, then writing something displayable (like an HTML table) to the transcription text also seems straightforward -- the persistence work needed here might be equivalent to the markdown-creation work needed in A.  On 2, we'd need to write displayable data but not process it; since users have been adding HTML tags directly into transcripts, we could just produce a table here.  On 3, we'd read the cell data from the table_cells and ignore the transcription text.

**Comment by benwbrum** [comment]
Progress checklist:

- [ ] Spreadsheet widget displays to user (in sample setting)
- [ ] Spreadsheet widget reads table headings from field config (sample config)
- [ ] Spreadsheet widget reads field data types from field config
- [ ] Spreadsheet widget reads drop-down vocabulary from field config
- [ ] Project owner adds spreadsheet widget to a field-based project
- [ ] Project owner configures fields to appear in spreadsheet (vs header or footer fields)
- [ ] Spreadsheet saves data in fields
- [ ] Spreadsheet loads data from fields when existing page is edited
- [ ] Readers see spreadsheet-entered data displayed correctly in application
- [ ] Spreadsheet is linked to image viewer, so that advancing rows in a spreadsheet moves the viewer forward
- [ ] Image viewer highlights the current row
- [ ] Project owner configures the image highlighting feature by entering number of rows per image, percentage of top and bottom that represents the spreadsheet.
- [ ] Transcriber is able to disable image highlighting/linking in case something goes horribly wrong.
- [ ] In-progress data is auto-saved in a draft state so that user work is not lost.

**Comment by saracarl** [comment]
Mock-Up:
![fromthepage_mockup_spreadsheet](https://user-images.githubusercontent.com/708566/106928336-b32d6d80-66d8-11eb-9e15-f1fba4045a88.png)

**Comment by benwbrum** [comment]
Reading the handsontable [6.2.2 documentation](https://handsontable.com/docs/6.2.2/demo-context-menu.html), it looks like we want these features (and not others):
* Headers
* Row/Column Resize
* Collapsible columns
* Context menu
  * Insert row above `row_above`
  * Insert row below `row_below`
  * Remove row `remove_row`
  * Undo `undo`  (Plug-in `UndoRedo` needs to be enabled)
  * Redo `redo`
  * `cut` (Plug-in `CopyPaste` needs to be turned on)
  * `copy`
  * `hidden_columns_hide` (Plugin `HiddenColumns` needed)
  * `hidden_columns_show`


### Cell Types

#### Desirable
* Standard: text (requires no special configuration)
* Dropdown: In addition we'd like drop-downs in table cells, which is done by passing in a `columns` element to the constructor with`{ type: 'dropdown', source: ['a','b','c'] }`.  This is based on Autocomplete.
* Autocomplete might be useful in other cases.  It has a strict mode, which forces selection from a controlled vocabulary chosen by typing (consider dropdown instead, which is basically the same).  It also has a lazy mode, which can be equivalent to auto-fill: we could populate the options for e.g. "place of birth" with the unique (or most popular) values of that cell from pages other than the one being edited.
* Numeric cell type will right-justify a cell, and highlight it in red if any non-numeric values are typed.
* Checkbox is desirable

#### Excluded
* Time seems useful in very rare cases
* Date is almost certainly not something we want; if needed we should use it without the calendar-based date picker




Consider autofill plugin as well.

**Comment by saracarl** [comment]
Open questions for the steering committee
- should fields with controlled vocabularies (i.e. country or race) use drop downs or autocomplete.  (Show the red cell in drop down if you enter a term that isn't included)
-

**Comment by saracarl** [comment]
Initial UI:

![Screenshot from 2021-02-04 14-47-08](https://user-images.githubusercontent.com/708566/106955277-a4f04900-66fa-11eb-88f2-ee6cc19eb9c0.png)

**Comment by saracarl** [comment]
Sample files from Missouri:
[F48_1850_V1_Adair.pdf](https://github.com/benwbrum/fromthepage/files/5934276/F48_1850_V1_Adair.pdf)
[RG213_MSP_NR_Vol.19_p0006.pdf](https://github.com/benwbrum/fromthepage/files/5934277/RG213_MSP_NR_Vol.19_p0006.pdf)
[StCen_1868_StCharles_v1_001.pdf](https://github.com/benwbrum/fromthepage/files/5934278/StCen_1868_StCharles_v1_001.pdf)

**Comment by benwbrum** [comment]
It will be a substantial effort, but we may be able to dramatically improve performance by addressing #1615 in this work.  If we address that when we are storing data, it _might_ reduce the time to implement data storage.

**Comment by saracarl** [comment]
Sample file from Indiana:
![ISTA_1876](https://user-images.githubusercontent.com/708566/107282726-feb98180-6a20-11eb-9996-ebac22a32326.jpg)

**Comment by saracarl** [comment]
Sample ledger data from North Carolina:
Troop return: https://digital.ncdcr.gov/digital/collection/p16062coll26/id/980
Tax list: https://digital.ncdcr.gov/digital/collection/p16062coll33/id/2339
Muster roll: https://digital.ncdcr.gov/digital/collection/p16062coll10/id/3804
Filled out form: https://digital.ncdcr.gov/digital/collection/p16062coll13/id/10950

**Comment by saracarl** [comment]
Samples from Florida:
[F48_1850_V1_Adair.pdf](https://github.com/benwbrum/fromthepage/files/5972857/F48_1850_V1_Adair.pdf)
[RG213_MSP_NR_Vol.19_p0006.pdf](https://github.com/benwbrum/fromthepage/files/5972858/RG213_MSP_NR_Vol.19_p0006.pdf)
[StCen_1868_StCharles_v1_001.pdf](https://github.com/benwbrum/fromthepage/files/5972859/StCen_1868_StCharles_v1_001.pdf)

**Comment by saracarl** [comment]
Sample files from Library of Virginia:
https://fromthepage.com/lva/african-american-free-registers
![083_1856_027_0268](https://user-images.githubusercontent.com/708566/108231405-59309d00-7107-11eb-970f-723021d4de82.jpg)
![083_1856_027_0272](https://user-images.githubusercontent.com/708566/108231408-59c93380-7107-11eb-900e-18b90d154ede.jpg)

**Comment by saracarl** [comment]
We had a discussion with [Evan Roberts](https://cla.umn.edu/about/directory/profile/eroberts), a demographer (we know him from Measuring the ANZACs) who has spent most of his career transcribing and analyzing spreadsheet style historical data.  Here's my notes from that discussion:

- "Screen Ruler" programs = term for the sort of highlighting we want to do to prevent eye skip.
- Header information on documents is very important; keep with transcriptions
- Pay attention to performance, especially as projects start building up large amounts of data
- He recommends transcribers work with columns rather than rows -- easier to follow and less likely to skip lines
- Columns vs. Rows -- unlike our assumptions that everything would be in rows and this type of transcript would be over/under, if we recommend folks work in columns then side by side makes more sense
- For documents with no ruled lines (i.e. [NC troop returns](https://digital.ncdcr.gov/digital/collection/p16062coll26/id/980)) 
    - you get "drift" down the page as folks write.
    - skipped cells often mean misalignment
    - encourage "across" transcription (rows) rather than columns
- around 1880 you start getting printed lines, not so much before that.
- Many sources have incremental numbers (record 1, record 2, record 3); can we automate that in some way?
- Should we show row numbers in our template?
    - i.e. census records always start at line 1 or line 51
- paragraphs in cells are tricky
- "age" should be a number but sometimes the original writer puts in birthdate
- Evan likes having notes per row -- maybe project could just add a column?
- Is there a way to flag exceptions?
- Ideally you have "select" fields that you can also overwrite
- He sees a lot of "false friend" letters -- folks misspell "Christchurch" and "Philadelphia" a lot

**Comment by saracarl** [comment]
A sample from Texas:

[TDCJ_Escape_Record_page01.pdf](https://github.com/benwbrum/fromthepage/files/6185027/TDCJ_Escape_Record_page01.pdf)

**Comment by saracarl** [comment]
@benwbrum Should we move these to their own issue(s) and close this out?
- [ ] Transcriber is able to disable image highlighting/linking in case something goes horribly wrong.
- [ ] Multiple spreadsheets may be configured per collection
- [ ] In-progress data is auto-saved in a draft state so that user work is not lost.

**Comment by benwbrum** [comment]
This has been deployed for a year; additional work will be tracked in new issues.
