### ISSUE TITLE
br in guest transcription screen

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2348]
Guest transcription screen shows a <br>:

` You may save up to three transcriptions <br> as a guest or sign up now.`

**Comment by IsaacArneson** [comment]
here is where the problem lies

https://github.com/benwbrum/fromthepage/search?q=You+may+save+up+to+three+transcriptions

**Comment by IsaacArneson** [comment]
as seen here

https://www.fromthepage.com/mountauburncemetery/mount-auburn-cemetery-letters/2021-010-001/guest/1797524

**Comment by IsaacArneson** [comment]
reproduction steps

* Log out FromThePage
* Find a page in any project
* Click the Transcribe tab
