### ISSUE TITLE
Advanced editor needs a narrower font

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2357]
At least two different users have complained that the advanced editor uses a wider font than the old textarea, which means they can't type as much in before a line wrap occurs.  See example [here](https://fromthepage.com/fwplarchives/mayor-and-council-proceedings/mcp-1899-0407-pt-2/display/1689562)

**Comment by saracarl** [comment]
A theme might help here:
https://codemirror.net/theme/

**Comment by kolking** [comment]
Yes, I've noticed that CodeMirror uses monospace font by default, which is good for writing code or markdown, but not very good for our case. I'll figure out how to change the editor font back to the proportional one we've used before in the old editor.
