### ISSUE TITLE
onHover help for editor buttons

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2371]
We've added configurable editor buttons to the advanced editor, but would like to give users more help about what the buttons do.  We'd like to add an `onHover` that displays text from `t(".#{button.key}_description")`

**Comment by kolking** [comment]
Are you okay to implement this using standard `title` attributes as the most easiest way to respect accessibility and avoid positioning problems when tooltip goes behind the window viewport? Or do we need something custom and more fancy?
