### ISSUE TITLE
offer statistics about works transcribed

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2384]
> It would be great if FtP could offer statistics on the number of works transcribed in addition to statistics on the number of pages transcribed. Granting agencies typically want statistics based on works rather than pages, so statistics on both would be incredibly useful for tracking our progress.

**Comment by benwbrum** [comment]
This is CWRGM top request of the 3 opened.

**Comment by benwbrum** [comment]
This should be a new item on the `Statistics` tab of the collection, driven from `work_statistic`.

**Comment by benwbrum** [comment]
`WorkStatistic` has a `complete` attribute which is a percentage.  Displaying the count of works in the collection with `complete==100` should work.  (Doing this with a query that is performant might be more challenging)

```
2.7.1 :004 > WorkStatistic.all.to_a.sample(20).map{|w| w.complete}
 => [100, 100, 28, 0, 0, 0, 100, 100, 100, 0, 0, 0, 100, 65, 100, 100, 100, 100, 100, 0] 
```
