### ISSUE TITLE
Organize subjects vertically instead of horizontally

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2385]
> On the subjects pages, subject terms would be easier to read and identify if they were organized alphabetically vertically in the column, rather than horizontally.

**Comment by IsaacArneson** [comment]
Here is where the problem lies

https://www.fromthepage.com/benwbrum/jeremiah-white-graves-diaries/subjects#category-260

**Comment by IsaacArneson** [comment]
https://0ca9c3cc648c4c9da4d1bdfd31006feb.vfs.cloud9.us-west-2.amazonaws.com/benwbrum/jeremiah-white-graves-diaries/subjects#category-260

**Comment by IsaacArneson** [comment]
look in app/views/article/list.html.slim:51
