### ISSUE TITLE
include lat and long on subject export 

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2386]
> This may already exist in the update work you did, but it would be great to also see which subject tags have latitude and longitude information in them. This was I can more easily tell which ones researchers missed. If this is already a feature, please let me know because I’ll start using it right away!

**Comment by benwbrum** [comment]
Currently we export the subject details header [here](https://github.com/benwbrum/fromthepage/blob/fc2575286a46b518ac184391de48742ee1c4c522/lib/subject_details_exporter.rb#L13) and the contents [here](https://github.com/benwbrum/fromthepage/blob/fc2575286a46b518ac184391de48742ee1c4c522/lib/subject_details_exporter.rb#L31)

We need to add code that prints the header columns for latitude and longitude, then fills in the appropriate cells with `subject.latitude` and `subject.longitude`.

**Comment by benwbrum** [comment]
We'll need to add sample data to one of the subjects, like the one for Mount Airy -- adding latitude/longitude (of `36.9429172, -79.1922420` for Mount Airy), then exporting the Subject Details csv should test this out.
