### ISSUE TITLE
document set note list is in reverse order

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2403]
![image](https://user-images.githubusercontent.com/708566/109068783-ecdd0d00-76b5-11eb-93ee-02d51281064c.png)

**Comment by saracarl** [comment]
working version in collections
https://github.com/benwbrum/fromthepage/blob/main/app/models/collection.rb#L11

**Comment by benwbrum** [comment]
Looks like this was fixed, possibly in #2039
