### ISSUE TITLE
Allow transcribers to delete empty subjects they created

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2429]
Bad subjects get created because the linked works have a typo or you don't know about the right canonical subject.  You should be able to delete the subjects if:
1)  you created it
2)  it has nothing linked to it

**Comment by benwbrum** [comment]
We can add "delete" as a button on `article#show` or perhaps on `article#edit`.  We may need to add a `created_by_user_id` field to `articles` if there isn't one already.

**Comment by benwbrum** [comment]
Closed by #3678
