### ISSUE TITLE
make editor buttons "sticky"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2432]
If you have a long page, you have to scroll up to get the mark up buttons.  We should make them stick to the top of the visible window.  (See Wilford Woodruff for examples)

**Comment by benwbrum** [comment]
The feature appears to already be implmented -- if I [edit a long JWG page](http://localhost:3000/benwbrum/jeremiah-white-graves-diaries/jeremiah-white-graves-diary-volume-2-book-14/transcribe/504623), the editor buttons do not scroll off screen.  (Note line numbers)

![Screenshot from 2023-06-02 09-47-38](https://github.com/benwbrum/fromthepage/assets/199961/cf01a519-91e2-49a6-8299-2dc1a4a6e5a1)

Reassigning to @saracarl to verify and close.

**Comment by saracarl** [comment]
verified.
