### ISSUE TITLE
Include metadata with zip export

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2439]
We should include metadata for documents exported in zip format, ideally in several formats.

At minimum, metadata should include
* FromThePage UI-entered metadata
* Uploaded filename (if any)
* Imported metadata (in `work.original_metadata`)
* Any user-created metadata from #2096 

It would probably be best to put this in a `metadata` folder containing files in `.csv`, `.yml`, and `.json` formats.

**Comment by saracarl** [comment]
This is a dupe of #2367

**Comment by benwbrum** [comment]
Work metadata export is now included in the bulk zip export for a collection.
