### ISSUE TITLE
Admin editing user wipes out display name field

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#244]
And maybe another field.  

If you are editing a user as an admin (to make a work owner), when you pull up the user it has blank fields (that I know were filled in at creation time).  If you try to save with them blank, the UI complains.

**Comment by saracarl** [comment]
I'm not sure if this is still an issue, but it might be.

**Comment by tbl73** [comment]
This doesn't seem to be an issue anymore.  Closing.
