### ISSUE TITLE
style an email template

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#245]
We're sending emails (under user mailer) for various tasks.  We'd like them to look & feel like the web UI.

This can be tested in the upload branch -- after an upload the user should receive an email.

Send me an email for mandrill config access if you need it.

**Comment by kolking** [comment]
@saracarl I see the following list of templates (please correct me if I wrong):
1) system_mailer/new_upload
2) system_mailer/upload_succeeded
3) user_mailer/upload_finished

There is also "system_mailer/new_user" template and I have a feeling that we are not using it and it should be deleted.

**Comment by saracarl** [comment]
1-3 yes
4 -- we're not using it "yet", but plan to.  Let's leave it alone.

Thanks!

Sara
