### ISSUE TITLE
UI Fixes for #2343 HandsOnTable spreadsheet

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2456]
We are developing a new user interface that supports tabular data (see #2343 for details) and there are some UI problems with the current state of the code (PR #2347).  

## Administrator side:
When configuring a spreadsheet, the text entry field for the number of rows to be displayed takes up the full width of the screen
![image](https://user-images.githubusercontent.com/708566/112330673-3d7c6180-8c86-11eb-89ac-c44eaa506506.png)

### Form submission
Previously the transcription screen was a simple HTML form which sent its parameters to the controller action to render a response including errors or redirect to the next screen.  To make the spreadsheet UI work, we need to read spreadsheet data from the HandsOnTable javascript object and submit this to the controller action as well as other form input fields.

I took a first attempt at this by adding [a script to read the fields and post them to the server via jQuery](https://github.com/benwbrum/fromthepage/blob/2343-spreadsheet-editor/app/views/transcribe/display_page.html.slim#L172-L196).  The problem with this approach is that it's designed for AJAX requests, and our server returns HTML for the browser to render or a redirect, both of which jQuery ignores.

We should either
* change the script to write the HandsOnTable data value to a form field, then submit normally, or
* change the script to act on the results of the jQuery post (which might require re-writing a lot of the server action), or
* something else.

### Spreadsheet widget resize
When transcribing a spreadsheet, the HandsOnTable component does not expand if the user switches to full screen
![image](https://user-images.githubusercontent.com/708566/112330497-17ef5800-8c86-11eb-9694-b6abe9b36d9a.png)  The component will resize itself if the user starts typing in a wide spreadsheet and their cursor scrolls off the right side of the screen; we should try to call the same resizing function that HandsOnTable uses, but call it from the Fullscreen button
I

**Comment by saracarl** [comment]
You'll want to reproduce this using branch `2343-spreadsheet-editor`, and PR against that branch as well.  There's some test data in issue #2343 -- I recommend the Indiana teacher's ledger; it's the widest and shows a lot of the problems.
