### ISSUE TITLE
Spreadsheet/Ledger UI Wraps typed input

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2464]
Even if a column has been resized to fit text, when a user is typing, the text entry box wraps their input.
![Screenshot from 2021-03-30 08-33-25](https://user-images.githubusercontent.com/199961/112997551-d7cf2000-9132-11eb-9087-20a0c797cec7.png)

Can we make the input field longer than the column width, or at least as long?

cf #2343

**Comment by saracarl** [comment]
Fixed.
