### ISSUE TITLE
Drag and drop field/spreadsheet field order

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2465]
So when I was testing a spreadsheet configuration, I left out the first field on the spreadsheet.  

In order to insert it, I have to 
1) add it to the end of the list of fields
2) Save
3) click the up button
4)  wait for the reload
5) find the field
6)  go to 3
repeat for the number of colums in the spreadsheet, in this case 25.

This is a humongus pain.  Can we do drag and droppable fields?

Once we get it working for spreadsheets, we should also make it work for field based.

**Comment by kolking** [comment]
Yeah, this is definitely something we need to improve 👍
