### ISSUE TITLE
CDM Exports aren't working

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2468]
```
  	Beginning export of work 55911, 'Box 069, folder 15: Roman Burghart' 

Updating p15808coll15	record p15808coll15:4988	from Page 1	1806244	Box 069, folder 15: Roman Burghart.  CONTENTdm response:
Error detail:  Invalid pointer p15808coll specified
..

Updating p15808coll15	record p15808coll15:4989	from Page 2	1806245	Box 069, folder 15: Roman Burghart.  CONTENTdm response:
Error detail:  Invalid pointer p15808coll specified
..

Updating p15808coll15	record p15808coll15:4990	from Page 3	1806246	Box 069, folder 15: Roman Burghart.  CONTENTdm response:
Error detail:  Invalid pointer p15808coll specified
..

Updating p15808coll15	record p15808coll15:4991	from Page 4	1806247	Box 069, folder 15: Roman Burghart.  CONTENTdm response:
Error detail:  Invalid pointer p15808coll specified
..

Updating p15808coll15	record p15808coll15:4992	from Page 5	1806248	Box 069, folder 15: Roman Burghart.  CONTENTdm response:
Error detail:  Invalid pointer p15808coll specified
..

Updating p15808coll15	record p15808coll15:4993	from Page 6	1806249	Box 069, folder 15: Roman Burghart.  CONTENTdm response:
Error detail:  Invalid pointer p15808coll specified
..

Updating p15808coll15	record p15808coll15:4994	from Page 7	1806250	Box 069, folder 15: Roman Burghart.  CONTENTdm response:
Error detail:  Invalid pointer p15808coll specified
..
Finished export of work 55911, 'Box 069, folder 15: Roman Burghart' 
	Skipping export of uncompleted work 45345, 'Farfel Notebook 01: Leaves 001-064' 
	Skipping export of uncompleted work 45346, 'Farfel Notebook 02: Leaves 065-134' 
	Skipping export of uncompleted work 45347, 'Farfel Notebook 03: Leaves 135-222' 
	Skipping export of uncompleted work 45349, 'Farfel Notebook 04: Leaves 223-316' 
	Skipping export of uncompleted work 45350, 'Farfel Notebook 05: Leaves 317-396' 
	Skipping export of uncompleted work 45353, 'Farfel Notebook 07: Leaves 469-498' 
	Skipping export of uncompleted work 55204, 'Ice hockey yearbook, 1984-1985 season, Ohio University' 
	Skipping export of uncompleted work 55205, 'Spectrum Green yearbook, 1978' 
```

Possibly this is just new or pdf items, needs testing.

Collections are now appended to the cdm record with a : between them; we need to look for the colon.

Erin at Ohio U is waiting for this.

**Comment by benwbrum** [comment]
This has been deployed, and Erin has been asked to test the fix via email.

**Comment by benwbrum** [comment]
This continues to be a problem, with NCDCR reporting the following error:


```
        Beginning export of work 59577, 'Tax Lists, Beaufort County, 1755' 
 
Updating https://cdm16062.contentdm.oclc.org/iiif/2/p16062coll33:2617/manifest.json        record 2585    from TreasurersComptrollers_TaxLists_Box1_Beaufort_1755_001       1856989        Tax Lists, Beaufort County, 1755.  CONTENTdm response:
Error detail:  Sorry, you do not have permissions to edit metadata in this collection.
 ```

**Comment by saracarl** [comment]
This has just been reported by Greenville as well.  
Here's the digital collection in ContentDM https://greenvillelibrary.contentdm.oclc.org/digital/collection/p17168coll36/search
Here's the collection in FTP https://www.fromthepage.com/sc-room/slater-news

**Comment by benwbrum** [comment]
```
2.7.1 :011 > page = Page.find 32566791
2.7.1 :012 > page.metadata
 => {"direct"=>{}, "title"=>"gcls_SN_009d", "covera"=>{}, "dpla"=>{}, "righta"=>{}, "source"=>{}, "digita"=>{}, "identi"=>{}, "media"=>{}, "format"=>{}, "digiti"=>{}, "datea"=>{}, "dmrecord"=>"8"} 
2.7.1 :013 > page.sc_canvas.sc_canvas_id
 => "https://cdm17168.contentdm.oclc.org/iiif/p17168coll36:8/canvas/c3" 
```

```
[["5", "https://cdm17168.contentdm.oclc.org/iiif/p17168coll36:5/canvas/c0"],
 ["6", "https://cdm17168.contentdm.oclc.org/iiif/p17168coll36:6/canvas/c1"],
 ["7", "https://cdm17168.contentdm.oclc.org/iiif/p17168coll36:7/canvas/c2"],
 ["8", "https://cdm17168.contentdm.oclc.org/iiif/p17168coll36:8/canvas/c3"]]
```

**Comment by benwbrum** [comment]
OCLC has asked how we are determining the dmrecord which we use in our SOAP call.

It looks like we are deriving it from the IIIF canvas ID for the page, in [this code](https://github.com/benwbrum/fromthepage/blob/development/lib/contentdm_translator.rb#L200-L202).  In the case of the value 8, we're parsing that from `https://cdm17168.contentdm.oclc.org/iiif/p17168coll36:8/canvas/c3`.

The results of that operation match the `dmrecord` value in the hash we stored from the REST call to dmGetItemInfo when we originally imported the item from CONTENTdm: 
 `{"direct"=>{}, "title"=>"gcls_SN_009d", "covera"=>{}, "dpla"=>{}, "righta"=>{}, "source"=>{}, "digita"=>{}, "identi"=>{}, "media"=>{}, "format"=>{}, "digiti"=>{}, "datea"=>{}, "dmrecord"=>"8"} `

The dmGetItemInfo call is `https://server17168.contentdm.oclc.org/dmwebservices/index.php?q=dmGetItemInfo/p17168coll36/8/json`, which returns
`{"direct":{},"title":"gcls_SN_009d","creato":{},"date":{},"subjec":{},"descri":{},"covera":{},"rights":{},"dpla":{},"righta":{},"langua":{},"source":{},"publis":{},"digita":{},"identi":{},"media":{},"type":{},"format":{},"digiti":{},"datea":{},"transc":{},"fullrs":{},"find":"9.jp2","dmaccess":{},"dmimage":{},"dmcreated":"2018-10-09","dmmodified":"2018-10-09","dmoclcno":{},"dmrecord":"8","restrictionCode":"1","cdmfilesize":"3529806","cdmfilesizeformatted":"3.37 MB","cdmprintpdf":"0","cdmhasocr":"0","cdmisnewspaper":"0"}`

**Comment by benwbrum** [comment]
OCLC does not plan to take any immediate action on this.  Closing until more work on CONTENTdm side.
