### ISSUE TITLE
Display page pre-loads next page from work

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#247]
If a user is looking at an individual page, it's likely that they will 1) be looking at that page for a while, and 2) click the 'next page' link when they're done.  If we use browser directives to pre-load and pre-render the next page from that work, we could substantially enhance the reading experience.

**Comment by benwbrum** [comment]
It looks like prerender/prefetch support is in Chrome only at this point -- certainly not in Firefox anytime soon.  Still, there may be some performance gains by prefetching the image from the next page?  cf https://en.wikipedia.org/wiki/Link_prefetching

**Comment by kolking** [comment]
@benwbrum yes, it seems that "prerender" is supported only by Chrome and IE11 at the moment, and "prefetch" is supported by most modern browsers. I'm not sure about using "prefetch", based on this stackoverflow comment, we need "prerender" to cache the next page - http://stackoverflow.com/questions/26387612/html-performance-prerendering-of-multiple-pages/26519065#26519065
I've tried to include "prefetch" tag to the next page and Chrome DevTools shows that the request to the prefetched page is cancelled every time.

**Comment by benwbrum** [comment]
OK, in that case we can move this to the bottom of the priority list.

**Comment by benwbrum** [comment]
Declaring this as good enough.
