### ISSUE TITLE
Create pricing grid page

### ISSUE THREAD

**Issue by kolking** [benwbrum/fromthepage#249]
> The first page will be linked from the main splash page from a prominent "start a project" which will take you page 1, the pricing grid. Bottom of each column should have a button -- we'll add the action on our own.

PAGE CONTENT:

Start a free trial -- one collection, up to 400 pages.
Then 3 columns

1st column: Researcher
$30/month, billed monthly
collaborative transcription, translation, OCR correction and subject indexing
multiple export formats (open annotation, TEI, CSV, html, IIIF)
1 projects
unlimited documents
up to 10,00 pages
e-mail support
pay via Credit Card

2nd column: Small Organization
$3000/year, billed annually
collaborative transcription, translation, OCR correction and subject indexing
multiple export formats (open annotation, TEI, CSV, html, IIIF)
unlimited projects
e-mail and instant message support
phone consultation on new projects
up to 50,000 pages
pay via Credit Card or Purchase Order

3rd column: Large Organization
ASK
collaborative transcription, translation, OCR correction and subject indexing
multiple export formats (open annotation, TEI, CSV, html, IIIF)
custom import and export formats
custom integration
custom feature development
strategic consulting

**Comment by kolking** [comment]
@saracarl @benwbrum I think that we should also add "Start Project" into the main top menu and link to this page.

@saracarl could you please explain - the very first line "Start a free trial -- one collection, up to 400 pages." should here be a link (to start the trial), or this line means that the trial period will be activated after signing up for a plan (1, 2 or 3) listed below?

**Comment by kolking** [comment]
@saracarl also, I think we should change this text on the home page:

>Start Your Project
>If you want to run a transcription project, we would be interested in hosting your effort. Send us your images and we will notify you once they are available for transcription.

once we'll add the pricing page, the second sentence should probable tell something about "see our pricing plans, sign up for free trial, etc" and contain the link to the page with pricing plans.

**Comment by benwbrum** [comment]
Regarding the "Start a free trial" should be another section and button, which we'll wire to the app later.  It should be below the main pricing grid.  We do not (at this time) expect free trial users to already choose a plan, but hope they will return to this page later to choose the appropriate plan for them.

Agreed about the "we would be interested in hosting your effort" -- we should make this link to the pricing grid page.

**Comment by kolking** [comment]
@benwbrum @saracarl I have a feeling that when we list $30/month and $3000/year it looks wrong. I mean, such a big difference between Plan 1 and Plan 2 is probably bad for Plan 2, and I'm sure you're more interested in Plan 2 users, so maybe we should list the prices like that:
Plan 1 - $30/month, billed monthly
Plan 2 - $250/month, billed annually
What do you think?

**Comment by saracarl** [comment]
Ben and I talked about this when we wrote it, and he liked the big
differentiation.  (one is targeting individuals, the other institutions.)

I think we should get actual user feedback, but let's leave it monthly and
annually for now.

Sara
