### ISSUE TITLE
need routes to have logical URLs

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#25]
Had to send someone this link today:  http://beta.fromthepage.com/collection/show?collection_id=20&ol=l_hd_c_link

I would have been a lot happier sending them this one:
http://beta.fromthepage.com/jmmclure/collection  or something involving the work name like:  http://beta.fromthepage.com/jmmclure/grinnell

**Comment by benwbrum** [comment]
This is a dupicate of #416
