### ISSUE TITLE
Easy Community Group

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2520]
So I was recently using Canva (to design beer labels for Ben's homebrew) and after I downloaded one of the labels, I received this invitation:

![image](https://user-images.githubusercontent.com/708566/115963028-99cfdc80-a4e3-11eb-9c51-a9b0f170b805.png)

When I clicked on "Join the Community" I was taken to a Facebook group:

![image](https://user-images.githubusercontent.com/708566/115963042-ab18e900-a4e3-11eb-8cf3-aa37647af521.png)

This would be a super simple way to create a project owner community or a transcriber community or let our project owners create their own communities for their projects.

**Comment by benwbrum** [comment]
Discussion forum will obviate this
