### ISSUE TITLE
editing a page puts a reviewed document back in unreviewed

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2530]
Is this the right thing to do?  I don't know.  Maybe not if the person who adds it is an owner or reviewer but yes if they are just a transcriber?

**Comment by benwbrum** [comment]
I think that we need to support two different scenarios for projects that have required review or restricted review:

### Post-review edit by "experts"

- User A transcribes the page and it is marked as needing review
- User B approves the page
- User B edits the page

##### or

- User A transcribes the page and it is marked as needing review
- User B approves the page
- Project owner C edits the page

##### or (for restricted review only)

- User A transcribes the page and it is marked as needing review
- User B approves the page
- User C (who is a member of the authorized reviewers) edits the page

Current behavior is that any post-approval edit moves a page to needing review.
Instead, we should leave the page in its completed state.  (`transcribed` or `indexed`).


### Post-review by others

- User A transcribes the page and it is marked as needing review
- User B approves the page
- User C (who is not a project owner or authorized reviewer) edits the page

This should move the page back into a `needs_review` state.

**Comment by symmetrically** [comment]
@benwbrum 
I have tested all the scenario as described on the issue. I am not able to produce the issue as described. On post review edits by the authorized user it is going to completed state and on post review edits by the other user it is going to `needs_review` state.

There are three review types, "Restricted "is one of them if collection owner make this review type true then all transcriptions need review, and only authorized reviewers may approve transcriptions. After approval it goes to completed state. The user can see the approve button for required and restricted options.
