### ISSUE TITLE
Long work titles make "sets" UI unusable

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2531]
This view (from https://fromthepage.com/document_sets?collection_id=mount-auburn-cemetery) makes adding a large number of documents -- i.e. letters -- to a document set very difficult.  You lose the headers as you scroll down in addition to the general ugliness.

![image](https://user-images.githubusercontent.com/708566/116439126-d289f180-a814-11eb-87a8-9d53d03f0dc2.png)

At a minimum we should make the title wider and add a horizontal scroll.  Making the default pagination larger might also make sense (40 or 50?).

**Comment by atbah** [comment]
Hi, @saracarl   The above link redirects to /findaproject page.  Would you attach a new link where I can see the issue?

**Comment by saracarl** [comment]
Hi @atbah I created some similar dummy data here:
https://fromthepage.com/document_sets?collection_id=testy
and added you as an owner of this collection.
You'll need to be logged in.
(You can add more if you'd like; this is a private test collection)

It's just awkward when you get a large number of document sets, especially if they have long titles.

Can we:
1)  Add a horizontal scroll to the table of document sets
2)  make the work title column of a certain, reasonable width instead of letting it be adaptive with the data
3)  "freeze" the work title in the horizontal scroll so you can always see it, even if you scroll to the right
