### ISSUE TITLE
assign document set as you move to a collection

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2532]
Mount Auburn moves documents from a private collection to a public collection once they are ready to transcribe.  As they move to the public collection, they also put them into two or more document sets.  Making adding them easier to add to doc sets here would be nice.

Caveat:  Metadata browse may make this obsolete.

**Comment by benwbrum** [comment]
There are a few other places in the UI--I think the Start a Project screen?--where we show a drop down of collections, with document sets nested under them.

**Comment by benwbrum** [comment]
To reproduce:
* Log in as a project owner (not Staff, not Individual Researcher account_type)
* Create collection A
* Add work 1 to A
* Create collection B
* Modify the Settings for B to enable document sets
* Add a document set C to B
* Return to collection A
* Move work 1 to collection B, document set C
  * _This might be done via the collection settings/work list, but I suspect that you will need to go to the Settings tab of work 1_
  * Current workflow
    * Move work 1 from collection A to collection B
    * Navigate to collection B
    * Modify the document sets for B
    * Add work 1 to document set C
  * Desired workflow
    * When moving work 1 from collection A, the list of possible target collections should include document sets, ideally nested under their parent collection.  Moving the work will change its collection and also add it to the target document set.  (I think that a similar nesting dropdown menu is visible under the Start a  Project screen on the Owner Dashboard, when a user is uploading--or perhaps importing--a work into a collection.)
