### ISSUE TITLE
Mobile thoughts

### ISSUE THREAD

**Issue by srl295** [benwbrum/fromthepage#255]
In the wonderful new add page box:
- make "choose file" button really big. 
- show a thumbnail and close up of the middle of the previous image (just as a sanity and continuity check). Also show the title of the previous page.

**Comment by benwbrum** [comment]
These are really good ideas.  We're still trying to work some of the kinks out of the mobile uploader, which mainly revolves around us finding the time to give it a thorough tests.  

Is the need for the zoomed image to spot-check your focus?  What kind of path would you like to take if you were to spot a problem?  Should we implement a mobile-edit workflow in addition to the mobile add?  ('cuz that's what it sounds like)

**Comment by saracarl** [comment]
Closing -- we'll review when or if we invest more heavily in mobile sometime in the future.
