### ISSUE TITLE
Rotation issue

### ISSUE THREAD

**Issue by srl295** [benwbrum/fromthepage#256]
On iOS 9.1 in the read view, images are rotated properly but the aspect ratio is wrong.

**Comment by srl295** [comment]
![image](https://cloud.githubusercontent.com/assets/855219/10713434/b4b1f268-7a73-11e5-9739-2a25621b695a.jpg) (page should be higher than it is wide)

**Comment by benwbrum** [comment]
Hey, @kolking, can you take a look at this?  

@srl295, it's not entirely clear to me whether the device is in portrait mode or landscape mode.

**Comment by kolking** [comment]
@benwbrum sorry but I don't see any wrong behavior here, at least, looking at the photo provided.

Here I've cropped the page photo and obviously it has been taken in landscape orientation, so it shown as it should after upload:
![image](https://cloud.githubusercontent.com/assets/4656448/11016881/1bfbfe38-859f-11e5-8e8d-22a8a9e062b1.png)

![image](https://cloud.githubusercontent.com/assets/4656448/11016895/920e0c2e-859f-11e5-93e0-14e30e157506.png)

**Comment by srl295** [comment]
The image aspect ratio is wrong. The diary page is higher than it is wide.
It was rotated but the aspect ratio was not rotated.

**Comment by kolking** [comment]
@srl295 could you please attach here the original image - the one with the right aspect ratio?

**Comment by tbl73** [comment]
@srl295 Is this still an issue?
