### ISSUE TITLE
Mobile upload: All uploads end up as the same file

### ISSUE THREAD

**Issue by srl295** [benwbrum/fromthepage#257]
may be part of #254 

On `/work/pages_tab?work_id=__#create-page` after a lot of uploads.. all the page images are the same..  as in #255 it would be nice to get thumbnails as i'm going through the upload cycle

Oh well. I'll scan again :)

**Comment by saracarl** [comment]
Closing -- we'll review when or if we invest more heavily in mobile sometime in the future.

(seems like a bug, though.)
