### ISSUE TITLE
Warn project owners when changing field config on transcribed projects

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2604]
A project owner recently changed a column name on a spreadsheet configuring

`When reviewing/ approving pages last Friday I came across an error. In “Overview” it showed middle initials/names when necessary, however; when I clicked on “Transcribe” the Middle Name column did not show any of the middle names/initials. We think this error could be linked to XXX having changed the title of the Middle Name field a few days earlier. I have not come across this error when reviewing pages today,
`

My response:

` This was caused by XXX changing the name of the middle name field.  If the page had been transcribed before the change it would show up in the overview if the transcription, since we generate that when the page is saved.  XXX didn't actually change the name of the middle name field (because she couldn't in our user interface); she had to delete the original field and create a new one.  That meant that when the data is loaded into the spreadsheet widget for a previously saved page the data from the original field has no where to be displayed and the new middle name field has no data in it.`

When a project owner loads the field OR spreadsheet configuration screen, we should check for existing transcriptions and warn them changing the configuration may result in lost data.  Perhaps say that *adding* fields is fine, but *deleting* them isn't?  Or to contact support if they want to *rename* fields?

**Comment by IsaacArneson** [comment]
Test on `@collection.table_cells.present?`

**Comment by saracarl** [comment]
The warning text should read:  `This project has already been partially transcribed.  Adding fields is fine, but deleting or changing fields may results in lost data.  Please contact support@fromthepage.com if you have questions or need to rename fields.`

**Comment by benwbrum** [comment]
I think the relevant view is https://github.com/benwbrum/fromthepage/blob/main/app/views/transcription_field/edit_fields.html.slim

**Comment by benwbrum** [comment]
And another view that needs the same warning is https://github.com/benwbrum/fromthepage/blob/main/app/views/transcription_field/edit_columns.html.slim

**Comment by saracarl** [comment]
Watch this to figure out how to create a spreadsheet transcription project:
https://www.youtube.com/watch?v=k3l_f0RqQj8
(You'll need to create a spreadsheet project, transcribe a page, and then go and pretend like you are going to add another column or something similar to reproduce.)
