### ISSUE TITLE
Add field above spreadsheet doesn't work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2606]
If you add a field after adding a spreadsheet, you can't drag the field above the spreadsheet (even if it's in a separate line).

Video:
https://app.searchie.io/watch/l7qL6wBMD9

**Comment by benwbrum** [comment]
The problem here appears to be that reordering sends an array of field IDs, which we use to re-order the position of fields within a line, but it does not send the line attribute.  As a result, we don't change the line number of a field that has been reordered.
