### ISSUE TITLE
BUG: delete work 

### ISSUE THREAD

**Issue by marcolarosa** [benwbrum/fromthepage#2676]
Delete work fails on version 21.7. This is in my containerised environment though I don't see why that would be a problem given other functionality works. Anyway:

![Screen Shot 2021-07-15 at 2 17 53 pm](https://user-images.githubusercontent.com/2639995/125728337-9ddf7ae5-e51b-4580-8a25-d1e8c12d55bb.png)

And then, the work still shows up on the collection page:
![Screen Shot 2021-07-15 at 2 21 34 pm](https://user-images.githubusercontent.com/2639995/125728559-27a2aed4-d231-4a80-a2ea-ea493247d8b4.png)

But when you select it it's not there:
![Screen Shot 2021-07-15 at 2 21 37 pm](https://user-images.githubusercontent.com/2639995/125728575-da210f31-ee10-47c6-b64b-52bf3fa62a24.png)

**Comment by benwbrum** [comment]
We've got a fix for this in the queue.  It'll get merged into the `development` branch we work from, then pushed into `main` before we cut the next release.
