### ISSUE TITLE
voice dictation doesn't work for comments or subjects

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2681]
Dictation function is not working when activated in the subject description field nor when adding a comment to a document page (not urgent--dictation is working in the document transcription field): https://fromthepage-t01.lib.utexas.edu/ap2253/early-modern-manuscripts-at-the-benson-latin-american-collection/article/633/edit

Albert.

**Comment by benwbrum** [comment]
We've just heard that the opposite is true -- more verification is needed.
