### ISSUE TITLE
error in subject versions tab when no display name

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2682]
When I click on the "Versions" tab in a subject entry: https://fromthepage-t01.lib.utexas.edu/ap2253/early-modern-manuscripts-at-the-benson-latin-american-collection/article_version/633

Subject page:  https://fromthepage-t01.lib.utexas.edu/ap2253/early-modern-manuscripts-at-the-benson-latin-american-collection/article/633

```
I, [2021-07-17T13:47:15.461771 #50484]  INFO -- : Completed 500  in 48ms (ActiveRecord: 7.8ms | Allocations: 15339)
F, [2021-07-17T13:47:15.480002 #50484] FATAL -- :   
ActionView::Template::Error (undefined method `display_name' for nil:NilClass):
     7: 
     8: -else
     9:   -selected_version_date = @selected_version.created_on.localtime.strftime("%b %d, %Y %I:%M %p")
    10:   -selected_version_user = link_to(@selected_version.user.display_name, user_profile_path(:user_id => @selected_version.user.id))
    11: 
    12:   p.diff-help Here you can see all subject revisions and compare the changes have been made in each revision. Left column shows the subject title and description in the selected revision, right column shows what have been changed. Unchanged text is <span>highlighted in white</span>, deleted text is <del>highlighted in red</del>, and inserted text is <ins>highlighted in green</ins> color.
    13: 
  
app/views/article_version/show.html.slim:10
app/controllers/article_version_controller.rb:11:in `list'
app/controllers/application_controller.rb:48:in `switch_locale'
```

**Comment by benwbrum** [comment]
It looks like the actual problem here is that the user record for the page version was `nil`.  This might happen when a user transcribes a page and then deletes their account, or it might happen when a spam user edits a page and then has their account expunged.

We should experiment, document the reproduction steps, then discuss how to fix the bug.

**Comment by WillNigel23** [comment]
@benwbrum I agree, the error is due to nil user. 

In these scenarios, what do we substitute instead if a user happens to be deleted? 'Anonymous', 'Guest User', etc
