### ISSUE TITLE
How to handle dittos

### ISSUE THREAD

**Issue by NatWooding** [benwbrum/fromthepage#27]
In Grinnell 1925 S3 Page 7, he uses dittos for several bird names as well as collection location descriptions. I chose to insert the actual text instead of the ditto marks. How many transcription rules does this violate :) ? My thinking is that using the marks would make the text harder to mine and Grinnell's meaning was patently clear.

**Comment by saracarl** [comment]
This is a collection specific transcription convention -- up to the owner.  Closing.
