### ISSUE TITLE
"Next Page" in transcribe mode should open next page in transcribe mode

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#271]
Rebecca Nesvet reports:
Can you make it so that if i’m in “transcribe” mode, save, and turn the page, it opens that page in “transcribe” mode? My workflow is now:
- select page
- select “transcribe” 
- select fullscreen
- enlarge photofacsimile
- transcribe
- save
- comment (workflow status - now, that it’s “transcribed,” but later, it might be “transcribed with versioning by Emily,” etc.)
- submit comment
- turn page
- select “transcribe” to do next page
  … drafting worksheet for students, so this suggestion would remove 1 step.
  (of course, there may be disadvantages to making this a default which i do not know.)

**Comment by saracarl** [comment]
Done.
