### ISSUE TITLE
Metadata ingest issues

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2715]
- In the upload metadata pop-up window, instead of providing a link to download the metadata template, could y'all provide the option to export current metadata instead? I am having to export metadata under the Export tab, deleting system generated columns (slugs, collection, subsets, etc.), placing the work_id column at the beginning, then adding new metadata columns--all so that I don't inadvertently ingest duplicate metadata. It would be easier if I could just get the metadata I have added already structured according to the template to add more/update information.

- I have been opening the metadata export in Excel and then saving it as a csv file, which the platform rejects when I try to ingest it. I have to open the Excel-generated csv in notepad, download the template, copy and paste from the former to the latter, and save the latter to be able to ingest it. I don't know if this is an issue with how Excel formats the csv file. I'm not sure if y'all need to add further guidelines on this or if it can be fixed automatically. I am attaching the 'problem' file.

- Is it possible to replace the FTP title with a new title in the ingested metadata csv? When I first updated metadata, I named one of the columns "title" hoping it would replace the main title of a document. Instead, it added it as a "title.1" field in the about page:  https://fromthepage.lib.utexas.edu/llilasbenson/colonial-mss/blac-wbs-2055/about

- I have a few documents that are either "undated", contain "circa", or are a year range in the date field. It seems like the platform only registers standalone years. Any chance these unspecified dates can be accommodated?

- This might be quite an ask, but would it be possible to add a metadata search option? My work around has been to activate metadata fields as facets so that I can easily find specific call numbers, which are not really useful for browsing. Even a "Search the metadata" bar below the ones you already have would be very useful.

Were y'all able to parse out multi-value metadata for faceting?

**Comment by benwbrum** [comment]
See also #3003

**Comment by benwbrum** [comment]
See also #3138

**Comment by benwbrum** [comment]
Covered in #2979
