### ISSUE TITLE
nybg: rotate image (enhancement)

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#273]
Rebecca Nesvet writes: 

I’ve come to a “gutter ad” (printed vertically, perpendicular to rest of text.) A “rotate image” feature would be helpful for these and the 19th century convention of crosswriting letters to save paper.

**Comment by saracarl** [comment]
@kolking could you look into this and see how easy it is to do?  
Here's the page the user is talking about:  http://fromthepage.com/display/display_page?page_id=7101#page/n0/mode/1up

**Comment by benwbrum** [comment]
Note that if this is remotely hard to do with the Internet Archive's Bookreader.js, we should wait and address it a different way:  the Internet Archive now supports the IIIF standard, which (itself) supports rotation on part of the image server.  

I believe that we've got a story somewhere about using OpenSeaDragon for IIIF-enabled image service, so this would become part of that story instead.

**Comment by saracarl** [comment]
We need to add a rotation button to our open seadragon displayed IIIF resources -- IIIF imports AND Internet Archive imports.

Docs:
https://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#.event:rotate

Example: https://github.com/openseadragon/openseadragon/blob/52fd82d4bee450400702615b77b5957c7df6ac5b/test/demo/overlay.html#L18

**Comment by saracarl** [comment]
Cross-writing or just rotated images.

**Comment by saracarl** [comment]
What about things that are upload vs IIIF or IA.  We'll  need this in zoomer.js which is used for uploaded documents.

So to summarize, we'll need to add "rotate" for pages  to:
-- zoomer.js for uploaded documents
-- open seadragon for IIIF imported documents
-- Internet archive bookreader.
Priority is the above order.  Can be broken into 3 separate issues if needed.

**Comment by benwbrum** [comment]
Let's start with research on what's involved with
* Adding rotation buttons to each of the viewers, or
* Replacing all viewers with Open Seadragon.

**Comment by saracarl** [comment]
IPL needs this as well.  That's a critical mass of customers, so let's prioritize this.

**Comment by saracarl** [comment]
Closing in favor of #1531
