### ISSUE TITLE
[FTP UT library install]: summary page of owner or admin dashboard should link to lists of collections, works, articles, etc (enhancement)

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#274]
My reaction to the summary page in the Administrator dashboard is that I'd like the statistics for collections, pages etc. hot-linked to lists of those items. There are of course other ways to get to those that aren't very complicated, but this path would be intuitive to me.

**Comment by kolking** [comment]
@atomrab yes, your suggestion sounds totally right, but as far as I remember, we don't have a separate pages for all the numbers listed in the Admin dashboard.

**Comment by benwbrum** [comment]
We can make those pages happen, but it'll probably be a minimum of three
weeks before @saracarl or I have capacity for the work on the back-end side.

**Comment by saracarl** [comment]
in admin-dashboard-274 -- needs review.  Has works, collections, owners, users (goes to users tab), but links are a whole box around the number and word, although only the word looks like a link.

**Comment by tbl73** [comment]
Merged in pull #427.
