### ISSUE TITLE
Version tab for spreadsheets

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2743]
From Molly K:
` Given how large my spreadsheets are, reading the versions is next to impossible, but I'm curious about how the version information works.`

The versions tab really doesn't work for dense information like spreadsheets. 

Related to, but different, from #2282

**Comment by saracarl** [comment]
@benwbrum could we see if this is something Sylvie could fix for us?  I'm hoping it's just applying the spreadsheet layout in the view.

**Comment by atbah** [comment]
@benwbrum  I am going to update the page and table like the below screenshot. And I added layout buttons (vertical, horizontal). 
Please let me know if it works. and let me know if it is missing something else.  
And I fixed a Javascript error on this page, but highlighting changed words still doesn't work for the table. 
![image](https://github.com/benwbrum/fromthepage/assets/159004143/e6c0b338-b03d-449d-9e2f-f03a489f4a7f)
![image](https://github.com/benwbrum/fromthepage/assets/159004143/6268a710-3192-4b22-835e-a104f3932441)
![image](https://github.com/benwbrum/fromthepage/assets/159004143/c21f593c-9a97-4afc-89ae-7113388b4143)

**Comment by atbah** [comment]
I will keep investigating and fix the issue.

**Comment by benwbrum** [comment]
I really like this.  Please make sure to test it with a non-spreadsheet project as well.
