### ISSUE TITLE
[FTP UT library install]: subject tab on individual collection page returns error (bug)

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#275]
Clicking the "Subjects" tab on the home-page for a particular collection returns a "500 Internal Server Error" message.

![image](https://cloud.githubusercontent.com/assets/4740995/12868635/0407ae62-ccd0-11e5-8be0-74783e03f216.png)

![image](https://cloud.githubusercontent.com/assets/4740995/12868640/1170de3e-ccd0-11e5-9b09-d04da1f17c55.png)

Refreshing the page has no effect.

**Comment by kolking** [comment]
@saracarl I cannot reproduce this bug, most likely there is something wrong with the Subjects in this particular collection. Would be good to get the error log.

**Comment by atomrab** [comment]
@kolking This is no longer happening for me, either -- must have had to do with the setup on the UT side, now fixed.

**Comment by saracarl** [comment]
Wonder if it happens if no subjects are defined?  Let me test that, and if it doesn't reproduce the problem we'll close it out.

**Comment by kolking** [comment]
@saracarl no, it won't happen when there is no subjects defined, in that case it will show a notice.

**Comment by kolking** [comment]
@atomrab happy to hear that! So, we can probably close the issue then?

**Comment by saracarl** [comment]
Yep, verified @kolking.  Let's close this out.
