### ISSUE TITLE
CodeMirror button for inserting markdown tables

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2753]
This might be a model for inserting spreadsheets or tables into textual documents that aren't consistent (using markdown):

https://www.tablesgenerator.com/markdown_tables

**Comment by saracarl** [comment]
This came up again on a sales call.

**Comment by benwbrum** [comment]
We'd like to add a new button, `table` to the CodeMirror flow which allows the easy insertion of markdown tables.

Currently buttons automatically insert XML tags around selected text, or insert an XML tag into the cursor position.

This new button would work similarly to the table insertion feature of Google Docs, prompting the user to select the number of rows and columns interactively.  It would then insert a markdown table (including headers) at the cursor position.
