### ISSUE TITLE
[FTP UT library install]: transcription completion bar is either 0 or 100 (UX)

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#276]
Even if the status of a transcription is set to "Incomplete transcription", the transcription completion bar for that work goes from 0 to 100% after the first save of any text. I assume this is actually measuring number of pages that have had at least one save, but even that is misleading, since you could have a 10-page document with one word for each page, and it would still say 100% transcribed. This metric should sync with the status of the document, so that "incomplete transcription" counts as "untranscribed", and only "transcription complete" or "no text" adds the page to the "complete" statistic. Otherwise this visualization is very misleading.

**Comment by saracarl** [comment]
More customer input on this, with our planned solution:

FromThePage will remove the document state drop down and add a “save and complete” button next to the current “save” button. We'll then have 3 states – 0% (not started), 50% (started/some transcription), 100% (“save and done” clicked).

**Comment by saracarl** [comment]
Comments from @NatWooding on this, pulled from issue #32  

In From the Page, the page status drop down window only has "Incomplete transcription" and "Blank: nothing to transcribe". It needs a "Transcription Complete" entry for use when the transcription is complete after it had earlier been marked incomplete.

E.g., Grinnell S3 Page 8
http://beta.fromthepage.com/display/display_page?page_id=4364

**Comment by saracarl** [comment]
Newest version has a much enhanced page status and statistics.
