### ISSUE TITLE
[FTP UT library install]: unclear action status on document upload (UX)

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#277]
I selected "Process upload" for a pdf that had been uploaded to a collection I administer by someone to whom I had given "owner" status for that collection. The status indicator switched to "Queued" and stayed there, even on page refresh. But the document now appears normally in the collection -- so what is the "Queued" status referring to? Will it switch at some point to "Processed"?

**Comment by atomrab** [comment]
UT libraries has installed the new version, but some funny things have happened to the document in question. It still appears to be in the system, since recent revisions to it are listed, and one can access it from the link in the recent revisions. In those revisions, it is listed as being part of the "Terrell, Calvert and Troy (UGS 302)" collection -- but it has now disappeared from that collection, and in fact everywhere I've looked, except for the revision log.

Also, that particular file still appears in the Uploads list as "Queued".

**Comment by saracarl** [comment]
Please let us know if this is fixed by #280 @atomrab

**Comment by saracarl** [comment]
I don't think this will be fixed by #280.  We've seen it reported by others as well, see #263

**Comment by tbl73** [comment]
@atomrab - Are you still having problems with this?
