### ISSUE TITLE
[FTP UT library install]: no admin permissions for documents uploaded to collection by non-owner (enhancement?)

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#278]
As the owner of a collection, I do not seem to have the ability to change the settings of a document or page uploaded to that collection by another individual with "owner" status (the only status that permits transcription -- so anyone who can transcribe must also be able to upload). The collection owner needs to have the ability to ensure that pages and documents are named in a consistent manner within that collection. Is there a way to establish super-user permissions for a collections manager over document and page settings within that collection?

**Comment by benwbrum** [comment]
Would it be better to create an "authorized transcriber" group who may see
and edit the items in a collection, but not upload new documents?  That
seems like a better analogue for classroom use to me, as you would still
like two tiers of access within private collections.

**Comment by atomrab** [comment]
I do like that idea, since I'd like to keep new docs from being uploaded randomly -- but there are also situations like the current one, in which someone who has a relevant doc and is authorized to upload it can do so, but I want to be able to rename it when I add it to the collection. This will be important if items are coming in from work done by other people -- student scanners, collaborators on a multi-site project, etc. So really I suppose I want three tiers: owners, who can do everything with every document in a collection (including renaming, deleting, etc); contributors, who can upload documents; and transcribers, who can see and edit. But if that isn't possible, I'd settle for an owner tier that can rename stuff uploaded by other owners to the same collection, and a transcriber tier that can see but not upload.

**Comment by benwbrum** [comment]
We need to review the existing multi-owner functionality to see if we can make it solve the challenge here -- it may require some code changes, but I think that [owners being able to edit settings for all works in a collection regardless of who uploaded them] is the right goal, and that the multi-owner features get us most of the way there.

**Comment by tbl73** [comment]
As far as I can tell, this works now - would you agree, @atomrab ?
