### ISSUE TITLE
User can adjust size of transcription window

### ISSUE THREAD

**Issue by NatWooding** [benwbrum/fromthepage#28]
I have encountered several cases where the transcription window was not wide enough to enter JG's entire line. See S3 Page 7. As I entered some of the lines, they wrapped, which makes it a little harder to read when checking the work. However, when I hit save, the wrapping disappeared. When I did this and similar pages, when I reach the last couple lines on the original text, I have scrolled so far that I cannot see the transcription window and have to either jot down the transcription or scroll, enter a few words, scroll down, back up, etc.

**Comment by saracarl** [comment]
Best solution for this is the over & under transcription option, which puts the transcription screen the width of the app, instead of half of it.

**Comment by NatWooding** [comment]
Sara

 

Thank you for this although I do not find it to be a satisfactory answer since I find it easier to work in a side-by-side mode rather than over and under.

 

Nat Wooding
