### ISSUE TITLE
[FTP UT Library install]: Uploading errors

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#280]
Ece seems to have uploaded four zip files containing new documents. When I click on "Actions" and select "Process Upload", I am directed to a 500 Server Error page. When I navigate back to the Uploads page in the Admin dashboard, I see that the zip file I attempted to process is now listed as "Queued". Although the zip file was apparently uploaded to the collection "Terrell, Calvert and Troy (UGS 302)", neither it nor its contents appear in that collection (in the previous install, the document that hung in "Queued" during upload nevertheless appeared in the collection, though it has now disappeared -- see #277).

**Comment by benwbrum** [comment]
We were just able to duplicate this problem on the UT server.  Apparently we're missing a parameter when generating an email to be sent to the site administrators notifying them that a user has attempted an upload.  

```
I, [2016-04-11T14:36:59.199550 #2610]  INFO -- : Started POST "/dashboard/new_upload" for 70.115.159.65 at 2016-04-11 14:36:59 -0500
I, [2016-04-11T14:36:59.200821 #2610]  INFO -- : Processing by DashboardController#new_upload as HTML
I, [2016-04-11T14:36:59.200910 #2610]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"mGXkIeqju1Z4MrKOu725hIuTcZ2VibjAb+L/tdNBhyk=", "document_upload"=>{"collection_id"=>"6", "file"=>#<ActionDispatch::Http::UploadedFile:0x007f1938b5c950 @tempfile=#<Tempfile:/tmp/RackMultipart20160411-2610-8bedn4>, @original_filename="Assises_de_Jrusalem_ou_recueil_des_ouv-1.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"document_upload[file]\"; filename=\"Assises_de_Jrusalem_ou_recueil_des_ouv-1.pdf\"\r\nContent-Type: application/pdf\r\n">}, "button"=>""}
I, [2016-04-11T14:36:59.423681 #2610]  INFO -- :   Rendered system_mailer/new_upload.html.erb within layouts/mailer (3.3ms)
I, [2016-04-11T14:36:59.423955 #2610]  INFO -- : Completed 500 Internal Server Error in 223ms
F, [2016-04-11T14:36:59.434668 #2610] FATAL -- : 
ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
    53: 
    54: <div style="margin-top:20px; padding-top:20px; border-top:1px solid #D3CFC6">
    55:   View all uploads at the
    56:   <%= link_to 'upload dashboard', { controller: 'admin', action: 'uploads', only_path: false } %>.
    57: </div>
  app/views/system_mailer/new_upload.html.erb:56:in `_app_views_system_mailer_new_upload_html_erb___2493046384189297887_69873152033400'
  app/mailers/system_mailer.rb:20:in `new_upload'
  app/controllers/dashboard_controller.rb:54:in `new_upload'
```

When an email is rendered, any links within the email have to contain a hostname (`fromthepage.lib.utexas.edu` in this case) so that user clicks go to the right system.  That hostname parameter needs to be specified in `config/environments/production.rb`.  I'm surprised that the `rake fromthepage:check_email_config` task doesn't check for this, as I thought that Perry had run it.

@saracarl can you double-check this?

**Comment by saracarl** [comment]
That looks correct.  When I remove this line from my test server's config/environments/development.rb file:
  config.action_mailer.default_url_options =  { host: 'sara.fromthepage.com' }

And run the task to check the email configuration:
$ rake fromthepage:check_email_config[saracarl@gmail.com]

I get:
No hostname set for this site: update config/environments/development.rb and set 
	config.action_mailer.default_url_options =  { host: 'fromthepagehostname.domainname.org' }

So to fix this, you just have to add 
	config.action_mailer.default_url_options =  { host: 'fromthepage.lib.utexas.edu' }
to your config/environments/production.rb file

And then run:
$ rake fromthepage:check_email_config[youremail@utexas.edu]
to verify it is configured correctly.

**Comment by saracarl** [comment]
We need to catch the exception here and move on even if we can't send the email -- not having email configured correctly is no reason not to successfully upload files.

**Comment by benwbrum** [comment]
Agreed.  The system and user email notifications provide a better
experience, but coupling them to basic upload functionality has been
nothing but painful.
​

**Comment by saracarl** [comment]
Fixed.
