### ISSUE TITLE
Transcription success metrics

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2815]
We'd like to make it easier for transcribers to be successful, but don't have any way to measure that.

To that end, we should analyze cohorts as follows:

- A transcriber cohort `C` are the users who created accounts between `t1` and `t2`
- `S` is the percentage of `C` who logged page-saved deeds between `t1` and `t1+n.days`
- Chart S over different periods

We should do something similar using a cohort of collections, to see when they attracted activity.

**Comment by saracarl** [comment]
Aren't we doing this by hand these days?  @benwbrum
