### ISSUE TITLE
Discussion Forum

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2820]
Here's our original notes code:

https://github.com/benwbrum/fromthepage/commit/128ae8cb90d9414ca5eecdbbae329817df74dbb0

**Comment by saracarl** [comment]
From a transcriber:

>   Even though transcribers are called “collaborators” there is no way for us to collaborate with each other. I suggest that each collection have a “message board” where we could post lessons-learned, tips & tricks for this collection, resources, etc. This would help transcribers learn and improve instead of making the same mistake page-after-page. One problem is that a good number of the transcribers don’t read the Help tab information posted by the institution. For example, the “Logbooks of the CSS Alabama” specifically requested we *not* hyphenate words across lines, but to put the whole word on the second line. I did so, and another transcriber followed behind me and re-instated such unwanted hyphenation. That could be corrected if there was a message board where transcribers could be informed of such errors. It would be optimum if the message board allowed both public messages and private messages, so as not to embarrass anyone. A transcriber would get a notice at the top of his Dashboard notifying him of his private message, which he could then click on to see it. Private messages would probably require a moderator to approve posts (to prevent abuse), but these moderators could also be volunteer collaborators. Other useful public messages could include handwriting quirks found in this collection, common abbreviations found in this collection & their meaning, commonly used industry terms found in this collection (ex: maritime), names of persons or places often referred to in this collection, etc. These are all things that lead to wildly varying interpretation page-to-page that could be remedied, and that leads to a faster, more accurate, more consistent transcription.

**Comment by saracarl** [comment]
Implementation Approach:

- [ ] Determine how this fits into our data model.  Use "Permissions Section" and think about customers with both private and public collections.
- [ ] Decide if users can do private messages (lean towards no)  Maybe only owners/staff can private message?
- [ ] Moderation -- what are our options?  Make sure staff & owners can moderate.  How do we make this as easy as Slack?  See "moderation" section.  I'm leaning towards "reactive moderation".  Or we disable moderation completely until spam starts showing up.  Or we can have FtP staff approving users in the "reactive moderation" mode; approve 1st user post and the rest of their posts are auto-approved.
- [ ] install following the steps here: https://www.rubydoc.info/gems/thredded up to "customizing views"
- [ ] Make sure we require authentication to post "Requiring authentication to access Thredded")
- [ ] Add forum activity to user profile ("user profile page")
- [ ] Update theming
- [ ] Decide about email notifications; do we like the default?  Include it in our emails?
- [ ] Decide about auto-follow (maybe when you join a collection you auto-follow the main forum?)
- [ ] Test other languages; do work from the i18n sections if needed.
- [ ] Decide how forum activity plays with deeds
- [ ] Customize views to include the page image (use "customizing views")
