### ISSUE TITLE
volunteer hours downloadable letter

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2858]
Similar to #1240, we should provide a downloadable letter that documents user contributions.  

We could start with a simple letter that says who the owning organization is (what if they work on multiple projects?), but we could also let project owners upload a logo and a signature and format a PDF for their specific project.

**Comment by anabeabas** [comment]
A transcriber needed it today.

**Comment by saracarl** [comment]
Here's a sample letter we built by hand today for someone needing documentation for court appointed service hours.  
[MichaelLaleskaServiceHours.pdf](https://github.com/benwbrum/fromthepage/files/13033255/MichaelLaleskaServiceHours.pdf)

(I have a doc file as well, if we want to use that while building this.)

Key things we decided:
-- document total hours for a time frame; that will include clicking around time and commenting/editing time.  
-- for the table, we counted "pages they had worked on" -- transcriptions, notes, edits, etc.  
-- We dropped the one collection that had a page count of 0 (not sure why it showed up, but it did)

**Comment by benwbrum** [comment]
Code we used to do this as a one-off in the console today:
### Get the user's time

```ruby
user_id = 32017019
user = User.find user_id

summaries_for_user= AhoyActivitySummary.where(user_id: user_id)
```

### Record time per collection
*Note that some time does not have a `collection_id`, so this could be undercount "overhead" time navigating to projects, etc.
```ruby
collection_minutes_map= summaries_for_user.group(:collection_id).sum(:minutes)
collection_minutes_map.each_pair do |collection_id, minutes|
  collection=Collection.where(id:collection_id).first
  if collection.nil?
    output_array << [nil, nil, minutes]
  else
    output_array << [collection.owner.display_name, collection.title, minutes]
  end
end
f = File.open("/tmp/time_per_collection.csv", "w+")
f.print output_array.map{|row| row.join(",")}.join("\n")
f.close
```
### Record time per day
```ruby
date_minutes_map= summaries_for_user.group(:date).sum(:minutes)
output_array= []
date_minutes_map.keys.sort.each do |date|
  output_array << [date, date_minutes_map[date]]
end
f = File.open("/tmp/time_per_day.csv", "w+")
f.print output_array.map{|row| row.join(",")}.join("\n")
f.close
```

### Record pages per collection
```ruby
pages_per_collection = user.deeds.where(deed_type: DeedType.collection_edits).group(:collection_id).count(:page_id)
output_array=[]
pages_per_collection.each_pair do |collection_id, edits|
  collection=Collection.where(id:collection_id).first
  if collection.nil?
    output_array << [nil, nil, edits]
  else
    output_array << [collection.owner.display_name, collection.title, edits]
  end
end
f = File.open("/tmp/pages_per_collection.csv", "w+")
f.print output_array.sort{ |a,b| b[2]<=>a[2]}.map{|row| row.join("\t")}.join("\n")
f.close
```

**Comment by saracarl** [comment]
Most likely do this using either HTML or markdown to pandoc.

**Comment by saracarl** [comment]
Ok.  Longer design discussion with @benwbrum  and here's what we decided:
1)  This belongs on the collaborator dashboard.  We should put it right under "Your Activity" and it should be a link that reads "Your Hours"
![image](https://github.com/benwbrum/fromthepage/assets/708566/174c2bef-a605-4824-95c4-acb5f2056f03)
2)   The "Your Hours" view should default to the last 7 days, and have a calendar selection widget for range similar to the Collaborators tab:
![image](https://github.com/benwbrum/fromthepage/assets/708566/7943e61c-3d2b-4cd4-8a41-17b108823990)
3)  We should show two things based on the dates:  a sentence "Michael Aleksa has contributed 81 hours and 32 minutes between July 22, 2023 and October 10, 2023" and a table of collections and pages (like the letter).
![image](https://github.com/benwbrum/fromthepage/assets/708566/8c41f62e-f7cc-47f3-89ac-0bde4f717dcb)
You can pull the table styling from the admin dashboard.
4)  Then there should be a button "download a letter" (this should produce the pdf as above in the issue, with the same data as shown on the screen).  


@benwbrum thinks we should build a maximum and minimum into the date picker to improve their experience.  Start date would be the date of their first ahoy visit/activity on the site.  End date date would be *yesterday*.  I think this is a nice-to-have, but worth exploring.
