### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2871]
The autolink button on the transcription view (with subject linking enabled) is missing the English message.

**Comment by sylvieed** [comment]
What message should the autolink button show?

**Comment by sylvieed** [comment]
The autolink, preview, and edit button tooltips on the transcription view are all missing English, Spanish, and Portuguese translations. 

Their translation IDs are shown [in the `_save_buttons` view](https://github.com/benwbrum/fromthepage/blob/main/app/views/transcribe/_save_buttons.html.slim#L3-L7); they are `autolink_tooltip`, `preview_tooltip`, and `edit_tooltip`.

The [translations file for this view](https://github.com/benwbrum/fromthepage/blob/main/config/locales/transcribe/transcribe-en.yml#L11-L21) is missing these three translations. To fix this, we can add these three lines at line 22 of transcribe-en.yml:
```
preview_tooltip: "Preview this page"
edit_tooltip: "Edit this page"
autolink_tooltip: ?
```

I'm not sure what the Autolink button does, so I don't know what phrase to add for the `autolink_tooltip`.

Translations would also need to be added to the [Spanish](https://github.com/benwbrum/fromthepage/blob/main/config/locales/transcribe/transcribe-es.yml) and [Portuguese](https://github.com/benwbrum/fromthepage/blob/main/config/locales/transcribe/transcribe-pt.yml) files, at line 22 of each.

**Comment by saracarl** [comment]
I think this needs a bit more investigation because when you hover over the buttons it shows which messages are missing and they don't have "tooltip" at the end.  e.g. `en.transcribe.save_buttons.preview`  So what's the disconnect?  Are we asking for the wrong (and missing) message in the view?

**Comment by saracarl** [comment]
Next step is probably to link to the line in the view so we can all see what the message key is.

**Comment by sylvieed** [comment]
[Here's the view](https://github.com/benwbrum/fromthepage/blob/main/app/views/transcribe/_save_buttons.html.slim#L3-L7). The keys are `autolink_tooltip`, `preview_tooltip`, and `edit_tooltip`. 

The Save and Done buttons use the same `title` key to store the tooltip message and they work, so I think the issue is only that the translations are not in the locales files. I'm not sure why the messages showing on hover are different, though.

Worst case, we could try it with and without the `_tooltip`.

**Comment by benwbrum** [comment]
The text for `autolink_tooltip` should be: `Suggest subject tags automatically`

**Comment by sylvieed** [comment]
Both the `autolink_tooltip` and just `autolink` translations need to be added -- both the button text and the button tooltip text seem to be missing.

So, these three lines should be added to the [translations file](https://github.com/benwbrum/fromthepage/blob/main/config/locales/transcribe/transcribe-en.yml#L11-L21) as well:

```
preview: "Preview"
edit: "Edit"
autolink: "Autolink"
```
