### ISSUE TITLE
Change “disable subject linking” to “enable”

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2872]
Having a negative default that is checked is awkward. We should make it unchecked by default but call it "enable subject linking"

**Comment by benwbrum** [comment]
What screen does this appear in?

**Comment by benwbrum** [comment]
Sorry, this wording appears in the collection settings page.

**Comment by benwbrum** [comment]
This appears in [the project configuration page for the sample collection](https://fromthepage.com/benwbrum/ben-s-test-collection/edit)

**Comment by benwbrum** [comment]
Url is https://fromthepage.com/benwbrum/ben-s-test-collection/edit
This corresponds to a route at https://github.com/benwbrum/fromthepage/blob/development/config/routes.rb#L77
The controller action for this route is at https://github.com/benwbrum/fromthepage/blob/development/app/controllers/collection_controller.rb#L337-L374
The line of code in the view is https://github.com/benwbrum/fromthepage/blob/development/app/views/collection/edit.html.slim#L45
The message key is in this locale file:
https://github.com/benwbrum/fromthepage/blob/development/config/locales/collection/collection.en.yml#L83


We suspect that the easiest fix to this (at least for the display) would be to change [line 44](https://github.com/benwbrum/fromthepage/blob/development/app/views/collection/edit.html.slim#L44) to `value: !@collection.subjects_disabled`

Some additional work might be needed in the `update` action to reverse the boolean in params, but try this first.
