### ISSUE TITLE
[FTP UT Library Install]: Problems with privacy settings for document sets (bug)

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#288]
When one creates a document set for an existing collection, the set is not given a default privacy setting, and clicking on the "edit" link produces a gray screen with a yellow alert triangle:

![image](https://cloud.githubusercontent.com/assets/4740995/14443987/53d8ab56-0008-11e6-9b6f-7ae622399932.png)

In the document list for the collection, documents appear to have different settings for public/private, even though in this case the entire collection is private; but even an apparent "public" setting does not make the document available for viewing by a visitor who is not logged in.

**Comment by benwbrum** [comment]
See stack trace at:
```
  Rendered document_sets/edit.html.slim (9.5ms)
Completed 500 Internal Server Error in 109ms

ActionView::Template::Error (First argument in form cannot contain nil or be empty):
    2:   h1 Edit Document Set
    3:   p If the document set is marked as public, works put within it will be readable even if the collection is marked as private.
    4: 
    5:   =form_for(@document_set, url: { :action => 'update' }) do |f|
    6:     =validation_summary @document_set.errors
    7:     =f.hidden_field :collection_id
    8:     table.form
  app/views/document_sets/edit.html.slim:5:in `_app_views_document_sets_edit_html_slim___3283201622595298714_23090100'
  app/controllers/document_sets_controller.rb:25:in `edit'


  Rendered /home/benwbrum/.rvm/gems/ruby-2.2.0@fromthepage_rails_3_from_github/gems/actionpack-4.1.2/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (2.0ms)
```

**Comment by benwbrum** [comment]
This should be fixed now.
