### ISSUE TITLE
autolink should also use canonical names

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#2882]
If you upload subject names, but don't have anything linked to the subject, the "autolink" button won't identify those subjects in the text.  It should.  (And it should also always check for the canonical name, not just the verbatim name.  Same implementation.)

from Dartmouth

**Comment by saracarl** [comment]
Transcriber asked for this today as well:

> When I find a term I want to index, but it is misspelled, I create an index entry using the pipe character.
> 
> For example: The thigh bone is the [[femur|femir]].
> 
> But, when I use Autolink later, it finds only the misspelled synonym, not the correctly spelled word (the index’s title).
> 
> The index’s title needs to be one of the synonyms that Autolink searches for.
> 
> You may have a good reason for not wanting a “pipe-created” title in the synonym list, and if so, that’s another good argument for an index’s list of synonyms to be visible and editable—to give users a way to handle cases like this one.
> 
>
