### ISSUE TITLE
[FTP UT Library install]: Interference between set/collection dashboards

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#289]
Document sets appear on the same level as "Collections" on the "Collections" page, as below:

![image](https://cloud.githubusercontent.com/assets/4740995/14444067/eae900ea-0008-11e6-99e0-33d3506dde8f.png)

When one clicks on a document set from this page, the initial overview page contains the document set and its documents, which can be viewed individually (from the "read" tab) and viewed page by page (from the "overview" tab) within that set (in a format identical to the collection view, below):

![image](https://cloud.githubusercontent.com/assets/4740995/14444121/47f84156-0009-11e6-9fd0-b178ab63336b.png)

But any click on another tab (versions, transcribe, settings, etc) from any of those pages directs the user (at least an admin user, because I can't see these when I'm not signed in) to the document page in the parent collection for the set, as below:

![image](https://cloud.githubusercontent.com/assets/4740995/14444163/944b3748-0009-11e6-9fd3-fc4d113bf4ca.png)

**Comment by benwbrum** [comment]
Painful as it may be, the right solution to what is fundamentally a breadcrumb problem is probably to implement nested routes, with a top-level for document set and child for work/page.  See the [rails guide on the subject](http://guides.rubyonrails.org/routing.html#nested-resources).

**Comment by benwbrum** [comment]
See also #25 and the work Diego did on this.

**Comment by atomrab** [comment]
Is the nested route solution something the library needs to implement, or something that you will/have implemented? The issue still appears on the current library install -- is there an update we should apply?
