### ISSUE TITLE
page status in settings tab

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2911]
![image](https://user-images.githubusercontent.com/708566/145888428-26c83318-9ff3-4b5d-bc64-b3456537059e.png)

This doesn't actually set the status if you set it to done.  I suspect we should remove it.

Dartmouth reported.

**Comment by benwbrum** [comment]
Correction: this does set the status correctly, but does not recalculate work statistics, so the progress bar is not updated.

**Comment by benwbrum** [comment]
Correction -- for some pages (ones that have never been transcribed?) the status is never saved.  This should be fixed and we should recalculate the progress bar statistics.

**Comment by saracarl** [comment]
So "completed" seems to work now, but if you change the status to "not started" the page status bar stays green.

Also, the "pages" view where you set this has a "status" column that says "ready to transcribe".  We have no idea what drives this, but it's not the same as the rest of the statuses.  We should either make it match the status on  the read work view (probably the right thing) or remove it.
