### ISSUE TITLE
UI -- login improvements for transcribers vs owners

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#292]
I like this UI for clarifying work owners vs transcribers and sending them to different places.

![upworkui](https://cloud.githubusercontent.com/assets/708566/14465985/a301561e-009a-11e6-8f1f-07bca594edb1.png)

**Comment by tbl73** [comment]
@saracarl - seems like this is probably covered in the dashboard functionality, is that correct?

**Comment by saracarl** [comment]
this is still an interesting idea, but it's not a problem we are trying to solve right now.  closing.
