### ISSUE TITLE
"pages needing transcription" doesn't show incomplete pages

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2929]
MO State Archives is reporting to "pages needing transcription" only shows incomplete pages, not incomplete pages.  

Transcriber also reports the same thing on a separate collection.

**Comment by benwbrum** [comment]
Transcribers are upset when the look for work and everything looks done.  Currently the Pages needing transcription button shows a call to action for unstarted pages, and just the page text for incomplete pages.  

Here's how we should change this:
- Have the button show unstarted and incomplete pages by default
- Show a call to action on incomplete pages -- possibly replacing the text with a teaser
- Add a "show all" vs. "only show untranscribed pages" filter similar to our completed work list.

**Comment by benwbrum** [comment]
In addition, we should address #2822 to help transcribers find things they worked on that isn't complete.
