### ISSUE TITLE
sorting "Works List" by "percent complete" doesn't work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2944]
When you click on the "works list" tab of a collection or document set, then select "percent complete" in the "sort by" drop down, you get a list like this:

![image](https://user-images.githubusercontent.com/708566/150380483-f4735f5a-7d0a-4e80-a090-806d02039412.png)

Which is definitely not sorted by any visible percent complete number I can see.  

I will note that when I do the same sort I get the same list as SusanGray, so at least it's consistent.

**Comment by benwbrum** [comment]
We should probably convert this to use Datatables.

**Comment by saracarl** [comment]
To address the 2nd half of your questions, @symmetrically: 

_Can you please describe the difference them & the formula for calculating the many different percentages (transcribed percentage, corrected percentage, review percentage etc) ?_

Pages have statuses (I almost said state, but these overlap quite a bit); the percentages are just "pages with that status/total of pages in the work" (work = document; could be a 2 page letter or a 500 page book).

- transcribed percentage:  A page that has been edited and any text typed into it is "transcribed".  (We can't tell that it's "done" based on this, but we infer "transcribed" by the presence of any text on the page.  I suspect, but @benwbrum can confirm, that we figure this out from the page versions -- or maybe we store it on the page?)
- corrected percentage:  similar to transcribed, but for projects that import OCR (and in the next year or so, handwritten text recognition) to be corrected.  Pages with imported text aren't corrected until the first edit is made.  There's a work attribute for whether a document is an OCR correction project or not.
- reviewed percentage: Review in FromThePage is optional, so this gets confusing.  There's a "reviewed" status that gets set to true when someone either unchecks the "needs review" checkbox (optional review) or "approved" (required review".  Do we actually show a "% reviewed"?  I think instead we show a "% needing review", which makes more sense in the optional review scenario -- pages with "needs review" set to true / total number of pages.

I wrote all of this from memory, so if the code contradicts anything, the code wins.

@anabeabas would you create a wiki page on github called "Understanding Page Statuses" and add this and create a trello card for us to work together on customer facing documentation on the same thing?  I've got a conversation in Intercom with John F where he asks a bunch of the same sorts of questions, so we obviously need to document this better for everyone.
