### ISSUE TITLE
restrict work checked with no collaborators

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2952]
In a private collection, a project owner checked "restrict collaborators" at the work level but didn't add any collaborators.  I'm not sure what the right approach is, but this is a problem.  Definitely catch it when you save?

Maybe the right solution is not to have it for private collections?  

I think there's a UI issue with sending folks to the work settings tab too much; I'll open a different issue for that.

**Comment by benwbrum** [comment]
Let's modify the work settings view to add a warning message if the work is restricted but the work collaborator count is 0.  The warning message should be displayed near the "restrict collaborators" button/option/thingy, and should read "Only project owners can edit this work.  Add collaborators to make the work editable by others."
