### ISSUE TITLE
owner dashboard work title links you to work settings and shouldn't.

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2953]
If you own a project, the work list in your owner dashboard links you to individual work settings pages. 

i.e. Here:

![image](https://user-images.githubusercontent.com/708566/150871724-428ba08a-3211-4bd0-85b5-f7dc6a31ad09.png)

links you to:
https://fromthepage.com/josie/ann-smith-letters/21460/edit

The problem is that project owners should rarely edit work settings.  (Most of the time they should edit collection settings.)

We should just link this to:
https://fromthepage.com/josie/ann-smith-letters/21460/

@benwbrum Can we make this one of @sylvieed's issues sooner rather than later?  :)

**Comment by sylvieed** [comment]
The [view for the Owner Dashboard](https://github.com/benwbrum/fromthepage/blob/main/app/views/dashboard/owner.html.slim#L16) creates a link to `edit_collection_work_path(c.owner, c, w.id)` for each work. Changing this to `collection_work_path(c.owner, c, w.id)` should fix this issue.

**Comment by saracarl** [comment]
Looks like the right solution, @sylvieed

**Comment by sylvieed** [comment]
It'll actually be `collection_read_work_path(c.owner, c, w)`
