### ISSUE TITLE
Importing from zip file on server

### ISSUE THREAD

**Issue by plutext** [benwbrum/fromthepage#2958]
Is there a good way to import/upload the contents of a zip file located in the file system of the server running FromThePage?

I guess I could SSH into the server and do this using a text mode web browser, but it would be nice to be able to do it from anywhere when signed in as the collection owner from the "Start a Project" page,

The benefit of this would be that large zip files wouldn't need to be uploaded over thin pipes.  Thanks.

**Comment by benwbrum** [comment]
We experimented with a sideload function back around 2006, but removed it around 2010 as it was overcomplicated and not really used.  Currently most projects that have really large images already host the images elsewhere on a IIIF-compatibile image server, so they can just use the IIIF integration to import the images and metadata for those works (or entire collections).

**Comment by plutext** [comment]
Thanks for the background.  

In my case I have 258 images in a 1.92 GB zip file.  

Turns out a text mode browser isn't so easy, since most of them don't support Javascript.  browsh does, but it depends on firefox, which in turn has a lot of deps.  X isn't installed on the server, so a remote X session isn't an option.

**Comment by benwbrum** [comment]
Those are some *huge* images!  FromThePage will compress them down to the greater of _1MB or 90% compression_ after they are uploaded to create access copies anyway, so I'd recommend compressing them before uploading them.

**Comment by plutext** [comment]
Thanks, I've come up with a good workflow for getting photographed documents into shape for FTP.  Paint.NET and digiKam are the key tools I'm using.  Paint.NET is useful for splitting pages and cropping; it also compresses on save which is nice.

**Comment by benwbrum** [comment]
Great!
