### ISSUE TITLE
language settings are not working (for Sara only?) in production

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2964]
So switching the language works fine in a dev environment, but doesn't work in production (for my account, at least).  The logs show a call to switch_locale, but no errors or messages.  

We need to figure this out before we cut a release that UT would use. 

Actually, I signed in as Sylvie and tested changing languages in production there, and it worked fine.  So, huh?  But I don't think it's as important as we thought.

**Comment by benwbrum** [comment]
We've determined that this is because Sara and I can't update our user accounts on production because of an AR validation which fails because of duplicate keys (`login`?  `email`?) which should be unique.  This is probably a side-effect of merging the Fordham and Zebrapedia databases into FromThePage.com

**Comment by benwbrum** [comment]
I've fixed the data in production by analyzing users with duplicate `login` values, identifying the less-active account, then changing its login:

### Analysis
```ruby
dup_logins = User.select(:login).group(:login).having("count(*) > 1").count.keys
dup_users = User.where(login: dup_logins)
users_to_review = []; dup_users.each{|u| users_to_review << [u.id, u.login, u.email, u.deeds.count, u.created_at, u.updated_at] }
f = File.open('/tmp/users_to_review.csv', 'w+')
f.print ['id', 'login', 'email', 'deeds', 'created', 'updated'].join("\t")
f.print("\n")
f.print(users_to_review.map{|row| row.join("\t")}.join("\n"))
```

Analyzing this file should determine which user IDs need their logins changed.

### Remediation
```ruby
# Rename logins for migrated users
inactive_ids = [32001188, 32000459, 32000785, 32002119, 32000944, 32000353, 537, 228125, 32000358, 32001120, 521, 202416, 32000373, 32001178, 32001846, 32000226,32001121, 32000763, 32000316, 32003096, 221114, 32002731, 32000744, 32000007]
inactive_users = User.find(inactive_ids)
inactive_users.each { |user| user.login = user.login+" (old)"; user.save!}
```
