### ISSUE TITLE
Extra white space showing up on text editor box when selecting Fullscreen Layout

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#2967]
A FromthePage user reported that, while on their browser zoomed to 175% or greater and after selecting Layout: Image and then Fullscreen, the text editor box shows extra white space at the bottom of the existing text lines. The extra lines are not numbered but the user was able to insert their cursor in that area. They added that among the existing text lines, there will be places that they could not insert their cursor, and these places seem to be random. It stops them from editing where they need to.

They learned that if they click the browser “refresh” button after selecting Layout: Image at the top, the problem is solved, and everything works as normal. However, if they later try to change the current Layout to something else, the problem recurs. According to the user, it happens on Chrome, Edge, and Firefox browsers.

How to Reproduce:
1. Select a "Started" document.
2. Select Layout: Image at the top, then select Fullscreen.

**Comment by benwbrum** [comment]
That makes sense.
