### ISSUE TITLE
Receiving Internal Server 500 Error when using '/' in Document Date field

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#2976]
Molly of History Revealed emailed us about getting an Internal Server 500 Error. She said it happens when adding information to the Additional Metadata section, specifically in the Document Date field. It wouldn't accept 1786-1787 or 1786 to 1787, but it accepted 1786/1787.

Whenever she tried entering anything other than a '/' in the date field, this showed up:

1 error prohibited the form from being saved:
Document date must be in EDTF format

Fix:
- "change the "date" field on a work's additional metadata to a string

**Comment by benwbrum** [comment]
Changing this date field to use an input mask (like we did in https://github.com/benwbrum/fromthepage/commit/baba15f2c580d7824f59daff8b47f5017bf37f03 ) is probably the best solution.

**Comment by sylvieed** [comment]
Line 26 of `app/views/transcription_field/_metadata_field_layout.html.slim` from that commit

**Comment by benwbrum** [comment]
Further usability enhancements are needed here:
We should display a hint/help text under the date entry field saying something like this:
`Document Date is in the EDTF format (e.g. 1843, 2001-02, 1643-06-30)`

We should also figure out why the code is January-padding: when the user enters 1862, the form reloads as "1862-01-01", which is incorrect.  This might be a problem in an EDTF library we are using, or in the MySQL date column type (if we are using that), or in some ActiveModel attribute accessor.
