### ISSUE TITLE
Request to No Longer Display Counties for Document Sets for WWI on LVA Page

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#2982]
Sonya at LVA emailed us asking to no longer display the counties for the document sets for WWI on the LVA page on FtP. She said that it was pushing the Virginia Untold collections too far down the page, making it difficult to spot for users.

**Comment by benwbrum** [comment]
I'd hoped that we could do a work-around for this by adding a space at the beginning, but that doesn't seem to affect sort order.
