### ISSUE TITLE
Download template for metadata

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3003]
Wilford Woodruff emailed us requesting for the download template for metadata to include data already there.

![Wilford Woodruff](https://user-images.githubusercontent.com/98731543/154081026-b4a02283-d106-4609-a0cf-c0eeabc2d148.jpg)

**Comment by benwbrum** [comment]
Sue Purdue also needs this:

> I am working with the metadata upload feature. I thought I could download the existing metadata for the collection, clean it up (add to and correct), and then upload the new file thereby making the changes in the metadata. I haven't been able to upload the corrected file and keep getting the attached error file. My corrected file I am trying to upload is also attached. I have not added any new metadata fields in columns E or F.
>  
> This is the collection
> https://fromthepage.com/fdp/correspondence-volume-3-1866-1880
>

**Comment by benwbrum** [comment]
See also #3138 .  I do not think that any users are likely mix imported metadata and uploaded metadata in the same collection, however.

**Comment by benwbrum** [comment]
Covered in #2979
