### ISSUE TITLE
Metadata download needs work_id

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3005]
An email from Wilford Woodruff: metadata download needs work_id.

![Wilford Woodruff](https://user-images.githubusercontent.com/98731543/154082963-83f31ba7-4b6b-4641-aad1-2271ab507b29.jpg)

**Comment by benwbrum** [comment]
Look at the collection export screen; at the bottom there is a work metadata csv button.  That will run an export that generates a CSV.  Add a new field to that CSV.  

There's a block of code that defines the headers -- add a column header there.
There's a block of code that defines the values -- add values there.

**Comment by sylvieed** [comment]
It looks like right now there's a column called "FromThePage ID" and its value is `work.id`, which seems like what the customer wants. Should I just rename this to "Work ID"?

![work metadata export has FromThePage ID](https://user-images.githubusercontent.com/35716893/159276820-2d0422d7-4dd8-4eb6-8f33-563685519bcd.jpg)

**Comment by sylvieed** [comment]
Instead we will add `work_id` in the metadata download after "Pages Marked Blank"
