### ISSUE TITLE
Work versions count is wrong

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3006]
Wilford Woodruff sent an email stating that the work versions count is wrong. They also asked to remove "transcription version".

![Wilford Woodruff](https://user-images.githubusercontent.com/98731543/154083084-7fd4eafb-6df6-47dd-a66b-9fac24d72a3d.jpg)

**Comment by benwbrum** [comment]
We should remove the Versions tab from the work tabs altogether, and remove the Transcription Version element from the work About tab.
