### ISSUE TITLE
UI Styling for Quality Reviews

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3017]
Video walk-through of the new feature and how to find it:

https://www.loom.com/share/14f1f8ba9cde4422b2e07febc02514ae

Use the DB dump we sent you, user cehorton, password password.

The goal of this feature is to help project owners on FromThePage identify the *right* pages and transcribers to review, rather than having to review *everything* in a collection.  We do this with a couple of different approaches:

1. New transcribers often need review early in the process; if you catch their mistakes and gently correct them, then they are less likely to make mistakes later.
2. "one-off" transcribers only transcribe a single page or part of a page; they are the lowest quality transcribers and you need to review everything they do.
3. "quality samplings" where we guide you to pick a statistically significant set of pages across transcribers and works, review them, and then we use the results of that review (For each page did you have to change the transcription?  how much?) to highlight the most problematic transcribers and works.  (i.e. the typewriter at a certain place was never cleaned, so the documents/pages from there are terrible to read & transcribe.)  The idea is you don't have to review everything, but you can identify what needs closer attention.
4. We also show you the list of all works; I'm not sure that even belongs here, but it's a nice interface if you want to skim through everything and choose certain things to look at based on your intuition or experience.  (This is probably the lowest priority/should be listed last in any view.)

With that in mind, here's what needs UI work:

- [ ] [Review Dashboard](http://localhost:3000/indianaarchives/indiana-wwi-service-record-cards/review) -- this has data and calls to action, mixed together.  We're really not sure how this should be presented.
- [ ] [Quality Samplings View](http://localhost:3000/indianaarchives/indiana-wwi-service-record-cards/quality_samplings)  
- [ ] Skip "New Sampling" for now -- we're still working on the functionality.
- [ ] [Sample Details](http://localhost:3000/indianaarchives/indiana-wwi-service-record-cards/quality_samplings/5) -- note that this has both transcriber lists and work lists that we need to display better.  The "relative corrections" is one of 5 quintiles (20% each) that need to be indicated.
- [ ] We're pretty happy with the UI for reviewing pages in this context (the "review" button and the review URL).
- [ ] [User Contribution List](http://localhost:3000/indianaarchives/indiana-wwi-service-record-cards/user_contribution_list/krhorton) -- shows you everything the user did in this collection, in time order, with any notes they left.  The project owner or review can review individual pages (maybe the ones with notes) or every page.  We'll be adding an "approve all" so that once they are OK with this user they can approve the rest of their transcriptions.
- [ ] We'll need to add some sort of action with the works; likely similar to the user contribution list.  @benwbrum -- let's do this next so @kolking  has that view to work on.
- [ ] [Recent Contributors](http://localhost:3000/indianaarchives/indiana-wwi-service-record-cards/recent_contributor_list) needs work.  When you click on a contributor, though, you get to the same view as the User Contribution List, so that shouldn't need work.
- [ ] The [One off Contributors](http://localhost:3000/indianaarchives/indiana-wwi-service-record-cards/one_off_list) list is almost identical to the recent contributors view.
- [ ] [Works with Pages Needing Review](http://localhost:3000/indianaarchives/indiana-wwi-service-record-cards/works_to_review) needs work.  This is based on what project owners are already doing; it just gives them a space to scan everything and see what's going on.

I think that's it, but if we missed anything let us know and we're happy to provide more info.

**Comment by saracarl** [comment]
Our work is in branch [2129-quality-control](https://github.com/benwbrum/fromthepage/tree/2129-quality-control)

**Comment by saracarl** [comment]
We've got the sampling set-up screen ready, too, but it requires a db migration and will wipe out the good test data you've got in your DB version.  So...  when you're done with the rest, we can give you that code to work on that specific view.  It's 1 page.

**Comment by kolking** [comment]
@saracarl @benwbrum Hi Sara and Ben!

I did the following:
- Re-created the DB using the new dump you've sent
- Applied all migrations
- Switched to `2129-quality-control` branch
- Logged in as `cehorton` user

As far as I understood from the walk-through video, I should start working on the Review (Dashboard) page, and Quality Sampling page. The Review Dashboard page looks similar to what I saw in your video, but the Quality Sampling page looks a bit different.

This is how it looks in your video:
![image](https://user-images.githubusercontent.com/4656448/154936352-d530dc3d-dc04-48d2-8b70-acbc1211be0a.png)

And this is how it looks in my local environment:
![image](https://user-images.githubusercontent.com/4656448/154936762-c5c5c29e-9dbb-4615-a6fb-5b4afc9713ef.png)

So before start, I'd like to check maybe there are some changes you haven't committed to the repo yet? Or maybe I've missed something during setup?

**Comment by benwbrum** [comment]
HI @kolking.  Since we worked together last, we've internationalized the interface, so the wording for the UI should live in `config/locales/quality_sampling`.  It looks like your browser/user account is not set to use English, so it is missing the wording.  (If I'm correct, the `onHover` pop-up will display a "message missing" error.)

You can adjust this in your browser by adding `en` as an option, or you could modify the user profile for the `cehorton` account:
* Click the menu drop-down in the upper right corner of the layout
* Chose "Your Profile"
* Edit Profile
* Change the Interface Language to English.

**Comment by benwbrum** [comment]
I've just pushed updated code with a new/different mechanism for creating quality samples.  You'll need to do this to see it (when you're ready):

- Pull down the new code from the same branch
- migrate your database
- create a new quality sampling
- use that sampling instead of the link Sara provided for the Sample Details view.

**Comment by kolking** [comment]
@benwbrum thanks Ben, I've set interface language to English in the profile and it works.

**Comment by kolking** [comment]
@benwbrum I've pulled the last commit and run migrations. Now when I click the "1 Quality Samplings" link at the Dashboard, I see this error screen:
![image](https://user-images.githubusercontent.com/4656448/155016670-af91434a-9cd8-408a-a714-2192ab96021e.png)

**Comment by benwbrum** [comment]
You'll need to delete the existing quality sampling data from the Rails Console ;`QualitySampling.delete_all`

Then create a new quality sampling in the UI.

**Comment by kolking** [comment]
@benwbrum deleted all. Now when I try to create a new sampling:

- When choosing "Each Work" (default value), then I see this error right after clicking Sample button
![image](https://user-images.githubusercontent.com/4656448/155022307-45c93d0e-1969-4f11-9c3b-342f37977fa2.png)

- When choosing "Each User", then it will create without error, but if I click Details button on the next screen, it will fail with this error:
![image](https://user-images.githubusercontent.com/4656448/155022515-8dd1444c-9f81-43c3-b649-d43b213a30d1.png)

- "Together" and "All permutations" options seems to work, but there are no corrections (to design the labels at least) and I have no idea how to fill in the table (add some corrections)

**Comment by saracarl** [comment]
@kolking We obviously didn't test this enough before handing it off to you.  Apologies!  We'll take a look and see if we can get it back to you in a working state in the next 24 hours.

**Comment by saracarl** [comment]
@benwbrum this is what I'm {still} getting:

> ActionController::UrlGenerationError at /indiana-deceased-world-war-ii-veterans/indiana-deceased-world-war-ii-veterans/quality_samplings

> No route matches {:action=>"show", :collection_id=>"indiana-deceased-world-war-ii-veterans", :controller=>"quality_samplings", :user_slug=>"indiana-deceased-world-war-ii-veterans"}, missing required keys: [:id]

At line 39 of _app_views_shared__review_breadcrumbs_html_slim___2069837338958050786_97940app/views/shared/_review_breadcrumbs.html.slim
