### ISSUE TITLE
spreadsheet ruler configuration isn't saving

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3022]
So I don't think the selection for setting the rows is working.  I selected with the top of what you see of the highlighted row as the top of the spreadsheet.  However, it only gets highlighted when you get to the 3rd row on the spreadsheet.

![image](https://user-images.githubusercontent.com/708566/155170839-49c7aee0-a9f2-41b2-8b05-9c66dc266127.png)

**Comment by benwbrum** [comment]
It looks like when we configure the spreadsheet rows, we are never storing the offsets in the DB:
```
2.7.1 :009 > TranscriptionField.find 4010
 => #<TranscriptionField id: 4010, label: "speadsheet", collection_id: 32000098, input_type: "spreadsheet", options: nil, line_number: 1, position: 1, percentage: nil, page_number: nil, starting_rows: 48, top_offset: 0.0, bottom_offset: 0.0, row_highlight: true, field_type: "transcription"> 
```
