### ISSUE TITLE
metadata documentation

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3036]
https://content.fromthepage.com/project-owner-documentation/metadata-upload-metadata-browse/

getting metadata in (upload, metadata.yml)
Displaying -- about page
using for faceted browse
Creating metadata (new feature)
revising metadata (uploading/creating + new feature)

**Comment by masonacjones** [comment]
https://docs.google.com/document/d/1EbE9TBpLPQNi65p85dN8AO45rHZy-fVtnL555eunX98/edit?usp=sharing

Little progress here, but created a dedicated doc to add to.

**Comment by benwbrum** [comment]
Check out the top four videos in the search results here: https://www.youtube.com/user/fromthepage/search?query=metadata

One of the most confusing bits is the flow.

### Ways to get Metadata into FromThePage

- Import from IIIF; the `metadata` block will be ingested into our `original_metadata` block on each work.
- Import a CSV on the settings screen; each row will update the `original_metadata` block on the corresponding work
- Project owner typing metadata into the work settings screen.  (Updates limited, pre-defined work-specific fields.)
- Project owner uploading `metadata.yml` along with a zip file image upload (Updates limited, pre-defined work-specific fields.)
- End user creates metadata through a metadata creation project (updates a `metadata_description` block on the work)

### Ways FromThePage uses metadata in the UI
- The work About screen displays pre-defined metadata fields as well as `original_metadata` block contents.
- If project owners set up metadata facets the facets may be used for discovery/filtering of works
- 

### Ways FromThePage exports metadata
- IIIF API exposes `original_metadata` block and pre-defined fields
- TEI exposes pre-defined fields in very specific TEI elements
- Work Metadata CSV Download produces a spreadsheet containing `original_metadata` and user-generated metadata.
- New structured API (in draft)

**Comment by masonacjones** [comment]
Hi @benwbrum and @saracarl. Apologies for the delay on getting these to you. I'm back to working in full force this month! I've added these three documents for metadata documentation with more to come. Currently working on metadata exportation documentation as well- will have some questions about that soon. Also working on IIIF documentation in conjunction with the CONTENTdm included below.

https://docs.google.com/document/d/1NDA87joREh-ikACoNiuuuOFGxfeRRgKPyczVjF3Pffk/edit?usp=sharing

https://docs.google.com/document/d/19bRtwuO0Dl3bH16IWsGVCdRsApc-col0c_KgGqHdp2Q/edit?usp=sharing

https://docs.google.com/document/d/1VwKf0DGCIMGmhvjwDfxEikgJrEyr_X1iirC0vcBalUk/edit?usp=sharing
