### ISSUE TITLE
No "save" button on full-screen transcription in iOS

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#304]
Rebecca reports:
On an Ipad mini, the full-screen view excludes the save button. Reverting to standard causes all transcription to vanish. This is really frustrating. Any way to fix this via:
floating save button?
key function for saving that will work on a bluetooth keyboard without F keys?
auto save that can be turned on/off? (this would be a great idea anyhow, perhaps… as people expect it due to Googledocs, 360, etc.?)

**Comment by benwbrum** [comment]
Rebecca continues:

> I just looked at this on a full-size ipad belonging to one of the student transcribers (Riley Burger.) SAVE definitely not visible in full screen

**Comment by benwbrum** [comment]
Current workaround:
> How I troubleshoot the disappearing-”save”-button-on-IPad Mini: use the Mini in “portrait” orientation. With the facsimile above the transcription box (yes, the best configuration for pages WITHOUT CENTRAL ENGRAVINGS) - the button remains visible.

**Comment by kolking** [comment]
@benwbrum I'll try to rework the layout to keep the button always visible, probably it may require to hide some secondary interface element(s) on a small screen width (ipad portrait mode)
