### ISSUE TITLE
Metadata for Project Discovery

### ISSUE THREAD

**Issue by bethanycayeradcliff** [benwbrum/fromthepage#3043]
Here's the Google Doc with the updated metadata tags for the FtP projects: https://docs.google.com/spreadsheets/d/1FVpjSFHI-5B08wVDHnp7OYe8gmUgW0pRhYLj3vH0bY8/edit?usp=sharing

I've also attached an xlxs: 
[CollectionMetadata_FtP.xlsx](https://github.com/benwbrum/fromthepage/files/8238921/CollectionMetadata_FtP.xlsx)

Let me know if you need anything else for this.

**Comment by benwbrum** [comment]
We've processed this and are incorporating it into the product.
