### ISSUE TITLE
Upload Transcriptions or OCR With Page Images

### ISSUE THREAD

**Issue by masonacjones** [benwbrum/fromthepage#3045]
https://docs.google.com/document/d/1h0CD03v9ctr7Qgq-CdhD0tupg7Ku0VHSUFPKsub-ldE/edit?usp=sharing

**Comment by anabeabas** [comment]
https://content.fromthepage.com/project-owner-documentation/uploading-transcriptions-or-ocr-transcripts-with-page-images/
