### ISSUE TITLE
Saving transcription should save unsaved notes

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#305]
One user is reporting that they "can't transcribe and add notes at the same time".  On further investigation, the project owner isolated the problem to this:

> i just tested this. if you alter the transcription, add a note, and save the transcription, the note box empties itself. But the other way around - transcribing, typing notes, saving the notes THEN the transcription - works fine. the unsaved transcription remains. so now it's important to remember to just not save the transcription BEFORE finishing and saving the note.

**Comment by kolking** [comment]
@benwbrum not sure what would be the best solution here. Transcription and notes live in their own separate forms. I don't really think that saving **not published** notes silently when user clicked to save the transcription is a good idea. Any thoughts?

**Comment by benwbrum** [comment]
We could check for unsaved notes when a user tries to save a transcription,
then add a dialogue asking if they want to "Save or Discard their note"
