### ISSUE TITLE
Easier way for transcribers/indexers to find & reference subjects

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3064]
> In the project I’m working on, I’m up to 272 index titles.
> 
> I’m having trouble remembering what each title represents.
> 
> The text search box for the project only looks at “pages,” not index descriptions.
> 
> It’s inefficient to go guessing and clicking on title-links to see if that’s the one I’m looking for.
> 
> My suggestion is that the Subjects tab show the indexes as a two-column table.
> 
> First column is Title, second column is Description (see pic below), and the Title is still the hyperlink.
> 
> This way I could use the browser’s search function to find something in the description.
> 
> I could also copy it to a spreadsheet for sorting, etc.

**Comment by benwbrum** [comment]
We think that this is best handled via #3193
