### ISSUE TITLE
rotated images can't pan to bottom

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3065]
If you look at this page:
https://fromthepage.com/folger/newdigate-family-collection-of-newsletters/lc2106/transcribe/25077910

And try to read the text that is written sideways in the margin, you'll discover that you can zoom and pan to see the first 2-3 lines of it, but you if you pan more than that it just slides back towards the center.

True in the default view and the full screen view.

**Comment by kolking** [comment]
@saracarl it sounds like a bug in OSD. The plugin does all image manipulations - zoom in, zoom out, panning, rotating, etc.

**Comment by saracarl** [comment]
dupe of #3246
