### ISSUE TITLE
Improve zoom persistence between pages

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#307]
User-reported:

> However, is there a way to keep the magnification in “transcription” as a default when changing pages? Here’s what I do now:
> Open page
> Click “transcribe”
> Click + + 
> Transcribe
> Save
> Write note 
> Save note
> Next page
> Transcribe
> Click + + 
> Etc.

**Comment by saracarl** [comment]
This was requested again by a transcriber working for Alabama.

We should finish the switch to openseadragon (#1531) so we only have to do it once.

**Comment by benwbrum** [comment]
We currently store the persistence between pages.
