### ISSUE TITLE
Work uploads with numeric filenames

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3074]
LVA ran into an upload issue.

> Ah!  Ok.  I took a closer look at the 2 that were hanging.  I think they should have failed, instead of just hanging, because I'm seeing this in the logs:
> 
> ```
> Found 280 image files in /tmp/fromthepage_uploads/32002985/1138339 -- converting to a work
> convert_to_work creating database record for /tmp/fromthepage_uploads/32002985/1138339	
> convert_to_work owner = LVA	
> convert_to_work collection = Virginia Untold: Free Registers (indexing)	
> convert_to_work default title = 1138339	
> convert_to_work looking for metadata.yml in /tmp/fromthepage_uploads/32002985/metadata.yml	
> convert_to_work no metadata.yml file; using default settings	convert_to_work loaded metadata.yml values 
> rake aborted!
> ActiveRecord::RecordInvalid: Validation failed: URL must have at least one letter
> ```
> 
> And that clued me in to what's happening, and why that error is occurring for the last two uploads in your set. 
> 
> We deployed a fix for another problem yesterday -- and we discussed that we needed to talk to LVA about this beforehand, and failed to do so -- which starts requiring a non-numeric character in the title of works. (Titles are used for the "slugs" -- the ending of the URL for the work -- which is why this is giving a "URL must have at least one letter".) The underlying problem this solved was a situation where documents had numbers like "1886" as their slug, and our look up code very quickly got confused on whether that was a slug or an identifier. 
> 
> It is totally reasonable for you to the PDFs that are named with your identifier numbers. And it's reasonable for us to use those as titles, and then as slugs. But this conflicts with the new requirement. 
> 
> I'm going to suggest 2 things: 
> 1) To get you going with these last 2 pdfs, you can rename (stick a letter at the end of the filename?) and reupload them. 
> 2) We'll discuss how to fix this on our end -- we'll probably append a letter or character automatically to the end in these cases -- and get it fixed in the next week or two. (Sooner, if you have a lot of pending uploads -- let me know.)
>

**Comment by saracarl** [comment]
@sylvieed Take a look at this.  :)

**Comment by sylvieed** [comment]
LOV is going to use a dash or underscore in their titles so this will be okay.
