### ISSUE TITLE
can't save notes on metadata forms

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3083]
Comments can't be saved on metadata fields:

![image](https://user-images.githubusercontent.com/708566/162228191-0704b5e3-eb12-4f1f-9a81-fbc7b9ac15d6.png)

```
F, [2022-04-07T14:52:58.263598 #10629] FATAL -- :   
NoMethodError (undefined method `notes' for nil:NilClass):
  
app/models/note.rb:31:in `email_users'
```

**Comment by benwbrum** [comment]
Resolved by #3823
