### ISSUE TITLE
approve all for review/quality control dashboard

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3093]
> At our last meeting we discussed adding an "approve all" option so that works completed by specific users (in specific collections) could be approved from the administrative dashboard, and Sonya confirmed the need for this. While it wouldn't be advisable for some collections (like our voter registration books, with various handwritings and multiple contributors per work), it could really save time in more traditional transcription projects where handwriting is more consistent and individual works are shorter.
> 
> Another option to achieve a similar outcome might be to allow admin users to approve entire documents from the "Works with Pages Needing Review" page. As it is now, you have to click through a document to approve pages individually, even if a work is completed by a contributor with a high accuracy score. If it were possible to select and approve multiple documents at one time from the dashboard, then the list would shrink and it would be easier to focus on works or users that merit more attention. A potential use scenario would be a large, consistent collection where everything is automatically tagged as needing review by default, but staff have decided to focus their review efforts on contributors with a quality score of less than 95%. (CONTENTdm gives a similar option for its approval queue, so I'm attaching a snapshot to show what I mean--it doesn't perfectly fit this situation, it's probably clearer than my written explanation!)

<img width="618" alt="CDM_approval" src="https://user-images.githubusercontent.com/708566/162982098-4406c2a3-ddb6-42f2-89b6-7159a5ada42c.png">

**Comment by benwbrum** [comment]
This should be visible on the user contribution screen.  Unfortunately, this currently shows no contributions at http://localhost:3000/nationalarchives/british-army-officers-service-1853-1913/quality_samplings/37
