### ISSUE TITLE
Handling page headings that vary

### ISSUE THREAD

**Issue by NatWooding** [benwbrum/fromthepage#31]
In the earlier Grinnell notes that I have seen, the page heading appeared to always have the elements collector, locality, date, and page number. However, in the late summer survey in Mexico that he did with Lamb, the locality notes are sometimes more complex and can include latitude and elevation. E.g.: 
Collector: Grinnell - 1925
Date: September 27
Location: San Jose, 2500 ft. Lat. 31 degrees (altitude according to our aneroid)
Page Number: 2550

My question is whether to render the transcription as I did above or whether to break up the location to aid future parsing. E.g.
Location: San Jose
Elevation: 2500 ft.
Latitude:  Lat. 31 degrees
Instrument: (altitude according to our aneroid)

**Comment by saracarl** [comment]
Closing -- this was a project specific question and we should have passed it to the collection owner.  (Oops!)
