### ISSUE TITLE
routes for collections by name

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#310]
also, I think we could write routes to change this:

  get   'ZenasMatthews' => 'collection#show', :collection_id => 7
  get   'JuliaBrumfield' => 'collection#show', :collection_id => 1
to do a auto-lookup by name so it was extendable to all collections

**Comment by benwbrum** [comment]
Ideally we'd let collection owners specify the slug they wanted:

"Choose your URL: http://fromthepage.com/_text entry box with JS to kill spaces_"

That slug would get saved on the collection as a new column, and would be used to look up collection homepages.

We could create slugs dynamically in an upgrade and implement, if we want to post point the UI piece.

**Comment by saracarl** [comment]
dupe of #416

**Comment by saracarl** [comment]
please research.

**Comment by benwbrum** [comment]
See in particular my comments on https://github.com/benwbrum/fromthepage/issues/416#issuecomment-271313400

**Comment by tbl73** [comment]
Duplicated in #416, closing
