### ISSUE TITLE
autolink should choose first linked name in case of multiple verbatim strings

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3104]
> I have become impressed with how Autolink has improved as I have added markup to more pages in my collection. The value comes from training it on all the possible variations in the form of a subject, until it can correctly catch common misspellings and all sorts of abbreviations.  However, I have some names that autolink is now misattributing.
> Harold Noice is a significant figure in the collection I am working in, and I've associated the text "Noice" with the subject "Harold Noice".  This worked for a time, until I had a newspaper clipping that included his wife, "Frances Allison Noice" and at one point described her as "Noice" in the text.  Autolink is now suggesting Frances.
> 
> I also have another name that comes up frequently; subject "Allan Crawford" is a central figure and is often referred to as "crawford" in the text.  He died on the expedition that is the focus of the collection, and there are letters from his father, one "J. T. Crawford".  J. T. has also been tagged as "crawford" and now comes up as the primary subject.
> For the short term, if I remove the reference for J. T. Crawford as "crawford" and for "Frances Allison Noice" as "noice", will autolink revert back to tagging Allan and Harold as the default subjects?  I assume from the two cases above that the default behavior is kind of a "last in, first suggested".  In the long term, could you change how you determine the default subject to include the frequency of that text being used to tag a particular subject?  In the "noice" case, Frances shows up in one document whereas Harold shows up in seven documents (and multiple times within those docs).
> 
> If you have any advice on how to bring Allan and Harold to the fore, I would appreciate it.  We have another 433 works left to index in this collection!  :) 
> 

from Colin at Dartmouth

**Comment by benwbrum** [comment]
From Samara at Dartmouth:
 

> When more than one person or subject shares a name, the autolink feature tends to link that subject to the wrong person or place. I’ve assumed it was the last subject tagged that did this, but in one case I couldn’t figure out why it consistently tagged the wrong person. We have one subject named “Knight”, who is mentioned hundreds of times. The father of that subject is mentioned once, but now is consistently autolinked with the name “Knight”, no matter how many times the son is relinked to the name. I’ve resorted to deleting the tags on the one mention of the father so that the son is autolinked correctly.
> 
> I’m wondering if there could be an option on the subject profile page that allows us to “turn off” the autolink feature for certain tags. For example, every mention of “John Knight” would be autolinked, but mentions of “Knight” have the autolink feature turned off for this particular subject, so that “Knight” is autolinked to his son instead. It could help when people have common words as names as well, like “white” or “young”.
> 
> That was my thought and suggestion, though I wouldn’t know if it’s actually possible to do that. Other than that I really enjoy working on FromThePage, so thank you for a very cool product!

**Comment by benwbrum** [comment]
We're revising this to chose the most recently linked subject, which we think better matches editor flow (and it's more computationally feasible).
