### ISSUE TITLE
"Pages That Need Transcription" title on work view

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3127]
![image](https://user-images.githubusercontent.com/708566/165528690-4723bcab-3ec5-4ba4-8860-79cd5be6c2ca.png)

I'm not sure what introduced this, but it's showing up on all work views and it shouldn't.  We need to look at the "git blame" to see why we added it, then remove it from the generic view but make sure it doesn't break whatever use case we added it for.

**Comment by benwbrum** [comment]
Here's the code that has the issue: https://github.com/benwbrum/fromthepage/blob/main/app/views/display/_pages_view.html.slim#L3-L12

Here's the PR that introduced the regression: https://github.com/benwbrum/fromthepage/pull/3032/files#diff-d77e4b7e660abc6cb454d38c18052233e83fe77d81a4bfca9ca597ea3198da2a

**Comment by benwbrum** [comment]
Addressed in #3258
