### ISSUE TITLE
metadata upload fights with original_metadata

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3138]
There are two problems with the metadata upload:
1) It replaces `work.original_metadata`, which means that it's possible to blank out all the metadata you imported if you are just trying to update a field
2) It promulgates `title` an `identifier` into `original_metadata`, so if the user updates these in the UI, they will not see those updates reflected in the About screen.

**Comment by saracarl** [comment]
The example csv that you download from the collection settings/metadata UI should include *all* metadata -- our built in documentary editing metadata fields and any that you've previously created via metadata.yml or a metadata spreadsheet upload.  

We should make sure that uploading a metadata spreadsheet matches to existing metadata fields of *both* types before creating new metadata fields.

**Comment by saracarl** [comment]
let Audra at ARI know when this is ready.

**Comment by benwbrum** [comment]
Covered in #2979
