### ISSUE TITLE
document status 150% transcribed

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3141]
We've uploaded the papers of the first governor, but all the documents are displaying as being 150% transcribed:

 
![image](https://user-images.githubusercontent.com/708566/166797238-1973e5e5-f28b-46ce-8a03-ee7c4490b31d.png)

But if you click on an individual work, the status is correct:

![image](https://user-images.githubusercontent.com/708566/166797605-cc104805-856c-4280-b3e6-5be2d7a1726b.png)

**Comment by saracarl** [comment]
Some notes:

1. This seems to only be occurring on works that have no pages transcribed at all.  
![image](https://user-images.githubusercontent.com/708566/183990392-4d3962da-d0af-44e2-a0a9-c1fcc40160c8.png)
![image](https://user-images.githubusercontent.com/708566/183990498-b4a08f83-94c6-4970-a4a2-02cc93e3f760.png)

2. If I look at the "export" tab for one of these documents ("33040" for instance) it's also wrong, but in a way that might lead to the 150% percent.  
![image](https://user-images.githubusercontent.com/708566/183990246-ab70ed25-5e7d-46c2-8894-87ab448727d7.png)

**Comment by benwbrum** [comment]
Bad data seems to exist for the number of pages needing review in some of these:
```ruby
=> #<WorkStatistic:0x00007fa9549dba70> {
                      :id => 32017762,
                 :work_id => 32017763,
       :transcribed_pages => 1,
         :annotated_pages => 0,
             :total_pages => 2,
              :created_at => Thu, 21 Apr 2022 14:16:24 UTC +00:00,
              :updated_at => Wed, 04 May 2022 14:12:51 UTC +00:00,
             :blank_pages => 0,
        :incomplete_pages => 0,
         :corrected_pages => 1,
            :needs_review => 3,
        :translated_pages => 0,
        :translated_blank => 0,
       :translated_review => 0,
    :translated_annotated => 0,
                :complete => 50,
    :translation_complete => 0,
              :line_count => nil
}
```

**Comment by benwbrum** [comment]
After calling recalculate, the work statistic is totally different:
```ruby
=> #<WorkStatistic:0x00007fa9549dba70> {
                 "work_id" => 32017763,
             "blank_pages" => 0,
             "total_pages" => 4,
         "annotated_pages" => 0,
            "needs_review" => 0,
       "transcribed_pages" => 0,
                      "id" => 32017762,
              "created_at" => Thu, 21 Apr 2022 14:16:24 UTC +00:00,
              "updated_at" => Wed, 10 Aug 2022 18:57:22 UTC +00:00,
        "incomplete_pages" => 0,
         "corrected_pages" => 0,
        "translated_pages" => 0,
        "translated_blank" => 0,
       "translated_review" => 0,
    "translated_annotated" => 0,
                "complete" => 0,
    "translation_complete" => 0,
              "line_count" => 0
}

```

**Comment by benwbrum** [comment]
The work in question has four untranscribed pages, so how did we end up with such a strange initial value?
```ruby
[15] pry(#<#<Class:0x00007fa954416608>>)> work.pages.pluck(:status)
   (1.9ms)  SELECT `pages`.`status` FROM `pages` WHERE `pages`.`work_id` = 32017763 ORDER BY position
  ↳ (pry):20:in `work_stats'
=> [
    [0] nil,
    [1] nil,
    [2] nil,
    [3] nil
]
```

**Comment by benwbrum** [comment]
No deeds exist for this work except for the work add:
```ruby
[16] pry(#<#<Class:0x00007fa954416608>>)> work.deeds
  Deed Load (30.8ms)  SELECT `deeds`.* FROM `deeds` WHERE `deeds`.`work_id` = 32017763 ORDER BY created_at DESC
  ↳ app/helpers/collection_helper.rb:69:in `work_stats'
=> [
    [0] #<Deed:0x00007fa9553bf398> {
                      :id => 32522008,
               :deed_type => "work_add",
                 :page_id => nil,
                 :work_id => 32017763,
           :collection_id => 32000130,
              :article_id => nil,
                 :user_id => 25091480,
                 :note_id => nil,
              :created_at => Thu, 21 Apr 2022 14:16:28 UTC +00:00,
              :updated_at => Thu, 21 Apr 2022 14:16:28 UTC +00:00,
                :visit_id => nil,
               :prerender => "<a href=\"/ameliachase\">Amelia H. Chase</a> added <a href=\"/adah/civil-war-and-reconstruction-governors-of-alabama/rsg00248-f01-q0000133031-q0000133034\">RSG00248_f01_Q0000133031_Q0000133034</a> in the work <a href=\"/adah/civil-war-and-reconstruction-governors-of-alabama/rsg00248-f01-q0000133031-q0000133034\">RSG00248_f01_Q0000133031_Q0000133034</a> in <a href=\"/adah/civil-war-and-reconstruction-governors-of-alabama\">Civil War and Reconstruction Governors of Alabama</a> collection",
        :prerender_mailer => "<a href=\"http://fromthepage.com/ameliachase\">Amelia H. Chase</a> added <a href=\"http://fromthepage.com/adah/civil-war-and-reconstruction-governors-of-alabama/rsg00248-f01-q0000133031-q0000133034\">RSG00248_f01_Q0000133031_Q0000133034</a> in the work <a href=\"http://fromthepage.com/adah/civil-war-and-reconstruction-governors-of-alabama/rsg00248-f01-q0000133031-q0000133034\">RSG00248_f01_Q0000133031_Q0000133034</a> in <a href=\"http://fromthepage.com/adah/civil-war-and-reconstruction-governors-of-alabama\">Civil War and Reconstruction Governors of Alabama</a> collection",
               :is_public => false
    }
]
```

**Comment by benwbrum** [comment]
Another work with the same problem has a different number of real pages, but the same (wrong) work statistic:
```ruby
2.7.1 :003 > pp w.work_statistic
#<WorkStatistic:0x00007fb994481c78
 id: 32017764,
 work_id: 32017765,
 transcribed_pages: 1,
 annotated_pages: 0,
 total_pages: 2,
 created_at: Thu, 21 Apr 2022 14:16:32 UTC +00:00,
 updated_at: Wed, 04 May 2022 14:12:51 UTC +00:00,
 blank_pages: 0,
 incomplete_pages: 0,
 corrected_pages: 1,
 needs_review: 3,
 translated_pages: 0,
 translated_blank: 0,
 translated_review: 0,
 translated_annotated: 0,
 complete: 50,
 translation_complete: 0,
 line_count: nil>
 => #<WorkStatistic id: 32017764, work_id: 32017765, transcribed_pages: 1, annotated_pages: 0, total_pages: 2, created_at: "2022-04-21 14:16:32", updated_at: "2022-05-04 14:12:51", blank_pages: 0, incomplete_pages: 0, corrected_pages: 1, needs_review: 3, translated_pages: 0, translated_blank: 0, translated_review: 0, translated_annotated: 0, complete: 50, translation_complete: 0, line_count: nil> 
2.7.1 :004 > w.pages.pluck(:status)
   (0.3ms)  SELECT `pages`.`status` FROM `pages` WHERE `pages`.`work_id` = 32017765 ORDER BY position
 => [nil, nil] 

```

**Comment by saracarl** [comment]
Sent to customer:

> I have good news:  we've fixed the 150% problem.  The remediation is running, so by tomorrow you shouldn't see any more 150% statuses.
> 
> I have bad news:  It was only happening on your Civil War Governor's collection, and we can't figure out what caused it.  The 150% transcribed works were all completely untranscribed (and had identical bad statistics); once anything happened to them we recalculated the statistics and everything was correct.  
> 
> Do you know/remember if all of the document statuses started at 150%?  We suspect so -- today there were still 2400 where the stats didn't look right.
> 
> Do you happen to have one of the zip files that were imported?  (The one with this folder: RSG00248_f01_Q0000133028_Q0000133030 would be a good one with a known problem).  We'd like to import it on a test machine and see if the problem happens again.

**Comment by benwbrum** [comment]
Remediation script is finished.

**Comment by saracarl** [comment]
Meredith said they had metadata description turned on, then turned it off.  We need to test that and see if that is what causes the problem.

**Comment by saracarl** [comment]
@sylvieed Could you try to reproduce this issue for us?
1.  Upload some documents to a new collection.
2. Configure "Metadata Description" for the collection with a handful of fields.
3. Go look at the collection home page and see & screenshot was the % done statistics look like.
4. Disable/turn off the metadata description and repeat 3.
  
If that gets us the 150% complete then we know what caused it!  If it doesn't, then we may need to experiment with reviewers, since Meredith also uses that feature.

**Comment by sylvieed** [comment]
That didn't seem to reproduce the issue.

After enabling metadata description,
![metadata](https://user-images.githubusercontent.com/35716893/185470095-25e339d1-af0b-4ca9-a75d-be0a8bc7cda5.jpg)
After disabling it,
![no metadata](https://user-images.githubusercontent.com/35716893/185470114-d4649d39-497c-427a-8d64-3ff2203864a4.jpg)

**Comment by sylvieed** [comment]
This time, trying (1) configuring metadata description (2) uploading documents (3) disabling metadata description.

Issue still not reproduced, has 0% transcribed.
![metadata](https://user-images.githubusercontent.com/35716893/185487719-5ccd8a2b-60f6-47b9-b6e1-33a1acaf5121.jpg)
![no metadata](https://user-images.githubusercontent.com/35716893/185487736-5460faee-929b-4ec8-9922-f2398ea05e43.jpg)
