### ISSUE TITLE
"image set" should be renamed "display set"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#316]
It's confusing otherwise.

**Comment by saracarl** [comment]
Invalid -- I was thinking this was the display subset, rather than the equivalent of creating a new work.

**Comment by benwbrum** [comment]
Image Sets are pre-uploader code that we should probably retire.  They
required users to FTP their files onto a server directory, then did a lot
of stuff that was specific to the Julia Brumfield Diaries, like titling
pages by date and merging recto directories and verso directories.
