### ISSUE TITLE
owner login with no collection should go to "Start a Project"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3161]
If you sign up with the trial flow, you end up at the "Start a Project" tab as soon as you log in.  However, if you are upgraded or log in later, you are taken to your collections / owner dashboard which is blank.

If a project owner (trial or paid) logs in and has no collections created, they should be sent to the "Start a Project" page.

**Comment by anabeabas** [comment]
We saw users getting confused with this again today.
