### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by rsmith-bu** [benwbrum/fromthepage#3164]
My predecessor has setup from the page on a windows system and the performance is horrible. I have picked this project back up and I would like to get it installed based on the recommendations here. I have used Ubuntu, Debian and I am working on a Fedora system now. I follow the instructions and after I run rail server it states that its listening on port 3000 but when attempting to go to the page in a browser it is unable to connect. I do not have any missing dependencies and everything loads up to the point it says its running.

Any hints as to what to look at would be appreciated

**Comment by benwbrum** [comment]
If you're trying to run the server in a production instance, you should use an app server like Apache/Passenger rather than running `rails s` at the command line.  That latter is optimized for development on a local machine.

**Comment by rsmith-bu** [comment]
I am revisiting this and I have development working and I can locally browse. I have followed the Phusion Passenger instructions but I am yet to have it server up the page. My Passenger and Apache Configs all validate properly. Any hint to some decent documentation on how to get this out there on passenger would be appreciated. I can get it to serve up the 500 page in the public directory but not the actual app
