### ISSUE TITLE
Translate the UI to French

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3165]
This task is to create an initial set of French messages for FromThePage.  We'll use the i18n-tasks gem and google translate to manage the work.  In software engineering, "internationalization" is often abbreviated "i18n".

Background:
please read: 
https://guides.rubyonrails.org/i18n.html (the building blocks)
https://glebm.github.io/i18n-tasks/ (the new tools)
and review our initial issue and pull request externalizing the messages and translating them in Spanish and Portuguese:
https://github.com/benwbrum/fromthepage/issues/1765 (our first, manual effort)
https://github.com/benwbrum/fromthepage/pull/1745 (our first, manual implementation)

You'll basically -- this is my cursory understanding -- use the i18n-tasks "add missing keys" for fr (`i18n-tasks add missing keys fr`), and then google translate using 
(`i18n-tasks translate-missing --from=base en fr`).  I'll send you a google translate API key in email.  Please document the exact steps you take in this issue so we can reproduce it for the nth language as well.

before doing that actual work, however, 
1)  let's normalize our keys (for all languages- en, es, pt) and 
2)  remove unused keys.  (We don't want to pay for translating unused keys!)  
3)  We should do some sort of check and review for unexternalized and untranslated messages (all languages) and make sure they are available in English before we do the translation into French.  (see #2735 and see if it's related)
4)  Open issues (or should we do it as part of this issue?) for updating the Spanish and Portuguese messages as well. (#2123 is related, although automation might be easier than working through screenshots.)
5)  One of the "gotchas" for translation work is that we don't care if the `admin` views are translated or externalized.  Trying to exclude those messages, however, may make this harder than it would be if we just included them.  Please evaluate whether it would be easier to do the work to include `admin` messages or not.  (How many and how much would it cost to translated them?)
6)  At some point before pulling the trigger on the google translate API, do a [SWAG](https://en.wikipedia.org/wiki/Scientific_wild-ass_guess) estimate on [how much it will cost](https://cloud.google.com/translate/pricing) us.  

As part of this work you'll also need to add a language switcher for French.  (Review [this issue](https://github.com/benwbrum/fromthepage/issues/1926) and the associated PR.)  We generally try to inherit the language of the browser and then let the user override with the language dropdown in the top right of the UI.

Once we have this done, we'll want to do some testing locally, then implement a feature flag to provide to our beta testers for French.  Then we'll deploy with a feature flag, have them work with it, and iterate on any messages that they say aren't great or are missing.

**Comment by benwbrum** [comment]
Hooray!
