### ISSUE TITLE
Internet Archive 422 error during import (USDA)

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3172]
Tried it again and I am receiving the same error. Here is the work from Internet Archive: https://archive.org/details/CAT30275959004

 

Thanks for your help on this.

**Comment by sylvieed** [comment]
This is causing a `ActiveRecord::RecordInvalid` error at `/ia/convert`: `Validation failed: Pages is invalid`, coming from here:

https://github.com/benwbrum/fromthepage/blob/f679cdd74ed3ecd5612018a25ebb51cef1c9d4f4/app/models/ia_work.rb#L91

The page that caused this error's content is `aoo)\n\n\n.rn..^!T0 . vv xw .toTriem-jv aiabn'^ \":7.....`

### More info: 

The leaf
`#<IaLeaf id: 27147, ia_work_id: 219, page_id: nil, page_w: 2730, page_h: 3771, leaf_number: 206, page_number: "Aoo)", page_type: "Normal", created_at: "2022-06-13 19:35:04", updated_at: "2022-06-13 19:36:26", ocr_text: "aoo)\n\n\n.rn..^!T0 . vv xw .toTriem-jv aiabn'^ \":7.....">`

The page
`#<Page id: nil, title: "Aoo)", source_text: "aoo)\n\n\n.rn..^!T0 . vv xw .toTriem-jv aiabn'^ \":7.....", base_image: nil, base_width: 2730, base_height: 3771, shrink_factor: nil, work_id: 42940, created_on: nil, position: nil, lock_version: 0, xml_text: nil, page_version_id: nil, status: nil, source_translation: nil, xml_translation: nil, search_text: nil, translation_status: nil, metadata: {}, edit_started_at: nil, edit_started_by_user_id: nil, line_count: nil, approval_delta: nil, last_editor_user_id: nil>
`

The work
`#<Work id: 42940, title: "Early horticultural literature : a check list of w...", description: "6 v. (loose-leaf) ; 30 cm\"Many titles in this list...", created_on: "2022-06-13 19:36:43", owner_user_id: 222951, restrict_scribes: false, transcription_version: 0, physical_description: "", document_history: nil, permission_description: nil, location_of_composition: nil, author: "Warner, Marjorie F. (Marjorie Fleming), 1871-", transcription_conventions: nil, collection_id: nil, scribes_can_edit_titles: false, supports_translation: false, translation_instructions: nil, pages_are_meaningful: true, ocr_correction: true, slug: "cat30275959004-07425f0e-d019-462f-979c-f99fccb3350...", picture: nil, featured_page: nil, identifier: nil, next_untranscribed_page_id: 1414781, original_metadata: nil, uploaded_filename: nil, genre: nil, source_location: nil, source_collection_name: nil, source_box_folder: nil, in_scope: true, editorial_notes: nil, document_date: nil, metadata_description: nil, metadata_description_version_id: nil, description_status: "undescribed", searchable_metadata: "Early horticultural literature : a check list of w...", recipient: nil>`
