### ISSUE TITLE
Start a Project needs collection creation step

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#320]
You need a collection before you import works.  We should have a simple text field and "create collection" (with some explanatory text, and perhaps a way to list your existing collections.) on the start project page, first thing.

**Comment by saracarl** [comment]
Comment from UT:

There’s disconnect between start a project because in order to start a project actually means that you need to upload something (work? Document? page?) into an already existing collection. Then at top right is the thing you want but it is hidden under Actions: there you have create a work and create a collection options. Why not make thes more visible and bring them to center stage?

**Comment by tbl73** [comment]
Closing due to issue being covered by #317.
