### ISSUE TITLE
Improvements to the "Your Collections" page

### ISSUE THREAD

**Issue by sylvieed** [benwbrum/fromthepage#3205]
The "Your Collections" page can become cluttered and hard to understand when:
* You have a lot of collections or works
* You have long collection descriptions
* You have long work names

> There is a lot of text that is visually hard to sort through. It’s hard to see the break between one project and the next. 

An example:

<img alt="long collections page" src="https://user-images.githubusercontent.com/35716893/178527121-c388e71f-411e-4901-84fb-4f00e60d6a6c.jpg" width="50%">

### Possible solutions

* Add clearer visual distinctions between collections, such as boxes around them or clearer lines between them
* Make the collections collapsible
* Add a search feature to quickly find a particular collection or work
* Add a sort feature for displaying the most recently created work or other filters

We could implement as many as these solutions as we see necessary or helpful.

**Comment by saracarl** [comment]
Christina at Missouri recently asked that we move inactive collections to the bottom.

**Comment by benwbrum** [comment]
To be covered in #3619
