### ISSUE TITLE
Maybe: add ability to mark page as incomplete

### ISSUE THREAD

**Issue by sylvieed** [benwbrum/fromthepage#3206]
When transcribing,
> Once “done” is clicked, there is no way to mark the page as undone again although editing is still possible. 

If you weren't really done transcribing the page, it could be marked as complete when it should be marked as incomplete.

We should consider adding some sort of "undone" button. This could also be a button that only project reviewer/owners have access to?

**Comment by benwbrum** [comment]
I don't think that we're going to implement this, given the other improvements we are making to the page status flow and usability.
