### ISSUE TITLE
Unclear distinction between different account types

### ISSUE THREAD

**Issue by sylvieed** [benwbrum/fromthepage#3208]
The distinction between signing up for a free transcriber account and signing up for a free trial of an owner account is unclear. 

The "Sign up as a transcriber" button takes you to create a free transcriber account, and the "Learn more" button takes you to create a free trial owner account, but this distinction is not immediately clear to someone unfamiliar with FromThePage.

We do explain this difference on the "Sign In" page in a way that is more clear to users (below), but someone looking to sign up for either of these accounts will probably not be on this page.

<img alt="transcriber vs owner signup" src="https://user-images.githubusercontent.com/35716893/178599120-63c6b0cf-dbd2-4100-af3c-b11f1961bb2b.jpg" width="65%">

### Possible solutions

We should make this distinction more abundantly clear, here's some possible ways to do that:
* Including the above comparison somewhere on the homepage (also helps #3211)
* Adding a column for a free transcriber account on the pricing guide in the "Learn more" page
* Adding a description to transcriber sign-up page explaining what the account you're signing up for is (you can transcribe other projects, but not make projects of your own...)
* Easy access between the transcriber and owner sign-up pages. This already exists from the owner sign-up to transcriber sign-up (see below), but not vise-versa.
<img alt="link between sign up pages" src="https://user-images.githubusercontent.com/35716893/178603661-44409c63-d5e0-4d6a-81ce-4c4b76fb5fa3.jpg" width="50%">

**Comment by saracarl** [comment]
Fixed
