### ISSUE TITLE
[FTP UT Library install]: zoom setting on document in public set is odd

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#321]
To replicate: 
-- go to fromthepage.lib.utexas.edu
-- do NOT log in -- use page as visitor
-- click on the link to the Frank Calvert letter on the home page
-- click on calvert_p4

When I do this, the page image opens already 5 zoom-steps in from the zoom size that fits in the window. If I zoom out until it's the normal size, it will stay that way even when I reload the page. This could be caching, but I'm pretty sure it opened with the zoom the very first time I opened it. Can you replicate?

**Comment by tbl73** [comment]
I'm not able to replicate this - are you still having issues with it, @atomrab ?

**Comment by benwbrum** [comment]
Can't reproduce.  Please reopen if you see it again.
