### ISSUE TITLE
"Sign up to transcribe" button isn't prioritized

### ISSUE THREAD

**Issue by sylvieed** [benwbrum/fromthepage#3211]
The "sign up to transcribe" button isn't prioritized/centered on the homepage, the "Learn more" button is. Also, what this signup button does might be unclear to users (see #3208)

![prioritize signup slide](https://user-images.githubusercontent.com/35716893/178825566-16d5908d-4d89-4f4d-b389-c6b68edd13f9.jpg)

**Comment by saracarl** [comment]
Fixed!
