### ISSUE TITLE
delete works from collection overview page?

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#322]
Now that I'm having to delete a lot of works at once to deal with the upload issues we had, I had to figure out how to do that -- and it took me a long time to figure out that I could only delete an individual work from its settings page (the delete button is all the way at the bottom, below the fold). I thought I'd deleted them already, but I'd just removed them from a collection. Is there a reason that there isn't an option to delete a work from the Owner Dashboard collection overview page? I'd love to have buttons or even checkboxes, at least for works in the "Not in a Collection" category, that would allow me to delete a bunch of them at once (or at least without navigating to the settings page of each individual work).

**Comment by saracarl** [comment]
We need to put more thought into this.
-- adding a delete icon on the list of works doesn't make a lot of sense (we'd need a bunch of other actions next to it to be internally consistent)
![ownerdashboarddeletes](https://cloud.githubusercontent.com/assets/708566/19524080/3051a758-95e2-11e6-9430-b8bc89e78d91.png)

-- checkboxes to perform actions on a set of works would also need other actions available (like permissions)  (not a bad idea, but a much bigger implementation)

@atomrab's real usecase is (perhaps?) "undo doc upload"?    (Or possibly "if your doc upload actually worked right in the first place, I wouldn't have this problem?")

@atomrab -- thoughts?  I'm happy to look at "a solution" but I would like it to be simple and consistent, and this is turning into something that isn't.  

I wonder if a "bulk delete" command line task would make any sense?  (Pass it a collection, delete everything under it?  Or pass it a list of workIDs, delete all of those?

**Comment by atomrab** [comment]
@saracarl is right. My use-case is directly related to inadvertent uploads, and I can't think of a case where you'd need to delete a bunch of stuff at once that isn't related to an upload gone bad (or, say, an upload where a student worker mixed in a bunch of inappropriate documents with some good ones, and one didn't want to go through and delete all the bad ones by hand). So "unload doc upload" would probably fix almost all situations.

**Comment by atomrab** [comment]
Sorry, meant to write *undo doc upload.

**Comment by saracarl** [comment]
We're closing this one.  Works can be deleted individually, or collections can be deleted as a whole.  Worse case, if you have a bunch of problem works, move the "good" ones to a new collection, and then delete the entire collection full of bad works.
