### ISSUE TITLE
upgrade to oath2

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3223]
Post-install message from oauth2:

You have installed oauth2 version 1.4.10, which is EOL.
No further support is anticipated for the 1.4.x series.

OAuth2 version 2 is released.
There are BREAKING changes, but most will not encounter them, and upgrading should be easy!

Please see:
• https://github.com/oauth-xx/oauth2#what-is-new-for-v20
• https://github.com/oauth-xx/oauth2/blob/master/CHANGELOG.md

Please upgrade, report issues, and support the project! Thanks, |7eter l-|. l3oling

**Comment by benwbrum** [comment]
Combining with #2573.  See also #3520
