### ISSUE TITLE
field based date format issue

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3224]
From Sonya at LVA:

I have a question about the date field and how it appears in forms versus spreadsheets in FTP.
![image](https://user-images.githubusercontent.com/708566/179616745-0b9104e6-0b34-470b-90d4-87479641e7d1.png)

When we made the [Virginia Untold indexing](https://fromthepage.com/lva/virginia-untold-free-registers-indexing) collection, we used the spreadsheet feature and the date field to indicate the format YYYY-MM-DD:

When I recently made the [WWI Nurses](https://fromthepage.com/lva/world-war-i-questionnaires-nurses/) collection, I wanted to use a form transcription like on the main WWI collection, but use the formatted date field. 

I selected the date input type in the form fields:
![lva2](https://user-images.githubusercontent.com/708566/179616772-d79b60da-2dc8-4d04-882b-73782f2fd002.png)

But the display does not show YYYY-MM-DD as I had hoped:
![lva3](https://user-images.githubusercontent.com/708566/179616795-d7aec3d6-581b-44ca-a99c-555edeafbaa0.png)

This one has been transcribed, but even when blank the dare format does not show, instead the cell is just taller than normal. 

Is this how the input type date is meant to display in the form transcription? Is there some way that I can get it to show YYYY-MM-DD instead?

**Comment by benwbrum** [comment]
Tracked in #3229
