### ISSUE TITLE
Issues with French translations in UI

### ISSUE THREAD

**Issue by sylvieed** [benwbrum/fromthepage#3232]
There are some issues with the new French translations in the UI, like the wording being too long to fit in buttons, etc. Let's note them here when we see them

**Comment by sylvieed** [comment]
Toggle for "nightly email with activity in collections you've worked on" in "Edit profile" page

![profile- nightly activity toggle](https://user-images.githubusercontent.com/35716893/180304640-9da3d022-e3d8-4f19-813b-8061c7b9fa63.jpg)

https://github.com/benwbrum/fromthepage/blob/559b66f53c09ddd9992b3beac226424c098a7db8/config/locales/user/user-fr.yml#L56

**Comment by sylvieed** [comment]
"Signed in as" on page header

![signed in as](https://user-images.githubusercontent.com/35716893/180304927-05d59e30-f741-4119-a452-17e295745a25.jpg)
https://github.com/benwbrum/fromthepage/blob/559b66f53c09ddd9992b3beac226424c098a7db8/config/locales/layouts/application-fr.yml#L24

**Comment by sylvieed** [comment]
"Browse" when uploading a file on "Start a Project" page

![browse](https://user-images.githubusercontent.com/35716893/180305681-144d15c1-4369-4e6a-bb91-a652e7ad4689.jpg)

https://github.com/benwbrum/fromthepage/blob/559b66f53c09ddd9992b3beac226424c098a7db8/config/locales/dashboard/dashboard-fr.yml#L125

**Comment by sylvieed** [comment]
"Import" when importing a work on "Start a Project" page

![import](https://user-images.githubusercontent.com/35716893/180306911-6e4bb729-b0cc-4fd2-b474-92cbcb22bb15.jpg)

https://github.com/benwbrum/fromthepage/blob/559b66f53c09ddd9992b3beac226424c098a7db8/config/locales/dashboard/dashboard-fr.yml#L80

**Comment by benwbrum** [comment]
Site footer has lower-case "terms et conditions"
![Screenshot from 2022-07-27 09-34-59](https://user-images.githubusercontent.com/199961/181274881-67c97d73-3852-4aec-9c5a-531d2b5d0fad.png)

**Comment by benwbrum** [comment]
Find A Project's Search button is too narrow
![Screenshot from 2022-07-27 09-36-18](https://user-images.githubusercontent.com/199961/181275194-bf833513-5168-400f-905d-ea363f6da1fe.png)

**Comment by saracarl** [comment]
![image](https://user-images.githubusercontent.com/708566/181278028-63d209bf-79e4-45b4-91ae-a9d2f2539ebe.png)

**Comment by benwbrum** [comment]
![Screenshot from 2022-07-27 09-53-45](https://user-images.githubusercontent.com/199961/181279294-231e0fb5-a543-4ad3-9484-71c8519eb646.png)

## Page overview

- [ ] Is "Aperçu" the correct name for "overview"
- [ ] Inconsistency between "Notes" and "Remarques".  Settle on "Notes"

**Comment by benwbrum** [comment]
## Page version tab
![Screenshot from 2022-07-27 09-55-56](https://user-images.githubusercontent.com/199961/181279897-c8ebf62f-1013-48c7-9221-6a653b443ae9.png)

Abbreviated months are English.

**Comment by benwbrum** [comment]
## Download screen

- [ ] "travail" intstead of "oeuvre"

**Comment by benwbrum** [comment]
![Screenshot from 2022-07-27 10-24-06](https://user-images.githubusercontent.com/199961/181286293-ddc9ff24-7c6c-4f9c-9eab-b8743b4928e4.png)
## About screen (work)

- [ ] "Uploaded by" is "téléchargé par", which probably means "downloaded by"

**Comment by benwbrum** [comment]
## Read Work screen

- [ ] Status bar for page needing review says "a besoin d'examen".  Button for pages needing review says "à reviser".

**Comment by benwbrum** [comment]
## Collection show screen

- [ ] Remarques vs. Notes in activity stream title
- [ ] "needs review" consistency issue in work status bars
- [ ] Search button too narrow
- [ ]

**Comment by saracarl** [comment]
![image](https://user-images.githubusercontent.com/708566/181288503-678b17ea-1d95-4f19-8754-31db9ae0143f.png)

**Comment by benwbrum** [comment]
![Screenshot from 2022-07-27 10-36-18](https://user-images.githubusercontent.com/199961/181289155-e194c668-3236-4243-92f5-42a627fd120c.png)
## New User Dashboard

- [ ] missing space between wording and the hyperlink to "collections" in final sentence.

**Comment by saracarl** [comment]
![image](https://user-images.githubusercontent.com/708566/181290060-4a7affc8-0316-43b2-8093-20f879934003.png)

**Comment by saracarl** [comment]
![image](https://user-images.githubusercontent.com/708566/181292233-c8a08b69-06de-4fbc-90c4-8fd0bd4ae6cd.png)

**Comment by benwbrum** [comment]
## Subject edit screen

- [ ] "La description" instead of "Description"

**Comment by benwbrum** [comment]
## Translate page screen

- [ ] Untranslated button labels for "Show Transcription"/"Show Image"

**Comment by sylvieed** [comment]
### Dates

- [ ] Date formats are not changes when locale is changed to French because we specify the format

https://github.com/benwbrum/fromthepage/blob/2c516c566e05f978f0d1186bba1453ee5347f808/app/views/page_version/show.html.slim#L3

In the Page Versions page, but might be in other places as well.

**Comment by sylvieed** [comment]
### Deed error message

When you input an incorrect password when signing in to be a transcriber, the error message "Invalid Login or password." isn't translated. We should find where this & other error messages are coming from.

However, it's also probably OK if this isn't translated.

**Comment by sylvieed** [comment]
- [ ] Work contents action buttons (except for describe) aren't translated (their translations are missing)

**Comment by sylvieed** [comment]
### OpenSeadragon

- [ ] On the page image viewer settings, tooltips are not translated

**Comment by benwbrum** [comment]
## Start a project page issues
![Screenshot from 2022-08-03 08-00-34](https://user-images.githubusercontent.com/199961/182614402-9d88ade0-bdaf-4bed-bd53-b2311b2a37bd.png)

- [ ] "Import" buttons are too narrow
- [ ] Missing space between "Importer" and "ou"
- [ ] "Upload" button ("Parcourir") is too narrow

**Comment by benwbrum** [comment]
## Work settings screen 
![Screenshot from 2022-08-03 09-12-42](https://user-images.githubusercontent.com/199961/182630412-c3376e4a-e707-46a9-8847-d56a0b237220.png)

- [ ] The check box and the "allow collaborators to modify page titles" label are on different lines.

**Comment by benwbrum** [comment]
## Add new page lightbox
![Screenshot from 2022-08-03 09-21-14](https://user-images.githubusercontent.com/199961/182632264-cddb22aa-7038-4e33-8cf7-a700d41a2b81.png)

- [ ]  too small for the buttons
