### ISSUE TITLE
IA import does not display images

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3238]
When the New Bedford Whaling Museum imports this IA book, no images appear: https://archive.org/details/nbw-1438-a

The read work view thumbnail tags are rendered as
```html
<a href="[/nbwm/logbooks-and-journals/nbw-1438-a/transcribe/32470207](https://fromthepage.com/nbwm/logbooks-and-journals/nbw-1438-a/transcribe/32470207)">
   <img alt="Untitled Page 4" src="" />
</a>
```

Similarly, the page image viewer does not display a page.  Looking at the source, it seems like we're handing OSD a blank tilesource

```js
viewer = OpenSeadragon({
  id: "image_container",
...
  tileSources: ["{\"type\":\"image\",\"url\":\"\"}"]
  });
```

**Comment by saracarl** [comment]
I successfully imported this work and all its images; could not reproduce the problem.
