### ISSUE TITLE
field based --> spreadsheet

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3241]
Camille's project:

> I had thought that this collection couldn’t be edited since it is complete, but clearly it wasn’t. Just went in and made the Convict Leasing Project - Tracy City collection private. Would it be possible to undo the work this person did? He changed the format into the spreadsheet form, which doesn’t work with the rest of the collection.

Told Camille we'd roll back that page version, but I'm worried about how this happened -- there seems to be a spreadsheet for this project where before there wasn't?  Or the data is now saved differently?  I'd like to figure this out.  

It's page 4 here:
https://fromthepage.com/slaveryproject/convict-leasing-project/roll-12-vol-39-s-z

**Comment by saracarl** [comment]
> Hi Camille,

> We took care of rolling back that page's version.

> What we are pretty sure happened is that your original configuration was "field based" (no spreadsheets) and the pages in this book were transcribed using that.  Then you reconfigured the project was reconfigured to use spreadsheets instead of fields.  Any pages transcribed -- OR EDITED -- after that would use the new spreadsheet transcription.  

> These two approaches will yield different spreadsheet styles upon export -- the spreadsheet pages will have one row per *line* of data in the page; the field based pages will have one (much longer) row per *page* in the work.  Hopefully each of your books are only of one type -- all field based or all spreadsheets -- so while you may have to do some spreadsheet manipulation to get them to match, each books export will be internally consistent.  That said, I suspect there are a handful like the one that prompted this email that were transcribed using field based and later edited using spreadsheet.  Those exports are going to look odd (long lines for each field based page; short lines for each spreadsheet based line) but shouldn't have any data loss.  (Here's an example I found when looking around:  https://fromthepage.com/slaveryproject/convict-leasing-project/roll-11-vol-25-part-2/display/1683438 )  If you want to talk through this when you're ready to export your data set, we're happy to have a call; I know it's confusing.  (link:  https://calendly.com/fromthepage/1-hour-meeting/ )

> We had talked through some of this when you made the change to spreadsheet configuration, but it's been so long I had forgotten.

**Comment by benwbrum** [comment]
To roll back the text of the page (but not the table cell data):

```ruby
url = 'https://fromthepage.com/page_version/show?page_version_id=4648362'
pv = PageVersion.find 4648362 # find the good page version
User.current_user = User.find 2 # set editor to Ben
page = pv.page # find the page
page.source_text = pv.transcription
page.save!
```
