### ISSUE TITLE
[FTP UT library install]: clearer indication of public/private status of sets and documents on sets page

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#330]
Currently, on the "sets" page in a collection, "public" status is noted for sets, but sets that have not been switched to public just show a blank field, which is confusing. I would assume that the setting should default to "private", and that the Privacy field should show "Private".

![image](https://cloud.githubusercontent.com/assets/4740995/15746212/365e82a6-289b-11e6-8d89-55827c5e17cb.png)

There is also some confusing behavior with the Privacy field for documents in the collection. This collection is private, but for some reason all the documents after the first are marked "Public". What does that mean?

![image](https://cloud.githubusercontent.com/assets/4740995/15746265/6d97fd56-289b-11e6-83c2-c6da814d60d8.png)

**Comment by saracarl** [comment]
I think the new doc sets UI will address this, but let's make sure!

**Comment by tbl73** [comment]
We discussed this this morning, and the new doc sets UI should address this.  On the work assignments, that's actually more about whether collaboration is restricted or not, so the wording has been changed.  The public/private setting on the document sets should show whether the set is public or private (without any blanks).
