### ISSUE TITLE
[FTP UT library install]: granularity of permissions management for sets (enhancement)

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#331]
I don't expect this to be implemented as part of the UT work package, but I thought it would be worth mentioning, since other people using the platform for pedagogy may have the same problem. 

Currently, user management allows one to make an entire private collection available to authorized users, and to make a set of documents from that collection public (and thus visible to everyone). One can make a private set, which will only be visible to authorized collection users, and this might be helpful, as we discussed, for focusing students on a set of documents.

What one cannot do is use the set function to hide parts of a collection from authorized users of that collection. So if you have a modular assignment design, where a student needs to complete one task to get access to a particular set of documents, you still need to put those documents in a separate collection with its own permissions. The same is true if you want to hide documents one group of students is working on from students in another group, or hide material that belongs in a collection but that for some reason you don't want everyone with access to that collection for transcription to see (redaction). 

If permissions settings for sets included public (everyone), private (authorized collection users), and RESTRICTED (only some of the authorized collection users), and if the last setting then allowed you to set permissions for the SET on the user level, it would be possible to carry out the student-management activities I'm talking about (hide part of a collection, then show it to certain users, for example), without distributing documents that belong -- archivally -- in a single collection across a number of different collections. This could be a useful functionality beyond just the UT instance, so it might be worth consideration.

**Comment by tbl73** [comment]
This should be covered by the new document sets UI and #704, about public/private collaborators on document sets.
