### ISSUE TITLE
page numbers not saving for page 1 in field based forms

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3318]
Jessi from LVA says:

> We are getting ready for our big annual Transcribe-a-versary on Saturday and I'm running into a tiny issue with the collection I'm putting up. I can't seem to get the numbers to denote what page I want the fields on to stick. I put them, press save, and they do not take.

> The collection in question is [https://fromthepage.com/lva/evergreen-cemetery-interment-cards ](https://fromthepage.com/lva/evergreen-cemetery-interment-cards)

> I don't think there are any actual two pagers in the collection at the moment but when I do place one in with a second page it results in all the fields from the first page populating again, then the ones for page 2 (which for some reason, is saving correctly).
> 
> Any help would be appreciated, thanks!

**Comment by saracarl** [comment]
I went and looked at the field config, and noticed that page 1 fields don't have a page number next to them:
![image](https://user-images.githubusercontent.com/708566/191299557-f26d4788-4a2a-43b3-ba4e-b322ac4a489d.png)
I entered all the "1"s in the page field and saved, and the result was the same as the image above -- we lose the page number (but just for page 1).

This would also explain the behavior Jessi is seeing.

**Comment by benwbrum** [comment]
Deployed
