### ISSUE TITLE
[FTP UT library install]: "Read" page for new document isn't downsizing image

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#332]
I just uploaded a couple of new documents -- large JPGS that I didn't downsize -- and while they appear normally within the window of the page for the individual document page, they do not appear as thumbnails but as full-size images on the overall "Read" page for the document:

![image](https://cloud.githubusercontent.com/assets/4740995/15748327/18fc9d52-28a4-11e6-97b3-dcc6e2027fbe.png)

To replicate, navigate to "fr_calvert_to_terrell_15dec1894" in the UGS 302 collection and click on the document title from the collection page.

**Comment by atomrab** [comment]
Huh, could this be due to three landscape-orientation photos I had in a separate document in the same upload set? See "calocherinos_to_terrell_10jan1895", last three images.

**Comment by saracarl** [comment]
@atomrab -- This link is to backmatter on a document, so I'm not sure if it is still a problem or not.  Would you check and let us know?  Thanks!

**Comment by atomrab** [comment]
@saracarl: this looks like it's been resolved. I think you can close.
