### ISSUE TITLE
"export everything" checkbox

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3329]
> I try to export regularly so we have a hardcopy - is there a way to export everything more easily than checking every box?

Perhaps add a checkbox -- on the bottom or top -- of the export all screen that when you check it auto-checks all the options in some smart default configuration.

**Comment by benwbrum** [comment]
Closed by #3539

**Comment by benwbrum** [comment]
@saracarl This is the origin of the usability problem you noted with GRI
