### ISSUE TITLE
figure out why iiif imports are so slow

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#333]
Here's a log for an import 

 SQL (0.4ms)  INSERT INTO `sc_canvases` (`created_at`, `sc_canvas_id`, `sc_manifest_id`, `sc_service_id`, `updated_at`) VALUES ('2016-06-02 14:32:08', 'http://manifests.ydc2.yale.edu/canvas/286b99bd-b289-41f7-933f-97bbaa9aebee', 3, 'http://scale.ydc2.yale.edu/iiif/7c70ccd3-5143-4157-a32c-c2a9413cfb5a/', '2016-06-02 14:32:08')
   (1.8ms)  COMMIT
   (0.2ms)  BEGIN
  Page Load (1.5ms)  SELECT  `pages`.\* FROM `pages`  WHERE (pages.position IS NOT NULL) AND `pages`.`work_id` = 136  ORDER BY pages.position DESC LIMIT 1
  SQL (0.5ms)  INSERT INTO `pages` (`created_on`, `position`, `work_id`) VALUES ('2016-06-02 14:32:08', 785, 136)
  Work Load (0.6ms)  SELECT  `works`.\* FROM `works`  WHERE `works`.`id` = 136 LIMIT 1
  SQL (0.4ms)  UPDATE `works` SET `transcription_version` = 1569 WHERE `works`.`id` = 136
  WorkStatistic Load (0.6ms)  SELECT  `work_statistics`.\* FROM `work_statistics`  WHERE `work_statistics`.`work_id` = 136 LIMIT 1
   (0.7ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136
   (1.4ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (source_text is not null)
   (0.5ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND ("pages.id in (select page_id from page_article_links)")
   (1.2ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'blank')
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'incomplete')
  SQL (0.4ms)  UPDATE `work_statistics` SET `total_pages` = 785, `updated_at` = '2016-06-02 14:32:08' WHERE `work_statistics`.`id` = 136
  PageVersion Load (0.6ms)  SELECT  `page_versions`._ FROM `page_versions`  WHERE (page_id = 3703)  ORDER BY page_version DESC LIMIT 1
  SQL (0.6ms)  INSERT INTO `page_versions` (`created_on`, `page_id`, `user_id`, `work_version`) VALUES ('2016-06-02 14:32:08', 3703, 3, 1568)
  TexFigure Load (0.6ms)  SELECT `tex_figures`.\* FROM `tex_figures`  WHERE `tex_figures`.`page_id` = 3703
   (5.7ms)  COMMIT
   (0.3ms)  BEGIN
   (0.5ms)  UPDATE `pages` SET `search_text` = '\n\n\n\n', `lock_version` = 1 WHERE (`pages`.`id` = 3703 AND `pages`.`lock_version` = 0)
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (position = 785)
  SQL (0.4ms)  UPDATE `works` SET `transcription_version` = 1570 WHERE `works`.`id` = 136
   (0.7ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136
   (1.6ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (source_text is not null)
   (0.5ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND ("pages.id in (select page_id from page_article_links)")
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'blank')
   (1.4ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'incomplete')
  PageVersion Load (0.5ms)  SELECT  `page_versions`.\* FROM `page_versions`  WHERE (page_id = 3703)  ORDER BY page_version DESC LIMIT 1
  SQL (0.5ms)  INSERT INTO `page_versions` (`created_on`, `page_id`, `page_version`, `user_id`, `work_version`) VALUES ('2016-06-02 14:32:08', 3703, 1, 3, 1569)
   (8.0ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (0.5ms)  UPDATE `sc_canvases` SET `page_id` = 3703, `updated_at` = '2016-06-02 14:32:08' WHERE `sc_canvases`.`id` = 2367
   (5.3ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (0.4ms)  INSERT INTO `sc_canvases` (`created_at`, `sc_canvas_id`, `sc_manifest_id`, `sc_service_id`, `updated_at`) VALUES ('2016-06-02 14:32:08', 'http://manifests.ydc2.yale.edu/canvas/f3533b9c-1c55-4c6e-878b-cdf340b06a4b', 3, 'http://scale.ydc2.yale.edu/iiif/9d46748d-4968-4723-82ab-5c4e933901a6/', '2016-06-02 14:32:08')
   (5.3ms)  COMMIT
   (0.2ms)  BEGIN
  Page Load (1.5ms)  SELECT  `pages`.\* FROM `pages`  WHERE (pages.position IS NOT NULL) AND `pages`.`work_id` = 136  ORDER BY pages.position DESC LIMIT 1
  SQL (0.5ms)  INSERT INTO `pages` (`created_on`, `position`, `work_id`) VALUES ('2016-06-02 14:32:08', 786, 136)
  Work Load (0.6ms)  SELECT  `works`.\* FROM `works`  WHERE `works`.`id` = 136 LIMIT 1
  SQL (0.4ms)  UPDATE `works` SET `transcription_version` = 1571 WHERE `works`.`id` = 136
  WorkStatistic Load (0.6ms)  SELECT  `work_statistics`.\* FROM `work_statistics`  WHERE `work_statistics`.`work_id` = 136 LIMIT 1
   (0.7ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136
   (1.5ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (source_text is not null)
   (0.5ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND ("pages.id in (select page_id from page_article_links)")
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'blank')
   (1.4ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'incomplete')
  SQL (0.5ms)  UPDATE `work_statistics` SET `total_pages` = 786, `updated_at` = '2016-06-02 14:32:08' WHERE `work_statistics`.`id` = 136
  PageVersion Load (0.5ms)  SELECT  `page_versions`._ FROM `page_versions`  WHERE (page_id = 3704)  ORDER BY page_version DESC LIMIT 1
  SQL (0.4ms)  INSERT INTO `page_versions` (`created_on`, `page_id`, `user_id`, `work_version`) VALUES ('2016-06-02 14:32:08', 3704, 3, 1570)
  TexFigure Load (0.5ms)  SELECT `tex_figures`.\* FROM `tex_figures`  WHERE `tex_figures`.`page_id` = 3704
   (5.3ms)  COMMIT
   (0.3ms)  BEGIN
   (0.5ms)  UPDATE `pages` SET `search_text` = '\n\n\n\n', `lock_version` = 1 WHERE (`pages`.`id` = 3704 AND `pages`.`lock_version` = 0)
   (1.4ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (position = 786)
  SQL (0.4ms)  UPDATE `works` SET `transcription_version` = 1572 WHERE `works`.`id` = 136
   (0.8ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136
   (1.4ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (source_text is not null)
   (0.6ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND ("pages.id in (select page_id from page_article_links)")
   (1.4ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'blank')
   (1.2ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'incomplete')
  PageVersion Load (0.6ms)  SELECT  `page_versions`.\* FROM `page_versions`  WHERE (page_id = 3704)  ORDER BY page_version DESC LIMIT 1
  SQL (0.5ms)  INSERT INTO `page_versions` (`created_on`, `page_id`, `page_version`, `user_id`, `work_version`) VALUES ('2016-06-02 14:32:08', 3704, 1, 3, 1571)
   (7.8ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (0.4ms)  UPDATE `sc_canvases` SET `page_id` = 3704, `updated_at` = '2016-06-02 14:32:08' WHERE `sc_canvases`.`id` = 2368
   (5.3ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (0.4ms)  INSERT INTO `sc_canvases` (`created_at`, `sc_canvas_id`, `sc_manifest_id`, `sc_service_id`, `updated_at`) VALUES ('2016-06-02 14:32:08', 'http://manifests.ydc2.yale.edu/canvas/a33c5f8b-690a-43f1-a4f9-843207b793b8', 3, 'http://scale.ydc2.yale.edu/iiif/a8ccafec-d7c7-4712-b5bf-0e6ba5931cc7/', '2016-06-02 14:32:08')
   (5.3ms)  COMMIT
   (0.3ms)  BEGIN
  Page Load (1.5ms)  SELECT  `pages`.\* FROM `pages`  WHERE (pages.position IS NOT NULL) AND `pages`.`work_id` = 136  ORDER BY pages.position DESC LIMIT 1
  SQL (0.5ms)  INSERT INTO `pages` (`created_on`, `position`, `work_id`) VALUES ('2016-06-02 14:32:08', 787, 136)
  Work Load (0.5ms)  SELECT  `works`.\* FROM `works`  WHERE `works`.`id` = 136 LIMIT 1
  SQL (0.4ms)  UPDATE `works` SET `transcription_version` = 1573 WHERE `works`.`id` = 136
  WorkStatistic Load (0.6ms)  SELECT  `work_statistics`.\* FROM `work_statistics`  WHERE `work_statistics`.`work_id` = 136 LIMIT 1
   (0.7ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (source_text is not null)
   (0.5ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND ("pages.id in (select page_id from page_article_links)")
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'blank')
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'incomplete')
  SQL (0.4ms)  UPDATE `work_statistics` SET `total_pages` = 787, `updated_at` = '2016-06-02 14:32:09' WHERE `work_statistics`.`id` = 136
  PageVersion Load (0.6ms)  SELECT  `page_versions`._ FROM `page_versions`  WHERE (page_id = 3705)  ORDER BY page_version DESC LIMIT 1
  SQL (0.4ms)  INSERT INTO `page_versions` (`created_on`, `page_id`, `user_id`, `work_version`) VALUES ('2016-06-02 14:32:09', 3705, 3, 1572)
  TexFigure Load (0.5ms)  SELECT `tex_figures`.\* FROM `tex_figures`  WHERE `tex_figures`.`page_id` = 3705
   (5.5ms)  COMMIT
   (0.3ms)  BEGIN
   (0.5ms)  UPDATE `pages` SET `search_text` = '\n\n\n\n', `lock_version` = 1 WHERE (`pages`.`id` = 3705 AND `pages`.`lock_version` = 0)
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (position = 787)
  SQL (0.5ms)  UPDATE `works` SET `transcription_version` = 1574 WHERE `works`.`id` = 136
   (0.9ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (source_text is not null)
   (0.5ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND ("pages.id in (select page_id from page_article_links)")
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'blank')
   (1.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'incomplete')
  PageVersion Load (0.6ms)  SELECT  `page_versions`.\* FROM `page_versions`  WHERE (page_id = 3705)  ORDER BY page_version DESC LIMIT 1
  SQL (0.4ms)  INSERT INTO `page_versions` (`created_on`, `page_id`, `page_version`, `user_id`, `work_version`) VALUES ('2016-06-02 14:32:09', 3705, 1, 3, 1573)
   (5.3ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (0.5ms)  UPDATE `sc_canvases` SET `page_id` = 3705, `updated_at` = '2016-06-02 14:32:09' WHERE `sc_canvases`.`id` = 2369
   (5.4ms)  COMMIT
   (0.3ms)  BEGIN
   (1.1ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136
   (0.3ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (source_text is not null)
   (0.4ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND ("pages.id in (select page_id from page_article_links)")
   (0.4ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'blank')
   (0.3ms)  SELECT COUNT(*) FROM `pages`  WHERE `pages`.`work_id` = 136 AND (status = 'incomplete')
  SQL (0.4ms)  UPDATE `work_statistics` SET `total_pages` = 787, `updated_at` = '2016-06-02 14:32:09' WHERE `work_statistics`.`id` = 136
   (7.8ms)  COMMIT
   (0.2ms)  BEGIN
  SQL (0.5ms)  UPDATE `sc_manifests` SET `updated_at` = '2016-06-02 14:32:09', `work_id` = 136 WHERE `sc_manifests`.`id` = 3
   (5.5ms)  COMMIT
Redirected to http://localhost:3000/display/read_work?work_id=136
Completed 302 Found in 773641ms (ActiveRecord: 57151.2ms)

Started GET "/display/read_work?work_id=136" for 127.0.0.1 at 2016-06-02 09:32:48 -0500
Processing by DisplayController#read_work as HTML
  Parameters: {"work_id"=>"136"}
  Work Load (0.5ms)  SELECT  `works`.\* FROM `works`  WHERE `works`.`id` = 136 LIMIT 1
  Collection Load (0.3ms)  SELECT  `collections`.\* FROM `collections`  WHERE `collections`.`id` = 6 LIMIT 1
  IaWork Load (0.5ms)  SELECT  `ia_works`.\* FROM `ia_works`  WHERE `ia_works`.`work_id` = 136 LIMIT 1
   (2.5ms)  SELECT COUNT(_) FROM `interactions`
  User Load (0.3ms)  SELECT  `users`._ FROM `users`  WHERE `users`.`id` = 3  ORDER BY `users`.`id` ASC LIMIT 1
   (0.3ms)  BEGIN
  SQL (0.4ms)  INSERT INTO `interactions` (`action`, `browser`, `collection_id`, `created_on`, `ip_address`, `params`, `session_id`, `status`, `user_id`, `work_id`) VALUES ('read_work', 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0', 6, '2016-06-02 14:32:48', '127.0.0.1', '{\"work_id\"=>\"136\", \"controller\"=>\"display\", \"action\"=>\"read_work\"}', 12705, 'incomplete', 3, 136)
   (8.0ms)  COMMIT
  PageBlock Load (0.5ms)  SELECT `page_blocks`.\* FROM `page_blocks`  WHERE `page_blocks`.`controller` = 'display' AND `page_blocks`.`view` = 'read_work'
  Work Load (0.3ms)  SELECT  `works`.\* FROM `works`  WHERE `works`.`id` = 136 LIMIT 1
  User Load (0.5ms)  SELECT  `users`.\* FROM `users`  WHERE `users`.`id` = 3 LIMIT 1
  Rendered shared/_work_tabs.html.slim (71.9ms)
   (0.6ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136
  Page Load (1.3ms)  SELECT  `pages`._ FROM `pages`  WHERE `pages`.`work_id` = 136  ORDER BY position LIMIT 5 OFFSET 0
  CACHE (0.1ms)  SELECT COUNT(_) FROM `pages`  WHERE `pages`.`work_id` = 136
  Work Load (0.3ms)  SELECT  `works`._ FROM `works`  WHERE `works`.`id` = 136 LIMIT 1
  IaLeaf Load (3.5ms)  SELECT  `ia_leaves`.\* FROM `ia_leaves`  WHERE `ia_leaves`.`page_id` = 2919 LIMIT 1
  ScCanvas Load (0.5ms)  SELECT  `sc_canvases`.\* FROM `sc_canvases`  WHERE `sc_canvases`.`page_id` = 2919 LIMIT 1
  PageVersion Load (0.7ms)  SELECT `page_versions`.\* FROM `page_versions`  WHERE `page_versions`.`page_id` = 2919  ORDER BY page_version DESC
  CACHE (0.1ms)  SELECT  `users`.\* FROM `users`  WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  CACHE (0.2ms)  SELECT  `works`.\* FROM `works`  WHERE `works`.`id` = 136 LIMIT 1  [["id", 136]]
  IaLeaf Load (0.6ms)  SELECT  `ia_leaves`.\* FROM `ia_leaves`  WHERE `ia_leaves`.`page_id` = 2920 LIMIT 1
  ScCanvas Load (0.5ms)  SELECT  `sc_canvases`.\* FROM `sc_canvases`  WHERE `sc_canvases`.`page_id` = 2920 LIMIT 1
  PageVersion Load (0.5ms)  SELECT `page_versions`.\* FROM `page_versions`  WHERE `page_versions`.`page_id` = 2920  ORDER BY page_version DESC
  CACHE (0.1ms)  SELECT  `users`.\* FROM `users`  WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  CACHE (0.1ms)  SELECT  `works`.\* FROM `works`  WHERE `works`.`id` = 136 LIMIT 1  [["id", 136]]
  IaLeaf Load (0.7ms)  SELECT  `ia_leaves`.\* FROM `ia_leaves`  WHERE `ia_leaves`.`page_id` = 2921 LIMIT 1
  ScCanvas Load (0.4ms)  SELECT  `sc_canvases`.\* FROM `sc_canvases`  WHERE `sc_canvases`.`page_id` = 2921 LIMIT 1
  PageVersion Load (0.9ms)  SELECT `page_versions`.\* FROM `page_versions`  WHERE `page_versions`.`page_id` = 2921  ORDER BY page_version DESC
  CACHE (0.1ms)  SELECT  `users`.\* FROM `users`  WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  CACHE (0.1ms)  SELECT  `works`.\* FROM `works`  WHERE `works`.`id` = 136 LIMIT 1  [["id", 136]]
  IaLeaf Load (0.6ms)  SELECT  `ia_leaves`.\* FROM `ia_leaves`  WHERE `ia_leaves`.`page_id` = 2922 LIMIT 1
  ScCanvas Load (0.5ms)  SELECT  `sc_canvases`.\* FROM `sc_canvases`  WHERE `sc_canvases`.`page_id` = 2922 LIMIT 1
  PageVersion Load (0.9ms)  SELECT `page_versions`.\* FROM `page_versions`  WHERE `page_versions`.`page_id` = 2922  ORDER BY page_version DESC
  CACHE (0.1ms)  SELECT  `users`.\* FROM `users`  WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  CACHE (0.1ms)  SELECT  `works`.\* FROM `works`  WHERE `works`.`id` = 136 LIMIT 1  [["id", 136]]
  IaLeaf Load (0.6ms)  SELECT  `ia_leaves`.\* FROM `ia_leaves`  WHERE `ia_leaves`.`page_id` = 2923 LIMIT 1
  ScCanvas Load (0.5ms)  SELECT  `sc_canvases`.\* FROM `sc_canvases`  WHERE `sc_canvases`.`page_id` = 2923 LIMIT 1
  PageVersion Load (0.6ms)  SELECT `page_versions`.\* FROM `page_versions`  WHERE `page_versions`.`page_id` = 2923  ORDER BY page_version DESC
  CACHE (0.1ms)  SELECT  `users`.\* FROM `users`  WHERE `users`.`id` = 3 LIMIT 1  [["id", 3]]
  Page Load (1.4ms)  SELECT  `pages`.\* FROM `pages`  WHERE `pages`.`work_id` = 136  ORDER BY position LIMIT 1 OFFSET 0
  Rendered shared/_pagination.html.slim (68.0ms)
  Category Load (3.0ms)  SELECT `categories`.\* FROM `categories`  WHERE `categories`.`collection_id` = 6  ORDER BY title
  Rendered display/_multi_page.html.slim (702.0ms)
  Rendered display/read_work.html.slim within layouts/application (807.8ms)
  Rendered shared/_breadcrumbs.html.slim (3.2ms)
Completed 200 OK in 1025ms (Views: 894.7ms | ActiveRecord: 36.3ms)

Started GET "/assets/application.css?body=1" for 127.0.0.1 at 2016-06-02 09:32:49 -0500

Started GET "/assets/jquery.js?body=1" for 127.0.0.1 at 2016-06-02 09:32:49 -0500

Started GET "/assets/jquery_ujs.js?body=1" for 127.0.0.1 at 2016-06-02 09:32:49 -0500

Started GET "/assets/plugins/jquery.are-you-sure.js?body=1" for 127.0.0.1 at 2016-06-02 09:32:50 -0500
Here's a log from an import...  

Started GET "/assets/plugins/jquery.fs.zoomer.js?body=1" for 127.0.0.1 at 2016-06-02 09:32:50 -0500

Started GET "/assets/plugins/jquery.fullheight.js?body=1" for 127.0.0.1 at 2016-06-02 09:32:50 -0500

Started GET "/assets/plugins/jquery.litebox.js?body=1" for 127.0.0.1 at 2016-06-02 09:32:50 -0500

Started GET "/assets/plugins/js.cookie.js?body=1" for 127.0.0.1 at 2016-06-02 09:32:50 -0500

Started GET "/assets/plugins/select2.js?body=1" for 127.0.0.1 at 2016-06-02 09:32:50 -0500

Started GET "/assets/plugins/svg4everybody.js?body=1" for 127.0.0.1 at 2016-06-02 09:32:50 -0500

Started GET "/assets/application.js?body=1" for 127.0.0.1 at 2016-06-02 09:32:50 -0500

Started GET "/assets/symbols.svg" for 127.0.0.1 at 2016-06-02 09:32:50 -0500

**Comment by tbl73** [comment]
@saracarl - did this get fixed in the performance enhancements we did earlier this year?
