### ISSUE TITLE
Missing transcription status in collection view when indexing & translation is present

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3331]
![image](https://user-images.githubusercontent.com/708566/192816581-312ec998-90fe-458c-b06e-0eedeb2e7832.png)
This doesn't show transcription status, which is 100%

**Comment by benwbrum** [comment]
To reproduce this, you will need to enable translation for a work.  (This is disabled by default, and is accessed on the Settings tab for the work.)
