### ISSUE TITLE
500 error retrieving first page of paginated collection manifest

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3348]
WHS reports:

> Here is the URL: https://cdm15932.contentdm.oclc.org/digital/collection/petitions/
> The collection holds 10,800 items, 2,534 compound objects.
> 
> When I attempt an import I get this page. Clicking the link produces a 500 server error.

**Comment by anabeabas** [comment]
We explained the ff to WHS:

> When CONTENTdm creates a IIIF collection manifest, from a CDM collection, it generates a different kind of manifest depending on how many items are in the collection.
> 
> For smaller collections (including quite large ones), CDM creates a simple collection manifest, listing all manifests in the collection. For larger collections, CDM separates the items into separate JSON "pages" , each one listing N manifest items, with links from each page to the next/previous page.  
> 
> When FromThePage reads a collection manifest, we have to deal with any pagination.  Until a few months ago, we didn't handle this at all, so you'd just see whatever was listed in the first page, with no way to see the following pages.  We added support for pagination while doing some other work, and apparently you're the first one to use it.  We'll see if we can get it sorted out this week.
> 
> (Utah State Archives has paginated collections, but they have a work around that involves them reading the javascript themselves and cut-and-pasting in the URIs for the individual collection pages.)
