### ISSUE TITLE
Making the Transcription side of the Transcribe full screen and draggable divider

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3358]
John of WWP has a feature request: a way to make the transcription side of the Transcribe tab go full screen. According to him, they have 2 use cases:
1. Some people would like to use 2 monitors and have the document take up one screen and the transcription box take up the other screen.
2. When doing a second level verification, generally they don't really need the document image.

He also requested for a draggable divider between the transcription and the document. One idea is that this would allow one to use the full screen button with the Image at the bottom layout and just make the transcription portion take up the full height.

**Comment by benwbrum** [comment]
See also #3476.

**Comment by benwbrum** [comment]
We should consider splitting this and #3476 into two different issues for these use cases:
* Make the divider between the image view and the transcription view a slider -- persist this between Transcription/Overview and from page to page
* Support transcribers with two monitors, who want to view the image in one monitor and view the transcription screen in the other monitor.  (Note that we need to avoid the case in which a user saves a page/navigates to another page and the image viewer stays on the old page's image.)
