### ISSUE TITLE
open source version needs more descriptions on the landing page

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#336]
open source

Add the below features on the .com main page to the UT page, these are cool and useful: 
Start Reading
You’re free to choose from the many interesting projects hosted on FromThePage. Start reading thehistorical writings that have been already transcribed by other members.

Start Transcribing
Help one of the great historical projects come into the digital age. Jeremiah White Graves's farm journal is only partly transcribed, so it would be a great place to test drive the software.

Start Your Project
If you want to run a transcription project, we would be interested in hosting your effort. Please compare the available pricing plans to choose the one that will fit your needs.
 Run Your Server
The software is released under the GNU AGPL v3.0, a Free/Open Source license. If you want to download and install FromThePage on your server,click here for more information.

**Comment by tbl73** [comment]
Use some of the information from https://github.com/benwbrum/fromthepage/wiki, including the license/features/picture.  https://github.com/benwbrum/fromthepage/wiki/Features also has relevant information.

**Comment by tbl73** [comment]
Changing the landing page is done through the page_blocks system.
