### ISSUE TITLE
support custom non-gravatar avatars

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#337]

**Comment by benwbrum** [comment]
Users could upload their own profile photo, rather than using gravatar.

**Comment by saracarl** [comment]
Donnie at UN Reno asked for this.

**Comment by benwbrum** [comment]
USDA has also asked for this.

**Comment by saracarl** [comment]
UToronto asked for this as well.

**Comment by saracarl** [comment]
Ohio U asked for this as well.

**Comment by saracarl** [comment]
This gem might make this easier:
https://github.com/ging/avatars_for_rails
