### ISSUE TITLE
Metadata overview 500s if not logged in

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3374]
To reproduce:
Sign out
Visit https://fromthepage.com/stefansson-wrangel-09-36-017/wrangel-island-set/32025492/metadata_overview

**Comment by saracarl** [comment]
wrap this in soem sort of "if logged in"

**Comment by saracarl** [comment]
Error message:
undefined method `slug' for nil:NilClass

/home/fromthepage/deployment/releases/20221025204017/app/views/work/metadata_overview.html.slim:49:in `_app_views_work_metadata_overview_html_slim___358607836671677422_743020'

**Comment by benwbrum** [comment]
See also #3575 -- possible duplicate, although the error messages are different.
