### ISSUE TITLE
Curly brace extending over several lines

### ISSUE THREAD

**Issue by NatWooding** [benwbrum/fromthepage#34]
In S3 Page 26, JG lists on three lines records of three quail. He then drew a curly brace from the first to the last and wrote a long note that started on the first line, went to the last, and then went on to  the next couple lines. I indicated this with a single { after each of the birds and added a note in the text and in the notes themselves.

**Comment by saracarl** [comment]
I think this is a transcription convention more than anything we'd do in the product itself.  I'm not sure what to do with it.  @benwbrum?

**Comment by saracarl** [comment]
Closing.  Collection specific.
