### ISSUE TITLE
"View" button gets a 500 if clicked after auto-link

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#340]
If you "auto-link" but don't save, and then click "view" if fails with a 500.  Probably need a reminder to save (or discard?)

**Comment by tbl73** [comment]
Are you clicking "preview" after autolink?  I don't see anywhere to click view.  (But preview definitely fails.)

**Comment by saracarl** [comment]
yes, "Preview" button.

**Comment by tbl73** [comment]
This was related to the way preview was working - when I fixed #387, it fixed this as well.  Pushed up in tbl73-dev branch.
