### ISSUE TITLE
Add green flash after clicking Approve button

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3440]
Jodi from Pratt Library emailed us asking if we could add a green flash when clicking the Approve button so the project owner can know something happened. She says she has to click the button several times before the page updates.

**Comment by benwbrum** [comment]
This appears to work correctly.  As @symmetrically pointed out on Slack, the problem was probably that we did not have a busy wait spinner, so the user was waiting and didn't realize that the request hadn't completed.
