### ISSUE TITLE
[FTP UT Library install]: collection owner still not inheriting permissions from document owner

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#345]
This is what I see when I look at one of the documents that Ece uploaded to the Terrell collection, of which I am the owner: 

![image](https://cloud.githubusercontent.com/assets/4740995/16698202/cdc9aa42-4512-11e6-9046-fd2a51b0043c.png)

![image](https://cloud.githubusercontent.com/assets/4740995/16698216/db11a1a0-4512-11e6-8c2b-dd4ec1aa4e60.png)

For the documents I uploaded, I also see Settings and Pages.

**Comment by benwbrum** [comment]
That's certainly a bug.  I'll see what I can do over the next week.

Ben
