### ISSUE TITLE
New landing page

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3454]
- [x] After clicking "Create Account" when signing up for a transcriber account, it shows a 404 Error page. The account is successfully made though.
- [x] Part of the Victoria Duncan quote gets covered by the end quote symbol.
- [x] Update app footer links.
- [x] Swap out old & new landing page.
- [x] Logged-in user viewing landing page has non-clickable links if they click the "sign up" actions

**Comment by saracarl** [comment]
Done and deployed, finally!
