### ISSUE TITLE
Access issues with TEI export

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3457]
Anneliese Dehner said the TEI export for 7 docs in the "In Omeka" set are inaccessible. Instead of a TEI export, she saw the message "This collection is private. The collection owner must enable API access to it or make it public for it to appear."

Here are the work ids of the docs with permission issues:
25000888
25000891
25000894
25000897
25000902
25000904
320000774

Note: Check line 295 in app/mailers/user_mailer.rb

**Comment by benwbrum** [comment]
This appears to have been a problem with numeric slugs matching these work IDs for a different collection.  We were unable to reproduce this in development, but remediated the data in production.
