### ISSUE TITLE
"You can add another work" shows up too many times in the owner dashboard

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#347]
Go to:
http://fromthepage.com/dashboard/owner

The phrase "You can add another work under Start A Project" shows up under every work.  It should show up at the end of a list of works in a collection.  
![screenshot from 2016-08-16 08 30 55](https://cloud.githubusercontent.com/assets/708566/17700544/d10cd70a-638b-11e6-8d14-bd8f2976d864.png)

**Comment by tbl73** [comment]
Updated app/views/dashboard/owner.html.slim to resolve this issue.

**Comment by saracarl** [comment]
I'm being nitpicky, but can we italicize the "You can add another work under Start A Project" so it's visually prominent?  I think that would look better.
