### ISSUE TITLE
block contributor by displayname

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3475]
Aaron at NBU has a contributor who is not responding to emails or comments or corrections.  He'd like to block him, and we decided it's the only thing we can do in this scenario.

**Comment by benwbrum** [comment]
We should add a new "Block User" button on the collection settings screen.  This would bring up a modal (similar to the Add Owner or Add Reviewer modals) listing users who can currently see the project and letting the project owner choose ones to block.

If a user is blocked from a collection, the collection should be invisible to them when they are logged in -- as if the collection were private.  I believe that we have a `Collection#show_to?` method that will need to consult the block list, and we may also have a scope we use to populate the FindAProject or Collaborator Dashboard screens.
