### ISSUE TITLE
No shared sessions between hostnames

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3477]
Kyle reports that users logged in on fromthepage.com are not logged in if they connect to www.fromthepage.com.

**Comment by benwbrum** [comment]
This fix was not successful.

**Comment by benwbrum** [comment]
Actually, I just tested it in an incognito window, and it worked!

**Comment by bencomp** [comment]
If I understand correctly, the FromThePage cookies will be sent to content.fromthepage.com as well, since it is valid for all subdomains. For self-hosting organisations, this is something to look out for.
