### ISSUE TITLE
Pink pages on uploaded zip files

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3488]
Illinois State is seeing page images displayed as pink when they upload them.

**Comment by saracarl** [comment]
This problem is back again.

Did we try this last time?  
https://stackoverflow.com/questions/15815309/image-turns-pink-when-compressing-it-with-imagemagick-php

**Comment by saracarl** [comment]
And here's another theory, courtesy of ChatGPT:

> Color profile mismatch: Firefox uses the color profile embedded in the image to display it. If the image has a different color profile than what Firefox expects, it may appear pink. ImageMagick may be stripping the color profile from the image during compression, causing Firefox to default to a generic color profile that makes the image appear pink. To fix this, you can try embedding a color profile in the image or configuring ImageMagick to preserve the color profile during compression.
