### ISSUE TITLE
Guest Dashboard Performance

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3498]
NewRelic reports that dashboard#guest is our slowest transaction over the last week, averaging 3 minutes.

**Comment by benwbrum** [comment]
This happens a lot, as you can see from this graph of last week:
![https://gorgon.nr-assets.net/image/7f62239c-d33a-4b73-8754-cbba53034dd1?type=area]

**Comment by saracarl** [comment]
```
/home/fromthepage/deployment/releases/20230228144139/app/views/dashboard/guest.html.slim:5:in `_app_views_dashboard_guest_html_slim__962965848960361099_6384580'
```

```
SELECT DISTINCT `collections`.* FROM `collections` INNER JOIN `deeds` ON `deeds`.`collection_id` = `collections`.`id` WHERE `collections`.`restricted` = ? ORDER BY deeds.created_at DESC LIMIT ?
```

**Comment by benwbrum** [comment]
The problem query is an attempt to list public collections by order of the most recently created deed.  Since this is now denormalized onto the `collections` table, we can rewrite the problem query with a much simpler one that only touches `collections`.

**Comment by saracarl** [comment]
So it didn't take 3 minutes to load the guest dashboard, but it was still a slow count to 18 to load it:

![image](https://user-images.githubusercontent.com/708566/228045234-5cc0412a-b667-46df-b68c-7b67420581bc.png)
![image](https://user-images.githubusercontent.com/708566/228045497-63289935-fce9-4dc6-bf26-43a18bf77a04.png)

**Comment by saracarl** [comment]
A second load of the same page only took 2 seconds.  We're going to merge this because it's a lot faster than 3 minutes, even if it wasn't great on first load (which is the one I think matters).  Some caching is in play, but we're not sure where and if it will be generally helpful.
