### ISSUE TITLE
3) Export of Project Volunteer Contact emails

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#350]
3) Export of Project Volunteer Contact emails
FromThePage will present a list of users names and emails (easily cut and pasted) who have made transcriptions to any of customer's works in a new “contributors” tab in the collection dashboard.

**Comment by benwbrum** [comment]
The key here is that we record important actions by users in a `deeds` table, which contains a `collection_id` and `user_id` column.

The SQL I'd use to get this kind of thing out is:
```

mysql> select user_id, count(*) from deeds where collection_id = 1 group by user_id;
+---------+----------+
| user_id | count(*) |
+---------+----------+
|       1 |       23 |
|       2 |     2500 |
|       3 |      124 |
|       4 |       45 |
|       5 |        1 |
|       6 |       19 |
|       8 |      130 |
|       9 |       18 |
|      10 |       13 |
|      11 |       17 |
|      12 |       16 |
|      20 |        1 |
|      22 |        6 |
|      23 |     1119 |
```

We should be able to do this via ActiveRecord somehow -- something like `@collection.deeds.collect([]) { |d,a| a << d.user_id }` or (ideally) something that generated unique sql.  I'm just not sure how at the moment.

**Comment by tbl73** [comment]
Should I be using the login or display name for the name part of this list?  Display names are probably more user friendly, but they aren't actually required.

**Comment by saracarl** [comment]
The sexiest thing to do would be to use Display names *unless* it's
blank/nil, and then use logins.  :)

Sara

**Comment by tbl73** [comment]
Tricky! ;-) That makes perfect sense.

**Comment by tbl73** [comment]
Oddly enough, Rails (or Devise?) seems to be magically doing that for me anyway, when I use display name attribute - when it's nil, it's displaying the login.

**Comment by tbl73** [comment]
Here's a screenshot of the transcriber emails as they currently look.  This format can be copied and pasted into both Google and Yahoo.
![ftp_transcriber_emails](https://cloud.githubusercontent.com/assets/16854029/18279061/46aab1a2-7422-11e6-9a93-7e2837df66fd.PNG)
