### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#351]
4) Notifications
FromThePage will send a nightly email to the owners of collections. The email will include:
    First time transcribers (aka “new users”) to any works in the LA County Collection.
    Notification when someone creates or updates a transcription, organized by work.
The same information will be available in the “Contributors” tab on the Collection dashboard.

Start with just the Contributor's tab on the collection dashboard

**Comment by saracarl** [comment]
Transcriptions in the last X days (or Since date).

**Comment by tbl73** [comment]
@saracarl  - Do they want to know if someone creates a note, as well?  Just thinking through the options.

**Comment by saracarl** [comment]
Yes, definitely.  Separated from the edits, though, I think.  (different
sections.)

**Comment by tbl73** [comment]
The Contributors tab should also include a clickable list of all transcribers/editors, which allows you to look at the profile of the transcriber.

**Comment by tbl73** [comment]
On the notification that a transcription has been created/updated - what kind of information do they want to see in the notification?  Page title?  Transcriber?  Anything else?

**Comment by benwbrum** [comment]
I'd say that all they know is that it's on their project, so we should
provide a lot of context.

User name, email address (presuming this is emailed to them or restricted
to project owners), work name, page name, kind of action.  Maybe whether or
not it was the first time the user contributed to the project?

Ben

**Comment by tbl73** [comment]
I'm having some trouble with the new transcribers - any pointers?  I think I need to find the list of transcribers who have deeds within the last day (or x days) and no previous deeds on the collection, but I'm having some trouble getting from that logic to anything that actually works.  (Or is there something I'm missing?)

**Comment by benwbrum** [comment]
New transcribers is hard.  I might (again presuming that this is just
visible to project owners) just add a user.deeds.where(:collection_id =>
@collection).count to show the number of interactions they've had.

**Comment by saracarl** [comment]
Customer wants a list of new transcribers to engage with.

I think we'll have to get down and play around a lot together to figure
this out.  @tbl73 can you find something else to work on and if we don't
have an answer by Monday we'll put our 3 heads together?

Thanks.

**Comment by tbl73** [comment]
Sounds good - I'll work on some of my other bugs.  (Kind of glad to hear it's hard, and not that I'm just missing something obvious!)

**Comment by tbl73** [comment]
Documenting the direction we decided to go:
Something along these lines to find the users: user_list = my_collection.deeds.where(Time.now - 3.days).pluck(:user_id), new_transcribers = User.where(id: user_list).  Then find the list of users with deeds older than x days and compare the two arrays.

**Comment by saracarl** [comment]
Create a rake task that when run prints statistics for a passed period of time to the console.

**Comment by saracarl** [comment]
http://railsguides.net/how-to-generate-rake-task/

**Comment by tbl73** [comment]
Question: when I get the deeds for new/updated transcriptions, I've been using page_transcription and page_edit; should I be including article_edit as well? And are we doing anything with translations here?

**Comment by saracarl** [comment]
Please open two issues, one for each of these (article deeds and
translation deeds in the contributors tab data).  We won't do them now, but
by having issues we will have a document that reminds us that we didn't do
them and may want to do them in the future.

Sara

**Comment by tbl73** [comment]
Couple of things on this - while I was making the change, I put in the "long view" from deeds (what's in the activity stream), so that the work that was changed would also show up.  Do you want that, or just the user/page?  Also, I made the UI change, but I'm wondering if it needs some punctuation before the time?  I'm including a screenshot so you can see what it looks like.
![contributor](https://cloud.githubusercontent.com/assets/16854029/18642261/fb08e63c-7e6d-11e6-9a86-955c623a2a92.PNG)

**Comment by saracarl** [comment]
So how much code are you reusing between the rake task with contributor
activities and the contributors tab?

(This is a round-about way to say "they should be doing the same thing",
and we should be thinking about making them consistent, instead of
addressing the actual question about how things should be worded.)

Given the rake task output as an example:

Recent Transcriptions:
On 2016-08-23 17:15:07 UTC, trisha2
<http://localhost:3000/user/profile?user_id=647> (trishablewis@gmail.com)
transcribed page Untitled Page 8
<http://localhost:3000/display/display_page?page_id=6337> in the work Diary
of Jeremiah White Graves, Volume 2, Book 2
<http://localhost:3000/display/read_work?work_id=132>.
On 2016-08-15 19:38:23 UTC, Trisha
<http://localhost:3000/user/profile?user_id=644> (trishablewis@yahoo.com)
transcribed page April 9, 1845 - April 17, 1845
<http://localhost:3000/display/display_page?page_id=6333> in the work Diary
of Jeremiah White Graves, Volume 2, Book 2
<http://localhost:3000/display/read_work?work_id=132>.
On 2016-08-15 19:25:35 UTC, Trisha
<http://localhost:3000/user/profile?user_id=644> (trishablewis@yahoo.com)
transcribed page March 26, 1845 - April 8, 1845
<http://localhost:3000/display/display_page?page_id=6332> in the work Diary
of Jeremiah White Graves, Volume 2, Book 2
<http://localhost:3000/display/read_work?work_id=132>.
On 2016-08-15 14:33:10 UTC, Trisha
<http://localhost:3000/user/profile?user_id=644> (trishablewis@yahoo.com)
transcribed page April 9, 1845 - April 17, 1845
<http://localhost:3000/display/display_page?page_id=6333> in the work Diary
of Jeremiah White Graves, Volume 2, Book 2
<http://localhost:3000/display/read_work?work_id=132>.
On 2016-08-15 14:07:04 UTC, Trisha
<http://localhost:3000/user/profile?user_id=644> (trishablewis@yahoo.com)
transcribed page March 26, 1845 - April 8, 1845
<http://localhost:3000/display/display_page?page_id=6332> in the work Diary
of Jeremiah White Graves, Volume 2, Book 2
<http://localhost:3000/display/read_work?work_id=132>.
On 2016-08-15 14:02:57 UTC, Trisha
<http://localhost:3000/user/profile?user_id=644> (trishablewis@yahoo.com)
transcribed page March 26, 1845 - April 8, 1845
<http://localhost:3000/display/display_page?page_id=6332> in the work Diary
of Jeremiah White Graves, Volume 2, Book 2
<http://localhost:3000/display/read_work?work_id=132>.

Recent Notes:
On 2016-08-15 18:57:30 UTC, Trisha
<http://localhost:3000/user/profile?user_id=644> added a note on page April
30, 1845 - May 7, 1845
<http://localhost:3000/display/display_page?page_id=6335> in the work Diary
of Jeremiah White Graves, Volume 2, Book 2
<http://localhost:3000/display/read_work?work_id=132> that read 'The
section at the bottom of the page is repeated from April 9-17.'
On 2016-08-15 18:37:25 UTC, Trisha
<http://localhost:3000/user/profile?user_id=644> added a note on page March
26, 1845 - April 8, 1845
<http://localhost:3000/display/display_page?page_id=6332> in the work Diary
of Jeremiah White Graves, Volume 2, Book 2
<http://localhost:3000/display/read_work?work_id=132> that read '11-14 at
the bottom of the page are the same on the next page, too - it looks like
they were scanned in but don't actually relate to this particular page.'


Work should be included.  "page" should show up *before* the page
description and "work" before the work description.

**Comment by tbl73** [comment]
Here's the look we discussed this morning (not including the datepicker, which is in another branch):
![contributor2](https://cloud.githubusercontent.com/assets/16854029/18680933/a66351a0-7f33-11e6-8fd7-dfcd0efb2fd8.PNG)

**Comment by tbl73** [comment]
In the contributor-mailer branch.
