### ISSUE TITLE
cookieoverflow error hitting collection show for particular collection

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3514]
For some reason this collection:
https://fromthepage.com/nicolev/schaffhausen-adomnan-challenge

is getting a `ActionDispatch::Cookies::CookieOverflow` in `collection#show `

https://one.newrelic.com/nr1-core/errors/overview/MjY5NTM2NnxBUE18QVBQTElDQVRJT058NTEzNTY3OTU0?duration=604800000&state=e590dee3-0144-05d8-c12d-5112ca9d3c3c

This is our second most common error, after bots hitting our version page not logged in.

**Comment by saracarl** [comment]
Possible helpful, but maybe not as this seems to be collection specific.
https://stackoverflow.com/questions/9473808/cookie-overflow-in-rails-application

**Comment by saracarl** [comment]
There also just 1 edit in the last week, despite 50+ errors.  Maybe folks really aren't getting to the page because of this error?

**Comment by benwbrum** [comment]
I can no longer reproduce this.
