### ISSUE TITLE
Retain original set even after merge

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3516]
Susan Perdue emailed us asking us to confirm that the set in collection X is retained and not lost after the merge, since the set being lost would prevent her from doing the merge.

Collection X:
https://fromthepage.com/fdp/correspondence-volume-2-unpublished

Collection Z:
https://fromthepage.com/fdp/correspondence-volume-2-1853-1865-published

**Comment by saracarl** [comment]
Sue decided she didn't want this after all.
