### ISSUE TITLE
Translate UI to German

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3532]
We've had an offer to review German-language translations as part of the DigEdTnT project, so need to do the initial pass of machine translation.

**Comment by benwbrum** [comment]
Initial feedback from @strubina:
# article-de.yml

create_category_message: "%{link} zum Gruppieren von Entitäten verwenden."

upload_subjects_description: Um Entitäten aus einer externen Normdatei zu erstellen, laden Sie eine %{link} hoch.

-> I couldn' locate these messages, but I would need to see the content of %{link} to see if the second half of the sentence matches in the first example and to choose the correct grammatical case in the second example.


# collection-de.yml

start_transcribing:
      notice: Sorry, but there are no qualifying pages in this collection.
-> Can I please get a screenshot or a short explanation what the "qualifying" stands for? Is that an answer for a search with filters?


# contact-de.yml

form:
    ...
      event: Anlass
      large_institution_quote: Großes Institutionsangebot
      other: Andere
      press: Drücken
-> Where can I find the contact form?


# dashboard-de.yml

you_can_new_collection: Sie können %{new_collection}
-> Where can I find this sentence in the dashboard?

account_type: "Konto für %{type}"
      account_types:
        individual_researcher: Einzelforschende
        large_institution: Großinstitutionen
        legacy: ?
        small_organization: Kleininstitutionen
        staff: Mitarbeitende
        trial: Testversion

-> Are the account types only filled into these curly brackets? Because I have to adapt the cases and I wanted to make sure, the account type translations are not used anywhere else as well (and might need another grammatical ending...)


# device-de.yml

invalid: Ungültiges %{authentication_keys}
failure: Sie konnten nicht von %{kind} authentifiziert werden, weil "%{reason}".
success: Erfolgreich vom %{kind}-Konto authentifiziert.
-> I would need to know the content of %{authentication_keys} and %{kind} to choose the right grammatical case.

real_name: Real Name
-> This means a person's real name?

errors:
    messages:
      expired: abgelaufen, fordern Sie bitte eine neue an
-> In EN it says: "has expired, please request a new one" - I would need to know what the new one is to get the correct german case again. Do you maybe have a screenshot?


# display-de.yml

 display_page:
      ...
      please_help_this_page: Bitte %{help_link} diese Seite

 pages_view:
      ...
      help_complete: Bearbeite diese Seite
      help_correct: korrigieren helfen
      help_transcribe: transkribieren helfen
      help_translate: übersetzen helfen
      ...
      page_not_translated: Diese Seite ist nicht übersetzt, bitte %{help_translate} diese Seite

-> Am I right that the %{help_link} part from please_help_this_page is completed with those help sentences from the pages_view section? Because if so, I would need to change it to get the correct word order. Just checking if the 4 help phrases in pages_view are really the only ones that are filled into the placeholder %{help_link} and if those 4 phrases are not used anywhere else? 


user_notes: User Notes
-> Are these notes from or for users?


# export-de.yml

export_metadata: FromThePage export of %{work} from %{collection} made on %{time}.
-> The preposition sounds like %{time} would be a date, but is it actually meant to be a time of day? I would just need to know for the correct preposition in German and I did not find it on the export screen...


# application-de.yml

undo_login_as: Undo Login As
-> Could that also be translated like "log out as" and where can I find it? It's a bit tricky with the German word order, but I would need to see it, to properly translate it.


# notes-de.yml

 notes:
      ...
      note_body: Note body

-> Where can I find this?


# page-block-de.yml

page_block:
   ...
    list:
     ...
      page_block: Page Block

-> Where can I find this one? 


# transcription-field-de.yml

    start_rows_label: 'Starting Row Count: '

-> Unfortunately I couldn't find this one as well. Do you maybe have a screen shot? 


# user_mailer-de.yml

user_mailer:
    ...
    bulk_export_finished:
      html:
        ready_message: wurde bearbeitet und steht unter %{this_link} bereit.
      text:
        ready_message: 'Ihr Export wurde verarbeitet und steht unter dieser URL bereit:'
      this_link: dieser Link

-> Just making sure here as well, that the placeholder %{this_link} is filled with the content of this_link and that it is only used there? Because so I would have to change the grammatical case and I do not want to corrupt any other sentence...


    click_here: Hier klicken,
    collection_collaborator:
      html:
        to_view: " um %{collection} anzuzeigen"
      ...
    collection_reviewer:
      html:
        to_view: " um %{collection} anzuzeigen"
      ...
    nightly_user_activity:
      html:
        to_view_note: " um die seit Ihrer letzten Bearbeitung hinzugefügten Anmerkung auf Seite %{page} in %{collection}: %{work} anzuzeigen."
        to_view_work: " um %{collection} anzuzeigen: %{work}"
     ...
      html:
        to_view: " um %{collection} - %{work} anzuzeigen."

-> And another one where I just need your confirmation that I got it correctly: There is this click_here key and I guess all those values from the "to_view..." keys are meant to be connected to it? 


# will_paginate-de.yml

 page_entries_info:
    ...
      single_page:
        ...
        zero: Kein %{model} gefunden

-> What's the content of %{model}? I would just need to know for the grammatical case of "Kein" (or maybe Keine)?

**Comment by strubrina** [comment]
Okay, thank you Ben! 
I was able to solve most of the translation problems or at least there are only two files with questions remaining:

# contact-de.yml

form:
...
event: Anlass
large_institution_quote: Großes Institutionsangebot
other: Andere
press: Drücken

Unfortunately, I cannot see the form on the pricing page in my version. So, I am going to change my question: 
Is "event" like the reason for contacting FromThePage or what does it stand for? 
What does Large Institution quote actually mean in this context? 
And does press mean click or is it the press media? 

# dashboard-de.yml

About the accounts: Instead of the "Konto für %{type}" I could also turn it around and make it compound words like 'Einzelforschendenkonto' or 'Großinstitutionskonto', but then I would just need to know, that there is no space added when I set the value of account_type to "%{type}konto".

**Comment by benwbrum** [comment]
Shipped!
