### ISSUE TITLE
Watchlist

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#354]
Think about renaming Watchlist tab in Editor Dashboard to something like My Projects - shows activity in all projects that a user has worked on. Note: if there hasn't been any activity yet, should return 5 most recently changed collections.

**Comment by saracarl** [comment]
Looks good.  Questioning "Your Projects" vs "My Projects" -- web standard actually seems to be to use "My" instead of "Your".  Let's change it to "My", please.

**Comment by tbl73** [comment]
This is changed.

**Comment by tbl73** [comment]
After further discussion this morning, "My Projects" should be changed back to "Your Projects" for consistency with other pages.
