### ISSUE TITLE
Owner login page

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#355]
When an owner logs in, they should go to Owner Dashboard rather than Editor Dashboard.

**Comment by saracarl** [comment]
Hmm.  I have at least 1 scenario where this didn't work.  My test user who owns a collection with no works in it logged in and was taken to the Editor Dashboard.  When I clicked on "Dashboard", though, I went to the Owner Dashboard.

**Comment by saracarl** [comment]
Ok, tested it with another owner and even though that owner had collections with works in it it still went to the editor dashboard instead of the owner dashboard.

**Comment by tbl73** [comment]
Apparently I didn't actually add that file to the commit - it should work now.
