### ISSUE TITLE
Account-level "help" configuration" feature

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3565]
Clayton Ruminski of USDA suggested a feature for us to make: account level "help" configuration.

**Comment by benwbrum** [comment]
Most--but not all--project owners use the same `Basic Help` text for each of their collections.  Allowing project owners to edit project help in their profile (similar to their footer in #3468) would save time and effort for them.  They should still be able to create collection-specific help text, however, which would override the account-wide help text.

(See an example of similar functionality with `Collection.transcription_conventions`, which is shown on each work, but can be overridden by `Work.transcription_conventions`.)

**Comment by symmetrically** [comment]
Do we have to add Subject linking help text i.e. `link_help`  column in collection modal too in the User modal? @benwbrum

**Comment by benwbrum** [comment]
I don't think we need to do this with subject linking.
