### ISSUE TITLE
Show contributors in work metadata download spreadsheet.

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3566]
Jason Godfrey of the Wilford Woodruff Papers Foundation asked for a feature that would let him see which specific documents collaborators are transcribing. He said being able to differentiate the documents that staff and public volunteers transcribe would be ideal. He said he wants to monitor the progress of collaborators so he can train them on specific components of documentary editing related to their project and recruit them to do more transcribing.

He said he wants to see this information for all of the collaborators, but especially new ones.

**NOTE: We should include contributors in the collection metadata spreadsheet**

**Comment by benwbrum** [comment]
This has been fixed.
