### ISSUE TITLE
IA_Work

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#357]
remove from the dashboard enumerations

**Comment by tbl73** [comment]
Removed IA_Work and Image Sets from owner dashboard, on tbl73-dev branch.

**Comment by tbl73** [comment]
@saracarl - do you want me to remove IA_Work and Image Sets from the Summary page of the admin dashboard as well?

**Comment by saracarl** [comment]
Yes.  Please remove it from there as well.
