### ISSUE TITLE
Document Uploads with bad metadata.yaml fail silently

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3570]
Sabrina at ZIM uploaded two zip files with extensive `metadata.yml` files which violated some syntax rules.  Instead of emailing her a problem or explaining that there was an error in the upload, the `document_upload` got stuck in the status `Processing`.

We should handle bad YML parsing more gracefully than that, resolving to an error state and explaining the problem (if possible) rather than leaving the user in limbo.

[Problem upload file: MA-Rezepte.zip](https://github.com/benwbrum/fromthepage/files/11052161/MA-Rezepte.zip)

**Comment by benwbrum** [comment]
To duplicate:

- Upload the attached file.
- Observe that the upload stays in the processing state

We need to catch the exception, print something useful in the logfile which is emailed to the user, and update the `document_upload.status` to Error

**Comment by symmetrically** [comment]
@benwbrum 
I can see that when we catch the exception, it creates the work object. So I have the following questions:

1. When we catch the exception, do we need to create the work for the uploaded file?
2. Apart from printing to the logfile, do we need to write mailer for this or is this already done?

**Comment by benwbrum** [comment]
1. We should not create a work for the uploaded file if there is an exception
2. I think that we only need to print an error to the logfile.  (I think we may already do this for some other exceptions, but I might be mistaken.)
