### ISSUE TITLE
make the user of "editor" and "transcriber" consistent

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#359]
We need to look through the UI and make the use of the word editor and transcriber more consistent.  Not sure which one we should use -- Ece says "transcribers" but it depends on how you think about their role.

**Comment by benwbrum** [comment]
This will be a touchy one for our markets.  Documentary editors recruiting volunteers would be horrified to call mere transcribers "editors".  Research groups using the tool to do serious annotation/translation/etc would be offended to have their efforts reduced to 'transcriber'.

**Comment by saracarl** [comment]
I like the word "collaborator" instead of "editor" or "transcriber", but it may not work everywhere.

**Comment by tbl73** [comment]
This has been done; closing.
