### ISSUE TITLE
Show collection owner when you look up a page/project on Google

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3607]
A transcriber emailed us asking for the owner of a collection they looked up on Google, but you can't figure out who owns a collection if you come in via Google search to a page.

This was the link:
https://fromthepage.com/paged_search?authenticity_token=V6I%2Bdy3KTUhqDOVDJWfgaHldWwPaT5UBAh6Sgc%2BZ%2FepneMS6pI8Q6TGpmQY7RkucMWonny%2F9cyfs9s85Ysp12Q%3D%3D&button=&collection_id=henry-a-parker&page=1&search_string=Henry+a+Parker

**Comment by benwbrum** [comment]
I see "Project by California State Library" on the side of this page.  It looks like CSL needs a footer, though.
