### ISSUE TITLE
Transcriber can't go back to the list of search terms after clicking on a page

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3608]
A transcriber emailed us saying she has trouble accessing information. She said the problem happens after logging in and getting to the pages that turn up after her search term. If she clicks on one and then wants to go back to the list, she clicks on the usual back arrow on the top left of the screen, but the screen dims, and the wheel in the middle just starts whirring, and nothing happens. She says she has to close it and start again.

**Comment by sylvieed** [comment]
This was fixed in #3679 -- there is now a search results page that has its own unique URL that can be returned to, which solves the browser back button issue. There's also a 'Search Results' button in the breadcrumbs that will return you to the page.
