### ISSUE TITLE
Pull "Export All" control into the main Export tab

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3612]
Jon Fackrell emailed us asking about exporting all of the Subject with the categories, which was moved from the Export tab to the Bulk Export tab. Sara told him that he can go to "Export" then "Export All Works", where there's a "subject index export". It will kick off a task and send an email with a download link.

To simplify it, we could try to pull that "Export All" spaceship control into the main Export tab. Maybe below the work-specific ones?

**Comment by symmetrically** [comment]
@benwbrum Can you Please elaborate more on this 

> **_To simplify it, we could try to pull that "Export All" spaceship control into the main Export tab. Maybe below the work-specific ones?_**

**Comment by benwbrum** [comment]
This will require some UI design, but essentially the idea is that the form currently displayed when the user clicks Export All.  (I believe that it's the `BulkExport#new` action)  could be displayed at the bottom of the `Export#index` view.  This should be in a hidden div which the user can open by clicking on a link.  

@symmetrically please us know if this does not sound like good UI to you.

**Comment by benwbrum** [comment]
@symmetrically and I have talked through it, and we think that there's no way to combine these two screens without making the UI even busier than it is already.  Cancelling this approach in favor of #3613
