### ISSUE TITLE
Can't click the Export tab to go back in Bulk Export

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3613]
Jon Fackrell emailed us about exporting all of the Subjects with the categories. Sara told him it was moved and that he has to go to "Export" then "Export All Works", where there's a "subject index export" there. It will kick off a task and send an email with a download link. He said that he couldn't click the Export tab to go back.

**Comment by benwbrum** [comment]
We should add a breadcrumb back from Export All to the main export tab, unless we address this by #3612

**Comment by benwbrum** [comment]
To be addressed by #3612 instead

**Comment by benwbrum** [comment]
Opening after deciding this approach was better than #3613
