### ISSUE TITLE
coveralls not reporting & error

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3623]
Travis shows this:

> [Coveralls] Submitting to https://coveralls.io/api/v1
> Coveralls encountered an exception:
> JSON::ParserError
> 859: unexpected token at '<html>
> <head><title>400 Bad Request</title></head>
> <body>
> <center><h1>400 Bad Request</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>

seems related to this:  https://github.com/lemurheavy/coveralls-public/issues/1240
which is references with a possible fix here:  https://github.com/siegfault/expiration/pull/592

Do we really need to upgrade our ruby version to get coveralls working?

**Comment by benwbrum** [comment]
This now makes tests appear like they failed, when they actually passed.
