### ISSUE TITLE
Skip landing page for logged-in users

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3639]
The new landing page has two very clear calls to action, Start a Trial and Sign in as  Transcriber.  Both of these are focused on new site visitors, not existing project owners or volunteers, and this was mentioned by LVA.  

We should consider redirecting from the landing page if `logged_in? == true`, either to the role-appropriate dashboard or to the findaproject page.

**Comment by saracarl** [comment]
So we want folks to be able to get to the landing page, but most folks won't need or want to see it.  

Let's implement the above, but make the logo in the upper left hand side of the screen take you back to the landing page.  We'll need to add a /landing route back in to take you to that page without the redirect.
