### ISSUE TITLE
Metadata refresh button

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3640]
CWRGM would like the ability to "refresh" the metadata from CDM / IIIF if they have to change it based on learning more information during the transcription and annotation proccess.

**Comment by benwbrum** [comment]
It is straightforward to refresh the metadata we store based on IIIF manifests.  Should this be done per work, or per document set?  CWRGM generally has requested this be done at the collection/document set level.

So we need a new action on the collection or document set settings, which will launch a process to update all metadata in the project.   This process has taken days to run in the past, so it will need to be launched as a rake task.

Here is the code I have used to refresh CWRGM's metadata manually:
```ruby
0.upto(12) do |thousand|
  works = all_works.slice(thousand*1000, thousand*1000+1000)
  p works.count
  # Update metadata from original manifests
  works.each do |w|
    if w.sc_manifest
      begin
        manifest = JSON.parse URI.open(w.sc_manifest.at_id).read
        old =  JSON.parse w.original_metadata
        new =  manifest['metadata']
        updated << w.slug
        w.original_metadata=new.to_json
        w.save!
      rescue
        print "Error fetching #{w.sc_manifest.at_id}\n"
        failed << w
      end
    end
  end
end
```
