### ISSUE TITLE
Track and report on search and navigation success

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3644]
How findable are projects?  How useful is our search feature for volunteers looking for something to work on?

We'd like to track these things:
* What are non-owner users (registered or not logged in) searching for?
* When they perform a search, do they get any results?
* If they get results, do they click on any of them?  (This indicates that the results were potentially useful)
* If they click on results, do they make any contributions?

For the data gathering portion of this, we can start by modifying the search form as follows:

* Create a new SearchAttempt model, with attributes for search text, hit count, click through count, and contributions.  
* Rather than a field that posts to an action, have the search function hit the `#create` action of the new `search_attempt_controller`.  This would redirect to the `show` action of that controller, which would contain the current object displaying the search results.  It would also update the hit count on the search attempt record.  (If necessary in later stages, we might also need to load this search attempt object into the user's session.)
* If a user clicks on a project, we should increment the click through count on the search attempt record.  While displaying the collection, we should also display a breadcrumb letting the user get back to their search results (closing #3608).
* If a user logs a deed on a project, we should find the relevant search attempt object (if any) and increment the contributions.

For the display portion, we should (at minimum) add a `Searches` tab to the admin dashboard.  This should list all search_attempts, with relevant fields.  We should also add a roll-up statistic or two to the dashboard showing average successful searches recently.  (@saracarl, what else are we interested in here?)

**Comment by sylvieed** [comment]
Should a SearchAttempt to belong to a user? (optionally, if they aren't a guest)

**Comment by benwbrum** [comment]
My temptation is to say "yes", however that feels a little creepy since people generally don't expect their search history to be logged.  Let's not, but attach the Ahoy visit ID so that we can aggregate all the searches in a session without knowing which particular user that was.
