### ISSUE TITLE
add editor permissions when adding owner permissions to a user

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#366]
This is minor, but took me a second to figure out. When you are made an owner of a document someone else has uploaded, you are able to change the document settings without difficulty. But if you restrict the editors of the document, *you have to add yourself* as an editor before you can start to transcribe it, since you're still not _really_ the owner. Otherwise you are sent to the home page with a "You are already signed in" message that seems to appear whenever you try to transcribe a restricted document for which you're not an editor (this is a confusing message, by the way -- presumably it should say "You don't have permission to transcribe this document", and then kick you back to the document "Read" page).

**Comment by saracarl** [comment]
This makes sense.  I'm going to rename the issue "add editor permissions when adding owner permissions to a user"  Shouldn't be hard to fix.  Thanks @atomrab

**Comment by tbl73** [comment]
Pushed this up in tbl73-dev after making previously discussed changes.
