### ISSUE TITLE
messy metadata (see brackets) in iiif manifest import

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3666]
When you import a multilingual (or perhaps iiif v3) manifest, this is really ugly:

![image](https://github.com/benwbrum/fromthepage/assets/708566/61416b81-90e7-4de9-a432-363d2fd09fff)

Notice all the brackets, especially on the title?

It looks fine once it's in the UI:

![image](https://github.com/benwbrum/fromthepage/assets/708566/b8ea235b-1820-4ec8-be5e-70f02538bf90)

**Comment by benwbrum** [comment]
Deployed.
