### ISSUE TITLE
"This page is not transcribed, please help transcribe this page.” still shows up on inactive projects

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3687]
Dan Gediman of Reckoning, Inc. emailed us to ask if there was a way to remove the "This page is not transcribed, please help transcribe this page.” from pages that haven't been indexed as their subscription is ending soon. We want to remove this prompt from read-only/inactive projects.

**Comment by benwbrum** [comment]
To reproduce:

Visit an active collection which has work in progress.  Note any UI invitations to transcribe.  (The `collection#show` description may include a _Start Transctibing_ button; the `display#read_work` view may show pages whose `status=='incomplete'` with an "Improve this page" button; clicking on an incomplete page may show the "Improve this page" button.)

Now mark the collection as inactive (Collection->Settings, lower right column)

Visit the collection again and verify that no UI invitations are presented to the user.

**Comment by benwbrum** [comment]
There are two invitations that still exist for inactive projects.  See video for reproduction scenarios:

https://github.com/benwbrum/fromthepage/assets/199961/3bddd2d4-631c-4036-9c97-9959d4e4cf3f
