### ISSUE TITLE
Notifications - time frame

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#369]
Make the time frame for notifications a selectable choice for the user.

**Comment by tbl73** [comment]
The datepicker is set up on the contributor tab.  I pushed it in its own branch - called datepicker.  I used this datepicker: https://github.com/freqdec/datePicker.
Here's a screenshot:
![datepicker](https://cloud.githubusercontent.com/assets/16854029/18552420/5c38d65c-7b2a-11e6-9e1c-8580fd4db6de.PNG)

**Comment by saracarl** [comment]
So this is minor, but annoying.  When you click "update" the little calendar icons disappear from the UI for a second, and then return once the results come back.  Can you figure out why?

**Comment by tbl73** [comment]
This isn't happening for me - they look slightly different as the page is refreshed, but they don't disappear.  What browser are you using?

**Comment by tbl73** [comment]
In the contributor-mailer branch.
