### ISSUE TITLE
missing translation message after kicking off a work level bulk export

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3711]
![image](https://github.com/benwbrum/fromthepage/assets/708566/7ef457b6-b96e-4948-83af-7dfa315f06f3)

Go to work download, click "facing pdf", end up at the downloads page in the screenshot above with a missing message in the flash message.

**Comment by WillNigel23** [comment]
I can't seem to replicate this locally @saracarl. Are we missing some context as to how this occured?

**Comment by saracarl** [comment]
Seems fixed already; closing!
