### ISSUE TITLE
shorten the amount of time alerts stay up

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#374]
The green alerts that show up at the top of a page after login and other tasks are there for too long.  We should make this shorter (and possibly remove it completely for login).

**Comment by tbl73** [comment]
How long do you want them to be up?  Right now it's 3 seconds.   (And do you want it removed altogether for login?)

**Comment by saracarl** [comment]
1 second

Yes, removed altogether for login.  It's obvious by the screenchange you
are logged in.

Sara

**Comment by tbl73** [comment]
Pushed up in tbl73-dev.

**Comment by tbl73** [comment]
Merged in pull #401 .
