### ISSUE TITLE
Empty "My Projects" Editor Dashboard -- suggest a work to start transcribing

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#376]
Current behavior of the "My Projects" tab in the Editor dashboard:

If user didn't make any activity yet, it will show first 5 collections. I'm not sure it's right, alternatively we can show a message saying that watchlist is empty because you didn't performed any actions yet.

The alternative is right -- if they haven't made any edits/transcriptions/comments it should say:
"You haven't participated in any project yet.  You might want to try transcribing a page of XXX."  Where XXX is the most recently active project in the system.  

There's code somewhere that we used to use to point people to something to try transcribing.  @benwbrum can you look for it and note it here?

**Comment by saracarl** [comment]
make sure xxx is a public work.

**Comment by tbl73** [comment]
Pushed up in editor-dashboard branch.

**Comment by saracarl** [comment]
Ok, this looks good, except we'd like to take them to the "next untranscribed page" in the "most recent work".  

Example code for that:
https://github.com/benwbrum/fromthepage/blob/e2a9424c268265884c23d5557ad6b70112a78130/app/controllers/demo_controller.rb

**Comment by saracarl** [comment]
Let's make sure whatever work we send them to they have the ability to edit (see #423).  If no permission, probably shouldn't even show up in the suggestion.

**Comment by tbl73** [comment]
Okay, I just pushed up some new code in the  editor-dashboard branch for you to look at.  It should take a new user to the next unrestricted and untranscribed page  in the most recently accessed work (in a collection that isn't restricted).  I'm not sure if there's a more direct way  than the method I used, but it seems to be working.

**Comment by tbl73** [comment]
This is covered in the code from pull request #438.

**Comment by tbl73** [comment]
Also covered in code from pull request #444.
