### ISSUE TITLE
Re-engineer Editor dashboard

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#378]
1)  Get rid of the tabs -- we are just going to have 1 now, and that will be the current "Your Projects" list
2)  Move the "Your Activity" list to replace the "Activity Stream" (it should be a filtered activity stream of your activities
3) Move the current "Activity Stream" below the default "Your Projects" list and label is "Everyone's Activity"
4) Add a sentence or two at the top of the "Your Projects" (before the first work) that explains what it is:  "Projects you have contributed to -- by transcribing, editing, or commenting on -- will be listed here with their most recent activity so you can stay up to date with what's going on."

See issue #118 which is where we started this conversation for background.  

Feel free to break this into 4 issues.

**Comment by saracarl** [comment]
#377 is part of this work effort as well.

**Comment by saracarl** [comment]
"Your activity" should be time based, not category based.
No tab -- doesn't make sense to have only 1 tab.

**Comment by tbl73** [comment]
Pushed up in editor-dashboard branch.

**Comment by saracarl** [comment]
2) Move the "Your Activity" list to replace the "Activity Stream" (it should be a filtered activity stream of your activities
-- Can we retitle the activity stream in this dashboard to "Your Activity"?

**Comment by tbl73** [comment]
Changed it to "Your Activity", pushed up in editor-dashboard branch.

**Comment by tbl73** [comment]
Merged in pull #419.
