### ISSUE TITLE
metadata only:  There is no button to access works that need review in the collection overview

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3795]
~~Ohio U. is doing a metadata only project and points out that there is not "start creating metadata" button on the collection homepage (analogous to the "start transcribing" button).~~

~~Here:  https://fromthepage.com/ohiouniversitylibraries/nikolais-louis-dance~~

**Comment by benwbrum** [comment]
I have moved the "start creating metadata" button to issue #3803 

This issue now tracks the "works that need review" problem in the title.
