### ISSUE TITLE
metadata only:  links are to transcription screen, not metadata screen

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3796]
> Links to works under "Recent edits" and those sent via the email activity report direct one to a transcription vs. metadata interface. Ex. https://fromthepage.com/ohiouniversitylibraries/nikolais-louis-dance/bach-ii-murray-louis-1964/transcribe/33156593

Ohio U.'s metadata creation project does not involve transcription, so no links in the UI or the email should send folks to a transcription page, only a metadata form.

**Comment by benwbrum** [comment]
This has been fixed.
