### ISSUE TITLE
add contributor's real name to work metadata export

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3798]
When you export the work metadata, we'd like to add a field of contributors that includes their real_name if we have one, or their displayname if we don't.  

Currently we just do user.display_name:
https://github.com/benwbrum/fromthepage/blob/c614fdea263852fd44bac539c63d055f5e7afc52/app/controllers/concerns/export_service.rb#L437

UT Austin asked for this.

**Comment by benwbrum** [comment]
This should be in a separate column, following the current contributor column.
