### ISSUE TITLE
Create a rake task for recent activity

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#380]
Create a rake task that when run prints statistics for a passed period of time to the console.  Make the information resemble the "recent activity" section of the website.  This relates to issue #351.

**Comment by tbl73** [comment]
This was pushed up in the rake-task branch.  Right not it's set to use localhost:3000 for the server in the html links - it should be able to pick that up from the SMTP task when we get to that point.  It's easiest to see how the output currently looks if it's piped into an html file.

**Comment by saracarl** [comment]
We should think about this bit in the task:
include Rails.application.routes.url_helpers
Rails.application.routes.default_url_options[:host] = 'localhost:3000'

And see if there is a way to inherit the default URL from the system when the rake task is run.

@benwbrum can you take a look?

https://github.com/benwbrum/fromthepage/blob/rake-task/lib/tasks/contributors.rake

@tbl73 thinks we can get it from the mailer when we get that working.

**Comment by tbl73** [comment]
After some further discussion, we're going to modify this to call an action mailer and present the information with better styling.

**Comment by tbl73** [comment]
This is in the contributor-mailer tab.

**Comment by tbl73** [comment]
This was superseded by the contributor-mailer rake task, and included in code that's been merged.
