### ISSUE TITLE
[FTP UT library install] Authorized editors not being able to access documents

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#381]
I've restricted all the documents in the Terrell collection, and then I've been adding students to the document set for transcription as they send me the necessary material to "unlock" that stage. Several students have tried to transcribe documents outside the set, and have been kicked back to the "you're already signed in" message. But now I've had two who were authorized and who were trying to work in that set, and were still kicked out of the documents when they tried to transcribe. I have deleted and readded those users, and I asked them to clear their browser cache and/or use a different browser. This has worked for one of the students so far; I'm waiting to hear from the other. 

Is there a caching issue that I should generally make students aware of -- if, for instance, I happen to add them while they're logged in elsewhere? This only happened with the last two students to be added; all the others had no problem at all.

**Comment by saracarl** [comment]
@atomrab -- Have you heard back from student #2 on this yet?  (We don't know of a caching issue, but...  )  

In order to truly fix this we'd need to figure out reproduction scenarios.  If we can't do that (or even if we need a faster solution) the best choice is to get the student to create a 2nd account.  (We suspect it would need to be a new email address, though.)

**Comment by saracarl** [comment]
@tbl73 -- Can you spend an hour or two and try to reproduce the scenario outlined above?  (And if you can, please capture the log and/or any exceptions you see.)  Thanks!

**Comment by atomrab** [comment]
@tbl73 -- don't spend any time on this. Eventually I realized that I could look at the logs for student activity, and despite answering in the affirmative to repeated questions such as "Are you working in the student transcription set??", it turned out that both of the students in question had been trying to transcribe documents that were NOT in the transcription set, and which they were therefore not authorized to edit. I don't know how I could have asked more clearly -- either they didn't bother to read my question, or they had already decided that it was the platform's fault (both of them were trying to do it at the absolute last minute, which didn't help). So you should go ahead and close this issue as user error. Sorry!

**Comment by saracarl** [comment]
Thanks, @atomrab!
