### ISSUE TITLE
FAQ: Create an FAQ

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#382]

**Comment by saracarl** [comment]
Copy edits:
1)  Let's drop the middle line here (square brackets)  -- it's covered in the next section
 Using HTML markup in FromThePage
Double square brackets for subjects
Basic HTML markup tags include: 
2)  See Uploads and Importsfor more information.   <-- need space between Imports and for
3)  Can we switch "What are categories" and "What are subjects" so they are in the opposite order?  It makes more sense to me to talk about subjects before you talk about categories.
4)  Missing space after the ? here:
How do I import from an IIIF Repository?In the Owner Dashboard

Other than that looks good.

**Comment by tbl73** [comment]
Pushed up copy edits in FAQ branch.
