### ISSUE TITLE
Metadata projects: can't "approve" needs-review works

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3824]
If you check "needs review" on a metadata description for a work, it's saved, but when the page is reloaded there is no way to approve that work:

![image](https://github.com/benwbrum/fromthepage/assets/708566/40a213eb-b476-4600-b011-9c42cd41e2e0)

You can reproduce this here:
https://fromthepage.com/ohiouniversitylibraries/nikolais-louis-dance/act-one-murray-louis-dance-company-promo-group-shot-circa-1987/save_description

**Comment by benwbrum** [comment]
@symmetrically reports that this is working as expected in both scenarios, whether the checkbox is checked or unchecked we can save the work metadata.
