### ISSUE TITLE
User-driven screen ruler

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#3825]
Yesterday we heard a feature request from a user who had worked on [Florida Tax Rolls](https://fromthepage.com/floridamemory/florida-county-tax-rolls-1868-1871/dade-1868-1871/display/33219115), which are very wide ledgers.  They were having trouble keeping track of which row they were transcribing, so they downloaded the image and highlighted a row with a transparent color overlay.

The user requested similar functionality within the product .

So we'd like to create a new control on the image viewer which lets users highlight a line across the screen, then drag the line lower as they advance.  Note that we already have some automated screen ruler functionality for spreadsheet data entry, but that is largely unused.

**Comment by saracarl** [comment]
So my impression was that she used a single line in red as an underline/ruler.  Which is a more flexible approach than a highlight (we wouldn't know how tall to make that).

**Comment by benwbrum** [comment]
Fixed in #3861
