### ISSUE TITLE
uploaded subject csv with descriptions does not automatically populate "description" on overview tab

### ISSUE THREAD

**Issue by atomrab** [benwbrum/fromthepage#3831]
I'm setting up a collection to allow students to transcribe my excavation notebooks and index them to contexts and small finds. I've managed to upload CSV files with lists of both (for contexts, about 170 values; for small finds, more than 400) to create subjects (this was a challenge, because it only seemed to work if I used the actual template file you provide; otherwise it wouldn't read my first line as a header row, even if I cut and pasted the values from the template into my own CSV file). 

The problem I'm having is that the descriptions came in as the "ARTICLE" values just fine, and are visible in the Settings tab for the subject -- but until I hit the save button for a given record, they do not appear in the Overview tab, which suggests that I should edit the description in the Settings tab. But since that tab shows the description, the only editing necessary seems to be clicking "Save", after which the description does indeed appear in the Overview tab.

The issue is that I don't want to have to click "save" for each of 700 subjects if I don't have to. Do I have to, or is there a way around this?

**Comment by benwbrum** [comment]
We've tested this and will put it in the next release.
