### ISSUE TITLE
Bad record ID exception loading globe svg

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3869]
We get a ton of these errors in the logs:

> E, [2023-12-14T14:15:20.267594 #26696] ERROR -- : Bad record ID exception for params=<ActionController::Parameters {"controller"=>"display", "action"=>"read_work", "user_slug"=>"assets", "collection_id"=>
"icons", "work_id"=>"globe", "format"=>"svg"} permitted: false>
E, [2023-12-14T14:15:20.267899 #26696] ERROR -- : /home/fromthepage/deployment/releases/20231109191750/app/controllers/application_controller.rb:146:in `load_objects_from_params'

more than any other errors.  It doesn't feel like spam, it feels like loading the globe icon in rails uses a bad route or something similar.

**Comment by saracarl** [comment]
This makes it hard to troubleshoot errors -- too much "noise".

**Comment by saracarl** [comment]
The current production log has 172K of these:

> fromthepage@fromthepage:~/deployment/shared/config/environments$ grep globe ../../log/production.log | wc -l
172081

**Comment by benwbrum** [comment]
This works in development but not in production, making me think that this may be an issue with the asset pipeline and image paths.  This svg appears next to the language switcher in the application layout, but might also appear in the static landing pages which do not use the application layout.
