### ISSUE TITLE
Preview doesn't save changes

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#387]
If you are transcribing a page and hit preview before hitting save, the changes are lost.

**Comment by tbl73** [comment]
The page was refreshing without passing any of the information - pushed up a fix in tbl73-dev branch.

**Comment by saracarl** [comment]
@suwinding -- Turns out we had already fixed the "preview loses transcription changes" but it needs to be merged into the master branch of the code and deployed to your site.  I'll do that before our next meeting and update this issue then.

**Comment by saracarl** [comment]
@suwinging -- resolved.  I will deploy to nybg's servers later on today.
