### ISSUE TITLE
Make subject articles easier to get to/create/edit

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#388]
If you want to create an article about a subject, you have to go to the subject "settings" tab and fill in a field called "description".  (I don't know if non-owners have the ability to edit this or not, need to test.)

Once you have a description it does show up on the subject page.    

This does not seem right.  The article should be on the subject page, editable (by all??).

**Comment by tbl73** [comment]
The description field shows up on the overview page - if there's text, that's available, but if there isn't any text, it provides a link to go to the settings page and add text.

**Comment by saracarl** [comment]
verified.
