### ISSUE TITLE
Missing service hours letter link

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3896]
If I run my service hours, I get the roll up time, but I don't have a link to download the letter:

![image](https://github.com/benwbrum/fromthepage/assets/708566/4ec5a743-a09d-4022-b0f3-4d3c35148c39)

I wonder if it's because I'm "staff" (added as an owner to a collection, so a weird state for the user).  

@anabeabas would you try the "hours" link on your collaborator dashboard under the deed list on the right hand side and see if you get a letter to download?

**Comment by anabeabas** [comment]
I checked mine and I got a letter to download. 
![image](https://github.com/benwbrum/fromthepage/assets/98731543/9d1db29a-2946-4cfd-a2e7-ce4c4cb6a20a)

But when I try to download it sends me to an error page. I don't know if that's related to the original issue or if it's a different one altogether.
![image](https://github.com/benwbrum/fromthepage/assets/98731543/461b4ed5-6fd4-427c-9935-da4f90230158)

**Comment by saracarl** [comment]
Good to know.  Can you try it as a transcriber account?  (I'm guessing you're a project owner.)

**Comment by saracarl** [comment]
solved this by clearing my ftp cookies.
