### ISSUE TITLE
Issue with bulk approval

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3917]
Susan Page of LVA emailed us to tell us about a problem with one of their collections, the [Virginia Untold: Bills of Sale and Deeds](https://fromthepage.com/lva/virginia-untold-bills-of-sale-and-deeds) collection. When she goes to the Pages That Need Review in [this document set](https://fromthepage.com/lva/virginia-untold-bills-of-sale-and-deeds-set), it shows "no pages found". When she clicks on one of the pages on the list, it shows as Complete with no pages needing review.

However, when she tries to transfer those works to the document set that she created for tracking her exports (https://fromthepage.com/lva/virginia-untold-bills-of-sale-and-deeds-ready-for-export), they don't move:

![image](https://github.com/benwbrum/fromthepage/assets/98731543/9863e6f3-dc0a-4c46-8a42-126187c983ab)

After clicking Transfer, the works are still in https://fromthepage.com/lva/virginia-untold-bills-of-sale-and-deeds-set:

![image](https://github.com/benwbrum/fromthepage/assets/98731543/82e61041-8ae5-4a39-ac7e-8a887d05f986)

Sonya looked at the pages and noticed that the transcriptions are all from "super users." She says she used FTP's new(ish) bulk approvals option via the Review Dashboard to approve pages like these and this is the first collection where she's used that tool. So it could be a bulk approval issue.

**Comment by benwbrum** [comment]
The work statistics are not being recalculated after an approve all.  We need to add the appropriate code here: https://github.com/benwbrum/fromthepage/blob/development/app/controllers/collection_controller.rb#L68
