### ISSUE TITLE
Error messages when the user doesn't have permissions

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#392]
If you try to transcribe a restricted work that you don't have permission to see, instead of getting an error message, you're kicked back to your editor dashboard and given a message that you're already signed in, which is a little confusing.

**Comment by saracarl** [comment]
@tbl73 Can you research this more and start a discussion here with what the code path is.

**Comment by tbl73** [comment]
The authorized? method in the transcribe controller currently redirects to the sign in unless you are signed in *and* have permissions to transcribe.  Since the user is already signed in, that sends you to the editor dashboard with a a message saying that you're already signed in.

**Comment by tbl73** [comment]
The transcribe tab shouldn't be visible unless you have permission to transcribe.

**Comment by tbl73** [comment]
Made this change and pushed in branch permissions.
