### ISSUE TITLE
Fix Javascript errors

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3920]
A frequent Javascript error keeps coming up when people transcribe: 

"JavaScript error: : lastFocused.setSelectionRange is not a function. (In 'lastFocused.setSelectionRange(lastFocused.selectionStart, lastFocused.selectionEnd)', 'lastFocused.setSelectionRange' is undefined)"

It doesn't seem to affect transcriber happiness, but it causes "noise" when we're looking for actual errors in Clarity.

**Comment by benwbrum** [comment]
More information in #4086
