### ISSUE TITLE
private collection link on public document set page

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3924]
This link:  https://fromthepage.com/voices-of-the-eastern-shore/voices-of-the-eastern-shore
Is to a public document set ("voices of the eastern shore") on a private collection ("voices of the eastern shore - main").  I'm not a collaborator or owner on the collection.  I shouldn't see the link to the collection, but I do.  If I click on it I get a "You do not have access" message.

![Screenshot from 2024-01-18 10-04-41](https://github.com/benwbrum/fromthepage/assets/708566/f19142bd-f7a4-4227-a07c-c8ba17fd5337)

**Comment by benwbrum** [comment]
Duplicate
