### ISSUE TITLE
change landing copy

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#393]
You've scanned your collection for years, but no one can find text locked in images. With FromThePage you can free your images and engage patrons all over the world.

to

If you've scanned your collection for years, but no one can find the text locked in your images, use FromThePage to free your images and engage patrons everywhere.

**Comment by saracarl** [comment]
Even better:

If you've scanned your collection for years, but no one can find the text locked in your images, use FromThePage to free your images and engage patrons everywhere.

to

You've scanned your collection for years, but no one can find the text locked in your images.  Use FromThePage to free your images and engage collaborators everywhere.

**Comment by tbl73** [comment]
Pushed up in landing branch.
