### ISSUE TITLE
"Enable Subject Linking" should be disabled by default

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3935]
This was fixed in #2872, but we seem to have lost the setting.  A new project should have "Enable Subject Linking" unchecked by default

**Comment by benwbrum** [comment]
I just created a collection on `development` locally, and "Enable subject indexing" was not checked.  Are there more detailed reproduction scenarios?

* log in as a project owner
* click Create Collection under Actions
* Name the collection
* From the StartAProject screen, click on the collection name
* Click on the Settings tab
* Observe "Enable Subject Indexing" is not checked.

**Comment by saracarl** [comment]
Tried again myself and could not recreate.  Closing.
