### ISSUE TITLE
links clicked in read views replace current tab

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3937]
New Bedford puts html links into their transcriptions.  If you click on one of the, they replace the current tab. 

https://www.fromthepage.com/nbwm/logbooks-and-journals/kwm-482/display/32946693

https://app.intercom.com/a/inbox/kp250kj7/inbox/shared/all/conversation/139745300094089?view=List

I can't tell if they want links to open a new tab in the overview/read views of FtP, or in the exports.  (We don't support links in their favorite pdf exports right now, anyway.)

**Comment by benwbrum** [comment]
Can we update the `a` tags which we display to dynamically add a `target` attribute so that they open in a different tab when users are viewing the `read_work` or `display` actions?  I don't want to do any such update in the exports, so this should just be in the xml_to_html methods.
