### ISSUE TITLE
subject count is 0, even with multiple links

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3957]
![image](https://github.com/benwbrum/fromthepage/assets/708566/feea5826-5aa6-4189-a855-20ed73f8a1d7)

![image](https://github.com/benwbrum/fromthepage/assets/708566/14b9032e-9d79-4f79-8c4e-a4577067726e)

https://fromthepage.com/gri/stendahl-letters-qc/article/32124662

![image](https://github.com/benwbrum/fromthepage/assets/708566/0410a3a9-d97f-435e-a4c9-bc1d106a9715)

https://fromthepage.com/gri/stendahl-letters-qc/article/32125930

**Comment by saracarl** [comment]
Kylie at GRI.

**Comment by benwbrum** [comment]
This should be maintained through a built-in Rails tool called counter caching.
the Article model has this line:
  has_many :pages, through: :page_article_links, counter_cache: true

However it looks like it's not being upgraded
2.7.3 :012 > pp article.attributes
{"id"=>32124662,
 "title"=>"Adams, Philip Rhys",
 "source_text"=>nil,
 "created_on"=>Wed, 10 Jan 2024 18:39:34.000000000 UTC +00:00,
 "lock_version"=>0,
 "xml_text"=>nil,
 "graph_image"=>
  "/home/fromthepage/deployment/releases/20240204185553/public/images/working/dot/32124662.png",
 "collection_id"=>1112,
 "latitude"=>nil,
 "longitude"=>nil,
 "uri"=>nil,
 "provenance"=>nil,
 "created_by_id"=>32016945,
 "pages_count"=>0}
 => {"id"=>32124662, "title"=>"Adams, Philip Rhys", "source_text"=>nil, "created_on"=>Wed, 10 Jan 2024 18:39:34.000000000 UTC +00:00, "lock_version"=>0, "xml_text"=>nil, "graph_image"=>"/home/fromthepage/deployment/releases/20240204185553/public/images/working/dot/32124662.png", "collection_id"=>1112, "latitude"=>nil, "longitude"=>nil, "uri"=>nil, "provenance"=>nil, "created_by_id"=>32016945, "pages_count"=>0} 
2.7.3 :013 > article.pages.count
 => 2
