### ISSUE TITLE
Staff profiles show private projects

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4018]
![image](https://github.com/benwbrum/fromthepage/assets/708566/d102642c-c85a-463c-b8d4-4d6e407f8e38)

Staff member profile pages naively show all the projects that staff member is a owner/staff on, even if they are private.  We should make this logic similar to the project owner profile page.

**Comment by benwbrum** [comment]
This may be closed by work done for #4048, since we won't be listing collections on staff pages.  @WillNigel23 can you verify?

**Comment by WillNigel23** [comment]
Staff profile will now not show collections. Yes #4048 should fix this as well
