### ISSUE TITLE
Gem updates

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#402]
At some point the gems in the gem list will need to be tested and then updated to current versions, particularly gems that have been specified (Devise, Rmagick, Mysql2, etc).

**Comment by benwbrum** [comment]
Sara's doing a lot of work on this as part of the NYBG install.  It's hard,
and we'll want to think pretty carefully about how to do this on the
fromthepage.com production code.

**Comment by tbl73** [comment]
Definitely - we talked about this a bit yesterday, so this issue is mostly meant to be a reminder to think about it.

**Comment by saracarl** [comment]
We should evaluate this, and likely close it, after the move to the new server this weekend.
