### ISSUE TITLE
creating categories during subject-category assignment

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#403]
When you create new subjects, they have to be assigned to a category.  If you have no categories, you can't assign them.  So a brand new collection owner would get confused here -- we need to ability to create a category directly from the dropdown  OR we should show the "uncategorized" category in the dropdown from the get go.

http://97.107.141.53/transcribe/assign_categories?page_id=1

**Comment by benwbrum** [comment]
When we create a new collection we should automatically create 2 categories:
People
Places

The export code looks for these categories and treats them specially, and
they're good defaults.

Ben

**Comment by tbl73** [comment]
Okay, I set these up to create automatically.  I had to change the validation scope on the category, so that it looks at the collection_id as well as the parent_id.  Pushed up in the categories branch.
