### ISSUE TITLE
fit to width in OSD doesn't work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4053]
I'm pretty sure this doesn't work anywhere, but here's where I saw it:
https://fromthepage.com/statelibrarynsw/hassall-family-papers-store-records-sales-books-ledgers/file-1-rowland-hassall-parramatta-store-day-sales-book-1803-1804-22e803f0-22ba-458e-9100-e7ffa38c486b/transcribe/34035624
(private project)
It's an over/under view with a spreadsheet.

Javascript error is:

> Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at HTMLDocument.OnClickHandler (content.js:536:104)

**Comment by rsimon** [comment]
Hi, I can't access that particular document, as you say. But I tried with some of the public ones. I don't get the JavaScript error, but the the button has no effect either.

From what I saw in the page source code, it looked like there was no click handler on the button though. (It would need to be  wired up with the OSD fit-width API method, [like in this commit](https://github.com/benwbrum/fromthepage/pull/3998/files).) That wouldn't explain the JS error though...
