### ISSUE TITLE
image layout options don't work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4066]
You can no longer change the image/transcription to image at top/bottom/right -- tested on both CRWRA and JWG.

Reported by a transcriber.

**Comment by saracarl** [comment]
Here's what I see in the console when I try to do this:

> Uncaught ReferenceError: freezeTableColumn is not defined
    at HTMLAnchorElement.<anonymous> (504716:485:42)
    at HTMLAnchorElement.dispatch (application-a43c53cfa691046fca7e833a7815f4dd8095632536f8d659fad48be0eeb38b6d.js:2:22084)
    at m.handle (application-a43c53cfa691046fca7e833a7815f4dd8095632536f8d659fad48be0eeb38b6d.js:2:18778)

**Comment by benwbrum** [comment]
Okay, it looks like the code we added to freeze display of spreadsheet headers for #3002 is causing JS errors _for pages that do not use/include the handsontable partial_.

See example at https://fromthepage.com/adah/civil-war-and-reconstruction-governors-of-alabama/shorter-administrative-rsg00204-f08-q138923/transcribe/33694881

**Comment by atbah** [comment]
@benwbrum 
In order to fix this bug,  please update the below code in `app/views/transcribe/display_page.html.slim`. 

```
if (typeof freezeTableColumn !== "undefined") {
          window.removeEventListener('scroll', freezeTableColumn);
          window.addEventListener('scroll', function (e) {
            if(mode === 'ttb') {
              freezeTableColumn('.page-imagescan', '.spreadsheet', '.ht_clone_top');
            } else {
              freezeTableColumn('.page-toolbar', '.spreadsheet', '.ht_clone_top');
            } 
          });
        }
```
