### ISSUE TITLE
validate html in description before saving

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4074]
Customers are importing descriptions in HTML, but they are getting cut off (maybe we have a limit?) so we have incompletely formed HTML for descriptions, which are causing export issues like #4073 

We should validate proper html when saving description and throw an error if it isn't.

**Comment by WillNigel23** [comment]
#4119 

I came up with this for the html validation.

However I think there are many moving parts to this issue:

1. Fields like intro_block are Mysql mediumtext type which I believe is max 16mb in size. This most likely is the cause why it is being cut off for some users. I added a validation for the size 16.megabytes - 1 for the relevant fields under collection as an example. Although this might still be missed sometimes depending on the browser/clipboard of the user themselves.

2. Here comes in the html validator component I suggested. We can extend this in future to add more capabilities, but for now it works. I am uncertain as to how effective will this be in catching trickier syntax. We can only do so much in validation for html syntax as I don't think there is an exact solution to this yet out there.

3. For whatever we miss in our model validations, we should add error handling at parts that parses html fields.
Example is in export_helper where the error happened in #4073.

Let me know your thoughts. I'd be happy adding all of the said measures in this PR, but if it would be too large maybe we can break it down to smaller tickets.

**Comment by saracarl** [comment]
One question when I opened this is whether we need longer intro blocks.  I'm not sure, but I'm currently leaning to "no".  

Error handling in exports would be great; different formats tend to run into different errors.  Hmm.  Ideally we'd go find all the ones we've fixed by fixing the data, there may be tickets for some and some we may have just fixed without documenting...  :frowning_face: 

I am always in favor of breaking things down into smaller tickets.  Much cleaner all around, and there's the psychological win of getting many smaller, clearer things done, faster.

**Comment by WillNigel23** [comment]
That sounds reasonable. It would help to get all documented failing cases though as a headstart. Can you provide links to these issues?

**Comment by benwbrum** [comment]
Let's go back to the original issue:
> Customers are *importing* descriptions in HTML, but they are getting cut off

These descriptions must come from someplace other than the UI -- perhaps the metadata.yml files which owners sometimes upload with zip files, perhaps the metadata spreadsheet upload, but _probably from imported IIIF manifests_.  

@saracarl, can you provide more context on the origin of this problem?  It would help us if we could track down the origin of the description text.  Also, is this the work description or the collection description?

(Regarding validation of HTML entered through the UI, see #1877, which is an approach that might obviate validation.)

**Comment by saracarl** [comment]
Nantucket historical is the customer.  I don't think they use IIIF, but I don't know if they copy and paste this in or use a metadata.yml file. Let me find out (possibly by asking).

**Comment by saracarl** [comment]
Asked.

**Comment by saracarl** [comment]
The customer is copy and pasting the description into the UI.  Can we run with this issue for fixing the UI validation, and open an issue for testing other import vectors?

I'll point out the problem has only happened for this specific customer.  

 @benwbrum what do you think?

**Comment by benwbrum** [comment]
Given that the customer is cut-and-pasting into the UI, and that the problem has only happened once, I think that the approach in @WillNigel23's PR is the right one.  (My earlier worries were incorrect.)

Let's internationalize the error message, test/merge and not spend more time on this until there's another problem.

**Comment by WillNigel23** [comment]
Fixed specs, should be ready for review @benwbrum  @saracarl
