### ISSUE TITLE
Add UI to automate account upgrades on FromThePage

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#4079]
Currently, trials who want to upgrade their account have to send emails to support or Sara. We want to automate that by adding an "upgrade" button on their dashboard that will link to a Bento form.

**Comment by anabeabas** [comment]
@saracarl I created this Bento form for trials who might be interested in upgrading their account: https://app.bentonow.com/f/6247d0278bfbafc3ef75b753f26a46d2/red-tree-885/

Let me know what you think of the form.

I feel like for the UI, we can do it two ways:

1. Add an "Upgrade Account" button to this section of the owner dashboard.
![image](https://github.com/benwbrum/fromthepage/assets/98731543/378a467f-fe7f-4a78-995f-0cda0a43b88d)

2. Add an "Upgrade Account" button to the Your Profile page, beside these buttons
![image](https://github.com/benwbrum/fromthepage/assets/98731543/00b6adae-5774-49e3-bf12-72bdde84e5c9)

**Comment by anabeabas** [comment]
@saracarl Like this? 
![image](https://github.com/benwbrum/fromthepage/assets/98731543/41505db1-c397-422b-9440-f30027c9e52c)

**Comment by saracarl** [comment]
Yes.  I like that.

On the form, can you link this:  For more information on the pricing tiers, please refer to https://fromthepage.com/pricing.  (ideally opening in a new tab)

And can you remove the pricing from the dropdown?  I don't want them to get out of sync.

Let's add 3 more yes/no questions:
Do you need a sole source letter?
Do you need a proposal?
Should we wait on a purchase order before we send an invoice?

**Comment by anabeabas** [comment]
@saracarl I can't add a link to the Bento survey description. (I asked on Discord and Jesse said it's not possible but that he'd note the suggestion.) I moved the sentence to a different section:

![image](https://github.com/benwbrum/fromthepage/assets/98731543/4a307cd7-4532-429e-a8b0-9f0cde61041a)

Here's the updated form: https://app.bentonow.com/f/6247d0278bfbafc3ef75b753f26a46d2/red-tree-885/

**Comment by anabeabas** [comment]
@saracarl @benwbrum Here's the account upgrade button added to the owner dashboard! Let me know what you think:

![image](https://github.com/benwbrum/fromthepage/assets/98731543/6ff77830-34f2-4aeb-b072-97dc36f0c7d6)

**Comment by saracarl** [comment]
Can we add the following to the form?  "For questions, please email Sara at sara@fromthepage.com."

But this looks good to me.

**Comment by anabeabas** [comment]
@saracarl Done adding it to the form!

In case you need it, here's the link to the Figma file for the account upgrade UI: https://www.figma.com/design/lJFNffS16ZjkUi0iqtjE1k/Account-Upgrade-UI?node-id=0-1&t=thEJfttivHEOxTr8-1

**Comment by benwbrum** [comment]
This is ready to be implemented!
