### ISSUE TITLE
JS error clicking between CodeMirror and OSD

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4086]
We get this error when we click from the editor to the image viewer on [this page](https://fromthepage.com/castatelibrary/gold-rush-letters/jonathan-bassett/transcribe/34048211)
```
34048211:244 Uncaught TypeError: lastFocused.setSelectionRange is not a function
    at 34048211:244:21
```

**Comment by atbah** [comment]
@benwbrum Does this JS error block any feature on the page?

**Comment by benwbrum** [comment]
No, it does not appear to block any features.  We'd still like to silence the error, as it creates a lot of noise for our usability analysis.

**Comment by atbah** [comment]
Fixed this issue, @benwbrum
