### ISSUE TITLE
"mentions" is unclear on statistics tab

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#410]
What does "mentions" mean in the statistics tab?  A work with 2 pages transcribed by 2 users, 2 subjects, and a couple of revisions has 2 "mentions" but I don't understand what they actually are.

Once we figure out what they are, we need to either explain them or take them away.

@suwiding fyi.

**Comment by tbl73** [comment]
As best I can tell, "mentions" are created when someone links a subject in a transcription.   It's not clear to me what the difference is between "subjects" and "mentions" is, though.  From a little testing, they appear to track together.

**Comment by saracarl** [comment]
So what if you link the same subject multiple times in the work?  Maybe the
mention count goes up?  (It's very common for the same person to appear
multiple times in a work, and get linked to the article about that person,
so this would make sense to me.)

**Comment by tbl73** [comment]
They do go up, so that's the difference.  I think we might need a different word than mentions, though, because I didn't understand that either.

**Comment by tbl73** [comment]
Oh, and while we're talking about this, it took me a while to realize that "comments" were the same thing as notes, though I don't know if anyone other than me is confused by that.

**Comment by tbl73** [comment]
Change "mentions" to "references", and change "comments" to "notes".

**Comment by saracarl** [comment]
reviewed.
