### ISSUE TITLE
improve document set settings tab to match collection settings

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4103]
The document set settings screen is almost as complex as the old collection settings screen.

We should redesign it, matching it as closely as possible to the new collection settings UI.

**Comment by benwbrum** [comment]
In addition to consistency with the collection settings UI, we should consider re-thinking how we manage adding works to a document set or removing works from it.

This is something that came up in a coversation with @WillNigel23 
Will:
> Another bug related to that is, at document_sets settings, once you add a work, it vanishes from the list. Can you confirm if this is actually happening in prod? Sorry I'm still not sure if the bugs I'm encountering are due to dev env or really persisting.

Ben
:
Sigh.  Okay, this one is less of a bug than a mis-feature.  On the `document_set#edit` view, you see a list of all the works not in the doc set right now, and have a way to add one or more.  On `document_set#works_list` you see all the works in the document set, and have a way to remove them.  It works and it's consistent, it's just pretty ugly.

**Comment by anabeabas** [comment]
@benwbrum @saracarl The document set settings UI redesign: https://www.figma.com/design/crsA5r8JAW4F03kCFrNao7/Document-Set-Settings-Redesign?node-id=0-1&t=7AIt4eB1IsHuN3s6-1

Let me know what you think!

**Comment by anabeabas** [comment]
@saracarl @benwbrum My latest version of the document set settings UI: https://www.figma.com/design/crsA5r8JAW4F03kCFrNao7/Document-Set-Settings-Redesign?node-id=0-1&t=dyqDMQdZz1PHXWsS-1

**Comment by anabeabas** [comment]
@benwbrum @saracarl Thoughts?

![Image](https://github.com/benwbrum/fromthepage/assets/98731543/c4b8a478-b16a-4c9a-9753-f8253b362ad1)

**Comment by benwbrum** [comment]
If we change the wording to get rid of the action verbs, we're good, I think.  "Public", "Private", "Read-only"

**Comment by benwbrum** [comment]
Sara's good with this, given the wording changes.
