### ISSUE TITLE
UT:  Missing documents in owner dashboard statistics if not originating owner

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#412]
"how many documents I own and/or have been added to as an owner (right now I only see 31, but I'm a de facto owner of nearly 80). "  (If you didn't create the work, but are later assigned to be an owner of it, it may not show up in this list.).

**Comment by tbl73** [comment]
Pushed up in owners branch.

**Comment by tbl73** [comment]
Resolved in pull request #440.
