### ISSUE TITLE
NYBG: "export as xhtml" should export whole collection as a zip file

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#413]
Instead of working work-by-work.

@suwiding

**Comment by tbl73** [comment]
This depends on #494.

**Comment by saracarl** [comment]
When exporting individually (click export xhtml, view web page, right click save-as), the header looks like:
<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"></head>
<body>
<h1 class="work-title">aivazian_sept1894</h1>
<div class="export-metadata">FromThePage export of aivazian_sept1894 from Brumfield Test Collection made on 2017-01-11 10:25:46 -0600.</div>

<hr>
<h2 class="divider">Page Transcripts</h2>

Within the zip it looks like:


<h1 class="work-title">aivazian_sept1894</h1>
<div class="export-metadata">FromThePage export of aivazian_sept1894 from Brumfield Test Collection made on 2017-01-11 10:25:06 -0600.</div>

<hr />
<h2 class="divider">Page Transcripts</h2>


We're missing this:

<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"></head>
<body>

(Also missing the closing body and html)

Does it matter?  Will this work for NYBG's purposes?

@benwbrum -- need your approval before we merge this in.
