### ISSUE TITLE
Unable to remove work from document set in Collection->Sets tab

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4141]
* Create Collection A
* Enable Document Sets
* Create Set 1
* Create Set 2
* Add a work W
* Go to the Collection->Sets tab
* Check the box to add work W to Set 1
* Press Save
  * The checkbox should be checked on the page reload
* Uncheck the box to add work W to Set 1
* Press Save
  * The checkbox should not be checked on the page reload _but it is still checked_

**Comment by WillNigel23** [comment]
To add, unchecking then save only works for as long as there is at least one document_set a work belongs to (which is the bug)
