### ISSUE TITLE
sitemap

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#415]
To make both fromthepage.com and any deployments of  the open source version more easily crawled by search engines, we need a sitemap.

**Comment by saracarl** [comment]
(That is automatically generated and covers collections and works.)

**Comment by tbl73** [comment]
There's a sitemap generating gem for rails - https://github.com/kjvarga/sitemap_generator, but in order to make it work best, we probably need to do some work on our routes first - see issues #310 and #416.

**Comment by saracarl** [comment]
I'd like to capture exactly what steps we think we need here, especially since #310 is closed.

**Comment by benwbrum** [comment]
This depends on friendly URLs for pages and subjects

**Comment by saracarl** [comment]
From our seo research and the fact that google is indexing us just fine, the well structured nature of our site means we don't need a sitemap.
