### ISSUE TITLE
SEO friendly work and collection URLs

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#416]
So:
http://fromthepage.com/collection/show?collection_id=1
Should become one of:
http://fromthepage.com/collection/JuliaBrumfieldDiaries
http://fromthepage.com/JuliaBrumfieldDiaries
http://fromthepage.com/BenBrumfield/JuliaBrumfieldDiaries
we'll have to decide, but I'm leaning toward the last with the work owner by name (not userid), then the collection name.

and 
http://fromthepage.com/display/read_work?work_id=2
Should become one of:
http://fromthepage.com/JuliaBrumfieldDiaries/1918
http://fromthepage.com/BenBrumfield/JuliaBrumfieldDiaries/1918

Should also consider what happens if/when (or if this is part of) a customer org subdomain, i.e.:
http://benbrumfield.fromthepage.com/JuliaBrumfieldDiaries/1918
(or can it be  both?)

**Comment by atomrab** [comment]
Have you thought about clean URIs (for collections, works, and pages) for linking? I know that's at odds with the SEO goal, but perhaps more useful for scholarship/citation.

**Comment by saracarl** [comment]
@atomrab I actually think clean URIs and SEO friendly URLs are the same thing.  (see https://en.wikipedia.org/wiki/Semantic_URL )  

If you have counter examples or improvements to the ones above I'd be happy to discuss them.  I'm not 100% sure what the "right" patterns are, I just know we need meaningful ones.

**Comment by benwbrum** [comment]
We know from the document set breadcrumb issue #289 that we need to look at
routes and nested resources.

At the moment if you navigate from document set S to work W, you can only
get back to collection C, and can never get back to S.

If our URLs looked a bit more like `
http://fromthepage.com/collection/C/work/W` for a set-less work, and `
http://fromthepage.com/colleciton/C/set/S/work/W` or `
http://fromthepage.com/set/S/work/W` then we'd have everything we need to
generate breadcrumbs and other navigation specific to sets.

**Comment by benwbrum** [comment]
Further thoughts on Collection-level slugs:

We should add a new `slug` field to the `collections` table and add a slug input field on the Collection Settings tab.  This needs to have the following validations:
* Slugs must not contain whitespace
* Slugs must be unique in a case-insensitive manner

We should consider populating slugs from CamelCase versions of collection titles.

We should create a new route which matches `/:slug` to the collection controller's `show` action with a `slug` parameter.  If `params[:slug]` is set (and `@collection` was not auto-loaded [note potential conflict with `RecordNotFound` handler on the `ApplicationController` `before_filter`!]) we should do a case-insensitive search on collections for the record with the appropriate slug.  (As a possibly better alternative, this logic could just live in the auto-load code.)

**Comment by saracarl** [comment]
notes from #25 

Had to send someone this link today: http://beta.fromthepage.com/collection/show?collection_id=20&ol=l_hd_c_link

I would have been a lot happier sending them this one:
http://beta.fromthepage.com/jmmclure/collection or something involving the work name like: http://beta.fromthepage.com/jmmclure/grinnell

**Comment by benwbrum** [comment]
Implementing the document set context problem, I suggest we create a new route
`:document_set_slug/:work_id`, but need to see how to propagate that through all url generation.  More research on nested routes needed.

**Comment by saracarl** [comment]
How do other people do this?  Gem?  Also -- what is the naming conventions?

**Comment by tbl73** [comment]
We settled on using the gem Friendly_id for the slug generation and finding.
