### ISSUE TITLE
owner with space in username can't create collection

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4162]
SLQ gets an error creating a collection:
![image](https://github.com/benwbrum/fromthepage/assets/708566/d5bb4ce9-4dc1-4a03-8631-2b7ac58d27eb)

I suspect it's because their username has a space in it:

![image](https://github.com/benwbrum/fromthepage/assets/708566/d3f4a554-a445-4f16-b651-9b6086a0c62f)

**Comment by benwbrum** [comment]
We have also had several reports from end users who have logins with spaces; when they attempt to sign in to their account, they get a validation error and can't sign in.

**Comment by benwbrum** [comment]
Possibly related (if the user actually had a space in their login) -- @benwbrum to research

> I just tried to log in to register as a volunteer transcriber but your computer would not accept me. Apparently someone else has used 'SecondDaughter' as an identification name (which I do understand because there must be hundreds of thousands of second daughters) but also my email address has been used. I am the only person who uses that email address. I did try to volunteer as a transcriber for the National War Memorial but by the time I had my new device, all the work had been done, Many years ago I belonged to a group of people who transcribed for Trove but I was living in a different town then and using a different Internet Service Provider.

> Please advise what I am doing wrong and how to fix it,

**Comment by benwbrum** [comment]
Possibly related -- @benwbrum to research:

> I'm having trouble signing on. The user name and password that I have in my records do not work. When I attempt, therefore, to reset my password, my new choice is not accepted because my user name, I am told, contains <, >, or a space. So, I tried to set up a new account, but of course, my email is already used, so that did not work. What to do?

**Comment by benwbrum** [comment]
The second issue is definitely the same problem:
```
2.7.3 :007 > u = User.where(email: 'peterutas@aol.com').first
 => #<User id: 32013996, login: "Peter Utas", 
```
