### ISSUE TITLE
Approve and Done buttons are both visible

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4172]
Last week we got feedback on early versions of the new done/approve flow (which did not include #4166 or #4171).  

Nat Wooding at LVA reports:

> 
> I'm working on the St. John's Parish second Vestry book collection and starting around Tuesday the screens have been acting a little differently, Since then, whenever I go to a new screen, the Done button appears along with Approved. The attached PNGs illustrate what I'm seeing.
> 
> In the first, I have edited the text but not hit any buttons.
> 
> In the second, I  have hit save. Approved has disappeared but Done remains
> 
> In three, I have hit Done and the system has automatically advance me to the next sheet
> 
> In four, I have returned to the prior page and both Done and Approve appear.
> 
> I don't show the result but I then hit Approve and the two buttons disappeared and the sheet did not change. 
> 
> All this caused me some confusion when I first encountered it and I'm still having to be careful lest I not complete a give page.

Aaron Taylor at NBU reports:
> Feliza and I noticed that there is a change in how the Done, Approved buttons are working and it is causing some difficulties. 

> First, normally, when reviewing a record, we would be presented with the Approve button, but now both Done and Approve show up.

> If we press Done, it automatically transfers us to the next record and then we have to go back to approve the previous record. If we press approve, it automatically moves us to the next record as well.

> I am including a brief video of one record (sorry for any background noise), but was wondering if this change is something you all can fix. The previous functionality worked just fine. Thanks so much!

Jane Kilvin at NEHGS reports:
> Why do I have so many records marked as needing review? I have started to not only click on Save but also on the Done button but they are often still labeled as needing review. Thank you. Jane Kivlin

Action items:
- [ ] Find out why both Done and Approve buttons appear on some pages, and fix this. 
- [ ] Review use cases and feedback to figure out what the correct behavior should be.

**Comment by benwbrum** [comment]
https://github.com/benwbrum/fromthepage/assets/199961/92479b54-9abb-4008-9875-f9a3c6988c6b

Aaron Taylor's uploaded video

**Comment by benwbrum** [comment]
After deploying the change to `transcribe#assign_categories`, we got this feedback from Samara Carey at Dartmouth:

>  I guess for the spirit of feedback, I'll explain how the new flow has affected my work: 
> Normally as I go through documents to finalize review and indexing, I'll select Done, categorize new subjects, then select Approve. Sometimes I'll still have to edit something, so I'll go through the process again. Since I'm working through documents in sets (for Wrangel Island), I'll then clean up the subjects once I'm done reviewing all of the documents. This often means I go back into the documents to delete unnecessary or missed-incorrect indexing, and therefore do the Done>Approve process again.
> 
> In the past week with the new workflow, I've learned that if I select Save first, it will allow me to categorize subjects and won't kick me onto the next page. I then select Done, which kicks me onto the next page, and then have to go back in order to select the Approve button, which again kicks me onto the next page. Then, just to make sure, I'll go back again to confirm everything looks good. Even after all that, it still leaves me with a feeling that I could easily miss approving a page if I got distracted and didn't notice/remember that I had been kicked onto the next page. It's taking me longer to finalize pages, and it means I'm clicking a finish-type button at least 3 times. Then, with subject clean-up, I'm having to go through it all again if I need to edit something. It's been a bit tedious.
> I'm not sure yet if the quick fix you deployed has changed any of that, though I did notice this morning that the Done/Approve buttons no longer appear while I was editing an incorrect indexing tag... perhaps because I already approved that page? It at least didn't kick me onto the next page or make me go through the approval process again, which was nice. 
>

**Comment by WillNigel23** [comment]
@benwbrum do we have a complete and detailed workflow for all scenarios regarding transcribe (or at least your ideal workflow as it seems some of the changes here are the outcome of proposed changes before so not really a bug right)? It would greatly help.

**Comment by benwbrum** [comment]
I'd say that these are misfeatures, rather than bugs.  We built exactly what we intended to build; it just might have been the wrong thing.

**Comment by benwbrum** [comment]
Researching the specific configurations for each of these four users:
* Samara is working on a project that has subject indexing enabled, and review type: required
* Aaron is working on a project with disabled subject indexing and review type: restricted
* Nat is working on a project with disabled subject indexing and review type: restricted
* Jane is working on a field-based project with review type: restricted

**Comment by WillNigel23** [comment]
This looks correct @benwbrum . Working on these changes

**Comment by benwbrum** [comment]
Today's comment from a researcher at the University of Stockholm:

> I am working on the following project together with the National Archives of Sweden:

> https://fromthepage.com/riksarkivet/i-demokratins-namn
> 
> There are some issues with that project site.
> 
> 1. The list "Recent Edits" is not updated. People contribute every day, but, as of today, according to the site, the most recent edit is from 10 days ago.
> 2. Contributors say that they need to press "Done" twice for a site to be recorded as "Done". However, there seems to be some misunderstanding on their part. What seems to happen is that once they press "Done", the available options are "Preview" "Save" "Done" "Approve", while about two weeks ago, pressing "Done" would leave the options "Preview" "Save" "Approve". Whether this is an error or change to the website, I do not know, but could you please take a look and see if everything works as intended?
>
