### ISSUE TITLE
"recent activity" feed has not been updated for 10 days, even though activity is happening

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4182]
This collection's: https://fromthepage.com/riksarkivet/i-demokratins-namn
"recent activity" feed has not been updated for 10 days, even though activity is happening.  The last update is one of these June 17th ones:
https://fromthepage.com/riksarkivet/i-demokratins-namn/30002886a/versions/32791751
(probably the 2nd Gunillaramstedt one)

Perhaps introduced by the following deployment:
![image](https://github.com/benwbrum/fromthepage/assets/708566/a3b253f3-fafc-4a09-9a7a-cd4f7e40dc2b)
which seems to be this PR:
https://github.com/benwbrum/fromthepage/pull/4160
I don't see anything there that would cause this.

Could this be related to the done button issues?

**Comment by saracarl** [comment]
recent activity is fine on FindAProject and the one other collection I checked.

**Comment by benwbrum** [comment]
We heard the same problem from another customer today.
