### ISSUE TITLE
Don't titlelize instructions

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4207]
On a call with Molly from History Revealed, we learned that the contents of field instructions now are being displayed with most words capitalized.

Let's remove `.titleize` from [this line](https://github.com/benwbrum/fromthepage/blob/3386004fbe434a3220f6bb6ea7bb3cf5b420fd82/app/views/transcription_field/_field_layout.html.slim#L20) to fix this.

**Comment by saracarl** [comment]
On this project:

https://fromthepage.com/missouristatearchives/missouri-state-penitentiary-register-of-inmates/msp-vol-99/transcribe/34209274

Every word in the "instruction" type fields is capitalized:
![image](https://github.com/user-attachments/assets/0c2f965e-fb3b-4697-9958-0198c0edbb17)

We should instead display it the way it was entered.
