### ISSUE TITLE
change "editor" and "transcriber" references in the UI to "contributor"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#422]
We've struggled with what to call someone who transcribes a work.  A "transcriber" is accurate, but discounts the level of work many transcribers are actually doing (some transcribers are actually professional editors working on their own projects).  Using "editor" for a volunteer/undergrad transcriber runs the risk of offending professional editors who bring 

We need to go through the UI and document everywhere we are using those terms, think about whether they could be successfully renamed "contributor", and change them if it's appropriate.  If it's not appropriate or questionable, we should discuss it here.  (Possible hack is to just search for those terms in the views.)

I also just noticed that's what github calls people "involved in an issue" -- coder, reviewer, tester, weigher-in -- are all called "contributors".

**Comment by saracarl** [comment]
Change the following from editor to collaborator:
1)  "Editor Dashboard" --> "Collaborator Dashboard"


work settings: http://fromthepage.com/work/edit?work_id=192
2) Allow editors to edit page titles

3) Restrict editors  

4)  Allowed editors

5)  "Add new scribe" ->  "Add new collaborator"

6)  "No allowed scribes selected" -> "No allowed collaborators selected"

FAQ:

What is an editor? The editor and transcriber roles are currently the same.

What is a transcriber? Transcribers transcribe or translate pages in a work/collection. They can also edit page titles if the work owner has given them permission to do so.

Who can transcribe a work? Anyone with a FromThePage account can transcribe any work, unless editors have been restricted by the owner of the work.

7)  get rid of "What is a transcriber?..."

8)  change "what is an editor"? to "What is a collaborator?" and add the above description from transcriber.

**Comment by tbl73** [comment]
What was the conclusion on the collection overview and collection statistics page with top transcribers/top editors?  Did we settle on Top Transcribers and Top Collaborators rather than Top Transcribers and Top Editors?

**Comment by tbl73** [comment]
Changing editors to collaborators in those instances as well.

**Comment by saracarl** [comment]
On Collection Overview, get rid of the whole "top transcribers", "top editors", and "top indexers".

Can we change the bottom of the Collection Statistics page to have a header:
Collaborators
And then 3 columns labelled:
Transcribing
Editing
Indexing

**Comment by tbl73** [comment]
Just pushed those changes up in wording branch.
