### ISSUE TITLE
Greenville County CDM Sync

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#4229]
> We contacted OCLC again since we are still having issues exporting transcriptions to CONTENTdm. Monica referenced the previous ticket #632345 you placed, and let OCLC know we continue to receive the “Invalid pointer 0 specified” error message. The attached screen shot was shared with OCLC and we requested a video call to troubleshoot the issue together. Below is the response we received from OCLC to our question:

> I see something standing out here that seems wrong to me and could be the root of the problem.
The collection is World Friendship Project, alias /WFP.
In your screenshot, the collection that is referenced appears to be alias /https, which doesn’t exist.  I now see on the original ticket you are also trying to change record 8 of collection alias /https.

**Comment by saracarl** [comment]
So a (maybe) working log looks something like this one from USD:
```        
Beginning export of work 32115500, 'Charley F. Gutch World War II letters, 1945-1946' 
 

Updating richardson    record 0       from Biographical Note 34056925       Charley F. Gutch World War II letters, 1945-1946.  CONTENTdm response:
```

note the **Updating richardson    record 0**

In this log (only provided via screenshot) we see:
**Updating https record 0**

![FTP_InvalidPointer_Example](https://github.com/user-attachments/assets/411c0453-e587-4644-bdb3-65e02d6cb9ae)

The line that produces **Updating https record 0** is this one:
https://github.com/benwbrum/fromthepage/blob/development/lib/contentdm_translator.rb#L151

IIIF Manifest is:  https://cdm17168.contentdm.oclc.org/iiif/WFP:997/manifest.json

the at-id in the manifest is `https://cdm17168.contentdm.oclc.org/iiif/WFP:997/manifest.json`
I wonder if the `:` in the manifest URI is causing parsing problems?

**Comment by benwbrum** [comment]
Here is a log file from today:

[cdm_sync_32000328.log](https://github.com/user-attachments/files/16396150/cdm_sync_32000328.log)

**Comment by benwbrum** [comment]
Since I was not able to reproduce the problem in our CDM ID resolver when I imported this manifest locally, I thought that maybe the problem might be a difference in the data between production and my local source:
```

2.7.0 :015 > work = Work.find(32030809)
 => #<Work id: 32030809, title: "World Friendship Project Scrapbook", description: nil, created_on: "2022-09-19 13:0... 
2.7.0 :016 > at_id = work.sc_manifest.at_id
 => "https://cdm17168.contentdm.oclc.org/iiif/WFP:997/manifest.json" 
2.7.0 :017 > # body of the ContentDMTranslator::cdm_collection, which determines the CDM colleciton ID from the manifest
 => nil 
2.7.0 :018 >     if at_id.match(/.*iiif\/info\//)
2.7.0 :019 >       at_id.sub(/.*iiif\/info\//, '').sub(/\/\d+\/manifest.json/, '')
2.7.0 :020 >     else
2.7.0 :021 >       at_id.sub(/.*iiif\/2\//, '').sub(/:.*/,'')
2.7.0 :022 >     end
 => "https" 
2.7.0 :023 > local_version_of_at_id = "https://cdm17168.contentdm.oclc.org/iiif/2/WFP:997/manifest.json"
 => "https://cdm17168.contentdm.oclc.org/iiif/2/WFP:997/manifest.json" 
2.7.0 :024 > at_id==local_version_of_at_id
 => false 
```

It appears that production has the canonical version of the manifest with no version number.  This URL redirects to the version-specific version of the manifest, which contains a version number.  Since our code looks for the version number when it parses the URL, this breaks.

The next question is, where did this value come from?

**Comment by benwbrum** [comment]
I've researched which installations are affected by these strange URLs and discovered that most of them have had problems syncing to CDM:
["Ben W. Brumfield", "Fort Worth Public Library", "Sara Carlstead Brumfield", nil, "Greenville County Library System", "Wisconsin Historical Society"]
