### ISSUE TITLE
Fix versions tab UI

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4288]
We lose line breaks and formatting (i.e. links, but probably other formatting as well) on the right side of the version comparison screen in the versions tab:

![image](https://github.com/user-attachments/assets/67233b53-e36b-494e-ace8-1dabe9ef59e5)

Can we make sure the right side gets the same UI processing as the left?

**Comment by benwbrum** [comment]
Note that we may need very different logic for document-based transcription like this vs. spreadsheet-based transcription, and that's OK.

**Comment by saracarl** [comment]
When testing this, we'll want to make sure the green/red/strikethrough formatting indicating changes between versions is still visible.
