### ISSUE TITLE
Analyze Coveralls report

### ISSUE THREAD

**Issue by WillNigel23** [benwbrum/fromthepage#4328]
Analyze coveralls report to find untested parts of codebase and break down into smaller tickets. This is in preparation of getting to at least 80+% coverage before rails upgrade

**Comment by benwbrum** [comment]
Looking at the coveralls report, I'd prioritize these low-coverage items.  (Items not appearing here either have high coverage or low use.)

- app
  - controllers
    - abstract_xml_controller
    - article_controller
    - bulk_export_controller
    - collection_controller
    - deed_controller
    - demo_controller -- this is dead code and can be removed
    - display_controller
    - document_sets_controller
    - export_controller
    - ia_controller
    - iiif_controller -- we should move most of the logic here to a separate library, keeping only the actions corresponding to routes
    - quality_samplings_controller -- we need a smoke test for quality sampling
    - search_attempt_controller
    - transcription_field_controler
    - work_controller
    - tei_controller -- this may be dead code
  - helpers
    - abstract_xml_helper
    - contributor_helper#activity
    - dashboard_helper -- the tagged collections and the constants look like they might be dead code
    - page_helper
    - export_helper
    - ia_helper
    - print_helper -- this looks like it might be dead code
    - transcription_helper
    - work_helper -- also dead code -- we haven't used docbook in 10 years!
  - models
    - article_version
    - bulk_export
    - cdm_bulk_import
    - collection_reviewer
    - page
    - page_version
    - sc_canvas
    - search_attempt
    - transcribe_authorization
    - user
    - work_search
    - xml_source_processor
  - overrides
    - controllers
      - thredded (Our thredded integration brakes pretty often, so even though it's not heavily used, it would be nice to have some basic tests.)
- lib
  - iiif
  - tasks
    - **bulk_export.rake**
    - cdm_bulk_import.rake
    - cdm_work_update.rake
    - **ingestor.rake** (also a good candidate for refactoring)
    - send_owner_emails.rake
    - update_line_counts.rake
  - ahoy_activity_utils
  - alto_transformer
  - contentdm_translator
  - **image_helper**
  - subject_details_exporter
  - subject_distribution_exporter

**Comment by WillNigel23** [comment]
#4330 Improves on a bunch of things related to `abstract_xml_helper`, `export_controller` and the likes. It would be good to merge the PR for this so we can check again on priorities.
