### ISSUE TITLE
collection level transcription convention changes not propagating down to works

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4343]
For this project:  https://fromthepage.com/ayn-rand-archives/ayn-rand-papers

I'm seeing the "Revert" button on the work settings, which usually means that they changed the work's transcription conventions.  *However*, spot checking shows that all 322 documents in that collection have the "revert" button.  I find it extremely hard to believe that the customer changed all 322 transcription conventions.

Then I tested on this project:  https://fromthepage.com/josie/ann-smith-letters/edit/help
And it works fine.

**Comment by benwbrum** [comment]
See also #4380

**Comment by benwbrum** [comment]
We need to do some experimentation to figure out how to reproduce this.  Several recent customers have experienced this after uploading zipfiles.
