### ISSUE TITLE
Notes list (DataTable) fails to load with HTTP 500

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#4372]
In a development environment with production data, we have 411 notes (as shown in the admin dashboard), but when I click through to the list of notes, I get a popup saying:

> DataTables warning: table id=notes-list - Ajax error. For more information about this error, please see http://datatables.net/tn/7

<img width="397" alt="Browser popup showing a DataTables warning" src="https://github.com/user-attachments/assets/a583cd0a-8977-4ad6-af63-395e55dd84fa">

Relevant log lines appear to be:

```
Started GET "/notes/list?draw=1&columns%5B0%5D%5Bdata%5D=userpic&columns%5B0%5D%5Bname%5D=userpic&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=user&columns%5B1%5D%5Bname%5D=user&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=note&columns%5B2%5D%5Bname%5D=note&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=page&columns%5B3%5D%5Bname%5D=page&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=work&columns%5B4%5D%5Bname%5D=work&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=collection&columns%5B5%5D%5Bname%5D=collection&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=time&columns%5B6%5D%5Bname%5D=time&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=6&order%5B0%5D%5Bdir%5D=desc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1728378329897" for 192.168.65.1 at 2024-10-08 09:05:29 +0000
Processing by NotesController#list as JSON
  Parameters: {"draw"=>"1", "columns"=>{"0"=>{"data"=>"userpic", "name"=>"userpic", "searchable"=>"true", "orderable"=>"false", "search"=>{"value"=>"", "regex"=>"false"}}, "1"=>{"data"=>"user", "name"=>"user", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "2"=>{"data"=>"note", "name"=>"note", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "3"=>{"data"=>"page", "name"=>"page", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "4"=>{"data"=>"work", "name"=>"work", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "5"=>{"data"=>"collection", "name"=>"collection", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}, "6"=>{"data"=>"time", "name"=>"time", "searchable"=>"true", "orderable"=>"true", "search"=>{"value"=>"", "regex"=>"false"}}}, "order"=>{"0"=>{"column"=>"6", "dir"=>"desc"}}, "start"=>"0", "length"=>"10", "search"=>{"value"=>"", "regex"=>"false"}, "_"=>"1728378329897"}
  [1m[36mUser Load (2.3ms)[0m  [1m[34mSELECT `users`.* FROM `users` WHERE `users`.`id` = 3 ORDER BY `users`.`id` ASC LIMIT 1[0m
  ↳ app/controllers/application_controller.rb:73:in `current_user'
  [1m[36mPageBlock Load (0.9ms)[0m  [1m[34mSELECT `page_blocks`.* FROM `page_blocks` WHERE `page_blocks`.`controller` = 'notes' AND `page_blocks`.`view` = 'list'[0m
  ↳ app/controllers/application_controller.rb:264:in `load_html_blocks'
  [1m[35m (13.6ms)[0m  [1m[34mSELECT COUNT(*) FROM (SELECT DISTINCT `notes`.`id` FROM `notes` INNER JOIN `collections` ON `collections`.`id` = `notes`.`collection_id` INNER JOIN `pages` ON `pages`.`id` = `notes`.`page_id` INNER JOIN `works` ON `works`.`id` = `notes`.`work_id` INNER JOIN `users` ON `users`.`id` = `notes`.`user_id` WHERE (collections.restricted = 0)) subquery_for_count[0m
  ↳ app/controllers/notes_controller.rb:83:in `block (2 levels) in list'
Completed 500  in 65ms (ActiveRecord: 21.0ms | Allocations: 20609)

NoMethodError (undefined method `metadata_only_entry?' for nil:NilClass):
  
app/datatables/note_datatable.rb:20:in `view_columns'
app/controllers/notes_controller.rb:83:in `block (2 levels) in list'
app/controllers/notes_controller.rb:80:in `list'
app/controllers/application_controller.rb:64:in `switch_locale'
```

I wonder if 
https://github.com/benwbrum/fromthepage/blob/e50502d6b60a2a577d12ba38eb12f513fef9fdf6/app/datatables/note_datatable.rb#L76
has anything to do with it, specifically the `where` clause. In `iiif_controller.rb` I see `Collection.where(:restricted => false)`. I'm mostly guessing here.

I don't know if any notes are on public collections. If all notes were made on private collections, that could influence the result of the query too. As the admin, however, I would expect to be able to see all notes anyway.

**Comment by WillNigel23** [comment]
Should we move away from ajax datatables? We can implement what I did to the works list table

**Comment by benwbrum** [comment]
I'd like to look at #3739 while we are at it.

Here's the history of the notes list:
* First, we did a single pages of notes, chronologically, for the whole site or a particular collection
* Next we added datatables to try to do filtering of notes to address #3739

Here are the problems I see with the current implementation
* Attempting to access notes for the entire site loads all notes into memory and brings down the server
* Visual pagination via datatables does not match the actual data
* This issue @bencomp is reporting

I'm open to any implementation that addresses this, including what you did with the works list table (so long as it is performant in the case of the whole site note list)

**Comment by bencomp** [comment]
On second thought, it looks like `@collection` is `nil` (always look at the line that raises the error... in this issue, line 20)

https://github.com/benwbrum/fromthepage/blob/e50502d6b60a2a577d12ba38eb12f513fef9fdf6/app/datatables/note_datatable.rb#L13-L21

The `NoteDatatable` only has `@collection` when it is passed as an option. It is only passed as an option when the controller has it as a param:

https://github.com/benwbrum/fromthepage/blob/e50502d6b60a2a577d12ba38eb12f513fef9fdf6/app/controllers/notes_controller.rb#L79-L90

And since I don't pass `?collection_id=XXX`, because that is not part of the link I clicked, we end up with the error.
So it's suggested that you can see all notes in a list, but the controller really only works for notes per collection.
