### ISSUE TITLE
Temporary files and logs are written to public directory

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#4383]
I just realised that during an export, intermediate files and logs are written to a directory that is directly accessible from the web.

https://github.com/benwbrum/fromthepage/blob/337b29aea556b20056fbf7a46e047da7757b95cb/app/controllers/concerns/export_service.rb#L65

When we start storing secrets in the environment (#1202) this is an obvious problem, because the log includes everything in the environment. Yes, to get to the log you need to know the filename including the start time of the export job, but that does not really provide security.

I suggest to store logs in `"#{Rails.root}/log"` and temporary files in `"#{Rails.root}/tmp"`.

**Comment by benwbrum** [comment]
I think that this is worth fixing.

**Comment by benwbrum** [comment]
We'll want to make sure we clean up any logfiles or temporary files -- I'm not sure how that's handled now.

**Comment by bencomp** [comment]
https://github.com/benwbrum/fromthepage/issues/2684#issuecomment-882703057 mentions moving `printable` to `/tmp`. I agree that it's not necessary to have files in `public/` to allow them to be streamed. [`ActionController` streams by default](https://guides.rubyonrails.org/v6.1/action_controller_overview.html#streaming-and-file-downloads), according to the docs.

I found an old issue of mine, about creating an overview of paths in use by FromThePage: #1548 

> We'll want to make sure we clean up any logfiles or temporary files -- I'm not sure how that's handled now.

For some types of files/records, I believe there are rake tasks that clean up files, perhaps triggered by cronjobs. But this is your project 😃 
It may be worth looking into [Active Jobs](https://guides.rubyonrails.org/v6.1/active_job_basics.html) to perform tasks (more) asynchronously, even though it would create other dependencies.
