### ISSUE TITLE
500 error in watchlist

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#442]
I was just looking at UT's server at another error and noticed this:
I, [2016-10-13T09:51:05.832106 #29272]  INFO -- : Started GET "/dashboard/owner" for 128.83.242.128 at 2016-10-13 09:51:05 -0500
I, [2016-10-13T09:51:05.833298 #29272]  INFO -- : Processing by DashboardController#owner as HTML
I, [2016-10-13T09:51:05.870282 #29272]  INFO -- :   Rendered dashboard/_owner_header.html.slim (9.6ms)
I, [2016-10-13T09:51:06.049336 #29272]  INFO -- :   Rendered deed/_deeds.html.slim (1.7ms)
I, [2016-10-13T09:51:06.049522 #29272]  INFO -- :   Rendered dashboard/owner.html.slim within layouts/application (189.0ms)
I, [2016-10-13T09:51:06.055894 #29272]  INFO -- :   Rendered shared/_breadcrumbs.html.slim (0.1ms)
I, [2016-10-13T09:51:06.056840 #29272]  INFO -- : Completed 200 OK in 223ms (Views: 191.0ms | ActiveRecord: 17.2ms)
I, [2016-10-13T09:51:08.420646 #29272]  INFO -- : Started GET "/dashboard/watchlist" for 128.83.242.128 at 2016-10-13 09:51:08 -0500
I, [2016-10-13T09:51:08.422295 #29272]  INFO -- : Processing by DashboardController#watchlist as HTML
I, [2016-10-13T09:51:08.464554 #29272]  INFO -- : Completed 500 Internal Server Error in 42ms
F, [2016-10-13T09:51:08.474451 #29272] FATAL -- : 
NoMethodError (undefined method `id' for nil:NilClass):
  app/controllers/dashboard_controller.rb:114:in `recent_work'
  app/controllers/dashboard_controller.rb:94:in `watchlist'

May be owner permissions related?

**Comment by tbl73** [comment]
Do they have the code we added yesterday?  Or from the push previous to that?  It sounds like the error I was seeing yesterday.

**Comment by saracarl** [comment]
Yes.  This is the same code we pushed to production.

**Comment by tbl73** [comment]
Okay, so I'm not sure why specifically the recent_deeds is coming up empty in their list if they have the newest code, but I was able to reproduce it in a blank database (so there weren't many deeds and/or no blank pages).  We need to check to see if there are any recent works, and if not, that link needs to be set differently.  We could either link to a specific database (but it might be old), or just not have a link if the recent deeds doesn't work.  (So, something like "You haven't participated in any projects yet.  Try transcribing a page of an interesting collection, and link to the collections list?)  Or link somewhere else, if you have any thoughts on where?

**Comment by tbl73** [comment]
I just pushed up changes to this code in editor-dash branch and created a pull request.

**Comment by tbl73** [comment]
Fixed in pull request #444 and #446.
