### ISSUE TITLE
(Old) verify-v1 meta tag is hardcoded

### ISSUE THREAD

**Issue by bencomp** [benwbrum/fromthepage#4454]
There is a hardcoded meta tag in application.html.slim with the name `verify-v1`. 

https://github.com/benwbrum/fromthepage/blob/076c5ba4f4fc2f104eb93926fb4eaf0b8e3dec82/app/views/layouts/application.html.slim#L17

I think this should be configurable (like #832) or be removed entirely. Apparently Google uses different meta tag names nowadays, as well as different verification methods.

**Comment by bencomp** [comment]
Oops, this is a duplicate of #1625

**Comment by benwbrum** [comment]
I think we will be fixing this after all with #4794
