### ISSUE TITLE
Status of page import from internet archive using OCR

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#447]
When you import a work from the internet archive and use OCR, the work shows up as transcribed in the collection view, but not in the page view (because of the revisions).  To make the workflow less confusing, we need to change the "transcribed" wording for OCR-imports to "corrected" - if you look at a page, rather than saying the page hasn't been transcribed yet, say the page hasn't been corrected yet.

**Comment by tbl73** [comment]
I changed this wording, but I just realized that this also means that the first time a person does a correction on the OCR text, it's going to be considered a transcription deed, rather than edit deed.  Is that what we want?  I could change the import so that OCR text ends up at revision 2 (so that deeds are edit deeds).  Sara and I had talked about that this morning, and the only thing that's problematic with that is that you can't really see what needs to be corrected at a glance, but I could change the UI so that the new pages show up as needing correction.  Just trying to figure out what the right workflow is here.  @benwbrum , @saracarl , what do you think?

**Comment by saracarl** [comment]
If we change the import to set it to revision 2, I have 2 concerns:
1)  What does the revision history look like?  (no real changes between 1 and 2?)
2)  How do you tell that a page has or hasn't been corrected yet?

#2 is the most important bit here -- and maybe we can't accomplish it with this change, but anything we can do that implies "this page here, it needs correcting" (and vice versa) would be good.

**Comment by saracarl** [comment]
Ah, your note says:  " the UI could be set up to show you the pages that haven't yet been corrected similar to the way new transcriptions show up. "  Should that actually read "couldn't"?  

And if it couldn't, then we should not set it to revision 2.

**Comment by benwbrum** [comment]
Should we be creating a new "Corrected" deed or "OCR Corrected" deed?  It
seems like this ought to be a totally separate process.

**Comment by tbl73** [comment]
I was actually thinking that I might be able to set it in the UI to show up saying "This page needs to be corrected", regardless of the revision.  When you use OCR in the import, the page status is set to "raw_ocr", and that doesn't change until someone actually saves a change to the page (i.e., it's true for revision 0 and revision 1 when those are done automatically).  I could use that status to display "this page needs to be corrected", much the way we do "this page needs to be transcribed", so that the user could tell by looking at the pages whether they have been corrected or not.

However, it's true that the revision history looks kind of strange.  I think Ben might be right about needing to have another kind of deed for this - it does seem like a separate sort of process.

**Comment by saracarl** [comment]
I love the first idea here.

A different type of deed probably makes the most sense.  We have one for
translation, right?

Sara

**Comment by tbl73** [comment]
We do have translation deeds - page-translate and page-translate-edit, apparently. So correction deeds would make sense.  It sounds as though what we want in the long run is for it to be revision 0, with new correction deeds rather than transcribe/edit deeds.  In the short term, do you want me to set it to revision 0 (first deed transcription, then edit) or revision 1 (all deeds edits).  In either case, I'll have it check the page status to display correction if no user has touched it yet.  And then I can create an issue to make the new deed types.

**Comment by tbl73** [comment]
We've decided to set it to revision 0, show the OCR pages as needing to be corrected, and set up a new issue for creating ocr_correction deeds.

**Comment by tbl73** [comment]
Pushed up code in ia-stats.  Further OCR correction deeds information in issue #451.
