### ISSUE TITLE
IA Import Error - Data too long for column description

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#448]
In selecting random works from the internet archive to import while testing, a number of them fail with  an error that says that "the data is too long for column 'description'".  Here's a screen shot of the error:
![iawork](https://cloud.githubusercontent.com/assets/16854029/19441485/dda74bf0-9453-11e6-8fff-e91c01426934.PNG)

The description column is set to varchar(255), and this particular description is really quite long (appears to be 887 characters).  It came up for multiple items, though.  @benwbrum , do you have any thoughts on this?  Do we need to make the description column longer?  Or is there something else that should be happening?

**Comment by benwbrum** [comment]
I think we should update the description field to 1024, but before that we
should truncate the data on the import.

Ben

**Comment by tbl73** [comment]
That makes sense.  I'll need some pointers on truncating the data on import, though.

**Comment by benwbrum** [comment]
Here's the best thing I found on truncation:
http://stackoverflow.com/questions/26122948/activerecord-intentionally-truncate-string-to-db-column-width

Apparently this happened automatically on older versions of Rails.

**Comment by tbl73** [comment]
I set up a migration to change the description field to 1024.  I also figured out that the description could be truncated on the import (during ingest work in the ia_work model), so it's now set to truncate to the column limit minus 200 (to leave room for the sponsor and contributor info that are added to the string in the convert process).   I pushed it up in the truncate-import branch.
