### ISSUE TITLE
Could links be added to each page

### ISSUE THREAD

**Issue by NatWooding** [benwbrum/fromthepage#45]
I don't know how many of the other JG trips would be affected but for the trip to the San Martir mountains, Chester Lamb was the other half of the party. A link to a cleaned up copy of his map of collecting stations as well as to his own notes could be useful at times. Also, are there records available on line of the plants that they collected? A link to these could be useful, especially since JG often used common names.

**Comment by saracarl** [comment]
Collection specific (but a cool idea!).  Closing.
