### ISSUE TITLE
missing works -- pages need to be deleted?

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#459]
There are a number of errors of "undefined method collection for nil:NilClass, application controller.rb 36, in load_objects_from_params.  I'm listing the page_ids and page_version_ids that are getting that error.  I found something very odd with them, though - when I look at my local database (which is an old version of the production server), I find that those pages are associated with a work_id of 135, but I don't actually have a work with the ID of 135.  Which obviously causes trouble for the params loading.  I'm not sure how that would happen, or how people would see the pages to click on them, but I think you might need to look into work id 135 in the database! 

    page_id=6406

    page_id=6451
    page_id=6490
    page_id=6498
    page_id = 6465
    page_id = 6485
    page_id = 6391

    Same error: /page_version/show?page_version_id=26773; "page_version_id"=>"26779"; /page_version/show?page_version_id=26774, "page_version_id"=>"26773

-- write code that finds orphan works/pages/articles and "deals with them appropriately" -- we don't know what that is however.

**Comment by saracarl** [comment]
Possibly following an "activity" link for a work that has since been deleted.  (Or possibly privatized.)
Should we be deleting deeds associated with a work that has been deleted.

**Comment by saracarl** [comment]
Also seeing this in Fordham's environment -- work with ID 10 is not in the database (assume deleted) but generating this error:

D, [2016-11-29T23:38:20.898844 #16869] DEBUG -- :   ESC[1mESC[36mWork Load (0.6m
s)ESC[0m  ESC[1mSELECT  `works`.* FROM `works`  WHERE `works`.`id` = 10 LIMIT 1
ESC[0m
I, [2016-11-29T23:38:20.899960 #16869]  INFO -- : Completed 500 Internal Server 
Error in 6ms
F, [2016-11-29T23:38:20.904091 #16869] FATAL -- : 
NoMethodError (undefined method `collection' for nil:NilClass):
  app/controllers/application_controller.rb:36:in `load_objects_from_params'

**Comment by tbl73** [comment]
Deleting collections and works hasn't been deleting child data up to this point, so there is a lot of orphaned data in the database.  I've set up the models to delete the child associations, and written a migration to clean up the database.
