### ISSUE TITLE
"create work" action on owner dashboard doesn't work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#460]
It just gives a yellow warning icon.

We may need to remove this -- the way to start a work at this point is to "start a project".  If we keep it, it needs to work!

**Comment by saracarl** [comment]
put it here instead:

http://localhost:3000/collection/new_work?collection_id=16

**Comment by tbl73** [comment]
Need to be able to create an empty new work for users who are uploading individual images.  Move into the "Start a Project" tab for consistency.  Remove from the Action menu.
Also, in the "Add a page" option in the Pages tab for a work, the modal currently has "Save & New Work" as an option, which should just be "Save".

**Comment by saracarl** [comment]
So I spoke with Ben about this particular bit more:

Also, in the "Add a page" option in the Pages tab for a work, the modal currently has "Save & New Work" as an option, which should just be "Save".

And his view is that building a work via individual pages won't ever be done via the web UI, but would be a pretty common thing using the mobile UI.  

Mobile is addressed in #458  I suggest we back out the page view changes and address them in that feature/issue.  (Let's note them there.)

**Comment by tbl73** [comment]
Closed with pull request #468
