### ISSUE TITLE
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#465]
When running rake tasks you get the above error.  

We probably need to change all references to RMagick to rmagick:
https://github.com/benwbrum/fromthepage/search?utf8=%E2%9C%93&q=RMagick

But it needs testing. A lot of that work is image processing; I'm not sure how thorough our test coverage is on that.

**Comment by tbl73** [comment]
Currently it's not very thorough on image processing, so that might involve adding some tests.  (And direction on what specifically needs to be tested within the image processing.)

**Comment by PeterTonoli** [comment]
Not just running rake tests get this error, running 'rails server' causes this error.

**Comment by saracarl** [comment]
@PeterTonoli I think this is a warning (rather than an error), but please confirm that you are able to run the server successfully even with this message?  (Or not!)

**Comment by PeterTonoli** [comment]
@saracarl Apologies - yes, it's a warning, not an error. Server runs successfully :-)
