### ISSUE TITLE
Linking: Catch unclosed [[ ]] pairs and error out so you can't save it if it's wrong.

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#473]

**Comment by saracarl** [comment]
workaround:  you can fix it by editing the page and adding back in the close brackets.  The problem is finding it in the first place -- this is the easiest way:

MariaDB [fromthepage_production]> select * from page_article_links where display_text like '%]%';
Empty set (0.00 sec)

MariaDB [fromthepage_production]> select * from page_article_links where display_text like '%[%';

**Comment by tbl73** [comment]
If a user adds a link but accidentally doesn't close the final bracket, additional links will show up with brackets inside the link.  This causes autolinking to fail, so we need to catch the unclosed bracket on save and prompt the user to fix it.

**Comment by tbl73** [comment]
We also need to catch unclosed extra brackets in the middle of the link - i.e., [[John[? Doe]] - the link can contain single brackets if they are closed properly, but autolinking breaks if they are not properly closed.

**Comment by saracarl** [comment]
tested successfully.
