### ISSUE TITLE
500 error in read_all_works

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#476]
D, [2016-11-30T00:44:12.531987 #16869] DEBUG -- :   ESC[1mESC[36mPageBlock Load 
(0.6ms)ESC[0m  ESC[1mSELECT `page_blocks`.* FROM `page_blocks`  WHERE `page_bloc
ks`.`controller` = 'display' AND `page_blocks`.`view` = 'read_all_works'ESC[0m
I, [2016-11-30T00:44:12.533319 #16869]  INFO -- : Completed 500 Internal Server Error in 254ms
F, [2016-11-30T00:44:12.537879 #16869] FATAL -- : 
ArgumentError (wrong number of arguments (2 for 1)):
  app/controllers/display_controller.rb:48:in `read_all_works'

**Comment by tbl73** [comment]
I can't figure out how you would even get to the read all works page unless you were coming from the articles page, which seems to work okay.  I'm not sure if this is still an issue. @saracarl , any idea?

**Comment by tbl73** [comment]
display_controllers read_all_works - line 44 doesn't seem to be getting any pages with the syntax as it currently stands.

**Comment by benwbrum** [comment]
This also shows up in the full-text search on the whole collection.  Maybe we're hitting the bug that way?

**Comment by benwbrum** [comment]
Could not reproduce.
