### ISSUE TITLE
Need a delete button for subjects that are bad/old/no links to them

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#478]
Here's an example of a subject that was created due to bad linking:
http://fromthepage.ace.fordham.edu/article/edit?article_id=121
We fixed the linking, which fixed the page that used to refer to this subject.  The subject itself is still here, however.  There's no way to delete it.  
So we need one or more of the following to fix this:
-- identify orphan subjects (no text linking to them) and delete them
OR
-- a "delete" button on subjects so someone can manually delete them.

I lean toward the 2nd solution -- manually click a button to delete a subject.  (Maybe we create a list of them in some owner view?)

**Comment by atomrab** [comment]
Lurking on the issue tracker -- from my own user perspective, having had this happen a lot with students, I would very much like a delete button. I know what I'm trying to delete, and I wouldn't want a subject to disappear if a student happened to unlink it by accident.

**Comment by saracarl** [comment]
Great, thanks for the feedback, Adam.  "Press a button to delete a subject"
is obviously the way to go, so we'll do it that way.

Sara

**Comment by saracarl** [comment]
Verified.  Only visible to owners.  Requires removing all referring links before deleting.
