### ISSUE TITLE
getting url_for to work in rake tasks

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#488]
1025  vi lib/tasks/contributors.rake 
remove:  
#include Rails.application.routes.url_helpers
#Rails.application.routes.default_url_options[:host] = 'localhost:3000'

add:
 Rails.application.routes.url_helpers.url_for..
to all instances of url_for

 1027  vi config/environments/production.rb 
add:
Rails.application.routes.default_url_options[:host] = 'fromthepage.com'

**Comment by tbl73** [comment]
Okay, I pushed those changes up in the rake-task branch.  I did find some references online to other people having some issues with url_for in production but not development environments, though I don't really know why.
