### ISSUE TITLE
add "login as" option for administrators

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#489]
There are gems that do this for you that work with devise.

Good for support and demos.

**Comment by saracarl** [comment]
please research & then we'll discuss.

**Comment by tbl73** [comment]
Noting the gems/instructions I've found as possibilities.
https://github.com/rcook/user_impersonate2
https://github.com/ankane/pretender
https://github.com/flyerhzm/switch_user
Not a gem, but a method of doing this: https://github.com/plataformatec/devise/wiki/How-To:-Sign-in-as-another-user-if-you-are-an-admin
