### ISSUE TITLE
recent_activity rake task needs edits

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#490]
1)  At first I thought it was just not reporting edits to transcriptions:

i.e.:  http://fromthepage.com/collection/show?collection_id=11

[fromthepage@fromthepage current]$ rake fromthepage:recent_activity[11]
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
No new transcribers
<br>
No recent transcriptions
<br>
No recent notes

2)  but now I think it's more than that:
http://fromthepage.com/collection/show?collection_id=16

[fromthepage@fromthepage current]$ rake fromthepage:recent_activity[11]
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
No new transcribers
<br>
No recent transcriptions
<br>
No recent notes
[fromthepage@fromthepage current]$ rake fromthepage:recent_activity[16]
[DEPRECATION] requiring "RMagick" is deprecated. Use "rmagick" instead
No new transcribers
<br>
No recent transcriptions
<br>
No recent notes

**Comment by tbl73** [comment]
@saracarl  - are you getting any errors, or is it just not giving you any data?  It seems to be working fine on my dev machine.  I wonder if there could be some kind of time zone issue?  (It does include edits in the recent transcriptions, by the way.)
