### ISSUE TITLE
Export does not seem to provide valid XHTML

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#494]
If you click Export as XHTML, a view of the data shows up.  If you save that page, it saves as HTML, not XHTML.  If you change the extension to xhtml, the file won't open.  

I'm pretty sure some of the problem is because that view isn't inheriting from layouts/application.html.slim - presumably it shouldn't, because the CSS shouldn't be included, but there's also no doctype declaration for the page then.

I ran the file (as xhtml) through an online validator, and the results are below:

Validation Output: 8 Errors

Error Line 3, Column 1: no document type declaration; implying "<!DOCTYPE html SYSTEM>"
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">…
✉
The checked page did not contain a document type ("DOCTYPE") declaration. The Validator has tried to validate with a fallback DTD, but this is quite likely to be incorrect and will generate a large number of incorrect error messages. It is highly recommended that you insert the proper DOCTYPE declaration in your document -- instructions for doing this are given above -- and it is necessary to have this declaration before the page can be declared to be valid.

Error Line 3, Column 86: end tag for "meta" omitted, but OMITTAG NO was specified
…tent="text/html; charset=UTF-8"></head><body><h1 class="work-title">[Letter to…
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 3, Column 13: start tag was here
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">…
Error Line 3, Column 86: end tag for "head" which is not finished
…tent="text/html; charset=UTF-8"></head><body><h1 class="work-title">[Letter to…
✉
Most likely, you nested tags and closed them in the wrong order. For example <p><em>...</p> is not acceptable, as <em> must be closed before <p>. Acceptable nesting is: <p><em>...</em></p>

Another possibility is that you used an element which requires a child element that you did not include. Hence the parent element is "not finished", not complete. For instance, in HTML the <head> element must contain a <title> child element, lists require appropriate list items (<ul> and <ol> require <li>; <dl> requires <dt> and <dd>), and so on.

Error Line 6, Column 5: end tag for "hr" omitted, but OMITTAG NO was specified
<hr>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 6, Column 1: start tag was here
<hr>
Error Line 33, Column 7: end tag for "br" omitted, but OMITTAG NO was specified
  <br>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 33, Column 3: start tag was here
  <br>
Error Line 53, Column 7: end tag for "br" omitted, but OMITTAG NO was specified
  <br>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 53, Column 3: start tag was here
  <br>
Error Line 73, Column 7: end tag for "br" omitted, but OMITTAG NO was specified
  <br>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 73, Column 3: start tag was here
  <br>
Error Line 76, Column 5: end tag for "hr" omitted, but OMITTAG NO was specified
<hr>
✉
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".

Info Line 76, Column 1: start tag was here
<hr>

**Comment by benwbrum** [comment]
I've looked into this -- we need to add code to generate this at the top of the show template:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
      <title>A Small Document</title>
    </head>
<body>
```

and this at the bottom:
```
  </body>
</html>
```

That should validate correctly at http://validator.w3.org/check

**Comment by tbl73** [comment]
I changed the export/show.html.erb page to use the headers listed above, and when I export the works as a zip file, they now validate correctly, so that seems to work.  It's in the export branch.
