### ISSUE TITLE
Autolinking finds only first instance

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#495]
The code to autolink subjects only finds the first instance of an entity - needs to be changed to find multiple entities if they exist.  (See the abstract_xml_controller.)

**Comment by saracarl** [comment]
for a collection, pull out all verbatim text from page-subject links.
search in source text field for the verbatim
currently "stop" once we find the first match for verbatim
guessing that's done via a search & replace (i.e. .sub).  

Turn line 33-? into a while loop:
give us the index of the first match
do our linking 
then loop again, but start at the index of this text starting at the index +1 

(check how "index" works.)

Alternative:  do all this using very clever regex and gsub.  Challenge is to make sure stuff isn't double linked.  
Option 1)  brute force: substitute verbatim with subject link, then a "cleanup" phase -- look for 4 [[[[ and substitute/cleanup in those instances.
Option 2)  Regex that uses look-aheads to make sure that what it's looking for in the text doesn't have square brackets.

**Comment by tbl73** [comment]
I ended up using a regex gsub with a block that can pass the matched text to a function that tests if it's already a link before doing the substitution.  In the autolinking branch.
