### ISSUE TITLE
Orphaned pages/deeds if work is deleted

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#496]
Currently, if a work is deleted, no dependencies are deleted, so we end up with orphaned pages and deeds in the database.  These need to be cleaned up when a work is deleted.

**Comment by benwbrum** [comment]
Yes!  That explains some artefacts I've seen elsewhere.

**Comment by tbl73** [comment]
#459 refers to the same issue, so I'm closing this one.
