### ISSUE TITLE
Access Control Lists/Private Transcription Projects

### ISSUE THREAD

**Issue by srl295** [benwbrum/fromthepage#5]
It's great that FTP is being used for transcribing important documents, however, it could be useful in situations where the content is not 'world readable'.  Consider access control lists to restrict access to projects. 

This could be a plugin model, where the access control is provided by other code. (In fact, that's where integrating fromthepage with other code might come in)

**Comment by dlev** [comment]
Hi Ben,

This just dropped into by mailbox and made me wonder what’s new with From the Page…  It looks like I missed the launch of FTP2 and I do hope you are continuing work with the program. I still have a HUGE project working with my grandmother’s letters and papers and would welcome a way to move forward. 

I’m checking out your website now. Please keep me on your mailing list.

Thanks,
Denise

Denise May Levenick
The Family Curator
http://thefamilycurator.com
dmlevenick@gmail.com
