### ISSUE TITLE
Mark document as complete to get to 100%.

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#502]
remove the document state drop down and add a “save and complete” button next to the current “save” button. We'll then have 3 states – 0% (not started), 50% (started/some transcription), 100% (“save and done” clicked).

**Comment by saracarl** [comment]
We discussed this with the customer, and settled on a checkbox on each page view that is "needs review".  This checkbox should replace the status drop down in terms of layout and formatting.

The status screen (collection homepage listing works & status -- http://fromthepage.com/JuliaBrumfield ) should then reflect pages by percentage based on 3 states:

1)  has any transcription + "needs review" not checked = transcribed; green in status bar
2)  has any transcription + "needs review" checked = does not count as transcribed + orange in status bar
3) has no transcription = does not count as transcribed

Open question: how do we mark blank pages?  I'm wondering about a checkbox for that.

**Comment by saracarl** [comment]
@benwbrum : need your input on blank page indicators.

**Comment by saracarl** [comment]
4 states:  transcribed, indexed (or not), needs review, or nothing.  Figure percentage of each one -- no overlaps (if something is transcribed and needs review, then it is in the "needs review" bucket/percentage, rather than the "transcribed" bucket.  Same for indexed.)

States should be listed on the green status bar in the following order from left to right:
indexed, transcribed, needs review, nothing.

needs review should be done in yellow.

**Comment by saracarl** [comment]
Remove status dropdown.  Add 2 checkboxes on each page view that is "needs review" and "blank"  on the same line as "save" and and "fullscreen", but aligned closer to the "save" button than the fullscreen button.

**Comment by tbl73** [comment]
Need to create a tab that lists the pages that need review.
