### ISSUE TITLE
Owned Works and Collections should be listed on user profile

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#504]
When I go to a user profile, i.e.:  http://fromthepage.com/user/profile?user_id=677
I should see the collections and works they own.

**Comment by benwbrum** [comment]
What is being suggested here is the idea that 
1) organizations will create an account for the organization (which they already do),
2) organizations need a public home for their projects (which they do need), and that
3) the organization user's profile page should be that public home.

This is a pretty elegant solution

**Comment by saracarl** [comment]
See also #370 .  The idea of an owner's page being the "strategic landing page" for everything that a customer is doing makes more sense than a collection level splash page.  We could also enhance this with other features like "announcements".  

We should do a user slug too, so that the user's page is easy to find/get to.

**Comment by tbl73** [comment]
This has been done in terms of showing owned user collections.  Further thoughts on this are included in #740.  Closing.
