### ISSUE TITLE
Restore this version

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#523]
Fordham has half a dozen people working on the same page simultaneously while they videoconference.  As a result, it's really easy for the person editing the most recent version to save, then someone else (viewing an older version) accidentally hits save and overwrites the good version.

Adding a "restore this version" function to the versions screen would help immensely.

**Comment by saracarl** [comment]
Obviated by both the "someone else is editing this" #1063 and our spam remediation work.
