### ISSUE TITLE
Table formatting instructions

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#525]
This needs to go somewhere:

Table formatting Instructions:
- Cells should be separated with a pipe and a space (" | ")

- Headers are formatted the same way a cell is, but followed by dashes and pipes on the following line:
| Items  |  Urgent  |  Not Urgent |
|---------|-------------|------------------|
The dashes set the amount of space the column will display with.

- A return will create a new line in the table
- empty cells can be indicated with a space (" | | ")

Troubleshooting: make sure you have spaces around the "|" characters.  The very beginning and end of the line and the header separator doesn't need spaces.  Everywhere else does.

**Comment by saracarl** [comment]
help screen?

**Comment by benwbrum** [comment]
This already exists on the documentation pages.
