### ISSUE TITLE
OCR Uploaded Documents

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#533]
It would be straightforward to add an "OCR" step to the document upload process.  If we modify the post-zip/pdf-extraction flow to loop over each file and do this:

`tesseract page_0002.jpg page_0002`
then slurp `page_0002.txt` into a string and use it as the initial transcript of the page.

(Note that we would need to `gsub` `<` and `>` characters to XML entities so that saving the XML didn't blow up.)

We'd need to consider whether to require the user to specify this in advance, or to add a step to an already-ingested work to perform this process.

**Comment by saracarl** [comment]
To make this backwards compatible across installations, we should add a configuration option with the execution path/command for the tesseract executable.

The `application_helper` should add a method `ocr_enabled?` which checks whether this is defined/nil/blank or has a value; returning a boolean.  

Controls in the application that prompt a user to perform OCR should check `ocr_enabled?` before they are displayed.

**Comment by saracarl** [comment]
Closing until we decide to add this to the product roadmap.
