### ISSUE TITLE
internet archive images not showing up

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#542]
http://fromthepage.com/display/read_work?work_id=120

http://fromthepage.com/display/display_page?page_id=5978#page/n0/mode/1up

Error serving request:
  Image error: Image stack does not exist at /13/items/doc3617pp3-12/doc3617pp3-12_jp2.zip

Debugging information:
#0 /var/cache/petabox/petabox/www/datanode/BookReader/BookReaderImages.inc.php(221): BookReaderImages->BRfatal('Image stack doe...')
#1 /var/cache/petabox/petabox/www/datanode/BookReader/BookReaderImages.php(15): BookReaderImages->serveRequest(Array)
#2 {main}

**Comment by saracarl** [comment]
This is a bug with IA.

This doesn't work:
https://archive.org/details/doc3617pp3-12

This does:
https://archive.org/details/doc3617pp3-61

plan:  open a bug with IA.

**Comment by saracarl** [comment]
Test this after #1531

**Comment by benwbrum** [comment]
The problem item is no longer available.
