### ISSUE TITLE
Guest user account - number of saves before sign up

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#549]
Currently, the guest account features requires the user to sign up after they've saved three times.  This is set in transcribe/save_transcription and transcribe/save_translation, currently hard-coded to three times.  If we wanted to make that number configurable, we'd need to change that to a variable which could be set either through a config file or on a collection level.  On a collection level, we'd need to create a new column in the database with that information, and then set the variable through that.

One thing to note is that this code is triggered after the data is saved, so even setting that number to zero would not prevent a guest from saving at least one time.  (If the code was parsed before the save, a new/guest user would lose their work when they are sent to the sign up, which would be a problem in the gradual engagement model.)

For documentation, this is the code for the save:
if current_user.guest?
   deeds = Deed.where(user_id: current_user.id).count
   if deeds < 3
     flash[:notice] = "You may save up to three transcriptions as a guest."
  else
     redirect_to new_user_registration_path, :resource => current_user
     return
  end
end
 +

**Comment by benwbrum** [comment]
Let's change this to a constant, to be set in `environments/whatever.rb`
