### ISSUE TITLE
option to align text to the right

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#566]
For Arabic, for example.

**Comment by benwbrum** [comment]
Needs more definition.  I did a write up a couple of years ago in an email.

**Comment by benwbrum** [comment]
This is suddenly of high importance.

We need to allow administrators to configure projects to use a specific language.  Eventually languages may vary between works within the same collection (e.g. letters in Polish and Yiddish from different correspondents may appear in a 19th century Eastern European's papers) or within a particular text, but at the moment we will focus on single-language collections and on alignment/justification for right-to-left languages.  If the language of a text is a right-to-left (RTL) language, we should add the appropriate tags to HTML forms, paragraphs, divs and spans to support proper text justification.

To support this feature:

- A project owner should be able to select a langage on the collection settings screen, using a drop-down populated with ISO-639 language names and storing the code in a new column on `collections`.  See the [ISO-639 gem] (https://github.com/alphabetum/iso-639)
- When displaying text (page overview, read work, subject article, possibly subject list screens) we should add `lang` and `dir` attributes to the [relevant HTML elements](http://sites.psu.edu/symbolcodes/web/rtl/).  The [rtl gem](https://github.com/abarrak/rtl) may be useful here.
- When transcribing text, the transcription form should be justified appropriately, also using `lang` and `dir` attributes.
- When exporting text as TEI, the `profileDesc` should have a [new `langUsage` block](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-langUsage.html) containing a `language` element with the appropriate code.

**Comment by benwbrum** [comment]
We should test the experience of adding subject links, as entering LTR characters `[[` and `]]` within RTL text can cause the cursor to jump around unnervingly.

**Comment by saracarl** [comment]
Let's spin the TEI export and subject linking out to a 2nd issue.  It's not a requirement for the customer who needs this RSN.  (We should still do it, but I'd like to deploy the first half first.)
