### ISSUE TITLE
Deeds for deleted users

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#568]
Currently, if you delete a user, any deeds for that user are still associated with that user id.  We need to determine the best course of action for handling the deeds if a user is deleted, to make sure that the views don't break due to a non-existent user id.

Option 1: delete the deeds on user delete
Option 2: migrate the deeds to a guest user account, using a before_destroy or after_destroy callback in the user model
Option 3: set a flag that hides the deeds somehow if a user is deleted

The only people who can currently delete a user account are either the user themselves or an admin.  Admin deletion is really only likely for abuse reasons.  We're leaning towards migrating the deeds to a guest user, with manual intervention on the admin's part if necessary in the case of abuse.

**Comment by saracarl** [comment]
@tbl73  is this still a problem when we move guest users over?  Or should we move deeds to a guest user account for a deleted user?

**Comment by tbl73** [comment]
This doesn't really apply to the guest user accounts, only to deleting an actual user.  We never made a decision about what to do with deeds when a user is deleted, though.  Migrating the deeds to the guest user account is one of the options we talked about - all three are listed above.

**Comment by saracarl** [comment]
@benwbrum I think this is resolved now?  Or does it need more thought?

**Comment by benwbrum** [comment]
See also #758

**Comment by saracarl** [comment]
Closing -- fix under #758
