### ISSUE TITLE
OpenSeadragon navigation images not displaying with imported IIIF works

### ISSUE THREAD

**Issue by jbhoward-dublin** [benwbrum/fromthepage#569]
Images for zooming, panning have incorrect file paths in transcription view of IIIF works and therefore the broken image icon displays. Example:

`<img src="../assets/iiif-images/zoomin_grouphover.png" alt="Zoom in" style="background: none transparent; border: none; margin: 0px; padding: 0px; position: absolute; top: 0px; left: 0px; opacity: 0;">`

**Comment by tbl73** [comment]
In my dev environment, those icons are fine, but I can see they aren't showing up in production.  The path seems the same (/assets/iiif-images), so I'm wondering if it's a problem with the actual icon files.  Perhaps something happened with them when the production server had disk issues a few weeks ago?  I don't have access to check, but they should be located in /public/assets/iiif-images on the production server.  @saracarl , let me know if you need me to look any further into this.

**Comment by benwbrum** [comment]
Is there a chance we need to precompile the assets?

**Comment by tbl73** [comment]
It looks like OpenSeadragon assets should be precompiling already, actually.  If the folder is there, could something have happened with permissions?

**Comment by saracarl** [comment]
So the funny thing with this one is on Firefox they icons just don't show up at all (so you don't notice the problem!).  On Chrome, they show up broken.  But that's irrelevant to this issue.

I think the path is wrong.  I see this in the source of the page:
prefixUrl:          "../assets/iiif-images/",

And if it's being called from assets/javascripts/openseadragon.js then the path should be ../images/iiif-images/

Now where to fix it...

**Comment by saracarl** [comment]
@tbl73 Could you try changing this line to ../images/iiif-images/ and testing it locally?  I think that's the fix.

https://github.com/benwbrum/fromthepage/blob/e2a9424c268265884c23d5557ad6b70112a78130/app/views/shared/_iiif_div.html.erb#L6

**Comment by tbl73** [comment]
Making that change breaks the icons for me locally (but they were working in dev already).  On my local machine, it looks like it's being called from a precompiled openseadragon file in the assets folder, so it makes sense that the path would be ../assets/iiif-images/ for my machine.  @saracarl Did we ever confirm where the actual icon files (or the iiif-images folder) are on the production server?

**Comment by saracarl** [comment]
Yes - I confirmed the files and permissions are ok on production.

**Comment by tbl73** [comment]
Hmm.  When I change the code mentioned above locally, I get the same error message as you currently see on production about those files, so that definitely is the right place to change the path.  It's strange that it can't get to the folder in assets, though, given that the files and permissions are right.

**Comment by saracarl** [comment]
On that Open Seadragon assets not showing up issue - when I was working on rewriting the routes and urls for the pages yesterday, my navigation images stopped working.  I ended up having to change the /shared/_iiif_div.html.erb file - the line that has "../assets/iiif-images/" to "/assets/iiif-images" (without the dots) to make it work again.  I don't know if that's helpful for production, but just FYI.

**Comment by jbhoward-dublin** [comment]
Wondering about the status of this issue; still not addressed in production instance of FromThePage

**Comment by bencomp** [comment]
I had noticed the same and looking at my Firefox web console, it seems that OpenSeadragon is looking for the 'original' images, like `zoomin_rest.png`, whereas the precompilation changed the images' filenames to include a hash, like `zoomin_rest-0cfe30647a634c60a68fa868d67c488f60e6f78ce2bf61effce1c25c13f1d0bc.png`.

Perhaps the OpenSeadragon images should not be precompiled, or the OpenSeadragon JavaScript should learn about the new URLs with hashes. Or images should not get hashes in their filenames at all.

**Comment by bencomp** [comment]
Reading a bit more in the [Rails guide about precompiling assets](http://guides.rubyonrails.org/asset_pipeline.html), it might help to move the OpenSeadragon assets to `lib/assets/` or `vendor/assets/`, since those will not be precompiled by default, whereas the assets under `app/assets/` will. I haven't tried this yet.
