### ISSUE TITLE
IIIF Manifest duplicate imports

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#570]
When you import an IIIF manifest via a link, the import process is creating two works - one in a collection that you select, and one in a collection of its own.

**Comment by saracarl** [comment]
@jbhoward-dublin this was deployed on fromthepage.com today.  You shouldn't see any more duplicates when importing via a iiif manifest.

**Comment by jbhoward-dublin** [comment]
Has this been implemented on the fromthepage.com site? I have imported two manifests as works to add to an existing collection, but they continue to also appear as new Collections (this with the Luke Wadding Collection)

**Comment by saracarl** [comment]
We'll investigate, @jbhoward-dublin and see why this is still happening.  (Hopefully it's just a deployment issue.)

**Comment by saracarl** [comment]
Fixed.  (Changes were merged, but not pushed back out to github.  Sigh.)
