### ISSUE TITLE
Adding Works to an existing Collection created via IIIF import creates new Collection

### ISSUE THREAD

**Issue by jbhoward-dublin** [benwbrum/fromthepage#574]
When adding a new Work to an existing Collection via IIIF import:
- Importing via “Import a IIIF Manifest” to an existing collection adds the work to the selected Collection but **also** creates a new Collection based on the manifest
- When importing a manifest via a IIIF Collection selected from the "Import from an IIIF Repository" list: selecting the checkbox “Use parent collection {collection_name}” seems to do nothing when import is executed ; selecting the target Collection from the dropdown list adds the work to the Collection, but **also** creates a new collection based on the imported manifest

**Comment by benwbrum** [comment]
I believe that this is a duplicate of the #570 we noticed last week -- @tbl73 can you double-check?

**Comment by jbhoward-dublin** [comment]
Indeed you are right--apologies for the duplication! I'll close this issue
