### ISSUE TITLE
Secure Mirador instance unable to load derivative manifests from insecure XMLHttpRequest endpoint

### ISSUE THREAD

**Issue by jbhoward-dublin** [benwbrum/fromthepage#575]
An instance of Mirador running under HTTP over TLS is unable to load derivative FromThePage manifest and annotations via insecure XMLHttpRequest endpoint at fromthepage.com

**Comment by saracarl** [comment]
@jbhoward-dublin -- is this resolved with the ssl cert work?  Thanks!

**Comment by jbhoward-dublin** [comment]
Problem resolved, thanks!
