### ISSUE TITLE
Internal Server Error on ZIP batch upload

### ISSUE THREAD

**Issue by lsm3n** [benwbrum/fromthepage#579]
After an apparently successful upload of a batch ZIP file, the file seems to begin processing but then returns an internal server error.

re-confirmed issue still exists using file `uvallsc-mss98-3-part 3.zip`

**Comment by saracarl** [comment]
@lsm3n Did this show up in your Crapo collection or was it lost?   

I'm showing "successful" in the upload, but I can't track it to a particular work in that collection to make sure.  

If it was lost, I'd like to try it again, now that we've fixed a bug in the uploader and have a larger server that is handling your files better.  Could you also rename the file to not include a space?  

Thanks.

**Comment by jpa4ad** [comment]
Zip file did not appear in collection. However, I restructured the collection and uploaded zip files without spaces in the file name, which worked just fine.

**Comment by saracarl** [comment]
Great.  Closing.
