### ISSUE TITLE
Default subject categories not created for standalone IIIF imported collection

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#580]
If you import an IIIF manifest and have it create a new collection, the default subject categories aren't being created.  I think the creation code needs to be moved from the collection controller to a before_save hook in the model.

**Comment by benwbrum** [comment]
I agree completely, though an `after_save` hook might work better.

**Comment by tbl73** [comment]
Yeah, now that you say that, after_save does make more sense.
