### ISSUE TITLE
Column size for 'browser' in interactions table needs to be increased.

### ISSUE THREAD

**Issue by PeterTonoli** [benwbrum/fromthepage#585]
Getting the following error:
`ActiveRecord::StatementInvalid in StaticController#splash
Mysql2::Error: Data too long for column 'browser' at row 1: INSERT INTO `interactions` (`action`, `browser`, `created_on`, `ip_address`, `params`, `session_id`, `status`) VALUES ('splash', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/5X.0.XXXX.XXXX Chrome/5X.0.XXXX.XXXX Safari/537.36', '2017-03-16 06:30:36', 'XXX.XXX.XXX.XXX', '{\"controller\"=>\"static\", \"action\"=>\"splash\"}', 1, 'incomplete')`

**Comment by saracarl** [comment]
We've seen this occasionally in development environments, but not consistently.  I'm wondering if it occurs depending on the version of mysql you're running?  

Ah.  Research points to this:  http://stackoverflow.com/questions/24310178/rails-4-migration-mysql2error-data-too-long-for-column-xxxx  

But I agree we shouldn't let mysql automatically truncate data for us.

We still log interactions, but we aren't using them for anything at this point.  I can see two ways to fix this:
1)  extend the browser column size
2)  find where we are inserting the browser details and just get rid of that call.  <-- this is a hack, but wouldn't affect the product.

We'll take a look.
