### ISSUE TITLE
Orphan subjects should be deleted

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#586]
Katherina Fostano at Fordham reports:

We had a small question about the categories. For some reason if we delete or remove tags from a page they still appears as "Uncategorized", is it possible to delete them permanently from the subject list?

**Comment by tbl73** [comment]
Do you know if they're going in and deleting the subject itself from the subject's settings page (which should get rid of it), or are they just removing the tags from a transcribed page?

**Comment by kfostano** [comment]
I just saw this option @tbl73. Thank you very much for your help!
