### ISSUE TITLE
parsing exception

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#591]
TRANSCRIPTION   User    ID: 682 Email:XXX@gmail.com       Display Name: lerivoir
TRANSCRIPTION   Collection      ID: 11  Title:Austin Fanzine Project    Owner Email: xxx@gmail.com
TRANSCRIPTION   Work    ID: 59  Title: Geek Weekly #6
TRANSCRIPTION   Page    ID: 3525        Position: 29    Title:29
TRANSCRIPTION   Source Text:
BEGIN_SOURCE_TEXT
upset about nude dancing because the more popular it becomes the more likely other men might have seen "his" wife naked.

Rather than looking at the stripper's childhood, as Miller suggests, we should look at the situation of women in our society. Nude dancing, though seemingly an act of f
reedom and independence, reinforces widespread cultural assumptions about women and reflects their cultural and economic oppression. [<i>That's my favorite - hey, don't
 blame me, I'm a tool of the patriarchy!</i>]

Aaron Smuts
Philosophy graduate student

[Image: book except with text]
[Image text:
<b>Chapter 2</b>
<b>EVADING THE ENEMY<?b>

2-1. Planning:
a. Evasion - the responsibility of every fighting man (figure 2-1).
U.S. FIGHTING MAN'S CODE OF CONDUCT

I
I am an American fighting man. I serve in the forces which guard my country and our way of life. I am prepared to give up my life in their defende.

2
I will never surrender of my own free will. If in command, I will never surrender my men while they still have the means to resist.

Figure 2-1. Code of Conduct.]
END_SOURCE_TEXT

E, [2017-03-18T18:21:48.860017 #13200] ERROR -- : TRANSCRIPTION 2017-03-18 18:21:48 +0000       ERROR   EXCEPTION       #<REXML::ParseException: Bad instruction declara
tion
Line: 4
Position: 1271
Last 80 unconsumed characters:
<?b><lb/></p><p> 2-1. Planning:<lb/> a. Evasion - the responsibility of every fig>
/usr/share/ruby/rexml/parsers/baseparser.rb:364:in `pull_event'
/usr/share/ruby/rexml/parsers/baseparser.rb:183:in `pull'

**Comment by tbl73** [comment]
@saracarl  - Where are you seeing this exception?  Is it in the logfile?  And what is the user doing when it happens?

**Comment by tbl73** [comment]
Looks like it was more of a user error.
