### ISSUE TITLE
Cache notes on manifest creation

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#596]
For works with many pages, the IIIF manifest generation is excruciating -- for example, http://fromthepage.com/iiif/402/manifest can take twelve minutes to execute.  Apparently we're hitting the database for each page to see if it has any notes.  I tried to cache this using ActiveRecord `includes`, but had no success.

We'll need to start with a multi-page manifest.  The example that's taking so long was imported from https://data.ucd.ie/api/img/manifests/ivrla:1015

**Comment by tbl73** [comment]
I was looking at this (related to #607 ), and I think the code that's slowing things down so much is creation of the image_resource in this blob: https://github.com/benwbrum/fromthepage/blob/master/app/controllers/iiif_controller.rb#L316-L331.  I don't know enough about what's happening there to change it, but if you comment that section of code out, everything else generates pretty quickly, even in very large manifests.

**Comment by tbl73** [comment]
After some further investigation and discussion, we realized that the iiif_create_iiif_image_resource process was making a call out to another server to set the page height and width, which we could do within FtP.  Making that change speeds up the process considerably.
