### ISSUE TITLE
Delete image files when work is deleted

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#602]
When a work is deleted, the /public/images/work_id folder of images is not deleted.  Should it be removed as part of the deletion process to save disk space?

**Comment by saracarl** [comment]
clean up scrip needed too.

**Comment by saracarl** [comment]
we should see if the cleanup script can handle cleanup for #499  as well.

**Comment by saracarl** [comment]
See #626 re: cleanup of old files

**Comment by tbl73** [comment]
The PR on this sets them up to be deleted in an after_destroy callback on the work.  I also wrote a rake task to delete old folders that don't have a work associated with them.
