### ISSUE TITLE
500 error -- loading owner user page

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#610]
This user profile: http://fromthepage.com/user/profile?user_id=740

Leads to this error:

I, [2017-03-25T01:08:07.451807 #9428]  INFO -- :   Rendered user/profile.html.slim within layouts/application (255.8ms)
I, [2017-03-25T01:08:07.452155 #9428]  INFO -- : Completed 500 Internal Server Error in 1047ms
F, [2017-03-25T01:08:07.455280 #9428] FATAL -- : 
ActionView::Template::Error (undefined method `subjects_disabled' for nil:NilClass):
     99:       th.w60 Categories
    100:       th.w15 Version
    101:     -@article_versions.each do |version|
    102:         -unless version.article.collection.subjects_disabled
    103:           -@collection = version.article.collection
    104:           -description = truncate(strip_tags(xml_to_html(version.article.xml_text)), :length => 100)
    105:           tr
  app/views/user/profile.html.slim:102:in `block in _app_views_user_profile_html_slim__2793693696411825216_69864726558360'
  app/views/user/profile.html.slim:101:in `_app_views_user_profile_html_slim__2793693696411825216_69864726558360'

Doesn't happen for everyone (this is the only one I've found, but I've only looked at 4).  

Suspect it's this line:
    102:         -unless version.article.collection.subjects_disabled

If you are an owner with no collections/no public collections?  Or some special case of collection?  (This customer has a number of collections, but they are mostly private.)

**Comment by saracarl** [comment]
Well, they have at least 1 public collection, this one:
http://fromthepage.com/collection/show?collection_id=130

So that theory is slightly off.

**Comment by tbl73** [comment]
This seems to involve some bad data, perhaps related to the upload problems in #579, or to a timing problem between uploads and the code that was pushed the other day to remove orphaned data.  There are 21 articles that have no collection id or source text.  To remove them, you can run "Article.all.each {|a| a.destroy unless a.collection}".

**Comment by tbl73** [comment]
Well, on further investigation, the articles actually aren't real orphans, so they shouldn't be deleted.  They need to be re-associated with the correct collection_id.

**Comment by saracarl** [comment]
Fixed and verified by the customer.
