### ISSUE TITLE
Add owner to the FtP Activity report

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#622]
We have activity on collections, but you can't tell who the owner is for the collection, which is confusing.

**Comment by tbl73** [comment]
@saracarl  - here's a screenshot of a version including the owner - does this provide enough information?
![admin_email](https://cloud.githubusercontent.com/assets/16854029/24875394/db3b75fe-1df5-11e7-99fa-4b988813fb58.PNG)

**Comment by saracarl** [comment]
Decided to make the owner a link to the owner profile.  Otherwise, looks good.
