### ISSUE TITLE
insert a pdf into a work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#625]
not just a page

**Comment by benwbrum** [comment]
Use case:  I upload a document with 100 pages, then later realize that I forgot to scan 20 pages in the middle.  I scan those pages, and have a PDF with pp 45-65.  Now I'd like to edit the document and upload the PDF, having those new pages inserted after page 44 of the existing document.

This seems like an awful lot of work for an edge case.

**Comment by benwbrum** [comment]
This has not come up in the last two years.
