### ISSUE TITLE
BookReader does not work when a doctype is added to the layout

### ISSUE THREAD

**Issue by diegoviola** [benwbrum/fromthepage#63]
BookReader does not work when a doctype such as `<!DOCTYPE html>` is added to the HTML document or layout.

I don't know why that is but the library won't display anything when a doctype is added to the document, I tried many doctypes and it never works with one.

BookReader will only work in quirks mode (without a doctype), which is odd.

**Comment by tbl73** [comment]
@benwbrum - do you know if this is still a problem?

**Comment by saracarl** [comment]
We are moving away from bookreader as an interface.  Closing.
