### ISSUE TITLE
Use OpenLibrary persistent URLs

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#66]
The code built around determining URLs for IA images is now obsolete thanks to the new redirection APIs built into OL.  As Mike Lichtenberg writes:

FWIW, IA added a way to access their images that doesn’t rely on knowing that the base address was “ia700609.us.archive.org/6/items/mcz13103363v2” at one time but might be different now.  See https://openlibrary.org/dev/docs/bookurls.

Using these addresses, this…

http://www.archive.org/download/mcz13103363v2/page/n2_w840

… redirects to this…

http://ia600609.us.archive.org/BookReader/BookReaderImages.php?id=mcz13103363v2&itemPath=/6/items/mcz13103363v2&server=ia600609.us.archive.org&page=n2_w840

… and returns the same image as this…

http://ia600609.us.archive.org/BookReader/BookReaderImages.php?zip=/6/items/mcz13103363v2/mcz13103363v2_jp2.zip&file=mcz13103363v2_jp2/mcz13103363v2_0003.jp2&scale=2

The beauty is you don’t need to know those ugly server names and file paths (and don’t need to double-check them every time).

**Comment by tbl73** [comment]
@benwbrum - it looks to me like this might be done, but I don't know enough about the bookreader code to really tell.  Can you let me know so I can determine what to do with this issue?
