### ISSUE TITLE
Document sets setting - public/private

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#673]
The public/private setting wasn't being set on document set creation, so unless the user went back in and edited it, it isn't set.  Moving forward, it is set (and being used), so we need to create a migration to inherit that setting from the collection for existing document sets if it isn't set already.

**Comment by benwbrum** [comment]
Trisha thinks this may work correctly -- to spot check and close if so.

**Comment by tbl73** [comment]
It's a little hard to tell, but I think they're working okay.  Nil seems to default to private (although some of them are accessible anyway, but they're all in public collections, so I don't think it's an actual issue.)
