### ISSUE TITLE
Settings for URLs need to reference server's DNS, not fromthepage.com

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#680]
|The current URL for this collection is <b>www.fromthepage.com/#{@collection.owner.slug}/#{@collection.slug}</b>. If you want to edit the work section of the URL, please use lowercase letters and dashes between any words.

The "www.fromthepage.com" needs to be the name of the server.  (And let's add a http/https as appropriate as well.)

See:
https://github.com/benwbrum/fromthepage/pull/659/files/c81a483a4ac54a66c4c025cb60ff243db0cf8d47..c3a7758c5a966d1d56d504e1f15b6d7cbe3defa5#diff-056bac2e5d7bf0bfdad7876f8f6d29ed

**Comment by saracarl** [comment]
Shows up in app/views/document_sets/edit.html.slim as well.

**Comment by saracarl** [comment]
And app/views/work/edit.html.slim

So collections, works, and document sets all have this issue.  (Anything else?)

**Comment by tbl73** [comment]
It would be in app/views/user/update_profile.html.slim, too. I can get the server name from the default_url_options to change that part, but I'm not entirely sure how to check if the server is set up with SSL - any thoughts?
