### ISSUE TITLE
Wrong Collaborators count in document set statistics

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#681]
![wrongcollaboratorscount](https://user-images.githubusercontent.com/708566/27445344-005c827e-573f-11e7-9753-7daf6c92d8e0.png)

I'm guessing this is coming from the parent collection, rather than the document set.  If I look at the collaborators tab info for the document set, it just shows 1 collaborator (which I think is right).  

I think you can reproduce by running the test suite, then creating a document set that matches the screenshot above.

**Comment by tbl73** [comment]
The collaborators in the document set come from deeds in the specific works, and I missed a distinct (so it's counting all users by deeds, not distinct users by deeds).
