### ISSUE TITLE
upgraded user profile failing

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#685]
Upgrade user profile failing:

I, [2017-06-26T11:52:11.340867 #35749]  INFO -- :   Rendered user/profile.html.slim within layouts/application (196.4ms)
I, [2017-06-26T11:52:11.341656 #35749]  INFO -- : Completed 500 Internal Server Error in 298ms
F, [2017-06-26T11:52:11.349304 #35749] FATAL -- : 
ActionView::Template::Error (undefined method `title' for nil:NilClass):
    66:       -note_text = truncate(strip_tags(note.body), :length => 200)
    67:       tr
    68:         td.nowrap =note.created_at.localtime.strftime("%b %d, %Y, %l:%M %p")
    69:         td.overflow =link_to note.page.title, { :controller => 'display', :action => 'display_page', :page_id => note.page_id }
    70:         td =link_to note_text, { :controller => 'display', :action => 'display_page', :page_id => note.page_id, :anchor => "note-#{note.id}" }
    71:   br
    72: 
  app/views/user/profile.html.slim:69:in `block in _app_views_user_profile_html_slim__4038069015503411588_64241900'
  app/views/user/profile.html.slim:65:in `_app_views_user_profile_html_slim__4038069015503411588_64241900'

**Comment by saracarl** [comment]
PSU issue.

**Comment by saracarl** [comment]
This is happening because there are pages without titles in the database.

**Comment by tbl73** [comment]
It looks to me like there might be notes that don't have a page_id associated with them - there's no title because the page is returning nil.

**Comment by saracarl** [comment]
Deleted a bad note and now the user profile works:

http://zebrapedia.psu.edu/user/profile?user_id=1
