### ISSUE TITLE
HOT:  User creation failing due to slug creation

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#691]
This is failing at user creation:

NoMethodError (undefined method `slug_changed?' for #<User:0x007f270fa55c48>):
  app/models/user.rb:132:in `should_generate_new_friendly_id?'
  app/controllers/registrations_controller.rb:21:in `create'

I suspect the reason is it's a new user and the slug hasn't been generated yet.  We should be testing for a blank slug field.

We pass all the tests in the test suite even with this.  It is failing in the master branch and the trial user branch, so it's a relic from the friendly ID work.  This has to be fixed before we deploy any of the recently merged PRs.

**Comment by tbl73** [comment]
Can you give me some information about your process when this is failing?  When I run in the server using the master and trial owner branches, I'm able to sign up as a new user without any errors.

**Comment by saracarl** [comment]
This seems to be limited to my test environment -- Ben and Trisha's environments don't exhibit the problem.

**Comment by saracarl** [comment]
Tried with the production DB and worked fine.  Closing this.
