### ISSUE TITLE
Security warnings on FromThePage.com

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#692]
Accessing FromThePage.com via Firefox yields security warnings that not all content is secure.  In one instance, the site failed to load at all.

**Comment by saracarl** [comment]
One issue causing this is references to gravatars:
http://gravatar.com/avatar/d34fc3a0018a48156439cccf0c62ee8e?default=blank&secure=false&size=80
should be:
https://gravatar.com/avatar/d34fc3a0018a48156439cccf0c62ee8e?default=blank&secure=false&size=80

**Comment by benwbrum** [comment]
Another problem is the URLs we generate for Internet Archive works.  The display/_multi_page view delegates to different kinds of page objects to generate the URL for images.  Looking at `model/ia_leaf.rb`, `http` is hard-coded for all the URLs.

**Comment by tbl73** [comment]
There are also a couple of spots in ia/ia_bookreader_div.html.slim that were hard-coded to http, so I switched them to https, too.  The gravatar image tags are set in the gravatar initializer (set use secure to true).
