### ISSUE TITLE
Subjects cannot have double quotes

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#7]
Apparently putting double quotes in the name of a subject (e.g. [[John "Jack" Coffee Hays]]) returns an indescript error.  We should A) catch the error and make it meaningful, and B) figure out what's wrong with the double quotes within a wikilink.

**Comment by tbl73** [comment]
This is an xml parsing error - it looks as though having the double-quotes is creating links that aren't valid in XML.

**Comment by saracarl** [comment]
Looks good.
