### ISSUE TITLE
Add owner to collections in activity report

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#701]
It currently says:

Collection Activity
Collection: C. S. Peirce Manuscripts
Recent Transcriptions

On 07/11/2017 at 10:51 PM, jeffdown1 edited page 2 in the work MS 618-627 (1909) - Meaning and Pragmatism

It needs to have the owner so we can tell who is doing what.

**Comment by saracarl** [comment]
done?

**Comment by tbl73** [comment]
Which activity report does this refer to?

**Comment by saracarl** [comment]
I'm pretty sure it's done -- the one we get every night (but I have to log in to get the right name!)
