### ISSUE TITLE
newline transcription convention

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#708]
This line in transcription conventions always shows up -- can't get rid of it:

A single newline indicates a line-break in the original document, and will not appear as a break in the text in some views or exports. Two newlines indicate a paragraph, and will appear as a paragraph break in all views. 

move to default conventions, out of the template

**Comment by tbl73** [comment]
We'll run a migration to update the default conventions of existing collections.  Collections with conventions that are different than our default will need those lines to be manually added.
