### ISSUE TITLE
missing zoomer.gif

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#719]
Error message

ActionView::MissingTemplate: Missing template collection/show, application/show with {:locale=>[:en], :formats=>[:gif], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :slim]}. Searched in: * "/home/fromthepage/deployment/releases/20170714131154/app/views" * "/home/fromthepage/deployment/shared/bundle/ruby/gems/devise-3.4.1/app/views"
Stack trace (show Rails)
…ruby/gems/actionview-4.1.2/lib/action_view/
path_set.rb:  46:in `find'
…ems/actionview-4.1.2/lib/action_view/
lookup_context.rb: 124:in `find'
…ew-4.1.2/lib/action_view/renderer/
abstract_renderer.rb:  18:in `find_template'
…ew-4.1.2/lib/action_view/renderer/
template_renderer.rb:  41:in `determine_template'
…ew-4.1.2/lib/action_view/renderer/
template_renderer.rb:   8:in `render'
…/actionview-4.1.2/lib/action_view/renderer/
renderer.rb:  42:in `render_template'
…/actionview-4.1.2/lib/action_view/renderer/
renderer.rb:  23:in `render'
…uby/gems/actionview-4.1.2/lib/action_view/
rendering.rb:  99:in `_render_template'
…uby/gems/actionview-4.1.2/lib/action_view/
rendering.rb:  82:in `render_to_body'

HTTP referrer | https://fromthepage.com/assets/application-23108daa08b4d6555ebd38e9185601099d6124537b45d49dc21ae22765d0e295.css
-- | --

**Comment by benwbrum** [comment]
This may be related to the image icons not appearing.

**Comment by benwbrum** [comment]
works for me
