### ISSUE TITLE
jenkins/travis test automation & deployment automation

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#721]
I'd like to investigate jenkins test automation when new code is checked in or a new pull request is created.  Will jenkins plugins support our current version of rspec?  Can we use it with our version capistrano?  What platforms can we run jenkins on or do we need to use a hosting services like jenkinshosting?  (leaning towards installing it on a linode)

@tbl73 if you'd take the first pass at this, I'll take the next, and then we can see what else needs to be done.  Let's use this issue for outlining the steps we'd need to take to get to automated testing (and then automated deployments...)

**Comment by benwbrum** [comment]
Github should run TravisCI spec tests whenever a pull request is opened.  This requires research, but probably not more definition.

**Comment by benwbrum** [comment]
This is becoming increasingly important as we receive contributions from outside the project team.
