### ISSUE TITLE
Changes to work homepage

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#739]
Changes to the work homepage that will provide more simplified access for transcribers, while leaving a separate path available for readers.

Add "Start Transcribing" and "Start Reviewing" buttons that take you straight to a page that needs transcription/review.  (see https://transcription.si.edu/project/8602)

Add button/checkbox to "show pages needing" transcription, similar to the needs review pages you can currently see.  (similar idea: https://transcription.si.edu/project/8602)

Work tab changes:  Rework "contents" tab -- filters, colors, surfacing more.  needs a new name.  Should be the first tab (go directly to this tab when you click on a work).  (interface more like this one: http://letters1916.maynoothuniversity.ie/diyhistory/items/show/687).  Rename "Read" to "Read Work" and move into the second position.

**Comment by benwbrum** [comment]
Start transcribing is now tracked in #949

**Comment by benwbrum** [comment]
Closing in favor of #949
