### ISSUE TITLE
Changes to owner homepages

### ISSUE THREAD

**Issue by tbl73** [benwbrum/fromthepage#740]
Owner homepage:
"featured collections" -- checkbox to feature a collection, put "featured" collections in a carousel on the main user page.  See here for a good example:  https://transcription.si.edu/

Owners should have the ability to embed the carousel in any webpage they want (email, etc).  We'd need to provide it in the owner/collection settings (???)

Collaborator homepage:
Thumbnails on collaborator dashboard -- collection thumbnails.  Perhaps replace empty gravatar images with page thumbnails?

**Comment by saracarl** [comment]
Good carousel plugin:  https://owlcarousel2.github.io/OwlCarousel2/index.html

**Comment by tbl73** [comment]
Also connects to #504.

**Comment by benwbrum** [comment]
Also remove the user's recent page edits/article edits from the bottom of the owner page.

And get rid of the word "Owner" on places like the gravatar ribbon.  (Maybe get rid of the gravatar ribbon?)

**Comment by benwbrum** [comment]
The carousel is now tracked in #826, so this should only include the clean-up items.
