### ISSUE TITLE
path instead of action nae on contents page buttons

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#753]
Some works contents pages have incorrect text for the "transcribe" button (? or possibly review button -- these pages often are the first ones in a work and usually have transcription done already)

![screenshot from 2017-08-17 06 26 35](https://user-images.githubusercontent.com/708566/29410209-35887712-8315-11e7-9f19-ddee1812e6c2.png)

Example page:  http://97.107.141.53/library/john-torrey-papers/agardh-jacob-georg-and-john-torrey-correspondence-1839/contents
(There are a number more in that collection, but not all.)

I wonder if it's a IA import issue?  All of those works were imported from IA.

**Comment by tbl73** [comment]
I was able to recreate the problem by disabling subjects in the collection.  It looks like an issue with the logic in the process of setting the wording.
