### ISSUE TITLE
IIIF Collection Import

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#772]
We have agreed to implement import of entire IIIF collections for Stanford University Archives in collaboration with @blalbrit, who will be overseeing creation of the collection manifests  

## Goals
* Reduce work load for project owners importing collections -- Importing collection `A-F` is easier than importing item manifests `A`, `B`, `C`, `D`, `E`, and `F` one at a time.
* Reduce potential for accidentally missing an item or importing the same item twice -- Importing collection `A-F` is less likely to result in `(ABCEF)` or `(ABCDDEF)`
* Allow incremental imports of collections, as when `(ABCD)` was imported, then had items `E` and `F` added to the collection manifest.
* Allow imports of items from more than one IIIF collection manifest into the same collection.
* Allow imports from one IIIF collection into more than one FromThePage collection.

## Out of scope
* Importing collections of collections is out of scope.  Only the item manifests listed in the imported collection manifest will be imported; sub-collections will not.  (This should be made explicit to the user.)

# User Interface
We will create a new collection import screen (or modify the existing collection view).  This will be accessed when
* A project owner navigates to a collection that contains manifests starting from _Import from a IIIF Repository_, or
* A project owner manually enters a collection manifest instead of an item manifest in the _Import an IIIF Manifest_ field on the _Start a Project_ screen.

The collection import screen will
* List each item manifest for the collection
* If that item manifest has already been imported into the system, it will warn the user that the item has been imported, listing the collection it was imported into, the owner of that collection, and linking to the imported work.  It is probable that a double-import is a mistake, but it's also possible that another user has imported a manifest for an unrelated project (e.g. a classroom project), and that a double-import is desirable.
* Display a checkbox next to each item--checked by default unless the item has been imported elsewhere--allowing the project owner to decide whether to include or exclude an item from the import.
* Display a "check/uncheck all" box to minimize clicking.
* Present a target collection selector, including the ability to create a new collection from the IIIF Collection manifest data.
* Display some big button to actually do the import.

# Import
The import should be performed in the background by a rake script, which will need to take the target collection and the list of IIIF item manifest IDs to import into it.  Upon completion, the script should email the project owner with a success message and a link to the imported collection.

# Open Questions

* Should the new collection import screen and the existing collection display screen be merged?
* Should item manifest imports also be run in the background?  (At present, the delay is not a big problem, and the user experience of being directed straight to the imported work is rewarding.)

**Comment by saracarl** [comment]
"Present a target collection selector, including the ability to create a new collection from the IIIF Collection manifest data". 

Let's clarify this to:

"Present a target FromThePage collection selector, including the ability to create a new FromThePage collection from the IIIF Collection manifest data.  The default name for the new FromThePage collection should be the collection name in the IIIF collection manifest. "

**Comment by saracarl** [comment]
We should also get rid of the list of top level IIIF collections list in the current import screen with this work.  That was great when IIIF was new but doesn't make sense now.

**Comment by saracarl** [comment]
"Should the new collection import screen and the existing collection display screen be merged?"

I believe this work will replace the existing collection display screen. I don't see a need for IIIF collection display other then for import.

**Comment by saracarl** [comment]
If we get rid of the top level IIIF collection list we should think through what the following really means:

"A project owner navigates to a collection that contains manifests starting from Import from a IIIF Repository"

 My personal opinion is that pasting in a IIIF collection manifest link is probably sufficient as a starting point for  importing a IIIF collection. 

 We could also support navigating from a collection manifest to a sub collection manifest that's listed in the top level manifest.  Should we?

**Comment by saracarl** [comment]
I think this is outside the scope of this feature:

"Should item manifest imports also be run in the background? (At present, the delay is not a big problem, and the user experience of being directed straight to the imported work is rewarding.)"

Let's roll it into another issue. My opinion is that it probably shouldn't be run in the background, but a collection import probably needs to be, since it could have a really large number of items.
