### ISSUE TITLE
Voice Recognition in text fields

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#781]
We need to add voice recognition to the transcript, translate, notes, and subject articles field.  

For research:  https://www.labnol.org/software/add-speech-recognition-to-website/19989/

https://developers.google.com/web/updates/2013/01/Voice-Driven-Web-Apps-Introduction-to-the-Web-Speech-API

**Comment by tbl73** [comment]
This appears to be Chrome-specific, just FYI.  Also, it only works with an https server now (apparently - it won't even ask me if it can access the microphone), so I'm not going to be able to do a whole lot with it unless/until I get my dev environment set up with SSL.
