### ISSUE TITLE
default transcription orientation for a collection

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#787]
It would be nice if a collection owner could set "over and under" for the default view.

**Comment by benwbrum** [comment]
We should add a new flag `default_orientation` to `collection`, editable on the collection settings screen.  We can edit it using the existing editor dropdown.  

When a user transcribes a page in a collection with `default_orientation` set, _if the user does not already have an orientation set in their session (or wherever we're storing that)_, display the transcription screen using the collection's default orientation.

**Comment by saracarl** [comment]
This has come up again.

Transcribers can set the page layout (image on top or bottom or left or right) for themselves and we remember it for a work.  We need a way for a project owner to set it for the whole collection.

We do set "image on top" as the default for form based /field transcription collections, but that is turning out not be a good option for all projects of this type.

**Comment by saracarl** [comment]
We set "field based" transcription to default to over/under, and while it worked for the first customer, it isn't working for the 2nd.  They'd like to be able to change the default in the collection settings.  (But field based should still *default* to over/under).

**Comment by saracarl** [comment]
Where to fix the "field based" bit:
https://github.com/benwbrum/fromthepage/blob/a58096fd0c15a64169340288df327962a0978d9c/app/controllers/transcribe_controller.rb#L22
