### ISSUE TITLE
TCMI owner dashboard works count wrong

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#835]
The TCMI owner dashboard which is shown to the user `childrensmuseum`displays as `0` even though the owner has thousands of works.

**Comment by benwbrum** [comment]
![owner_dashboard_works__count](https://user-images.githubusercontent.com/199961/32016554-df7e886a-b989-11e7-9f0a-fe19e8318d25.png)

**Comment by tbl73** [comment]
This seems to have gotten broken at some point, and no one realized it.  It's actually wrong in production, too.  Just pushed up a PR with a fix.
