### ISSUE TITLE
Add identifier to exports

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#844]
Ben added an "identifier" field to a work recently.  We need to provide it in all the export formats.

**Comment by tbl73** [comment]
@benwbrum - Where does the identifier belong in the TEI export?

**Comment by saracarl** [comment]
need it in the csv export too??  Where does that go?

**Comment by saracarl** [comment]
For TEI do this:  
<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:id="KYR-0001-001-0001"> 

from here:   https://github.com/CivilWarGovernorsOfKentucky/Documents/blob/master/xml/KYR-0001-001-0001.xml

note that not everything will have an identifier.

**Comment by saracarl** [comment]
subject CSV it should be a new column next to work title
