### ISSUE TITLE
contentDM IIIF testing

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#851]
work to import:  https://cdm17217.contentdm.oclc.org/digital/iiif-info/p17217coll3/1327
corresponds to:  http://cdm17217.contentdm.oclc.org/cdm/compoundobject/collection/p17217coll3/id/1327/

Let's just make sure it works and "looks right"

**Comment by tbl73** [comment]
Looks good.   The only difference I see is that the site has a record (Albert Walton Barnes (2), which doesn't get imported.  That record on the site is a two page PDF, though, rather than an image like the rest of them appear to be.
