### ISSUE TITLE
Missing document set tab in collection management

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#852]
I had a hard time figuring out how to manage document sets for a collection -- eventually I found the UI by going into the "settings" tab while in the document set itself.  I think we should add a "document sets" tab to the collection (if you are an owner) that takes you to this screen:

![screenshot from 2017-11-07 13 13 45](https://user-images.githubusercontent.com/708566/32512725-a17a2234-c3bd-11e7-92c0-b6588db9535d.png)

(any idea why we didn't do that in the first place?  oversight?  or is there a good reason?)

**Comment by tbl73** [comment]
This is because document sets aren't being enabled when they're created with the metadata file; otherwise you should see the sets tab. We'll need to enable that setting when the metadata files are uploaded.
