### ISSUE TITLE
Field-based configuration

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#870]
Collections settings should be modified to support field definitions for record-based transcription.

## Data Model

We will need to modify the data model as follows:
* `collections` will need a new `field_based` boolean which defaults to `false`.
* A new `transcription_fields` table will be created, with a child relationship to `collections` (and the appropriate foreign key), as well as 
    - `label` a string containing a label for the field.
    - `input_type` a string containing one of `text`, `select`, `textarea` or possibly `text_with_select`
    - `options` a long string containing a list of values for select drop-downs.  This will be delimited by something that is unlikely to be a character in a valid option, possibly semicolon or pipe.
    - `line_number` an integer defining the line of text the input field will be displayed on
    - `order` an integer defining the order the field will be displayed in.  (This may be implied in the user interface, rather than manually entered, so that we will not need to deal with duplicates.)

## User Interface

The collection settings tab should have a new buttton that toggles between document-based transcription and record-based transcription.  _I'm not entirely clear how we should phrase it, but it's important to make it obvious that enabling fields will disable our standard textarea._

When the collection is record based, we should display a new link or button saying _Configure Fields_.

Clicking _Configure Fields_ should open up a field configuration screen in a lightbox.  It will contain a single form, with a row for each `TranscriptionField` associated with the collection, followed by a row with blank entries.

The form should present _Add_, _Done_, and _Cancel_ buttons to the user.  _Add_ will save the contents of the form (including both edits to existing `transcription_fields` and addition of a new field) and ajax-redirect to presenting the form again (with a new row).  _Done_ will save the contents of the form and close it, returning the user to the collection settings screen.  _Cancel will return the user to the collection settings screen without saving the form contents.

Each row of the form should present a text input for the _label_, a select dropdown for _input_type_, a short text input (validated to numeric) for _line_number_, and a longish text input for _options_.  (Ideally, _options_ would be disabled unless _input_type_ was a select.  

We may use up/down links to re-order the _order_field, as we do with _position_ in the Work Pages tab.

**Comment by benwbrum** [comment]
Open questions: 

* Should we give administrators the option to choose either a `select` or a text input with optional select?  The latter supports Type-What-You-See editorial projects, so we may be asking for trouble with the former.
* How should we phrase this in the UI?

**Comment by benwbrum** [comment]
![field_based_alabama_better](https://user-images.githubusercontent.com/199961/33272084-b53e3c10-d34e-11e7-814d-cbe71f86727a.png)

**Comment by saracarl** [comment]
Example input:  http://cdm17217.contentdm.oclc.org/cdm/compoundobject/collection/p17217coll3/id/1327/

**Comment by saracarl** [comment]
Needs a preview in the lightbox.
Most likely when you save a field config, it previews the form in the lightbox.

**Comment by saracarl** [comment]
Buttons on the lightbox:
"Save and Add"
"Done"

Button per field "x" -- to delete.
