### ISSUE TITLE
Bug in owner activity stream.

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#879]
The activity stream on this owner's page has works that aren't his, and activity done by someone else.  (Peirce stuff, gnox user)  Seems like a bug.  https://fromthepage.com/jbhoward

**Comment by benwbrum** [comment]
This also seems to be a problem for non-owners.  For example, this user just edited something, as apparent on the collections tab:
```
about 1 hour ago
Ryan Donaldson edited page Brief Prepared by James Monroe in Monroe v. Skinner, 20 October 1824 - Page 3 in Practicing Law in the Early American Republic collection
```

But when I click on his username, I see a collection (owned by UVA Law Library, not by him), and an activity stream that starts with:
```
Recent Activity
5 months ago
Ryan Donaldson transcribed page 18 in UN Commission on Human Rights Documents collection
5 months ago
Ryan Donaldson transcribed page 17 in UN Commission on Human Rights Documents collection
```

**Comment by tbl73** [comment]
I'm pretty sure this is because we're getting IDs from both collections and document sets.

**Comment by tbl73** [comment]
That specific user that you mentioned actually is an owner of the collection that you mentioned.  The more general problem seems to have been related to document set ids.
