### ISSUE TITLE
field based:  double space between lines of output

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#900]
So if we do a double return between each field in the transcription view, they'll look good in the overview of the work.

**Comment by tbl73** [comment]
I don't really understand what you mean here.

**Comment by saracarl** [comment]
In a normal transcription field, double return means "paragraph break" and single return means "line break".  When you view the work in the read work view (the "read" tab on the work), we ignore line breaks (you'd like a continuous block of text breaking for screen width, rather than the short lines that handwritten text normally is).

Right now with field based transcription, we have a single return between fields.  That means in the "read" view, multiple field names and values get squished onto a single line, wrapping based on the screen width.  

If we were to do double returns after each field name/value pair, then we'd display them "appropriately" (one per line) in the read view.
