### ISSUE TITLE
voice dictation icons broken

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#916]
![image](https://user-images.githubusercontent.com/708566/35168206-b1a8970a-fd1d-11e7-8102-cbdfc74b3717.png)

If you click the microphone on a page you can dictate, but the icon is broken.  when you click that broken icon (the stop dictating one) the returning microphone icon is also missing.  

Also, after doing that you get the written message "Click microphone for dictation" after turning it on and off.

Let me go try a rake assets recompile.

**Comment by saracarl** [comment]
This is on production, so you can see it there.

**Comment by saracarl** [comment]
precompiling assets didn't fix it.

**Comment by tbl73** [comment]
The javascript that changes the microphone icon is pointed directly at the
various file names in the assets folder, but it looks like production
assets end up with different file names, so that doesn't work. I'm going to
have to look into how it should be done in production.
