### ISSUE TITLE
too many open files / can't connect

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#929]
Indianapolis Public Library had a handful of users reporting errors from Passenger where there were too many file handles open for them to start a session.

We believed we fixed the problem by turning off the geocoding in ahoy, which had caused similar problems on the RWL site.  However, the problem continued to happen.

We verified ulimits for apache and the system, took multiple lsof counts and dumps, and did not find an obvious reason for the problem -- we never reached anywhere near the limits that were set.

We then looked at the new thumbnail image generation code.

**Comment by benwbrum** [comment]
I looped through each page, calling `thumbnail_image` on it and logging the filename it resulted to [generate_thumbnail.log](https://github.com/benwbrum/fromthepage/files/1671212/generate_thumbnail.log)

After running this, `lsof` yielded [lsof_post_thumbnail_generation.txt](https://github.com/benwbrum/fromthepage/files/1671211/lsof_post_thumbnail_generation.txt)

After restarting apache, `lsof` yielded [lsof_post_thumbnail_generation_post_restart.txt](https://github.com/benwbrum/fromthepage/files/1671210/lsof_post_thumbnail_generation_post_restart.txt)

Following this, I tested to see whether there were files that still required thumbnail generation:
```ruby
Page.order(:id => :asc).all.each { |page| p page.id; f.print page.id; f.print "\t";  if page.ia_leaf || page.base_image.blank? then f.print "bailing out" else if File.exists?(page.thumbnail_filename) then f.print "has thumbnail" else f.print "might generate" end  end ; f.print "\n" }; f.print "DONE"; f.close
```

Results: [has_thumbnail.log](https://github.com/benwbrum/fromthepage/files/1671209/has_thumbnail.log)

**Comment by saracarl** [comment]
Theories to work with:

It seems unlikely this related, but our host patched the hypervisor for meltdown security vulnerability in the same timeframe.  

We've seen similar behavior when a binding.pry statements were accidentally deployed.  

Ammelioration possibilities:  restart apache daily to free open file handles?  (although this did not solve the reporting customer's problem...)  Maybe more than once a day?

**Comment by saracarl** [comment]
Image files that would be regenerated:
2266	might generate
2303	might generate
2623	might generate
6155	might generate
6156	might generate
6157	might generate
6158	might generate
6159	might generate
33367	might generate

**Comment by saracarl** [comment]
Had the customer test it again.  Problem is still occurring.  

Here's how she's getting to FtP:
I have been Googling From the Page and clicking https://fromthepage.com when it comes up. I've also tried just typing fromthepage.com, which has always worked in the past and tried some of the direct links to the collections, like the Indianapolis Public Schools , that I send to new volunteers.

**Comment by saracarl** [comment]
We're 90% sure this was from an old server being rebooted and apache running (poorly) there.  DNS is likely the culprit -- should not have been pointing to that server.  Only seemed to be in a handful of computer in Indianapolis -- perhaps the local service provider had cached the old IP?  

Turned off apache (and the automatic startup of it) on the old server.  

Researching how to refresh the IP in a way that they should get it.
