### ISSUE TITLE
IIIF Stats don't match UI stats

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#933]
And just one more note. Please take a look at the stats returned by https://fromthepage.com/iiif/contributions/ucd.ie. They are out of alignment with the actual status of the various items, and with the statistics returned through the web interface ("Works List").

@tbl73 could you look at this and see if you can figure out why they don't match?  

From @jbhoward-dublin    Needs these fixed before UCD can deploy the IIIF round trip integration (which we're talking about this spring!).

**Comment by tbl73** [comment]
They don't match currently because of the way that we find the statistics (based on page status).  Ben and I discussed this, and he has a new plan about what information to provide in the statistics.
