### ISSUE TITLE
Minutes worked report should be proportional

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#937]
If a user works on collection A and collection B during the same session (logging deeds or ahoy activity for both), their total time will appear under each collection's activity report.  Worse, their activity will get multiplied if the user is working on the same account.

This is causing problems for Stanford, as one user (who worked on four collections) is appearing as having worked for 222 minutes on each collection. 

Suggested resolution: when displaying total time, adjust it proportionally for the collection by 
`figure_to_show = total_minutes * (deeds_for_this_collection_during_this_session/all_deeds_for_this_session)`

**Comment by jackweinbender** [comment]
Assuming people aren't flipping back and forth between tabs every other deed, we could probably group events (sorted chronologically) by collection by taking the time difference between deeds of differing `collection_id`.

Depending on how granular/consistent the deeds are, however, the benefit may not outweigh the computation cost.

**Comment by jackweinbender** [comment]
I ended up writing it as you suggested, FYI.
