### ISSUE TITLE
Start Transcribing/Start Reviewing Widgets

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#949]
We need a reusable widget that drops users straight into transcribing a page in the collection.

### Reusability:
The interface should be a friendly URL of the form `project_name/start-transcribing`.  Hitting this URL should take the user to the first qualifying page (see below), or to the collection homepage with a flash message apologizing if there are no qualifying pages.

This URL should be displayed on the collection settings page, so that project owners can cut-and-paste it into their newsletter and/ or email messages.  _(What about crawling?  We should try not to spam ourselves here.)_  Possibly, we should display an HTML snippet owners can cut-and-paste if they can't do their own links

### Qualifying pages
For the collection, the first qualifying page is:
* A page that is not transcribed that
* Is in a work which has not been edited in the last 48 hours

**Comment by tbl73** [comment]
In terms of the "first" page - do you want it to actually be the first page that has those qualifications, or do you want it to be a random page that has those qualifications?
