### ISSUE TITLE
User profile copy -- needs updating

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#958]
"Your name is the only required field here, but we would appreciate if you tell the FromThePage community a little bit more about yourself. "

There's no field other than Name.

**Comment by saracarl** [comment]
http://localhost:3000/freetrial#update-profile

**Comment by tbl73** [comment]
FWIW, all the information is available if you're an owner but not if you're a regular user.

**Comment by saracarl** [comment]
Verify that this does not show up on the account creation screen as well.  (Probably doesn't, but please check.)

**Comment by jackweinbender** [comment]
There also seems to be a "Location" box (perhaps this was added since this issue was opened). So, "A little bit more about yourself" still makes sense.

**Comment by benwbrum** [comment]
Let's get rid of Location, then.  We're probably going to need to do a GDPR audit in the future, so minimizing the information we ask of users is wise.
