### ISSUE TITLE
Owner Dashboard note count incorrect

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#971]
Note count on owner dashboard is incorrect.

This shows 1 note:
![image](https://user-images.githubusercontent.com/708566/36753312-63b433d4-1bcb-11e8-8a08-8632aba762c4.png)

But the first 2 collections (earthquake and ann battles) show 4 and 3 notes respectively.

**Comment by tbl73** [comment]
@saracarl  - Right now, this is actually looking at how many notes the owner has added, not how many notes have been added to the owner's collections.

**Comment by saracarl** [comment]
Ok...  So I think we get rid of it?  It doesn't make sense in this context.  If it confused me, then it would confuse others.
