### ISSUE TITLE
RTL/LTR in About Work Screen

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#973]
The About screen for the work looks jumbled compared to the settings screen:

See https://fromthepage.com/bldigital/arabic-scientific-manuscripts/add-ms-23494/about

Compare with:
*Work title:* al-Durr al-naqī fī fann al-mūsīqī الدرّ النقيّ في الفنّ الموسيقي Mawṣilī, Aḥmad ibn ʿAbd al-Raḥman موصلي، أحمد بن عبد الرحمن [‎2v] (27/70)

*Description:* Treatise on music theory relating the musical modes, or maqams (مقامات), to the Prophets, signs of the zodiac, hours of the day, etc. by Abū Ṣāliḥ al-Sayyid Aḥmad al-Rifā‘ī ibn ‘Abd al-Raḥmān, given the laqab al-Musallam al-Mawṣlī (أبو صالح السيّد الرفاعي الملقّب بالمسلم الموصلي ابن عبد الرحمن, d. 1737; see f. 3r, lines 6-7). The text is a commentary on a Persian treatise on music theory by ‘Abd al-Mu’min al-Balkhī (عبد المؤمن البلخي; see f. 3r, line 9).

*Author name:* Abū Ṣāliḥ al-Sayyid Aḥmad al-Rifā‘ī ibn ‘Abd al-Raḥmān, given the laqab al-Musallam al-Mawṣlī (أبو صالح السيّد الرفاعي الملقّب بالمسلم الموصلي ابن عبد الرحمن, d. 1737

**Comment by tbl73** [comment]
I think this is fixed in the work in PR #968, so it just hasn't been pushed yet.
