### ISSUE TITLE
Request for (iiif) transcription returns HTTP 302

### ISSUE THREAD

**Issue by jbhoward-dublin** [benwbrum/fromthepage#974]
When requesting a transcription, such as

[`https://fromthepage.com/iiif/18194/list/transcription`](https://fromthepage.com/iiif/18194/list/transcription)

the server issues an HTTP 302 redirect to https://fromthepage.com/dashboard. Replicate with:

curl -I --request GET https://fromthepage.com/iiif/18194/list/transcription -v -L

**Comment by saracarl** [comment]
So we redirect to the dashboard when we encounter a 500 error.  Looking in the logs I see this is the cause:

I, [2018-02-28T14:08:43.933432 #3369]  INFO -- : Completed 500 Internal Server Error in 8ms
F, [2018-02-28T14:08:43.934792 #3369] FATAL -- : 
NoMethodError (undefined method `restricted' for nil:NilClass):
  app/controllers/collection_controller.rb:53:in `show'


I, [2018-02-28T14:08:44.094654 #3369]  INFO -- : Started GET "/iiif/18194/list/transcription" for 70.112.51.219 at 2018-02-28 14:08:44 +0000
I, [2018-02-28T14:08:44.096322 #3369]  INFO -- : Processing by IiifController#list as HTML
I, [2018-02-28T14:08:44.096392 #3369]  INFO -- :   Parameters: {"page_id"=>"18194", "annotation_type"=>"transcription"}
I, [2018-02-28T14:08:44.109373 #3369]  INFO -- : Redirected to https://fromthepage.com/dashboard

**Comment by saracarl** [comment]
@jbhoward-dublin also notes:

when requesting

https://fromthepage.com/iiif/18194/list/transcription

through Safari and Firefox, the browser redirects to the dashboard page; in Chrome the browser displays the JSON response with the transcription text.


Which needs more investigation after we fix the above.
