### ISSUE TITLE
after signup, redirect to page you were on

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#980]
This is a regression.

When you log in, you get redirected to the collections page.  You should be sent to where you were instead.

This should also work on new signups.

**Comment by tbl73** [comment]
The odd thing is that the code that made this happen is still there, but for some reason it doesn't seem to be working correctly anymore.

**Comment by tbl73** [comment]
I looked again, and the code I referenced above is for new sign ups, which actually do seem to redirect back to the original page.  People who aren't new sign ups are being redirected to their dashboard pages, which I know was the original behavior.  I can't remember when/if we changed it.  I'm not finding any situation when I'm being redirected to the collections page, though, @saracarl  - what are you doing when you have that happen?

**Comment by saracarl** [comment]
I think I was signing up for a new account.

So this is surprisingly hard.  The key thing here is we have clients with projects.  They are sending out their project pages, i.e. https://fromthepage.com/bldigital/arabic-scientific-manuscripts  Those people are signing up for accounts and getting lost.

New Account Sign Up Case
If you go to that page and you sign up for a FtP account, afterwards you should still "see" that page -- we should redirect new accounts post-login to:
-- the page they were on when they logged in
-- unless that page was the splash screen, in which case they should go to the collection page.

So we're rewriting this issue as "sign up" rather than "login".

**Comment by tbl73** [comment]
I'll try again with that link - I actually did test new sign ups and was properly redirected to the page I was on at the time, which makes me think this is going to be tricky to track down what's happening there.

**Comment by tbl73** [comment]
After some further testing/discussion, new sign ups are redirecting correctly.  We decided to change the login behavior to redirect back to the page you were on (rather than to your dashboard).
