### ISSUE TITLE
Wrong `@collection` for LTR/RTL and breadcrumbs

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#983]
Occasionally--usually when clicking on a page on an activity stream--we load the correct page and work, but see the breadcrumb title and RTL setting for a different collection.

Two leads on this:

- The activity stream  links don't use friendly URLs, so they are passing `page_id` without any collection or work slugs.
- The code for loading the `@collection` for the `page_id` is loading the collection based on a session variable `col_id`, then blanking it after it was loaded.  If the `col_id` variable is set elsewhere, then we try to load a `page_id`, we will load the wrong collection.

Relevant code from `application_controller.rb`:
```
    if params[:page_id]
      @page = Page.find(params[:page_id])
      @work = @page.work
      if session[:col_id] != nil
        @collection = set_friendly_collection(session[:col_id])
        session[:col_id] = nil
      else
        @collection = @page.collection
      end
    end
```
I still don't know how to reproduce this.

See also #879

**Comment by tbl73** [comment]
You can reproduced by clicking on a work in a collection, then going to the Collections page and clicking on a page in the activity stream.  Possibly the col_id isn't being correctly blanked out at this point?
The activity stream links are in the deed/deed partial and should probably be updated to use the Rails url helpers.
