### ISSUE TITLE
Strikethrough markup isn't working

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#985]
See discussion here:
https://fromthepage.com/display/display_page?page_id=53554

**Comment by tbl73** [comment]
This seems to be working for me with the tags <strike></strike>.  The tags jump around sort of oddly when you put them in the RTL transcription pages, but they do appear to work.  Is this still a problem?

**Comment by benwbrum** [comment]
Worked fine for me too.  Closing.
